CREATE TABLE IF NOT EXISTS src.WFQueue (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , ENTITYTYPECODE VARCHAR(2) NOT NULL
	 , ENTITYSUBSET VARCHAR(4) NOT NULL
	 , ENTITYSEQ NUMBER(19, 0) NOT NULL
	 , WFTASKSEQ NUMBER(10, 0) NULL
	 , PRIORWFTASKSEQ NUMBER(10, 0) NULL
	 , STATUS VARCHAR(1) NULL
	 , PRIORITY VARCHAR(1) NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , CREATEDATE DATETIME NULL
	 , MODUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , TASKMESSAGE VARCHAR(500) NULL
	 , PARAMETER1 VARCHAR(35) NULL
	 , CONTEXTID VARCHAR(256) NULL
	 , PRIORSTATUS VARCHAR(1) NULL
);