CREATE TABLE IF NOT EXISTS src.BillRuleFire (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , LINESEQ NUMBER(5, 0) NOT NULL
	 , RULEID VARCHAR(5) NOT NULL
	 , RULETYPE VARCHAR(1) NULL
	 , DATERULEFIRED DATETIME NULL
	 , VALIDATED VARCHAR(1) NULL
	 , VALIDATEDUSERID VARCHAR(2) NULL
	 , DATEVALIDATED DATETIME NULL
	 , PENDTOID VARCHAR(13) NULL
	 , RULESEVERITY VARCHAR(1) NULL
	 , WFTASKSEQ NUMBER(10, 0) NULL
	 , CHILDTARGETSUBSET VARCHAR(4) NOT NULL
	 , CHILDTARGETSEQ NUMBER(10, 0) NOT NULL
	 , CAPSTONERULEID NUMBER(10, 0) NULL
);

