CREATE TABLE IF NOT EXISTS src.EDIMapTool (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , SITECODE VARCHAR(3) NOT NULL
	 , EDIPORTTYPE VARCHAR(1) NOT NULL
	 , EDIMAPTOOLID NUMBER(10, 0) NOT NULL
	 , EDISOURCEID VARCHAR(2) NULL
	 , EDIMAPTOOLNAME VARCHAR(50) NULL
	 , EDIMAPTOOLTYPE VARCHAR(4) NULL
	 , EDIMAPTOOLDESC VARCHAR(50) NULL
	 , EDIOBJECTID NUMBER(10, 0) NULL
	 , MENUTITLE VARCHAR(50) NULL
	 , SECURITYLEVEL NUMBER(10, 0) NULL
	 , EDIINPUTFILENAME VARCHAR(50) NULL
	 , EDIOUTPUTFILENAME VARCHAR(50) NULL
	 , EDIMULTIFILES VARCHAR(1) NULL
	 , EDIREPORTTYPE NUMBER(5, 0) NULL
	 , FORMPROPERTIES VARCHAR NULL
	 , JURISDICTION VARCHAR(2) NULL
	 , EDITYPE VARCHAR(1) NULL
	 , EDIPARTNERID VARCHAR(3) NULL
	 , BILLCONTROLTABLECODE VARCHAR(4) NULL
	 , EDICONTROLFLAG VARCHAR(1) NULL
	 , BILLCONTROLSEQ NUMBER(5, 0) NULL
	 , EDIOBJECTSITECODE VARCHAR(3) NULL
	 , PERMITUNDEFINEDRECIDS VARCHAR(1) NULL
	 , SELECTIONQUERY VARCHAR(255) NULL
	 , REPORTSELECTIONQUERY VARCHAR(255) NULL
	 , CLASS VARCHAR(4) NULL
	 , LINESELECTIONQUERY VARCHAR(255) NULL
	 , PORTPROPERTIES VARCHAR NULL
	 , EDIFILECONFIGSITECODE VARCHAR(3) NULL
	 , EDIFILECONFIGSEQ NUMBER(10, 0) NULL
	 , LZCONTROLTABLECODE VARCHAR(4) NULL
	 , LZCONTROLSEQ NUMBER(5, 0) NULL
);

