CREATE TABLE IF NOT EXISTS src.ODGData (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , ICDDIAGNOSISID NUMBER(10, 0) NOT NULL
	 , PROCEDURECODE VARCHAR(30) NOT NULL
	 , ICDDESCRIPTION VARCHAR(300) NULL
	 , PROCEDUREDESCRIPTION VARCHAR(800) NULL
	 , INCIDENCERATE NUMBER(19, 4) NULL
	 , PROCEDUREFREQUENCY NUMBER(19, 4) NULL
	 , VISITS25PERC NUMBER(5, 0) NULL
	 , VISITS50PERC NUMBER(5, 0) NULL
	 , VISITS75PERC NUMBER(5, 0) NULL
	 , VISITSMEAN NUMBER(19, 4) NULL
	 , COSTSMEAN NUMBER(19, 4) NULL
	 , AUTOAPPROVALCODE VARCHAR(5) NULL
	 , PAYMENTFLAG NUMBER(5, 0) NULL
	 , COSTPERVISIT NUMBER(19, 4) NULL
);

