CREATE TABLE IF NOT EXISTS src.BillFee (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , FEETYPE VARCHAR(1) NOT NULL
	 , TRANSACTIONTYPE VARCHAR(6) NOT NULL
	 , FEECTRLSOURCE VARCHAR(1) NULL
	 , FEECONTROLSEQ NUMBER(10, 0) NULL
	 , FEEAMOUNT NUMBER(19, 4) NULL
	 , INVOICESEQ NUMBER(19, 0) NULL
	 , INVOICESUBSEQ NUMBER(5, 0) NULL
	 , PPONETWORKID VARCHAR(2) NULL
	 , REDUCTIONCODE NUMBER(5, 0) NULL
	 , FEEOVERRIDE VARCHAR(1) NULL
	 , OVERRIDEVERIFIED VARCHAR(1) NULL
	 , EXCLUSIVEFEE VARCHAR(1) NULL
	 , FEESOURCEID VARCHAR(20) NULL
	 , HANDLINGFEE VARCHAR(1) NULL
);

