CREATE TABLE IF NOT EXISTS src.BillICD (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , BILLICDSEQ NUMBER(5, 0) NOT NULL
	 , CODETYPE VARCHAR(1) NOT NULL
	 , ICDCODE VARCHAR(8) NULL
	 , CODEDATE DATETIME NULL
	 , POA VARCHAR(1) NULL
);

