CREATE TABLE IF NOT EXISTS src.EDIXmitBill (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , EDIXMITBILLSEQ NUMBER(10, 0) NOT NULL
	 , EDIXMITSEQ NUMBER(10, 0) NULL
	 , EDIHISTORYPROVIDERSEQ NUMBER(10, 0) NULL
	 , EDIHISTORYCLAIMSEQ NUMBER(10, 0) NULL
	 , EDIHISTORYINSURERSEQ NUMBER(10, 0) NULL
	 , EDICONTROLSEQ NUMBER(10, 0) NULL
	 , CLIENTCODE VARCHAR(4) NULL
	 , BILLSEQ NUMBER(10, 0) NULL
	 , JURISDICTION VARCHAR(2) NULL
	 , TOB VARCHAR(1) NULL
	 , UB92TOB VARCHAR(10) NULL
	 , BILLSEQORGREV NUMBER(10, 0) NULL
	 , TOTALCHARGE NUMBER(19, 4) NULL
	 , BILLABLELINES NUMBER(10, 0) NULL
	 , PAIDDATE DATETIME NULL
	 , PAIDAMOUNT NUMBER(19, 4) NULL
	 , DRG VARCHAR(3) NULL
	 , PATIENTSTATUS VARCHAR(2) NULL
	 , POSTDATE DATETIME NULL
	 , DOCCTRLID VARCHAR(50) NULL
	 , DOSFIRST DATETIME NULL
	 , DOSLAST DATETIME NULL
	 , PPONETWORKID VARCHAR(2) NULL
	 , PPOCONTRACTID VARCHAR(30) NULL
	 , ADJUSTER VARCHAR(25) NULL
	 , CARRIERSEQNEW VARCHAR(30) NULL
	 , PROVINVOICE VARCHAR(14) NULL
	 , PROVSPECIALTY1 VARCHAR(10) NULL
	 , CLIENTTOB VARCHAR(5) NULL
	 , SUBPRODUCTCODE VARCHAR(1) NULL
	 , DUPCLIENTCODE VARCHAR(4) NULL
	 , DUPBILLSEQ NUMBER(10, 0) NULL
	 , CONSULTDATE DATETIME NULL
	 , ADMITDATE DATETIME NULL
	 , DISCHARGEDATE DATETIME NULL
	 , SUBMITDATE DATETIME NULL
	 , RCVDDATE DATETIME NULL
	 , RCVDBRDATE DATETIME NULL
	 , REVIEWDATE DATETIME NULL
	 , DUEDATE DATETIME NULL
	 , PMTAUTH VARCHAR(4) NULL
	 , FORCEPAY VARCHAR(1) NULL
	 , PROVLICENSENUM VARCHAR(30) NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , MODUSERID VARCHAR(2) NULL
	 , PATIENTACCOUNT VARCHAR(20) NULL
	 , REFPROVNAME VARCHAR(40) NULL
	 , PROVTYPE VARCHAR(3) NULL
	 , DOI DATETIME NULL
	 , GEOSTATE VARCHAR(2) NULL
	 , MANUALREDUCTIONMODE NUMBER(5, 0) NULL
	 , PPONETWORKJURISDICTIONIND VARCHAR(1) NULL
	 , PPONETWORKJURISDICTIONINSURERSEQ NUMBER(10, 0) NULL
	 , WFQUEUEPARAMETER1 VARCHAR(35) NULL
	 , CHECKNUM VARCHAR(30) NULL
	 , EXTERNALID VARCHAR(50) NULL
	 , EDITESTINDICATOR VARCHAR(1) NULL
	 , ICDVERSION NUMBER(5, 0) NULL
);

