CREATE TABLE IF NOT EXISTS src.WFTaskLink (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , FROMTASKSEQ NUMBER(10, 0) NOT NULL
	 , LINKWHEN NUMBER(5, 0) NOT NULL
	 , TOTASKSEQ NUMBER(10, 0) NULL
);

