CREATE TABLE IF NOT EXISTS src.Adjuster (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLAIMSYSSUBSET VARCHAR(4) NOT NULL
	 , ADJUSTER VARCHAR(25) NOT NULL
	 , FIRSTNAME VARCHAR(20) NULL
	 , LASTNAME VARCHAR(20) NULL
	 , MINITIAL VARCHAR(1) NULL
	 , TITLE VARCHAR(20) NULL
	 , ADDRESS1 VARCHAR(30) NULL
	 , ADDRESS2 VARCHAR(30) NULL
	 , CITY VARCHAR(20) NULL
	 , STATE VARCHAR(2) NULL
	 , ZIP VARCHAR(9) NULL
	 , PHONENUM VARCHAR(20) NULL
	 , PHONENUMEXT VARCHAR(10) NULL
	 , FAXNUM VARCHAR(20) NULL
	 , EMAIL VARCHAR(128) NULL
	 , CREATEDATE DATETIME NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , MODUSERID VARCHAR(2) NULL
);

