CREATE TABLE IF NOT EXISTS src.ProfileRegionDetail (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , PROFILEREGIONSITECODE VARCHAR(3) NOT NULL
	 , PROFILEREGIONID NUMBER(10, 0) NOT NULL
	 , ZIPCODEFROM VARCHAR(5) NOT NULL
	 , ZIPCODETO VARCHAR(5) NULL
);

