CREATE TABLE IF NOT EXISTS src.UserInfo (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , USERID VARCHAR(2) NOT NULL
	 , USERPASSWORD VARCHAR(35) NULL
	 , NAME VARCHAR(30) NULL
	 , SECURITYLEVEL VARCHAR(1) NULL
	 , ENABLEADJUSTERMENU VARCHAR(1) NULL
	 , ENABLEPROVADDS VARCHAR(1) NULL
	 , ALLOWPOSTING VARCHAR(1) NULL
	 , ENABLECLAIMADDS VARCHAR(1) NULL
	 , ENABLEPOLICYADDS VARCHAR(1) NULL
	 , ENABLEINVOICECREDITVOID VARCHAR(1) NULL
	 , ENABLEREEVALUATIONS VARCHAR(1) NULL
	 , ENABLEPPOACCESS VARCHAR(1) NULL
	 , ENABLEURCOMMENTVIEW VARCHAR(1) NULL
	 , ENABLEPENDRELEASE VARCHAR(1) NULL
	 , ENABLEXTABLEUPDATE VARCHAR(1) NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , CREATEDATE DATETIME NULL
	 , MODUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , ENABLEPPOFASTMATCHADDS VARCHAR(1) NULL
	 , EXTERNALID VARCHAR(30) NULL
	 , EMAILADDRESS VARCHAR(255) NULL
	 , EMAILNOTIFY VARCHAR(1) NULL
	 , ACTIVESTATUS VARCHAR(1) NULL
	 , COMPANYSEQ NUMBER(5, 0) NULL
	 , NETWORKLOGIN VARCHAR(50) NULL
	 , AUTOMATICNETWORKLOGIN VARCHAR(1) NULL
	 , LASTLOGGEDINDATE DATETIME NULL
	 , PROMPTTOCREATEMCC VARCHAR(1) NULL
	 , ACCESSALLWORKQUEUES VARCHAR(1) NULL
	 , LANDINGZONEACCESS VARCHAR(1) NULL
	 , REVIEWLEVEL NUMBER(3, 0) NULL
	 , ENABLEUSERMAINTENANCE VARCHAR(1) NULL
	 , ENABLEHISTORYMAINTENANCE VARCHAR(1) NULL
	 , ENABLECLIENTMAINTENANCE VARCHAR(1) NULL
	 , FEEACCESS VARCHAR(1) NULL
	 , ENABLESALESTAXMAINTENANCE VARCHAR(1) NULL
	 , BESALESTAXZIPCODEACCESS VARCHAR(1) NULL
	 , INVOICEGENACCESS VARCHAR(1) NULL
	 , BEPERMITALLOWOVER VARCHAR(1) NULL
	 , PERMITREREVIEWS VARCHAR(1) NULL
	 , EDITBILLCONTROL VARCHAR(1) NULL
	 , RESTRICTEORNOTES VARCHAR(1) NULL
	 , UWQAUTONEXTBILL VARCHAR(1) NULL
	 , UWQDISABLEOPTIONS VARCHAR(1) NULL
	 , UWQDISABLERULES VARCHAR(1) NULL
	 , PERMITCHECKREISSUE VARCHAR(1) NULL
	 , ENABLEEDIAUTOMATIONMAINTENANCE VARCHAR(1) NULL
	 , RESTRICTDIARYNOTES VARCHAR(1) NULL
	 , RESTRICTEXTERNALDIARYNOTES VARCHAR(1) NULL
	 , BEDEFERMANUALMODEMSG VARCHAR(1) NULL
	 , USERROLEID NUMBER(10, 0) NULL
	 , ERASEBILLTEMPHISTORY VARCHAR(1) NULL
	 , EDITPPOPROFILE VARCHAR(1) NULL
	 , ENABLEURACCESS VARCHAR(1) NULL
	 , CAPSTONECONFIGURATIONACCESS VARCHAR(1) NULL
	 , PERMITUDFDEFINITION VARCHAR(1) NULL
	 , ENABLEPPOPROFILEEDIT VARCHAR(1) NULL
	 , ENABLESUPERVISORROLE VARCHAR(1) NULL
);

