CREATE TABLE IF NOT EXISTS src.ClaimSysData (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLAIMSYSSUBSET VARCHAR(4) NOT NULL
	 , TYPECODE VARCHAR(6) NOT NULL
	 , SUBTYPE VARCHAR(12) NOT NULL
	 , SUBSEQ NUMBER(5, 0) NOT NULL
	 , NUMDATA NUMBER(18, 6) NULL
	 , TEXTDATA VARCHAR(6000) NULL
);

