CREATE TABLE IF NOT EXISTS src.PPOProfileNetworksHistory (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , PPOPROFILENETWORKSHISTORYSEQ NUMBER(19, 0) NOT NULL
	 , RECORDDELETED BOOLEAN NULL
	 , LOGDATETIME DATETIME NULL
	 , LOGINAME VARCHAR(256) NULL
	 , PPOPROFILESITECODE VARCHAR(3) NOT NULL
	 , PPOPROFILEID NUMBER(10, 0) NOT NULL
	 , PROFILEREGIONSITECODE VARCHAR(3) NOT NULL
	 , PROFILEREGIONID NUMBER(10, 0) NOT NULL
	 , NETWORKORDER NUMBER(5, 0) NOT NULL
	 , PPONETWORKID VARCHAR(2) NULL
	 , SEARCHLOGIC VARCHAR(1) NULL
	 , VERIFICATION VARCHAR(1) NULL
	 , EFFECTIVEDATE DATETIME NOT NULL
	 , TERMINATIONDATE DATETIME NULL
	 , JURISDICTIONIND VARCHAR(1) NULL
	 , JURISDICTIONINSURERSEQ NUMBER(10, 0) NULL
	 , JURISDICTIONUSEONLY VARCHAR(1) NULL
	 , PPOSSTINREQ VARCHAR(1) NULL
	 , PPOSSLICREQ VARCHAR(1) NULL
	 , DEFAULTEXTENDEDSEARCHES NUMBER(5, 0) NULL
	 , DEFAULTEXTENDEDFILTERS NUMBER(5, 0) NULL
	 , SEVEREDTIES VARCHAR(1) NULL
	 , POS VARCHAR(500) NULL
);

