CREATE TABLE IF NOT EXISTS src.Line (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , LINESEQ NUMBER(5, 0) NOT NULL
	 , DUPCLIENTCODE VARCHAR(4) NULL
	 , DUPBILLSEQ NUMBER(10, 0) NULL
	 , DOS DATETIME NULL
	 , PROCTYPE VARCHAR(1) NULL
	 , PPOOVERRIDE NUMBER(19, 4) NULL
	 , CLIENTLINETYPE VARCHAR(5) NULL
	 , PROVTYPE VARCHAR(3) NULL
	 , URQTYALLOW NUMBER(5, 0) NULL
	 , URQTYSVD NUMBER(5, 0) NULL
	 , DOSTO DATETIME NULL
	 , URALLOW NUMBER(19, 4) NULL
	 , URCASESEQ NUMBER(10, 0) NULL
	 , REVENUECODE VARCHAR(4) NULL
	 , PROCBILLED VARCHAR(30) NULL
	 , URREVIEWSEQ NUMBER(5, 0) NULL
	 , URPRIORITY NUMBER(5, 0) NULL
	 , PROCCODE VARCHAR(30) NULL
	 , UNITS NUMBER(11, 3) NULL
	 , ALLOWUNITS NUMBER(11, 3) NULL
	 , CHARGE NUMBER(19, 4) NULL
	 , BRALLOW NUMBER(19, 4) NULL
	 , PPOALLOW NUMBER(19, 4) NULL
	 , PAYOVERRIDE NUMBER(19, 4) NULL
	 , PROCNEW VARCHAR(30) NULL
	 , ADJALLOW NUMBER(19, 4) NULL
	 , REEVALAMOUNT NUMBER(19, 4) NULL
	 , POS VARCHAR(2) NULL
	 , DXREFLIST VARCHAR(30) NULL
	 , TOS VARCHAR(2) NULL
	 , REEVALTXTPTR NUMBER(5, 0) NULL
	 , FSAMOUNT NUMBER(19, 4) NULL
	 , UCAMOUNT NUMBER(19, 4) NULL
	 , COPAY NUMBER(19, 4) NULL
	 , DEDUCTIBLE NUMBER(19, 4) NULL
	 , COSTTOCHARGERATIO FLOAT(53) NULL
	 , RXNUMBER VARCHAR(20) NULL
	 , DAYSSUPPLY NUMBER(5, 0) NULL
	 , DXREF VARCHAR(4) NULL
	 , EXTERNALID VARCHAR(30) NULL
	 , ITEMCOSTINVOICED NUMBER(19, 4) NULL
	 , ITEMCOSTADDITIONAL NUMBER(19, 4) NULL
	 , REFILL VARCHAR(1) NULL
	 , PROVSECONDARYID VARCHAR(30) NULL
	 , CERTIFICATION VARCHAR(1) NULL
	 , REEVALTXTSRC VARCHAR(3) NULL
	 , BASISOFCOST VARCHAR(1) NULL
	 , DMEFREQUENCYCODE VARCHAR(1) NULL
	 , PROVRENDERINGNPI VARCHAR(10) NULL
	 , PROVSECONDARYIDQUALIFIER VARCHAR(2) NULL
	 , PAIDPROCCODE VARCHAR(30) NULL
	 , PAIDPROCTYPE VARCHAR(3) NULL
	 , URSTATUS VARCHAR(1) NULL
	 , URWORKFLOWSTATUS VARCHAR(1) NULL
	 , OVERRIDEALLOWUNITS NUMBER(11, 3) NULL
	 , LINESEQORGREV NUMBER(5, 0) NULL
	 , ODGFLAG NUMBER(5, 0) NULL
	 , COMPOUNDDRUGINDICATOR VARCHAR(1) NULL
	 , PRIORAUTHNUM VARCHAR(50) NULL
	 , REEVALPARAGRAPHJURISDICTION VARCHAR(2) NULL
);

