CREATE TABLE IF NOT EXISTS src.Bill (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , CLAIMSEQ NUMBER(10, 0) NULL
	 , CLAIMSYSSUBSET VARCHAR(4) NULL
	 , PROVIDERSEQ NUMBER(19, 0) NULL
	 , PROVIDERSUBSET VARCHAR(4) NULL
	 , POSTDATE DATETIME NULL
	 , DOSFIRST DATETIME NULL
	 , INVOICED VARCHAR(1) NULL
	 , INVOICEDPPO VARCHAR(1) NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , CARRIERSEQNEW VARCHAR(30) NULL
	 , DOCCTRLTYPE VARCHAR(2) NULL
	 , DOSLAST DATETIME NULL
	 , PPONETWORKID VARCHAR(2) NULL
	 , POS VARCHAR(2) NULL
	 , PROVTYPE VARCHAR(3) NULL
	 , PROVSPECIALTY1 VARCHAR(8) NULL
	 , PROVZIP VARCHAR(9) NULL
	 , PROVSTATE VARCHAR(2) NULL
	 , SUBMITDATE DATETIME NULL
	 , PROVINVOICE VARCHAR(14) NULL
	 , REGION NUMBER(5, 0) NULL
	 , HOSPITALSEQ NUMBER(10, 0) NULL
	 , MODUSERID VARCHAR(2) NULL
	 , STATUS NUMBER(5, 0) NULL
	 , STATUSPRIOR NUMBER(5, 0) NULL
	 , BILLABLELINES NUMBER(5, 0) NULL
	 , TOTALCHARGE NUMBER(19, 4) NULL
	 , BRREDUCTION NUMBER(19, 4) NULL
	 , BRFEE NUMBER(19, 4) NULL
	 , TOTALALLOW NUMBER(19, 4) NULL
	 , TOTALFEE NUMBER(19, 4) NULL
	 , DUPCLIENTCODE VARCHAR(4) NULL
	 , DUPBILLSEQ NUMBER(10, 0) NULL
	 , FUPSTARTDATE DATETIME NULL
	 , FUPENDDATE DATETIME NULL
	 , SENDBACKMSG1SITECODE VARCHAR(3) NULL
	 , SENDBACKMSG1 VARCHAR(6) NULL
	 , SENDBACKMSG2SITECODE VARCHAR(3) NULL
	 , SENDBACKMSG2 VARCHAR(6) NULL
	 , PPOREDUCTION NUMBER(19, 4) NULL
	 , PPOPRC NUMBER(5, 0) NULL
	 , PPOCONTRACTID VARCHAR(30) NULL
	 , PPOSTATUS VARCHAR(1) NULL
	 , PPOFEE NUMBER(19, 4) NULL
	 , NGDREDUCTION NUMBER(19, 4) NULL
	 , NGDFEE NUMBER(19, 4) NULL
	 , URFEE NUMBER(19, 4) NULL
	 , OTHERDATA VARCHAR(30) NULL
	 , EXTERNALSTATUS VARCHAR(1) NULL
	 , URFLAG VARCHAR(1) NULL
	 , VISITS NUMBER(5, 0) NULL
	 , TOS VARCHAR(2) NULL
	 , TOB VARCHAR(1) NULL
	 , SUBPRODUCTCODE VARCHAR(1) NULL
	 , FORCEPAY VARCHAR(1) NULL
	 , PMTAUTH VARCHAR(4) NULL
	 , FLOWSTATUS VARCHAR(1) NULL
	 , CONSULTDATE DATETIME NULL
	 , RCVDDATE DATETIME NULL
	 , ADMISSIONTYPE VARCHAR(1) NULL
	 , PAIDDATE DATETIME NULL
	 , ADMITDATE DATETIME NULL
	 , DISCHARGEDATE DATETIME NULL
	 , TXBILLTYPE VARCHAR(1) NULL
	 , RCVDBRDATE DATETIME NULL
	 , DUEDATE DATETIME NULL
	 , ADJUSTER VARCHAR(25) NULL
	 , DOI DATETIME NULL
	 , RETCTRLFLG VARCHAR(1) NULL
	 , RETCTRLNUM VARCHAR(9) NULL
	 , SITECODE VARCHAR(3) NULL
	 , SOURCEID VARCHAR(2) NULL
	 , CASETYPE VARCHAR(1) NULL
	 , SUBPRODUCTID VARCHAR(30) NULL
	 , SUBPRODUCTPRICE NUMBER(19, 4) NULL
	 , URREDUCTION NUMBER(19, 4) NULL
	 , PROVLICENSENUM VARCHAR(30) NULL
	 , PROVMEDICARENUM VARCHAR(20) NULL
	 , PROVSPECIALTY2 VARCHAR(8) NULL
	 , PMTEXPORTDATE DATETIME NULL
	 , PMTACCEPTDATE DATETIME NULL
	 , CLIENTTOB VARCHAR(5) NULL
	 , BRFEENET NUMBER(19, 4) NULL
	 , PPOFEENET NUMBER(19, 4) NULL
	 , NGDFEENET NUMBER(19, 4) NULL
	 , URFEENET NUMBER(19, 4) NULL
	 , SUBPRODUCTPRICENET NUMBER(19, 4) NULL
	 , BILLSEQNEWREV NUMBER(10, 0) NULL
	 , BILLSEQORGREV NUMBER(10, 0) NULL
	 , VOCPLANSEQ NUMBER(5, 0) NULL
	 , REVIEWDATE DATETIME NULL
	 , AUDITDATE DATETIME NULL
	 , REEVALALLOW NUMBER(19, 4) NULL
	 , CHECKNUM VARCHAR(30) NULL
	 , NEGOTYPE VARCHAR(2) NULL
	 , DISCHARGEHOUR VARCHAR(2) NULL
	 , UB92TOB VARCHAR(3) NULL
	 , MCO VARCHAR(10) NULL
	 , DRG VARCHAR(3) NULL
	 , PATIENTACCOUNT VARCHAR(20) NULL
	 , EXAMINERREVFLAG VARCHAR(1) NULL
	 , REFPROVNAME VARCHAR(40) NULL
	 , PAIDAMOUNT NUMBER(19, 4) NULL
	 , ADMISSIONSOURCE VARCHAR(1) NULL
	 , ADMITHOUR VARCHAR(2) NULL
	 , PATIENTSTATUS VARCHAR(2) NULL
	 , DRGVALUE NUMBER(19, 4) NULL
	 , COMPANYSEQ NUMBER(5, 0) NULL
	 , TOTALCOPAY NUMBER(19, 4) NULL
	 , UB92PROCMETHOD VARCHAR(1) NULL
	 , TOTALDEDUCTIBLE NUMBER(19, 4) NULL
	 , POLICYCOPAYAMOUNT NUMBER(19, 4) NULL
	 , POLICYCOPAYPCT NUMBER(5, 0) NULL
	 , DOCCTRLID VARCHAR(50) NULL
	 , RESOURCEUTILGROUP VARCHAR(4) NULL
	 , POLICYDEDUCTIBLE NUMBER(19, 4) NULL
	 , POLICYLIMIT NUMBER(19, 4) NULL
	 , POLICYTIMELIMIT NUMBER(5, 0) NULL
	 , POLICYWARNINGPCT NUMBER(5, 0) NULL
	 , APPBENEFITS VARCHAR(1) NULL
	 , APPASSIGNEE VARCHAR(1) NULL
	 , CREATEDATE DATETIME NULL
	 , MODDATE DATETIME NULL
	 , INCREMENTVALUE NUMBER(5, 0) NULL
	 , ADJVERIFREQUESTDATE DATETIME NULL
	 , ADJVERIFRCVDDATE DATETIME NULL
	 , RENDERINGPROVLASTNAME VARCHAR(35) NULL
	 , RENDERINGPROVFIRSTNAME VARCHAR(25) NULL
	 , RENDERINGPROVMIDDLENAME VARCHAR(25) NULL
	 , RENDERINGPROVSUFFIX VARCHAR(10) NULL
	 , REREVIEWCOUNT NUMBER(5, 0) NULL
	 , DRGBILLED VARCHAR(3) NULL
	 , DRGCALCULATED VARCHAR(3) NULL
	 , PROVRXLICENSENUM VARCHAR(30) NULL
	 , PROVSIGONFILE VARCHAR(1) NULL
	 , REFPROVFIRSTNAME VARCHAR(30) NULL
	 , REFPROVMIDDLENAME VARCHAR(25) NULL
	 , REFPROVSUFFIX VARCHAR(10) NULL
	 , REFPROVDEANUM VARCHAR(9) NULL
	 , SENDBACKMSG1SUBSET VARCHAR(2) NULL
	 , SENDBACKMSG2SUBSET VARCHAR(2) NULL
	 , PPONETWORKJURISDICTIONIND VARCHAR(1) NULL
	 , MANUALREDUCTIONMODE NUMBER(5, 0) NULL
	 , WHOLESALESALESTAXZIP VARCHAR(9) NULL
	 , RETAILSALESTAXZIP VARCHAR(9) NULL
	 , PPONETWORKJURISDICTIONINSURERSEQ NUMBER(10, 0) NULL
	 , INVOICEDWHOLESALE VARCHAR(1) NULL
	 , INVOICEDPPOWHOLESALE VARCHAR(1) NULL
	 , ADMITTINGDXREF NUMBER(5, 0) NULL
	 , ADMITTINGDXCODE VARCHAR(8) NULL
	 , PROVFACILITYNPI VARCHAR(10) NULL
	 , PROVBILLINGNPI VARCHAR(10) NULL
	 , PROVRENDERINGNPI VARCHAR(10) NULL
	 , PROVOPERATINGNPI VARCHAR(10) NULL
	 , PROVREFERRINGNPI VARCHAR(10) NULL
	 , PROVOTHER1NPI VARCHAR(10) NULL
	 , PROVOTHER2NPI VARCHAR(10) NULL
	 , PROVOPERATINGLICENSENUM VARCHAR(30) NULL
	 , EHUBID VARCHAR(50) NULL
	 , OTHERBILLINGPROVIDERSUBSET VARCHAR(4) NULL
	 , OTHERBILLINGPROVIDERSEQ NUMBER(19, 0) NULL
	 , RESUBMISSIONREASONCODE VARCHAR(2) NULL
	 , CONTRACTTYPE VARCHAR(2) NULL
	 , CONTRACTAMOUNT NUMBER(19, 4) NULL
	 , PRIORAUTHREFERRALNUM1 VARCHAR(30) NULL
	 , PRIORAUTHREFERRALNUM2 VARCHAR(30) NULL
	 , DRGCOMPOSITEFACTOR NUMBER(19, 4) NULL
	 , DRGDISCHARGEFRACTION NUMBER(19, 4) NULL
	 , DRGINPATIENTMULTIPLIER NUMBER(19, 4) NULL
	 , DRGWEIGHT NUMBER(19, 4) NULL
	 , EFTPMTMETHODCODE VARCHAR(3) NULL
	 , EFTPMTFORMATCODE VARCHAR(10) NULL
	 , EFTSENDERDFIID VARCHAR(27) NULL
	 , EFTSENDERACCTNUM VARCHAR(50) NULL
	 , EFTORIGCOSUPPLCODE VARCHAR(24) NULL
	 , EFTRECEIVERDFIID VARCHAR(27) NULL
	 , EFTRECEIVERACCTQUAL VARCHAR(3) NULL
	 , EFTRECEIVERACCTNUM VARCHAR(50) NULL
	 , POLICYLIMITRESULT VARCHAR(1) NULL
	 , HISTORYBATCHNUMBER NUMBER(10, 0) NULL
	 , PROVBILLINGTAXONOMY VARCHAR(11) NULL
	 , PROVFACILITYTAXONOMY VARCHAR(11) NULL
	 , PROVRENDERINGTAXONOMY VARCHAR(11) NULL
	 , PPOSTACKLIST VARCHAR(255) NULL
	 , ICDVERSION NUMBER(5, 0) NULL
	 , ODGFLAG NUMBER(5, 0) NULL
	 , PROVBILLLICENSENUM VARCHAR(30) NULL
	 , PROVFACILITYLICENSENUM VARCHAR(30) NULL
	 , PROVVENDOREXTERNALID VARCHAR(30) NULL
	 , BRACTUALCLIENTCODE VARCHAR(4) NULL
	 , BROVERRIDECLIENTCODE VARCHAR(4) NULL
	 , BILLREEVALREASONCODE VARCHAR(30) NULL
	 , PAYMENTCLEAREDDATE DATETIME NULL
	 , ESTIMATEDBRCLIENTCODE VARCHAR(4) NULL
	 , ESTIMATEDBRJURIS VARCHAR(2) NULL
	 , OVERRIDEFEECONTROLRETAIL VARCHAR(4) NULL
	 , OVERRIDEFEECONTROLWHOLESALE VARCHAR(4) NULL
	 , StatementThroughDate DATETIME NULL
	 , StatementFromDate DATETIME NULL
);


CALL ADM.ALTER_COLUMN('ADD', 'SRC', 'BILL', 'StatementFromDate', 'DATETIME', 'NULL');

CALL ADM.ALTER_COLUMN('ADD', 'SRC', 'BILL', 'StatementThroughDate', 'DATETIME', 'NULL');
