CREATE TABLE IF NOT EXISTS src.LineMod (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , LINESEQ NUMBER(5, 0) NOT NULL
	 , MODSEQ NUMBER(5, 0) NOT NULL
	 , USERENTERED VARCHAR(1) NULL
	 , MODSITECODE VARCHAR(3) NULL
	 , MODIFIER VARCHAR(6) NULL
	 , REDUCTIONCODE NUMBER(5, 0) NULL
	 , MODSUBSET VARCHAR(2) NULL
	 , MODUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , REASONCLIENTCODE VARCHAR(4) NULL
	 , REASONBILLSEQ NUMBER(10, 0) NULL
	 , REASONLINESEQ NUMBER(5, 0) NULL
	 , REASONTYPE VARCHAR(1) NULL
	 , REASONVALUE VARCHAR(30) NULL
);

