CREATE TABLE IF NOT EXISTS src.ProviderSpecialty (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , ID VARCHAR NOT NULL
	 , DESCRIPTION VARCHAR NULL
	 , IMPLEMENTATIONDATE TIMESTAMP_NTZ(0) NULL
	 , DEACTIVATIONDATE TIMESTAMP_NTZ(0) NULL
	 , DATASOURCE VARCHAR NULL
	 , CREATOR VARCHAR(128) NULL
	 , CREATEDATE TIMESTAMP_NTZ(0) NULL
	 , LASTUPDATER VARCHAR(128) NULL
	 , LASTUPDATEDATE TIMESTAMP_NTZ(0) NULL
	 , CBRCODE VARCHAR(4) NULL
);

