CREATE TABLE IF NOT EXISTS src.BillICDDiagnosis (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , BILLDIAGNOSISSEQ NUMBER(5, 0) NOT NULL
	 , ICDDIAGNOSISID NUMBER(10, 0) NULL
	 , POA VARCHAR(1) NULL
	 , BILLEDICDDIAGNOSIS VARCHAR(8) NULL
	 , ICDBILLUSAGETYPEID NUMBER(5, 0) NOT NULL
);

