CREATE TABLE IF NOT EXISTS src.MedicareICQM (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , JURISDICTION VARCHAR(2) NOT NULL
	 , MDICQMSEQ NUMBER(10, 0) NOT NULL
	 , PROVIDERNUM VARCHAR(6) NULL
	 , PROVSUFFIX VARCHAR(1) NULL
	 , SERVICECODE VARCHAR(25) NULL
	 , HCPCS VARCHAR(5) NULL
	 , REVENUE VARCHAR(3) NULL
	 , MEDICAREICQMDESCRIPTION VARCHAR(40) NULL
	 , IP1995 NUMBER(10, 0) NULL
	 , OP1995 NUMBER(10, 0) NULL
	 , IP1996 NUMBER(10, 0) NULL
	 , OP1996 NUMBER(10, 0) NULL
	 , IP1997 NUMBER(10, 0) NULL
	 , OP1997 NUMBER(10, 0) NULL
	 , IP1998 NUMBER(10, 0) NULL
	 , OP1998 NUMBER(10, 0) NULL
	 , NPI VARCHAR(10) NULL
);

