CREATE OR REPLACE TABLE stg.Modifier (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , JURISDICTION VARCHAR(2) NOT NULL
	 , CODE VARCHAR(6) NOT NULL
	 , SITECODE VARCHAR(3) NOT NULL
	 , FUNC VARCHAR(1) NULL
	 , VAL VARCHAR(3) NULL
	 , MODTYPE VARCHAR(1) NULL
	 , GROUPCODE VARCHAR(2) NULL
	 , MODDESCRIPTION VARCHAR(30) NULL
	 , MODCOMMENT1 VARCHAR(70) NULL
	 , MODCOMMENT2 VARCHAR(70) NULL
	 , CREATEDATE DATETIME NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , MODUSERID VARCHAR(2) NULL
	 , STATUTE VARCHAR(30) NULL
	 , REMARK1 VARCHAR(6) NULL
	 , REMARKQUALIFIER1 VARCHAR(2) NULL
	 , REMARK2 VARCHAR(6) NULL
	 , REMARKQUALIFIER2 VARCHAR(2) NULL
	 , REMARK3 VARCHAR(6) NULL
	 , REMARKQUALIFIER3 VARCHAR(2) NULL
	 , REMARK4 VARCHAR(6) NULL
	 , REMARKQUALIFIER4 VARCHAR(2) NULL
	 , CBREREASONID NUMBER(10, 0) NULL
);

