CREATE OR REPLACE TABLE stg.Jurisdiction (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , JURISDICTIONID VARCHAR(2) NOT NULL
	 , NAME VARCHAR(30) NULL
	 , POSTABLECODE VARCHAR(2) NULL
	 , TOSTABLECODE VARCHAR(2) NULL
	 , TOBTABLECODE VARCHAR(2) NULL
	 , PROVTYPETABLECODE VARCHAR(2) NULL
	 , HOSPITAL VARCHAR(1) NULL
	 , PROVSPCLTABLECODE VARCHAR(2) NULL
	 , DAYSTOPAY NUMBER(5, 0) NULL
	 , DAYSTOPAYQUALIFY VARCHAR(2) NULL
	 , OUTPATIENTFS VARCHAR(1) NULL
	 , PROCFILEVER VARCHAR(1) NULL
	 , ANESTUNIT NUMBER(5, 0) NULL
	 , ANESTRNDUP NUMBER(5, 0) NULL
	 , ANESTFORMAT VARCHAR(1) NULL
	 , STATEMANDATESSN VARCHAR(1) NULL
	 , ICDEDITION NUMBER(5, 0) NULL
	 , ICD10COMPLIANCEDATE DATETIME NULL
	 , EBILLSDAYSTOPAY NUMBER(5, 0) NULL
	 , EBILLSDAYSTOPAYQUALIFY VARCHAR(2) NULL
	 , DISPUTEDAYSTOPAY NUMBER(5, 0) NULL
	 , DISPUTEDAYSTOPAYQUALIFY VARCHAR(2) NULL
);

