CREATE OR REPLACE TABLE stg.Pend (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , PENDSEQ NUMBER(5, 0) NOT NULL
	 , PENDDATE DATETIME NULL
	 , RELEASEFLAG VARCHAR(1) NULL
	 , PENDTOID VARCHAR(13) NULL
	 , PRIORITY VARCHAR(1) NULL
	 , RELEASEDATE DATETIME NULL
	 , REASONCODE VARCHAR(8) NULL
	 , PENDBYUSERID VARCHAR(2) NULL
	 , RELEASEBYUSERID VARCHAR(2) NULL
	 , AUTOPENDFLAG VARCHAR(1) NULL
	 , RULEID VARCHAR(5) NULL
	 , WFTASKSEQ NUMBER(10, 0) NULL
	 , RELEASEDBYEXTERNALUSERNAME VARCHAR(128) NULL
);

