CREATE OR REPLACE TABLE stg.ProviderSys (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , PROVIDERSUBSET VARCHAR(4) NOT NULL
	 , PROVIDERSUBSETDESC VARCHAR(30) NULL
	 , PROVIDERACCESS VARCHAR(1) NULL
	 , TAXADDRREQUIRED VARCHAR(1) NULL
	 , ALLOWDUMMYPROVIDERS VARCHAR(1) NULL
	 , CASCADEUPDATESONIMPORT VARCHAR(1) NULL
	 , ROOTEXTIDOVERRIDEDELIMITER VARCHAR(1) NULL
);

