CREATE OR REPLACE TABLE stg.CityStateZip (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , ZIPCODE VARCHAR(5) NOT NULL
	 , CTYSTKEY VARCHAR(6) NOT NULL
	 , CPYDTLCODE VARCHAR(1) NULL
	 , ZIPCLSCODE VARCHAR(1) NULL
	 , CTYSTNAME VARCHAR(28) NULL
	 , CTYSTNAMEABV VARCHAR(13) NULL
	 , CTYSTFACCODE VARCHAR(1) NULL
	 , CTYSTMAILIND VARCHAR(1) NULL
	 , PRELSTCTYKEY VARCHAR(6) NULL
	 , PRELSTCTYNME VARCHAR(28) NULL
	 , CTYDLVIND VARCHAR(1) NULL
	 , AUTZONEIND VARCHAR(1) NULL
	 , UNQZIPIND VARCHAR(1) NULL
	 , FINANCENUM VARCHAR(6) NULL
	 , STATEABBRV VARCHAR(2) NULL
	 , COUNTYNUM VARCHAR(3) NULL
	 , COUNTYNAME VARCHAR(25) NULL
);

