CREATE OR REPLACE TABLE stg.Claim (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLAIMSYSSUBSET VARCHAR(4) NOT NULL
	 , CLAIMSEQ NUMBER(10, 0) NOT NULL
	 , CLAIMID VARCHAR(35) NULL
	 , DOI DATETIME NULL
	 , PATIENTSSN VARCHAR(9) NULL
	 , PATIENTFIRSTNAME VARCHAR(10) NULL
	 , PATIENTLASTNAME VARCHAR(20) NULL
	 , PATIENTMINITIAL VARCHAR(1) NULL
	 , EXTERNALCLAIMID VARCHAR(35) NULL
	 , POLICYCOPAYAMOUNT NUMBER(19, 4) NULL
	 , POLICYCOPAYPCT NUMBER(5, 0) NULL
	 , POLICYDEDUCTIBLE NUMBER(19, 4) NULL
	 , STATUS VARCHAR(1) NULL
	 , POLICYLIMIT NUMBER(19, 4) NULL
	 , POLICYID VARCHAR(30) NULL
	 , POLICYTIMELIMIT NUMBER(5, 0) NULL
	 , ADJUSTER VARCHAR(25) NULL
	 , POLICYLIMITWARNINGPCT NUMBER(5, 0) NULL
	 , FIRSTDOS DATETIME NULL
	 , LASTDOS DATETIME NULL
	 , LOADDATE DATETIME NULL
	 , MODDATE DATETIME NULL
	 , MODUSERID VARCHAR(2) NULL
	 , PATIENTSEX VARCHAR(1) NULL
	 , PATIENTCITY VARCHAR(20) NULL
	 , PATIENTDOB DATETIME NULL
	 , PATIENTSTREET2 VARCHAR(30) NULL
	 , PATIENTSTATE VARCHAR(2) NULL
	 , PATIENTZIP VARCHAR(9) NULL
	 , PATIENTSTREET1 VARCHAR(30) NULL
	 , MMIDATE DATETIME NULL
	 , BODYPART1 VARCHAR(3) NULL
	 , BODYPART2 VARCHAR(3) NULL
	 , BODYPART3 VARCHAR(3) NULL
	 , BODYPART4 VARCHAR(3) NULL
	 , BODYPART5 VARCHAR(3) NULL
	 , LOCATION VARCHAR(10) NULL
	 , NATUREINJ VARCHAR(3) NULL
	 , URFLAG VARCHAR(1) NULL
	 , CARKNOWDATE DATETIME NULL
	 , CLAIMTYPE VARCHAR(2) NULL
	 , CTRLDAY NUMBER(5, 0) NULL
	 , MCOCHOICE VARCHAR(2) NULL
	 , CLIENTCODEDEFAULT VARCHAR(4) NULL
	 , CLOSEDATE DATETIME NULL
	 , REOPENDATE DATETIME NULL
	 , MEDCLOSEDATE DATETIME NULL
	 , MEDSTIPDATE DATETIME NULL
	 , LEGALSTATUS1 VARCHAR(2) NULL
	 , LEGALSTATUS2 VARCHAR(2) NULL
	 , LEGALSTATUS3 VARCHAR(2) NULL
	 , JURISDICTION VARCHAR(2) NULL
	 , PRODUCTCODE VARCHAR(1) NULL
	 , PLAINTIFFATTORNEYSEQ NUMBER(19, 0) NULL
	 , DEFENDANTATTORNEYSEQ NUMBER(19, 0) NULL
	 , BRANCHID VARCHAR(20) NULL
	 , OCCCODE VARCHAR(2) NULL
	 , CLAIMSEVERITY VARCHAR(2) NULL
	 , DATELOSTBEGAN DATETIME NULL
	 , ACCIDENTEMPLOYMENT VARCHAR(1) NULL
	 , RELATIONTOINSURED VARCHAR(1) NULL
	 , POLICY5DAYS VARCHAR(2) NULL
	 , POLICY90DAYS VARCHAR(2) NULL
	 , JOB5DAYS VARCHAR(2) NULL
	 , JOB90DAYS VARCHAR(2) NULL
	 , LOSTDAYS NUMBER(5, 0) NULL
	 , ACTUALRTWDATE DATETIME NULL
	 , MCOTRANSIND VARCHAR(2) NULL
	 , QUALIFIEDINJWORKIND VARCHAR(2) NULL
	 , PERMSTATIONARYIND VARCHAR(2) NULL
	 , HOSPITALADMIT VARCHAR(2) NULL
	 , QUALIFIEDINJWORKDATE DATETIME NULL
	 , RETTOWORKDATE DATETIME NULL
	 , PERMSTATIONARYDATE DATETIME NULL
	 , MCOFEIN VARCHAR(9) NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , IDCODE VARCHAR(80) NULL
	 , IDTYPE VARCHAR(2) NULL
	 , MPNOPTOUTEFFECTIVEDATE DATETIME NULL
	 , MPNOPTOUTTERMINATIONDATE DATETIME NULL
	 , MPNOPTOUTPHYSICIANNAME VARCHAR(50) NULL
	 , MPNOPTOUTPHYSICIANTIN VARCHAR(9) NULL
	 , MPNCHOICE VARCHAR(2) NULL
	 , JURISDICTIONCLAIMID VARCHAR(35) NULL
	 , POLICYLIMITRESULT VARCHAR(1) NULL
	 , PATIENTPRIMARYPHONE VARCHAR(20) NULL
	 , PATIENTWORKPHONE VARCHAR(20) NULL
	 , PATIENTALTERNATEPHONE VARCHAR(20) NULL
	 , ICDVERSION NUMBER(5, 0) NULL
	 , LASTDATEOFTRAUMA DATETIME NULL
	 , CLAIMADMINCLAIMNUM VARCHAR(35) NULL
	 , PATIENTCOUNTRYCODE VARCHAR(3) NULL
);

