CREATE OR REPLACE TABLE stg.PolicyInsurer (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLAIMSYSSUBSET VARCHAR(4) NOT NULL
	 , POLICYSEQ NUMBER(10, 0) NOT NULL
	 , JURISDICTION VARCHAR(2) NOT NULL
	 , INSURERTYPE VARCHAR(1) NOT NULL
	 , EFFECTIVEDATE DATETIME NOT NULL
	 , INSURERSEQ NUMBER(10, 0) NULL
	 , TERMINATIONDATE DATETIME NULL
);

