CREATE OR REPLACE TABLE stg.ProviderCluster (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , PROVIDERSUBSET VARCHAR(4) NOT NULL
	 , PROVIDERSEQ NUMBER(19, 0) NOT NULL
	 , ORGODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , MITCHELLPROVIDERKEY VARCHAR(200) NULL
	 , PROVIDERCLUSTERKEY VARCHAR(200) NULL
	 , PROVIDERTYPE VARCHAR(30) NULL
);

