CREATE OR REPLACE TABLE stg.PPOContract (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , PPONETWORKID VARCHAR(2) NOT NULL
	 , PPOCONTRACTID VARCHAR(30) NOT NULL
	 , SITECODE VARCHAR(3) NULL
	 , TIN VARCHAR(9) NULL
	 , ALTERNATETIN VARCHAR(9) NULL
	 , STARTDATE DATETIME NULL
	 , ENDDATE DATETIME NULL
	 , OPLINEITEMDEFAULTDISCOUNT NUMBER(5, 0) NULL
	 , COMPANYNAME VARCHAR(35) NULL
	 , FIRST VARCHAR(35) NULL
	 , GROUPCODE VARCHAR(3) NULL
	 , GROUPNAME VARCHAR(40) NULL
	 , OPDISCOUNTBASEVALUE VARCHAR(1) NULL
	 , OPOFFFS NUMBER(5, 0) NULL
	 , OPOFFUCR NUMBER(5, 0) NULL
	 , OPOFFCHARGE NUMBER(5, 0) NULL
	 , OPEFFECTIVEDATE DATETIME NULL
	 , OPADDITIONALDISCOUNTOFFLINK NUMBER(5, 0) NULL
	 , OPTERMINATIONDATE DATETIME NULL
	 , OPUCRPERCENTILE NUMBER(5, 0) NULL
	 , OPCONDITION VARCHAR(2) NULL
	 , IPDISCOUNTBASEVALUE VARCHAR(1) NULL
	 , IPOFFFS NUMBER(5, 0) NULL
	 , IPOFFUCR NUMBER(5, 0) NULL
	 , IPOFFCHARGE NUMBER(5, 0) NULL
	 , IPEFFECTIVEDATE DATETIME NULL
	 , IPTERMINATIONDATE DATETIME NULL
	 , IPCONDITION VARCHAR(2) NULL
	 , IPSTOPCAPAMOUNT NUMBER(19, 4) NULL
	 , IPSTOPCAPRATE NUMBER(5, 0) NULL
	 , MINDISC NUMBER(10, 4) NULL
	 , MAXDISC NUMBER(10, 4) NULL
	 , MEDICALPERDIEM NUMBER(10, 4) NULL
	 , SURGICALPERDIEM NUMBER(10, 4) NULL
	 , ICUPERDIEM NUMBER(10, 4) NULL
	 , PSYCHIATRICPERDIEM NUMBER(10, 4) NULL
	 , MISCPARM VARCHAR(2) NULL
	 , SPCCODE VARCHAR(1) NULL
	 , PPOTYPE VARCHAR(1) NULL
	 , BILLINGADDRESS1 VARCHAR(30) NULL
	 , BILLINGADDRESS2 VARCHAR(30) NULL
	 , BILLINGCITY VARCHAR(20) NULL
	 , BILLINGSTATE VARCHAR(2) NULL
	 , BILLINGZIP VARCHAR(9) NULL
	 , PRACTICEADDRESS1 VARCHAR(30) NULL
	 , PRACTICEADDRESS2 VARCHAR(30) NULL
	 , PRACTICECITY VARCHAR(20) NULL
	 , PRACTICESTATE VARCHAR(2) NULL
	 , PRACTICEZIP VARCHAR(9) NULL
	 , PHONENUM VARCHAR(10) NULL
	 , OUTFILE VARCHAR(12) NULL
	 , INPATFILE VARCHAR(12) NULL
	 , URCOORDINATORFLAG VARCHAR(1) NULL
	 , EXCLUSIVEPPOORGFLAG VARCHAR(1) NULL
	 , STOPLOSSTYPECODE VARCHAR(4) NULL
	 , BR_RNEDISCOUNT NUMBER(5, 0) NULL
	 , MODDATE DATETIME NULL
	 , EXPORTFLAG VARCHAR(1) NULL
	 , OPMANUALINDICATOR VARCHAR(1) NULL
	 , OPSTOPCAPAMOUNT NUMBER(19, 4) NULL
	 , OPSTOPCAPRATE NUMBER(5, 0) NULL
	 , SPECIALTY1 VARCHAR(4) NULL
	 , SPECIALTY2 VARCHAR(4) NULL
	 , LESSOROFTHRESHOLD NUMBER(5, 0) NULL
	 , BILATERALDISCOUNT NUMBER(5, 0) NULL
	 , SURGERYDISCOUNT2 NUMBER(5, 0) NULL
	 , SURGERYDISCOUNT3 NUMBER(5, 0) NULL
	 , SURGERYDISCOUNT4 NUMBER(5, 0) NULL
	 , SURGERYDISCOUNT5 NUMBER(5, 0) NULL
	 , MATRIX VARCHAR(1) NULL
	 , PROVTYPE VARCHAR(5) NULL
	 , ALLINCLUSIVE VARCHAR(1) NULL
	 , REGION VARCHAR(4) NULL
	 , PAYMENTADDRESSFLAG VARCHAR(1) NULL
	 , MEDICALGROUP VARCHAR(1) NULL
	 , MEDICALGROUPCODE VARCHAR(4) NULL
	 , RATEMODE VARCHAR(1) NULL
	 , PRACTICECOUNTY VARCHAR(25) NULL
	 , FIPSCOUNTYCODE VARCHAR(3) NULL
	 , PRIMARYCAREFLAG VARCHAR(1) NULL
	 , PPOCONTRACTIDOLD VARCHAR(14) NULL
	 , MULTISURG VARCHAR(1) NULL
	 , BILEVEL VARCHAR(1) NULL
	 , DRGRATE NUMBER(10, 4) NULL
	 , DRGGREATERTHANBC NUMBER(5, 0) NULL
	 , DRGMINPERCENTBC NUMBER(5, 0) NULL
	 , CARVEOUT VARCHAR(1) NULL
	 , PPOTOFSSEQ NUMBER(10, 0) NULL
	 , LICENSENUM VARCHAR(30) NULL
	 , MEDICARENUM VARCHAR(20) NULL
	 , NPI VARCHAR(10) NULL
);

