CREATE OR REPLACE TABLE stg.Insurer (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , INSURERTYPE VARCHAR(1) NOT NULL
	 , INSURERSEQ NUMBER(10, 0) NOT NULL
	 , JURISDICTION VARCHAR(2) NULL
	 , STATEID VARCHAR(30) NULL
	 , TIN VARCHAR(9) NULL
	 , ALTID VARCHAR(18) NULL
	 , NAME VARCHAR(30) NULL
	 , ADDRESS1 VARCHAR(30) NULL
	 , ADDRESS2 VARCHAR(30) NULL
	 , CITY VARCHAR(20) NULL
	 , STATE VARCHAR(2) NULL
	 , ZIP VARCHAR(9) NULL
	 , PHONENUM VARCHAR(20) NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , CREATEDATE DATETIME NULL
	 , MODUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , FAXNUM VARCHAR(20) NULL
	 , NAICCOCODE VARCHAR(6) NULL
	 , NAICGPCODE VARCHAR(30) NULL
	 , NCCICARRIERCODE VARCHAR(5) NULL
	 , NCCIGROUPCODE VARCHAR(5) NULL
);

