CREATE OR REPLACE TABLE stg.PendComment (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , PENDSEQ NUMBER(5, 0) NOT NULL
	 , PENDCOMMENTSEQ NUMBER(5, 0) NOT NULL
	 , PENDCOMMENT VARCHAR(7500) NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , CREATEDATE DATETIME NULL
	 , CREATEDBYEXTERNALUSERNAME VARCHAR(128) NULL
);

