CREATE OR REPLACE TABLE stg.BillPPORate (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , LINKNAME VARCHAR(12) NOT NULL
	 , RATETYPE VARCHAR(8) NOT NULL
	 , APPLIED VARCHAR(1) NULL
);

