CREATE OR REPLACE TABLE stg.PPORateType (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , RATETYPECODE VARCHAR(8) NOT NULL
	 , PPONETWORKID VARCHAR(2) NULL
	 , CATEGORY VARCHAR(1) NULL
	 , PRIORITY VARCHAR(1) NULL
	 , VBCOLOR NUMBER(5, 0) NULL
	 , RATETYPEDESCRIPTION VARCHAR(70) NULL
	 , EXPLANATION VARCHAR(6000) NULL
);

