CREATE OR REPLACE TABLE stg.Policy (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLAIMSYSSUBSET VARCHAR(4) NOT NULL
	 , POLICYSEQ NUMBER(10, 0) NOT NULL
	 , NAME VARCHAR(60) NULL
	 , EXTERNALID VARCHAR(20) NULL
	 , POLICYID VARCHAR(30) NULL
	 , ADMINKEY VARCHAR(40) NULL
	 , LOCATIONCODE VARCHAR(10) NULL
	 , ADDRESS1 VARCHAR(30) NULL
	 , ADDRESS2 VARCHAR(30) NULL
	 , CITY VARCHAR(20) NULL
	 , STATE VARCHAR(2) NULL
	 , ZIP VARCHAR(9) NULL
	 , PHONENUM VARCHAR(20) NULL
	 , FAXNUM VARCHAR(20) NULL
	 , EFFECTIVEDATE DATETIME NULL
	 , TERMINATIONDATE DATETIME NULL
	 , TIN VARCHAR(9) NULL
	 , STATETAXID VARCHAR(30) NULL
	 , DEPTINDUSRELNUM VARCHAR(20) NULL
	 , EQOPPINDICATOR VARCHAR(1) NULL
	 , MODUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , MCOFLAG VARCHAR(1) NULL
	 , MCOSTARTDATE DATETIME NULL
	 , FEERATECTRLEX VARCHAR(4) NULL
	 , CREATEBY VARCHAR(2) NULL
	 , FEERATECTRLIN VARCHAR(4) NULL
	 , CREATEDATE DATETIME NULL
	 , SELFINSURED VARCHAR(1) NULL
	 , NAICSCODE VARCHAR(15) NULL
	 , MONTHLYPREMIUM NUMBER(19, 4) NULL
	 , PPOPROFILESITECODE VARCHAR(3) NULL
	 , PPOPROFILEID NUMBER(10, 0) NULL
	 , SALESTAXEXEMPT VARCHAR(1) NULL
	 , RECEIPTHANDLINGCODE VARCHAR(1) NULL
	 , TXNONSUBSCRIB VARCHAR(1) NULL
	 , SUBDIVISIONNAME VARCHAR(60) NULL
	 , POLICYCOPAYAMOUNT NUMBER(19, 4) NULL
	 , POLICYCOPAYPCT NUMBER(5, 0) NULL
	 , POLICYDEDUCTIBLE NUMBER(19, 4) NULL
	 , POLICYLIMITAMOUNT NUMBER(19, 4) NULL
	 , POLICYTIMELIMIT NUMBER(5, 0) NULL
	 , POLICYLIMITWARNINGPCT NUMBER(5, 0) NULL
	 , POLICYLIMITRESULT VARCHAR(1) NULL
	 , URPROFILEID VARCHAR(8) NULL
);

