CREATE OR REPLACE TABLE stg.AttorneyAddress (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLAIMSYSSUBSET VARCHAR(4) NOT NULL
	 , ATTORNEYADDRESSSEQ NUMBER(10, 0) NOT NULL
	 , RECTYPE VARCHAR(2) NULL
	 , ADDRESS1 VARCHAR(30) NULL
	 , ADDRESS2 VARCHAR(30) NULL
	 , CITY VARCHAR(30) NULL
	 , STATE VARCHAR(2) NULL
	 , ZIP VARCHAR(9) NULL
	 , PHONENUM VARCHAR(20) NULL
	 , FAXNUM VARCHAR(20) NULL
	 , CONTACTFIRSTNAME VARCHAR(20) NULL
	 , CONTACTLASTNAME VARCHAR(20) NULL
	 , CONTACTMIDDLEINITIAL VARCHAR(1) NULL
	 , URFIRSTNAME VARCHAR(20) NULL
	 , URLASTNAME VARCHAR(20) NULL
	 , URMIDDLEINITIAL VARCHAR(1) NULL
	 , FACILITYNAME VARCHAR(30) NULL
	 , COUNTRYCODE VARCHAR(3) NULL
	 , MAILCODE VARCHAR(20) NULL
);

