CREATE OR REPLACE TABLE stg.FSProcedureMV (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , JURISDICTION VARCHAR(2) NOT NULL
	 , EXTENSION VARCHAR(3) NOT NULL
	 , PROCEDURECODE VARCHAR(6) NOT NULL
	 , EFFECTIVEDATE DATETIME NOT NULL
	 , TERMINATIONDATE DATETIME NULL
	 , FSPROCDESCRIPTION VARCHAR(24) NULL
	 , SV VARCHAR(1) NULL
	 , STAR VARCHAR(1) NULL
	 , PANEL VARCHAR(1) NULL
	 , IP VARCHAR(1) NULL
	 , MULT VARCHAR(1) NULL
	 , ASSTSURGEON VARCHAR(1) NULL
	 , SECTIONFLAG VARCHAR(1) NULL
	 , FUP VARCHAR(3) NULL
	 , BAV NUMBER(5, 0) NULL
	 , PROCGROUP VARCHAR(4) NULL
	 , VIEWTYPE NUMBER(5, 0) NULL
	 , UNITVALUE NUMBER(19, 4) NULL
	 , PROUNITVALUE NUMBER(19, 4) NULL
	 , TECHUNITVALUE NUMBER(19, 4) NULL
	 , SITECODE VARCHAR(3) NULL
);

