CREATE OR REPLACE TABLE stg.ReductionType (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , REDUCTIONCODE NUMBER(5, 0) NOT NULL
	 , REDUCTIONDESCRIPTION VARCHAR(50) NULL
	 , BEOVERRIDE VARCHAR(1) NULL
	 , BEMSG VARCHAR(1) NULL
	 , ABBREVIATION VARCHAR(8) NULL
	 , DEFAULTMESSAGECODE VARCHAR(6) NULL
	 , DEFAULTDENIALMESSAGECODE VARCHAR(6) NULL
);

