CREATE OR REPLACE TABLE stg.ClaimSys (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLAIMSYSSUBSET VARCHAR(4) NOT NULL
	 , CLAIMIDMASK VARCHAR(35) NULL
	 , CLAIMACCESS VARCHAR(1) NULL
	 , CLAIMSYSDESC VARCHAR(30) NULL
	 , POLICYHOLDERREQ VARCHAR(1) NULL
	 , VALIDATEBRANCH VARCHAR(1) NULL
	 , VALIDATEPOLICY VARCHAR(1) NULL
	 , LGLCODE1TABLECODE VARCHAR(2) NULL
	 , LGLCODE2TABLECODE VARCHAR(2) NULL
	 , LGLCODE3TABLECODE VARCHAR(2) NULL
	 , UROCCTABLECODE VARCHAR(2) NULL
	 , POLICY5DAYSTABLECODE VARCHAR(2) NULL
	 , POLICY90DAYSTABLECODE VARCHAR(2) NULL
	 , JOB5DAYSTABLECODE VARCHAR(2) NULL
	 , JOB90DAYSTABLECODE VARCHAR(2) NULL
	 , HCOTRANSINDTABLECODE VARCHAR(2) NULL
	 , QUALIFIEDINJWORKTABLECODE VARCHAR(2) NULL
	 , PERMSTATIONARYTABLECODE VARCHAR(2) NULL
	 , VALIDATEADJUSTER VARCHAR(1) NULL
	 , MCOPROGRAM VARCHAR(1) NULL
	 , ADJUSTERREQUIRED VARCHAR(1) NULL
	 , HOSPITALADMITTABLECODE VARCHAR(2) NULL
	 , ATTORNEYTAXADDRREQUIRED VARCHAR(1) NULL
	 , BODYPARTTABLECODE VARCHAR(2) NULL
	 , POLICYDEFAULTS VARCHAR(1) NULL
	 , POLICYCOPAYAMOUNT NUMBER(19, 4) NULL
	 , POLICYCOPAYPCT NUMBER(5, 0) NULL
	 , POLICYDEDUCTIBLE NUMBER(19, 4) NULL
	 , POLICYLIMIT NUMBER(19, 4) NULL
	 , POLICYTIMELIMIT NUMBER(5, 0) NULL
	 , POLICYLIMITWARNINGPCT NUMBER(5, 0) NULL
	 , RESTRICTUSERACCESS VARCHAR(1) NULL
	 , BEOVERRIDEPERMISSIONFLAG VARCHAR(1) NULL
	 , ROOTCLAIMLENGTH NUMBER(5, 0) NULL
	 , RELATECLAIMSTOTALPOLICYDETAIL VARCHAR(1) NULL
	 , POLICYLIMITRESULT VARCHAR(1) NULL
	 , ENABLECLAIMCLIENTCODEDEFAULT VARCHAR(1) NULL
	 , REEVALCOPYDOCCTRLID VARCHAR(1) NULL
	 , ENABLECEPHEADERFIELDEDITS VARCHAR(1) NULL
	 , ENABLESMARTCLIENTSELECTION VARCHAR(1) NULL
	 , SCSCLIENTSELECTIONCODE VARCHAR(12) NULL
	 , SCSPROVIDERSUBSET VARCHAR(4) NULL
	 , SCSCLIENTCODEMASK VARCHAR(4) NULL
	 , SCSDEFAULTCLIENT VARCHAR(4) NULL
	 , CLAIMEXTERNALIDASCARRIERCLAIMID VARCHAR(1) NULL
	 , POLICYEXTERNALIDASCARRIERPOLICYID VARCHAR(1) NULL
	 , URPROFILEID VARCHAR(8) NULL
	 , BEUROVERRIDESREQUIREREVIEWREF VARCHAR(1) NULL
	 , URENTRYVALIDATIONS VARCHAR(1) NULL
	 , PENDPPOEDICONTROL VARCHAR(1) NULL
	 , BEREEVALLINEADDDELETE VARCHAR(1) NULL
	 , CPTGROUPTOINDIVIDUAL VARCHAR(1) NULL
	 , CLAIMEXTERNALIDASCLAIMADMINCLAIMNUM VARCHAR(1) NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , CREATEDATE DATETIME NULL
	 , MODUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , FINANCIALAGGREGATION VARCHAR NULL
);

