CREATE OR REPLACE TABLE stg.EntityType (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , ENTITYTYPEID NUMBER(10, 0) NOT NULL
	 , ENTITYTYPEKEY VARCHAR(250) NULL
	 , DESCRIPTION VARCHAR NULL
);

