CREATE OR REPLACE TABLE stg.LineReduction (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , LINESEQ NUMBER(5, 0) NOT NULL
	 , REDUCTIONCODE NUMBER(5, 0) NOT NULL
	 , REDUCTIONAMOUNT NUMBER(19, 4) NULL
	 , OVERRIDEAMOUNT NUMBER(19, 4) NULL
	 , MODUSERID VARCHAR(2) NULL
);

