CREATE OR REPLACE TABLE stg.EDIControl (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , EDICONTROLSEQ NUMBER(10, 0) NOT NULL
	 , EDIMAPTOOLSITECODE VARCHAR(3) NULL
	 , EDIPORTTYPE VARCHAR(1) NULL
	 , EDIMAPTOOLID NUMBER(10, 0) NULL
	 , NAME VARCHAR(50) NULL
	 , LASTTAPEDATE DATETIME NULL
	 , LASTSTARTDATE DATETIME NULL
	 , LASTENDDATE DATETIME NULL
	 , DAYCOUNTER NUMBER(5, 0) NULL
	 , TOTALCOUNTER NUMBER(10, 0) NULL
	 , VENDORNUM VARCHAR(20) NULL
	 , VENDORCONTACT VARCHAR(50) NULL
	 , VENDORPHONE VARCHAR(10) NULL
	 , ACCOUNTNUM VARCHAR(20) NULL
	 , OFFICENUM VARCHAR(20) NULL
	 , EDISENDERQUALIFIER VARCHAR(2) NULL
	 , EDISENDERIDENTIFIER VARCHAR(15) NULL
	 , EDIRECEIVERQUALIFIER VARCHAR(2) NULL
	 , EDIRECEIVERIDENTIFIER VARCHAR(15) NULL
	 , EDIACKNOWLEDGEMENT VARCHAR(1) NULL
	 , EDITESTINDICATOR VARCHAR(1) NULL
	 , EXPORTCREDITS VARCHAR(1) NULL
	 , EXPORTNEGATIVES VARCHAR(1) NULL
	 , CREATEEORS VARCHAR(1) NULL
	 , SPECIALPROCESSFLAG VARCHAR(120) NULL
	 , ARCOMPANY VARCHAR(20) NULL
	 , ARCONTACT VARCHAR(30) NULL
	 , ARADDR1 VARCHAR(30) NULL
	 , ARADDR2 VARCHAR(30) NULL
	 , ARCITY VARCHAR(30) NULL
	 , ARSTATE VARCHAR(2) NULL
	 , ARZIP VARCHAR(9) NULL
	 , ARPHONE VARCHAR(10) NULL
	 , EDISENDERZIP VARCHAR(9) NULL
	 , EDIRECEIVERZIP VARCHAR(9) NULL
	 , CREATEDATE DATETIME NULL
	 , CREATEUSERID VARCHAR(2) NULL
	 , MODDATE DATETIME NULL
	 , MODUSERID VARCHAR(2) NULL
	 , PENDUSERGROUP VARCHAR(12) NULL
	 , DAYBILLCOUNT NUMBER(10, 0) NULL
	 , TOTALBILLCOUNT NUMBER(19, 0) NULL
	 , EXPORTZEROALLOWBILLS VARCHAR(1) NULL
	 , CREATENF10S VARCHAR(1) NULL
	 , PRINTNF10IDENTIFIER VARCHAR(1) NULL
	 , NF10FILEFORMAT VARCHAR(3) NULL
	 , EORFILEFORMAT VARCHAR(3) NULL
	 , PRINTEORIDENTIFIER VARCHAR(1) NULL
	 , CREATEEORWITHNF10 VARCHAR(1) NULL
	 , EXCLUDEADJUSTER VARCHAR(1) NULL
	 , EXCLUDEATTORNEY VARCHAR(1) NULL
	 , EXCLUDEBRANCH VARCHAR(1) NULL
	 , EXCLUDECLAIM VARCHAR(1) NULL
	 , EXCLUDEINSURER VARCHAR(1) NULL
	 , EXCLUDEPOLICY VARCHAR(1) NULL
	 , DAYSPAST NUMBER(5, 0) NULL
	 , EMAILNOTIFICATIONLIST VARCHAR(255) NULL
	 , WFVALIDATIONFLAG VARCHAR(1) NULL
	 , PRINTNF10PROVBILLINGADDR VARCHAR(1) NULL
	 , BATCHACKSLA NUMBER(10, 0) NULL
	 , DETAILACKSLA NUMBER(10, 0) NULL
	 , EXPORTOTHERBILLINGPROVIDER VARCHAR(1) NULL
	 , FORMATREVENUECODES VARCHAR(1) NULL
	 , CREATEC8S VARCHAR(1) NULL
	 , PRINTC8IDENTIFIER VARCHAR(1) NULL
	 , CREATEEORWITHC8 VARCHAR(1) NULL
	 , NYPROVIDERC81 VARCHAR(1) NULL
	 , NYPROVIDERC84 VARCHAR(1) NULL
	 , NYPROVIDERC8IDENTIFIER VARCHAR(1) NULL
	 , NYPROVIDERC8EOR VARCHAR(1) NULL
	 , NYBOARDC81 VARCHAR(1) NULL
	 , NYBOARDC84 VARCHAR(1) NULL
	 , NYBOARDC8IDENTIFIER VARCHAR(1) NULL
	 , NYBOARDC8EOR VARCHAR(1) NULL
	 , NYCLAIMANTC81 VARCHAR(1) NULL
	 , NYCLAIMANTC8IDENTIFIER VARCHAR(1) NULL
	 , NYCLAIMANTC8EOR VARCHAR(1) NULL
	 , NYCLAIMANTC8EORCOVER VARCHAR(1) NULL
	 , NYATTORNEYC81 VARCHAR(1) NULL
	 , NYATTORNEYC8IDENTIFIER VARCHAR(1) NULL
	 , NYATTORNEYC8EOR VARCHAR(1) NULL
	 , NYATTORNEYC8EORCOVER VARCHAR(1) NULL
	 , NYPROVIDERFORMAT VARCHAR(3) NULL
	 , NYBOARDFORMAT VARCHAR(3) NULL
	 , NYCLAIMANTFORMAT VARCHAR(3) NULL
	 , NYATTORNEYFORMAT VARCHAR(3) NULL
	 , EXPORTPPOBILLCOMMENT VARCHAR(1) NULL
	 , INCLUDENETWORK VARCHAR(1) NULL
	 , INCLUDECLAIMUDF VARCHAR(1) NULL
	 , INCLUDEPROVIDERUDF VARCHAR(1) NULL
	 , INCLUDEBILLUDF VARCHAR(1) NULL
	 , NETREEVALFEES VARCHAR(1) NULL
	 , EXPORTCARCS VARCHAR(1) NULL
	 , EXTENDEDHEADER VARCHAR(1) NULL
	 , EXTENDEDTRAILER VARCHAR(1) NULL
	 , SUBMISSIONREASONCODE VARCHAR(50) NULL
	 , INCLUDEBILLATTACHMENT VARCHAR(1) NULL
	 , USEEXTENDEDLAYOUT VARCHAR(120) NULL
	 , EXCLUDEBILLATTACHMENT VARCHAR(500) NULL
	 , EXPORTDIARYNOTES VARCHAR(1) NULL
	 , UPDATEZABILLCONTROLTOACCEPTED VARCHAR(1) NULL
	 , UPDATEZAPAIDDATETOPOSTDATE VARCHAR(1) NULL
	 , SETZAPAIDDATETOPOSTDATEDAYS NUMBER(10, 0) NULL
	 , INCLUDEADJUSTERUDF VARCHAR(1) NULL
	 , INCLUDEPOLICYUDF VARCHAR(1) NULL
	 , EXPORTZEROALLOWREEVALS VARCHAR(1) NULL
	 , UPDATEREVALBILLCONTROLTOACCEPTED VARCHAR(1) NULL
	 , UPDATEREVALPAIDDATETOPOSTDATE VARCHAR(1) NULL
	 , SETREVALPAIDDATETOPOSTDATEDAYS NUMBER(10, 0) NULL
	 , REDUCTIONSPEREORPROFILE VARCHAR(1) NULL
	 , INCLUDEBILLIMAGE VARCHAR(1) NULL
	 , NYCLAIMANTC84 VARCHAR(1) NULL
	 , NYATTORNEYC84 VARCHAR(1) NULL
	 , EDIJURISDICTION VARCHAR(20) NULL
);

