CREATE OR REPLACE TABLE stg.BillICDProcedure (
	  ODSPOSTINGGROUPAUDITID NUMBER(10, 0) NOT NULL
	 , ODSCUSTOMERID NUMBER(10, 0) NOT NULL
	 , ODSCREATEDATE DATETIME NOT NULL
	 , ODSSNAPSHOTDATE DATETIME NOT NULL
	 , ODSROWISCURRENT INT NOT NULL
	 , ODSHASHBYTESVALUE BINARY(8000) NULL
	 , DMLOPERATION VARCHAR(1) NOT NULL
	 , CLIENTCODE VARCHAR(4) NOT NULL
	 , BILLSEQ NUMBER(10, 0) NOT NULL
	 , BILLPROCEDURESEQ NUMBER(5, 0) NOT NULL
	 , ICDPROCEDUREID NUMBER(10, 0) NULL
	 , CODEDATE DATETIME NULL
	 , BILLEDICDPROCEDURE VARCHAR(8) NULL
	 , ICDBILLUSAGETYPEID NUMBER(5, 0) NOT NULL
);

