-- DW_API perissions

GRANT USAGE ON SCHEMA &DB_NAME.CNFG TO ROLE DW_API;
GRANT SELECT ON ALL TABLES IN SCHEMA &DB_NAME.CNFG TO ROLE DW_API;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA &DB_NAME.CNFG TO ROLE DW_API;
GRANT SELECT ON ALL VIEWS IN SCHEMA &DB_NAME.CNFG TO ROLE DW_API;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA &DB_NAME.CNFG TO ROLE DW_API;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA &DB_NAME.CNFG TO ROLE DW_API;

GRANT USAGE ON SCHEMA &DB_NAME.DBO TO ROLE DW_API;
GRANT SELECT ON ALL TABLES IN SCHEMA &DB_NAME.DBO TO ROLE DW_API;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA &DB_NAME.DBO TO ROLE DW_API;
GRANT SELECT ON ALL VIEWS IN SCHEMA &DB_NAME.DBO TO ROLE DW_API;

GRANT USAGE ON SCHEMA &DB_NAME.ADM TO ROLE DW_API;
GRANT SELECT ON ALL TABLES IN SCHEMA &DB_NAME.ADM TO ROLE DW_API;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA &DB_NAME.ADM TO ROLE DW_API;
GRANT SELECT ON ALL VIEWS IN SCHEMA &DB_NAME.ADM TO ROLE DW_API;
