DROP PROCEDURE IF EXISTS ADM.ADD_TABLE_COLUMN(STRING, STRING, STRING, STRING, STRING );
DROP PROCEDURE IF EXISTS ADM.DROP_ALL_FOREIGN_KEYS();
DROP PROCEDURE IF EXISTS ADM.DROP_MATERIALIZED_VIEW(STRING, STRING);
DROP PROCEDURE IF EXISTS ADM.DROP_TABLE(STRING, STRING);
DROP PROCEDURE IF EXISTS ADM.DROP_TABLE_COLUMN(STRING, STRING, STRING );
DROP PROCEDURE IF EXISTS ADM.DROP_VIEW( STRING, STRING);

-- There are a lot of CNFG objects that have been moved to dw_configuration in PostgreSQL.
-- We have a lot of hardcoded stuff used for the POC here, as well.  In order to keep things tidy, 
-- let's drop them here.

-- Functions
DROP FUNCTION IF EXISTS CNFG.FN_GET_GLOBAL_FILTERS(ARRAY);
DROP FUNCTION IF EXISTS CNFG.FN_GET_GLOBAL_HIERARCHIES(ARRAY);
DROP FUNCTION IF EXISTS CNFG.FN_GET_HIERARCHY_PARTICIPANTS(NUMBER, NUMBER, NUMBER, NUMBER);
DROP FUNCTION IF EXISTS CNFG.FN_GET_METRICS();
DROP FUNCTION IF EXISTS CNFG.FN_GET_REPORT_SUBJECT_AREAS();

-- Stored Procedures
DROP PROCEDURE IF EXISTS CNFG.POPULATE_JSON(varchar);
DROP PROCEDURE IF EXISTS CNFG.PROC_API_POC_GEN_RPRT(VARCHAR, VARCHAR, DOUBLE);
DROP PROCEDURE IF EXISTS CNFG.PROC_API_POC_GEN_RPRT_FILTERS(VARCHAR, VARCHAR, DOUBLE, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS CNFG.PROC_EXECUTE_SQL(VARCHAR(16777216));
DROP PROCEDURE IF EXISTS CNFG.PROC_GENERATE_REPORT(VARCHAR(16777216));
DROP PROCEDURE IF EXISTS CNFG.PROC_GENERATE_SQL(VARCHAR(16777216));
DROP PROCEDURE IF EXISTS CNFG.PROC_GENERATE_SQL__API_TESTING(VARCHAR(16777216));
DROP PROCEDURE IF EXISTS CNFG.PROC_GET_HIERARCHY_PARTICIPANTS(double, double, varchar, double, boolean);
DROP PROCEDURE IF EXISTS CNFG.PROC_GETFILTERDROPDOWNLIST(VARCHAR, VARCHAR);

-- Views
DROP VIEW IF EXISTS CNFG.DATA_SOURCE_TO_FILTER_MAPPING;
DROP VIEW IF EXISTS CNFG.METRIC_TO_DATA_SOURCE_MAPPING;
DROP VIEW IF EXISTS CNFG.REPORT_DATA_SOURCE_DEPTH;

-- Tables
DROP TABLE IF EXISTS CNFG.METRIC_CATEGORY;
DROP TABLE IF EXISTS CNFG.METRIC_TO_METRIC_CATEGORY_MAPPING;
DROP TABLE IF EXISTS CNFG.REPORT_COLUMN_DATA_TYPE;
DROP TABLE IF EXISTS CNFG.REPORT_DATA_SOURCE;
DROP TABLE IF EXISTS CNFG.REPORT_FILTER;
DROP TABLE IF EXISTS CNFG.REPORT_FILTER_REPORT_DATA_SOURCE;
DROP TABLE IF EXISTS CNFG.REPORT_HIERARCHY;
DROP TABLE IF EXISTS CNFG.REPORT_HIERARCHY_PARTICIPANT;
DROP TABLE IF EXISTS CNFG.REPORT_HIERARCHY_REPORT_DATA_SOURCE;
DROP TABLE IF EXISTS CNFG.REPORT_METRIC;
DROP TABLE IF EXISTS CNFG.REPORT_METRIC_REPORT_DATA_SOURCE;
DROP TABLE IF EXISTS CNFG.REPORT_SUBJECT_AREA;

