CREATE OR REPLACE VIEW aw.AnalysisRule
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ANALYSISRULEID
		,TITLE
		,ASSEMBLYQUALIFIEDNAME
		,METHODTOINVOKE
		,DISPLAYMESSAGE
		,DISPLAYORDER
		,ISACTIVE
		,CREATEDATE
		,LASTCHANGEDON
		,MESSAGETOKEN
FROM src.AnalysisRule
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


