CREATE OR REPLACE VIEW aw.AnalysisRuleThreshold
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ANALYSISRULETHRESHOLDID
		,ANALYSISRULEID
		,THRESHOLDKEY
		,THRESHOLDVALUE
		,CREATEDATE
		,LASTCHANGEDON
FROM src.AnalysisRuleThreshold
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


