CREATE OR REPLACE VIEW aw.ClaimantProviderSummaryEvaluation
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMANTPROVIDERSUMMARYEVALUATIONID
		,CLAIMANTHEADERID
		,EVALUATEDAMOUNT
		,MINIMUMEVALUATEDAMOUNT
		,MAXIMUMEVALUATEDAMOUNT
		,COMMENTS
FROM src.ClaimantProviderSummaryEvaluation
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


