CREATE OR REPLACE VIEW aw.ClaimantManualProviderSummary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MANUALPROVIDERID
		,DEMANDCLAIMANTID
		,FIRSTDATEOFSERVICE
		,LASTDATEOFSERVICE
		,VISITS
		,CHARGEDAMOUNT
		,EVALUATEDAMOUNT
		,MINIMUMEVALUATEDAMOUNT
		,MAXIMUMEVALUATEDAMOUNT
		,COMMENTS
FROM src.ClaimantManualProviderSummary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


