CREATE OR REPLACE VIEW aw.DemandPackage
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDPACKAGEID
		,DEMANDCLAIMANTID
		,REQUESTEDBYUSERNAME
		,DATETIMERECEIVED
		,CORRELATIONID
		,PAGECOUNT
FROM src.DemandPackage
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


