CREATE OR REPLACE VIEW aw.DemandPackageRequestedService
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDPACKAGEREQUESTEDSERVICEID
		,DEMANDPACKAGEID
		,REVIEWREQUESTOPTIONS
FROM src.DemandPackageRequestedService
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


