CREATE OR REPLACE VIEW aw.DemandClaimant
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDCLAIMANTID
		,EXTERNALCLAIMANTID
		,ORGANIZATIONID
		,HEIGHTININCHES
		,WEIGHT
		,OCCUPATION
		,BIREPORTSTATUS
		,HASDEMANDPACKAGE
		,FACTSOFLOSS
		,PREEXISTINGCONDITIONS
		,ARCHIVED
FROM src.DemandClaimant
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


