CREATE OR REPLACE VIEW aw.DemandPackageUploadedFile
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDPACKAGEUPLOADEDFILEID
		,DEMANDPACKAGEID
		,FILENAME
		,SIZE
		,DOCSTOREID
FROM src.DemandPackageUploadedFile
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


