CREATE OR REPLACE VIEW aw.EvaluationSummary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDCLAIMANTID
		,DETAILS
		,CREATEDBY
		,CREATEDDATE
		,MODIFIEDBY
		,MODIFIEDDATE
		,EVALUATIONSUMMARYTEMPLATEVERSIONID
FROM src.EvaluationSummary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


