CREATE OR REPLACE VIEW aw.EvaluationSummaryTemplateVersion
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EVALUATIONSUMMARYTEMPLATEVERSIONID
		,TEMPLATE
		,TEMPLATEHASH
		,CREATEDDATE
FROM src.EvaluationSummaryTemplateVersion
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


