CREATE OR REPLACE VIEW aw.EventLogDetail
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EVENTLOGDETAILID
		,EVENTLOGID
		,PROPERTYNAME
		,OLDVALUE
		,NEWVALUE
FROM src.EventLogDetail
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


