CREATE OR REPLACE VIEW aw.EvaluationSummaryHistory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EVALUATIONSUMMARYHISTORYID
		,DEMANDCLAIMANTID
		,EVALUATIONSUMMARY
		,CREATEDBY
		,CREATEDDATE
FROM src.EvaluationSummaryHistory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


