CREATE OR REPLACE VIEW aw.ManualProvider
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MANUALPROVIDERID
		,TIN
		,LASTNAME
		,FIRSTNAME
		,GROUPNAME
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
FROM src.ManualProvider
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


