CREATE OR REPLACE VIEW aw.ManualProviderSpecialty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MANUALPROVIDERID
		,SPECIALTY
FROM src.ManualProviderSpecialty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


