CREATE OR REPLACE VIEW aw.Note
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,NOTEID
		,DATECREATED
		,DATEMODIFIED
		,CREATEDBY
		,MODIFIEDBY
		,FLAG
		,CONTENT
		,NOTECONTEXT
		,DEMANDCLAIMANTID
FROM src.Note
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


