CREATE OR REPLACE VIEW aw.PROVIDEDLINK
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDEDLINKID
		,TITLE
		,URL
		,ORDERINDEX
FROM src.PROVIDEDLINK
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';

