CREATE OR REPLACE VIEW dbo.UDFClaim
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMIDNO
		,UDFIDNO
		,UDFVALUETEXT
		,UDFVALUEDECIMAL
		,UDFVALUEDATE
FROM src.UDFClaim
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


