CREATE OR REPLACE VIEW dbo.UB_APC_DICT
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STARTDATE
		,ENDDATE
		,APC
		,DESCRIPTION
FROM src.UB_APC_DICT
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


