CREATE OR REPLACE VIEW dbo.CustomBillStatuses
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATUSID
		,STATUSNAME
		,STATUSDESCRIPTION
FROM src.CustomBillStatuses
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


