CREATE OR REPLACE VIEW dbo.lkp_TS
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SHORTNAME
		,STARTDATE
		,ENDDATE
		,LONGNAME
		,GLOBAL
		,ANESMEDDIRECT
		,AFFECTSPRICING
		,ISASSISTANTSURGERY
		,ISCOSURGEON
FROM src.lkp_TS
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


