CREATE OR REPLACE VIEW dbo.UDFClaimant
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CMTIDNO
		,UDFIDNO
		,UDFVALUETEXT
		,UDFVALUEDECIMAL
		,UDFVALUEDATE
FROM src.UDFClaimant
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


