CREATE OR REPLACE VIEW dbo.RevenueCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REVENUECODE
		,REVENUECODESUBCATEGORYID
FROM src.RevenueCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


