CREATE OR REPLACE VIEW dbo.Bill_Sentry_Endnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,LINE
		,RULEID
		,PERCENTDISCOUNT
		,ACTIONID
FROM src.Bill_Sentry_Endnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


