CREATE OR REPLACE VIEW DBO.CBRETODPENDNOTEMAPPING
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENDNOTE
		,ENDNOTETYPEID
		,CBREENDNOTE
		,PRICINGSTATE
		,PRICINGMETHODID
FROM src.CBRETODPENDNOTEMAPPING
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';