CREATE OR REPLACE VIEW dbo.ProviderNumberCriteria
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERNUMBERCRITERIAID
		,PROVIDERNUMBER
		,PRIORITY
		,FEESCHEDULETABLE
		,STARTDATE
		,ENDDATE
FROM src.ProviderNumberCriteria
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


