CREATE OR REPLACE VIEW dbo.CriticalAccessHospitalInpatientRevenueCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REVENUECODE
FROM src.CriticalAccessHospitalInpatientRevenueCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


