CREATE OR REPLACE VIEW dbo.ProviderNumberCriteriaTypeOfBill
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERNUMBERCRITERIAID
		,TYPEOFBILL
		,MATCHINGPROFILENUMBER
		,ATTRIBUTEMATCHTYPEID
FROM src.ProviderNumberCriteriaTypeOfBill
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


