CREATE OR REPLACE VIEW dbo.ApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,APPORTIONMENTENDNOTE
		,SHORTDESCRIPTION
		,LONGDESCRIPTION
FROM src.ApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


