CREATE OR REPLACE VIEW dbo.GeneralInterestRuleBaseType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,GENERALINTERESTRULEBASETYPEID
		,GENERALINTERESTRULEBASETYPENAME
FROM src.GeneralInterestRuleBaseType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


