CREATE OR REPLACE VIEW dbo.InjuryNature
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,INJURYNATUREID
		,INJURYNATUREPRIORITY
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.InjuryNature
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


