CREATE OR REPLACE VIEW dbo.ProviderSpecialty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERID
		,SPECIALTYCODE
FROM src.ProviderSpecialty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


