CREATE OR REPLACE VIEW dbo.SupplementBillCustomEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,SEQUENCENUMBER
		,LINENUMBER
		,ENDNOTE
FROM src.SupplementBillCustomEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


