CREATE OR REPLACE VIEW dbo.UDFViewOrder
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,OFFICEID
		,UDFIDNO
		,VIEWORDER
FROM src.UDFViewOrder
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


