CREATE OR REPLACE VIEW dbo.SENTRY_RULE_ACTION_DETAIL
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULEID
		,LINENUMBER
		,ACTIONID
		,ACTIONVALUE
FROM src.SENTRY_RULE_ACTION_DETAIL
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


