CREATE OR REPLACE VIEW dbo.RuleType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULETYPEID
		,NAME
		,DESCRIPTION
FROM src.RuleType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


