CREATE OR REPLACE VIEW dbo.CMT_ICD9
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,SEQNO
		,ICD9
		,ICDVERSION
FROM src.CMT_ICD9
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


