CREATE OR REPLACE VIEW dbo.ReferenceSupplementBillApcLines
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,SEQNO
		,LINE_NO
		,PAYMENTAPC
		,SERVICEINDICATOR
		,PAYMENTINDICATOR
		,OUTLIERAMOUNT
		,PRICERALLOWED
		,MEDICAREAMOUNT
FROM src.ReferenceSupplementBillApcLines
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


