CREATE OR REPLACE VIEW dbo.CreditReason
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CREDITREASONID
		,CREDITREASONDESC
		,ISVISIBLE
FROM src.CreditReason
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


