CREATE OR REPLACE VIEW dbo.MedicareStatusIndicatorRuleProcedureCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MEDICARESTATUSINDICATORRULEID
		,PROCEDURECODE
FROM src.MedicareStatusIndicatorRuleProcedureCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


