CREATE OR REPLACE VIEW dbo.MedicareStatusIndicatorRuleCoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MEDICARESTATUSINDICATORRULEID
		,SHORTNAME
FROM src.MedicareStatusIndicatorRuleCoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


