CREATE OR REPLACE VIEW dbo.StateSettingsNyRoomRate
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSNYROOMRATEID
		,STARTDATE
		,ENDDATE
		,ROOMRATE
FROM src.StateSettingsNyRoomRate
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


