CREATE OR REPLACE VIEW dbo.SentryRuleTypeCriteria
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULETYPEID
		,CRITERIAID
FROM src.SentryRuleTypeCriteria
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


