CREATE OR REPLACE VIEW dbo.DiagnosisCodeGroup
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DIAGNOSISCODE
		,STARTDATE
		,ENDDATE
		,MAJORCATEGORY
		,MINORCATEGORY
FROM src.DiagnosisCodeGroup
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


