CREATE OR REPLACE VIEW dbo.StateSettingsNewYorkPolicyPreference
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,POLICYPREFERENCEID
		,SHARECOPAYMAXIMUM
FROM src.StateSettingsNewYorkPolicyPreference
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


