CREATE OR REPLACE VIEW dbo.CMT_DX
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,DX
		,SEQNUM
		,POA
		,ICDVERSION
FROM src.CMT_DX
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


