CREATE OR REPLACE VIEW dbo.SurgicalModifierException
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MODIFIER
		,STATE
		,COVERAGETYPE
		,STARTDATE
		,ENDDATE
FROM src.SurgicalModifierException
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


