CREATE OR REPLACE VIEW dbo.StateSettingsHawaii
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSHAWAIIID
		,PHYSICALMEDICINELIMITOPTION
FROM src.StateSettingsHawaii
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


