CREATE OR REPLACE VIEW dbo.VpnBillableFlags
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SOJ
		,NETWORKID
		,ACTIVITYFLAG
		,BILLABLE
		,COMPANYCODE
		,COMPANYNAME
FROM src.VpnBillableFlags
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


