CREATE OR REPLACE VIEW dbo.Bills_OverrideEndNotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,OVERRIDEENDNOTEID
		,BILLIDNO
		,LINE_NO
		,OVERRIDEENDNOTE
		,PERCENTDISCOUNT
		,ACTIONID
FROM src.Bills_OverrideEndNotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


