CREATE OR REPLACE VIEW dbo.Bill_Payment_Adjustments
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILL_PAYMENT_ADJUSTMENT_ID
		,BILLIDNO
		,SEQNO
		,INTERESTFLAGS
		,DATEINTERESTSTARTS
		,DATEINTERESTENDS
		,INTERESTADDITIONALINFORECEIVED
		,INTEREST
		,COMMENTS
FROM src.Bill_Payment_Adjustments
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


