CREATE OR REPLACE VIEW dbo.BIReportAdjustmentCategoryMapping
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BIREPORTADJUSTMENTCATEGORYID
		,ADJUSTMENT360SUBCATEGORYID
FROM src.BIReportAdjustmentCategoryMapping
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


