CREATE OR REPLACE VIEW dbo.prf_CTGMaxPenaltyLines
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CTGMAXPENLINEID
		,PROFILEID
		,DATESBASEDON
		,MAXPENALTYPERCENT
		,STARTDATE
		,ENDDATE
FROM src.prf_CTGMaxPenaltyLines
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


