CREATE OR REPLACE VIEW dbo.CMT_HDR
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CMT_HDR_IDNO
		,CMTIDNO
		,PVDIDNO
		,LASTCHANGEDON
FROM src.CMT_HDR
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


