CREATE OR REPLACE VIEW dbo.VpnProcessFlagType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,VPNPROCESSFLAGTYPEID
		,VPNPROCESSFLAGTYPE
FROM src.VpnProcessFlagType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


