CREATE OR REPLACE VIEW dbo.StateSettingsFlorida
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSFLORIDAID
		,CLAIMANTINITIALSERVICEOPTION
		,CLAIMANTINITIALSERVICEDAYS
FROM src.StateSettingsFlorida
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


