CREATE OR REPLACE VIEW dbo.Bills_Pharm
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,LINE_NO_DISP
		,DATEOFSERVICE
		,NDC
		,PRICETYPECODE
		,UNITS
		,CHARGED
		,ALLOWED
		,ENDNOTE
		,OVERRIDE
		,OVERRIDE_RSN
		,ANALYZED
		,CTGPENALTY
		,PREPPOALLOWED
		,PPODATE
		,POS_REVCODE
		,DPALLOWED
		,HCRA_SURCHARGE
		,ENDDATEOFSERVICE
		,REPACKAGEDNDC
		,ORIGINALNDC
		,UNITOFMEASUREID
		,PACKAGETYPEORIGINALNDC
		,PPOCTGPENALTY
		,SERVICECODE
		,PREAPPORTIONEDAMOUNT
		,DEDUCTIBLEAPPLIED
		,BILLREVIEWRESULTS
		,PREOVERRIDDENDEDUCTIBLE
		,REMAININGBALANCE
		,CTGCOPAYPENALTY
		,PPOCTGCOPAYPENALTYPERCENTAGE
		,CTGVUNPENALTY
		,PPOCTGVUNPENALTYPERCENTAGE
		,RENDERINGNPI
FROM src.Bills_Pharm
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


