CREATE OR REPLACE VIEW dbo.Adjustment360OverrideEndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.Adjustment360OverrideEndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


