CREATE OR REPLACE VIEW dbo.cpt_PRC_DICT
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PRC_CD
		,STARTDATE
		,ENDDATE
		,PRC_DESC
		,FLAGS
		,VAGUE
		,PERVISIT
		,PERCLAIMANT
		,PERPROVIDER
		,BODYFLAGS
		,COLOSSUS
		,CMS_STATUS
		,DRUGFLAG
		,CURATIVEFLAG
		,EXCLPOLICYLIMIT
		,SPECNETFLAG
FROM src.cpt_PRC_DICT
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


