CREATE OR REPLACE VIEW dbo.Zip2County
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ZIP
		,COUNTY
		,STATE
FROM src.Zip2County
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


