CREATE OR REPLACE VIEW dbo.PROVIDER
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,PVDMID
		,PVDSOURCE
		,PVDTIN
		,PVDLICNO
		,PVDCERTNO
		,PVDLASTNAME
		,PVDFIRSTNAME
		,PVDMI
		,PVDTITLE
		,PVDGROUP
		,PVDADDR1
		,PVDADDR2
		,PVDCITY
		,PVDSTATE
		,PVDZIP
		,PVDZIPPERF
		,PVDPHONE
		,PVDFAX
		,PVDSPC_LIST
		,PVDAUTHNO
		,PVDSPC_ACD
		,PVDUPDATECOUNTER
		,PVDPPO_PROVIDER
		,PVDFLAGS
		,PVDERRATE
		,PVDSUBNET
		,INUSE
		,PVDSTATUS
		,PVDELECTROSTARTDATE
		,PVDELECTROENDDATE
		,PVDACCREDSTARTDATE
		,PVDACCREDENDDATE
		,PVDREHABSTARTDATE
		,PVDREHABENDDATE
		,PVDTRAUMASTARTDATE
		,PVDTRAUMAENDDATE
		,OPCERT
		,PVDDENTALSTARTDATE
		,PVDDENTALENDDATE
		,PVDNPINO
		,PVDCMSID
		,CREATEDATE
		,LASTCHANGEDON
FROM src.PROVIDER
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


