CREATE OR REPLACE VIEW dbo.UDF_Sentry_Criteria
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,UDFIDNO
		,CRITERIAID
		,PARENTNAME
		,NAME
		,DESCRIPTION
		,OPERATORS
		,PREDEFINEDVALUES
		,VALUEDATATYPE
		,VALUEFORMAT
FROM src.UDF_Sentry_Criteria
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


