CREATE OR REPLACE VIEW dbo.Provider_Rendering
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,RENDERINGADDR1
		,RENDERINGADDR2
		,RENDERINGCITY
		,RENDERINGSTATE
		,RENDERINGZIP
FROM src.Provider_Rendering
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


