CREATE OR REPLACE VIEW dbo.VPNActivityFlag
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ACTIVITY_FLAG
		,AF_DESCRIPTION
		,AF_SHORTDESC
		,DATA_SOURCE
		,DEFAULT_BILLABLE
		,CREDIT
FROM src.VPNActivityFlag
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


