CREATE OR REPLACE VIEW dbo.Vpn
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,VPNID
		,NETWORKNAME
		,PENDANDSEND
		,BYPASSMATCHING
		,ALLOWSRESENDS
		,ODSELIGIBLE
FROM src.Vpn
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


