CREATE OR REPLACE VIEW dbo.NcciBodyPart
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,NCCIBODYPARTID
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.NcciBodyPart
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


