CREATE OR REPLACE VIEW dbo.BillCustomEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,LINENUMBER
		,ENDNOTE
FROM src.BillCustomEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


