CREATE OR REPLACE VIEW dbo.DeductibleRuleCriteriaCoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEDUCTIBLERULECRITERIAID
		,COVERAGETYPE
FROM src.DeductibleRuleCriteriaCoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


