CREATE OR REPLACE VIEW dbo.prf_CTGPenalty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CTGPENID
		,PROFILEID
		,APPLYPRECERTS
		,NOPRECERTLOGGED
		,MAXTOTALPENALTY
		,TURNTIMEFORAPPEALS
		,APPLYENDNOTEFORPERCERT
		,APPLYENDNOTEFORCAREPATH
		,EXEMPTPRECERTPENALTY
		,APPLYNETWORKPENALTY
FROM src.prf_CTGPenalty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


