CREATE OR REPLACE VIEW dbo.ProviderSpecialtyToProvType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERTYPE
		,PROVIDERTYPE_DESC
		,SPECIALTY
		,SPECIALTY_DESC
		,CREATEDATE
		,MODIFYDATE
		,LOGICALDELETE
FROM src.ProviderSpecialtyToProvType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


