CREATE OR REPLACE VIEW dbo.SEC_Users
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,USERID
		,LOGINNAME
		,PASSWORD
		,CREATEDBY
		,CREATEDDATE
		,USERSTATUS
		,FIRSTNAME
		,LASTNAME
		,ACCOUNTLOCKED
		,LOCKEDCOUNTER
		,PASSWORDCREATEDATE
		,PASSWORDCASEFLAG
		,EPASSWORD
		,CURRENTSETTINGS
FROM src.SEC_Users
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


