CREATE OR REPLACE VIEW dbo.UdfDataFormat
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,UDFDATAFORMATID
		,DATAFORMATNAME
FROM src.UdfDataFormat
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


