CREATE OR REPLACE VIEW dbo.ICD10ProcedureCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ICDPROCEDURECODE
		,STARTDATE
		,ENDDATE
		,DESCRIPTION
		,PASGRPNO
FROM src.ICD10ProcedureCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


