CREATE OR REPLACE VIEW dbo.lkp_SPC
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,LKP_SPCID
		,LONGNAME
		,SHORTNAME
		,MULT
		,NCD92
		,NCD93
		,PLUSFOUR
		,CBRESPECIALTYCODE
FROM src.lkp_SPC
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


