CREATE OR REPLACE VIEW dbo.Bill_History
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,SEQNO
		,DATECOMMITTED
		,AMTCOMMITTED
		,USERID
		,AMTCOPAY
		,AMTDEDUCTIBLE
		,FLAGS
		,AMTSALESTAX
		,AMTOTHERTAX
		,DEDUCTIBLEOVERRIDE
		,PRICINGSTATE
		,APPORTIONMENTPERCENTAGE
		,FLORIDADEDUCTIBLERULEELIGIBLE
FROM src.Bill_History
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


