CREATE OR REPLACE VIEW dbo.StateSettingsNY
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSNYID
		,NF10PRINTDATE
		,NF10CHECKBOX1
		,NF10CHECKBOX18
		,NF10USEUNDERWRITINGCOMPANY
		,UNDERWRITINGCOMPANYUDFID
		,NAICUDFID
		,DISPLAYNYPRINTOPTIONSWHENZOSORSOJISNY
		,NF10DUPLICATEPRINT
FROM src.StateSettingsNY
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


