CREATE OR REPLACE VIEW dbo.ZipCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ZIPCODE
		,PRIMARYRECORD
		,STATE
		,CITY
		,CITYALIAS
		,COUNTY
		,CBSA
		,CBSATYPE
		,ZIPCODEREGIONID
FROM src.ZipCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


