CREATE OR REPLACE VIEW dbo.SEC_RightGroups
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RIGHTGROUPID
		,RIGHTGROUPNAME
		,RIGHTGROUPDESCRIPTION
		,CREATEDDATE
		,CREATEDBY
FROM src.SEC_RightGroups
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


