CREATE OR REPLACE VIEW dbo.Icd10DiagnosisVersion
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DIAGNOSISCODE
		,STARTDATE
		,ENDDATE
		,NONSPECIFIC
		,TRAUMATIC
		,DURATION
		,DESCRIPTION
		,DIAGNOSISFAMILYID
		,TOTALCHARACTERSREQUIRED
		,PLACEHOLDERREQUIRED
FROM src.Icd10DiagnosisVersion
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


