CREATE OR REPLACE VIEW dbo.BillExclusionLookUpTable
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REPORTID
		,REPORTNAME
FROM src.BillExclusionLookUpTable
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


