CREATE OR REPLACE VIEW dbo.SupplementBill_Pharm_ApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,SEQUENCENUMBER
		,LINENUMBER
		,ENDNOTE
FROM src.SupplementBill_Pharm_ApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


