CREATE OR REPLACE VIEW dbo.ny_specialty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RATINGCODE
		,DESC_
		,CBRESPECIALTYCODE
FROM src.ny_specialty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


