CREATE OR REPLACE VIEW dbo.SEC_User_OfficeGroups
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SECUSEROFFICEGROUPID
		,USERID
		,OFFCGROUPID
FROM src.SEC_User_OfficeGroups
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


