CREATE OR REPLACE VIEW dbo.ProcedureServiceCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROCEDURESERVICECATEGORYID
		,PROCEDURESERVICECATEGORYNAME
		,PROCEDURESERVICECATEGORYDESCRIPTION
		,LEGACYTABLENAME
		,LEGACYBITVALUE
FROM src.ProcedureServiceCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


