CREATE OR REPLACE VIEW dbo.UDFLibrary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,UDFIDNO
		,UDFNAME
		,SCREENTYPE
		,UDFDESCRIPTION
		,DATAFORMAT
		,REQUIREDFIELD
		,READONLY
		,INVISIBLE
		,TEXTMAXLENGTH
		,TEXTMASK
		,TEXTENFORCELENGTH
		,RESTRICTRANGE
		,MINVALDECIMAL
		,MAXVALDECIMAL
		,MINVALDATE
		,MAXVALDATE
		,LISTALLOWMULTIPLE
		,DEFAULTVALUETEXT
		,DEFAULTVALUEDECIMAL
		,DEFAULTVALUEDATE
		,USEDEFAULT
		,REQONSUBMIT
		,INCLUDEDATEBUTTON
FROM src.UDFLibrary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


