CREATE OR REPLACE VIEW dbo.prf_PPO
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPOSYSID
		,PROFILEID
		,PPOID
		,BSTATUS
		,STARTDATE
		,ENDDATE
		,AUTOSEND
		,AUTORESEND
		,BYPASSMATCHING
		,USEPROVIDERNETWORKENROLLMENT
		,TIEREDTYPEID
		,PRIORITY
		,POLICYEFFECTIVEDATE
		,BILLFORMTYPE
FROM src.prf_PPO
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


