CREATE OR REPLACE VIEW dbo.SENTRY_CRITERIA
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CRITERIAID
		,PARENTNAME
		,NAME
		,DESCRIPTION
		,OPERATORS
		,PREDEFINEDVALUES
		,VALUEDATATYPE
		,VALUEFORMAT
		,NULLALLOWED
FROM src.SENTRY_CRITERIA
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


