CREATE OR REPLACE VIEW dbo.ProviderNumberCriteriaRevenueCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERNUMBERCRITERIAID
		,REVENUECODE
		,MATCHINGPROFILENUMBER
		,ATTRIBUTEMATCHTYPEID
FROM src.ProviderNumberCriteriaRevenueCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


