CREATE OR REPLACE VIEW dbo.Rsn_Override
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SHORTDESC
		,LONGDESC
		,CATEGORYIDNO
		,CLIENTSPEC
		,COAINDEX
		,NJPENALTYPCT
		,NETWORKID
		,SPECIALPROCESSING
FROM src.Rsn_Override
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


