CREATE OR REPLACE VIEW dbo.UB_BillType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TOB
		,DESCRIPTION
		,FLAG
		,UB_BILLTYPEID
FROM src.UB_BillType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


