CREATE OR REPLACE VIEW dbo.RENDERINGNPISTATES
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,APPLICATIONSETTINGSID
		,STATE
FROM src.RENDERINGNPISTATES
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';
