CREATE OR REPLACE VIEW dbo.CoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,LONGNAME
		,SHORTNAME
		,CBRECOVERAGETYPECODE
		,COVERAGETYPECATEGORYCODE
		,PRICINGMETHODID
FROM src.CoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


