CREATE OR REPLACE VIEW dbo.BillApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,LINENUMBER
		,ENDNOTE
FROM src.BillApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


