CREATE OR REPLACE VIEW dbo.BILLS_CTG_Endnotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,ENDNOTE
		,RULETYPE
		,RULEID
		,PRECERTACTION
		,PERCENTDISCOUNT
		,ACTIONID
FROM src.BILLS_CTG_Endnotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


