CREATE OR REPLACE VIEW dbo.MedicalCodeCutOffs
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CODETYPEID
		,CODETYPE
		,CODE
		,FORMTYPE
		,MAXCHARGEDPERUNIT
		,MAXUNITSPERENCOUNTER
FROM src.MedicalCodeCutOffs
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


