CREATE OR REPLACE VIEW dbo.Bills_Tax
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLSTAXID
		,TABLETYPE
		,BILLIDNO
		,LINE_NO
		,SEQNO
		,TAXTYPEID
		,IMPORTTAXRATE
		,TAX
		,OVERRIDENTAX
		,IMPORTTAXAMOUNT
FROM src.Bills_Tax
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


