CREATE OR REPLACE VIEW dbo.EncounterType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENCOUNTERTYPEID
		,ENCOUNTERTYPEPRIORITY
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.EncounterType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


