CREATE OR REPLACE VIEW dbo.cpt_DX_DICT
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ICD9
		,STARTDATE
		,ENDDATE
		,FLAGS
		,NONSPECIFIC
		,ADDITIONALDIGITS
		,TRAUMATIC
		,DX_DESC
		,DURATION
		,COLOSSUS
		,DIAGNOSISFAMILYID
FROM src.cpt_DX_DICT
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


