CREATE OR REPLACE VIEW dbo.CustomEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CUSTOMENDNOTE
		,SHORTDESCRIPTION
		,LONGDESCRIPTION
FROM src.CustomEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


