CREATE OR REPLACE VIEW dbo.Claimant_ClientRef
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CMTIDNO
		,CMTSUFFIX
		,CLAIMIDNO
FROM src.Claimant_ClientRef
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


