CREATE OR REPLACE VIEW dbo.UDFListValues
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,LISTVALUEIDNO
		,UDFIDNO
		,SEQNO
		,LISTVALUE
		,DEFAULTVALUE
FROM src.UDFListValues
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


