CREATE OR REPLACE VIEW dbo.CTG_Endnotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENDNOTE
		,SHORTDESC
		,LONGDESC
FROM src.CTG_Endnotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


