CREATE OR REPLACE VIEW dbo.StateSettingMedicare
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGMEDICAREID
		,PAYPERCENTOFMEDICAREFEE
FROM src.StateSettingMedicare
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


