CREATE OR REPLACE VIEW dbo.prf_CTGPenaltyHdr
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CTGPENHDRID
		,PROFILEID
		,PENALTYTYPE
		,PAYNEGRATE
		,PAYPPORATE
		,DATESBASEDON
		,APPLYPENALTYTOPHARMACY
		,APPLYPENALTYCONDITION
FROM src.prf_CTGPenaltyHdr
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


