CREATE OR REPLACE VIEW dbo.ny_pharmacy
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,NDCCODE
		,STARTDATE
		,ENDDATE
		,DESCRIPTION
		,FEE
		,TYPEOFDRUG
FROM src.ny_pharmacy
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


