CREATE OR REPLACE VIEW dbo.AdjustmentEndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.AdjustmentEndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


