CREATE OR REPLACE VIEW dbo.BIReportAdjustmentCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BIREPORTADJUSTMENTCATEGORYID
		,NAME
		,DESCRIPTION
		,DISPLAYPRIORITY
FROM src.BIReportAdjustmentCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


