CREATE OR REPLACE VIEW dbo.Rsn_Reasons_3rdParty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SHORTDESC
		,LONGDESC
FROM src.Rsn_Reasons_3rdParty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


