CREATE OR REPLACE VIEW dbo.Bitmasks
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TABLEPROGRAMUSED
		,ATTRIBUTEUSED
		,DECIMAL
		,CONSTANTNAME
		,BIT
		,HEX
		,DESCRIPTION
FROM src.Bitmasks
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


