CREATE OR REPLACE VIEW dbo.Provider_ClientRef
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,CLIENTREFID
		,CLIENTREFID2
FROM src.Provider_ClientRef
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


