CREATE OR REPLACE VIEW dbo.ModifierToProcedureCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROCEDURECODE
		,MODIFIER
		,STARTDATE
		,ENDDATE
		,SOJFLAG
		,REQUIRESGUIDELINEREVIEW
		,REFERENCE
		,COMMENTS
FROM src.ModifierToProcedureCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


