CREATE OR REPLACE VIEW dbo.UDFProvider
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,UDFIDNO
		,UDFVALUETEXT
		,UDFVALUEDECIMAL
		,UDFVALUEDATE
FROM src.UDFProvider
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


