CREATE OR REPLACE VIEW dbo.GeneralInterestRuleSetting
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,GENERALINTERESTRULEBASETYPEID
FROM src.GeneralInterestRuleSetting
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


