CREATE OR REPLACE VIEW dbo.SPECIALTY
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SPCIDNO
		,CODE
		,DESCRIPTION
		,PAYEESUBTYPEID
		,TIEREDTYPEID
FROM src.SPECIALTY
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


