CREATE OR REPLACE VIEW dbo.CustomerBillExclusion
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,CUSTOMER
		,REPORTID
		,CREATEDATE
FROM src.CustomerBillExclusion
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


