CREATE OR REPLACE VIEW dbo.prf_COMPANY
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,COMPANYID
		,COMPANYNAME
		,LASTCHANGEDON
FROM src.prf_COMPANY
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


