CREATE OR REPLACE VIEW dbo.prf_Office
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,COMPANYID
		,OFFICEID
		,OFCNO
		,OFCNAME
		,OFCADDR1
		,OFCADDR2
		,OFCCITY
		,OFCSTATE
		,OFCZIP
		,OFCPHONE
		,OFCDEFAULT
		,OFCCLAIMMASK
		,OFCTINMASK
		,VERSION
		,OFCEDITS
		,OFCCOAENABLED
		,CTGENABLED
		,LASTCHANGEDON
		,ALLOWMULTICOVERAGE
FROM src.prf_Office
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


