CREATE OR REPLACE VIEW dbo.SENTRY_ACTION
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ACTIONID
		,NAME
		,DESCRIPTION
		,COMPATIBILITYKEY
		,PREDEFINEDVALUES
		,VALUEDATATYPE
		,VALUEFORMAT
		,BILLLINEACTION
		,ANALYZEFLAG
		,ACTIONCATEGORYIDNO
FROM src.SENTRY_ACTION
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


