CREATE OR REPLACE VIEW dbo.UDFBill
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,UDFIDNO
		,UDFVALUETEXT
		,UDFVALUEDECIMAL
		,UDFVALUEDATE
FROM src.UDFBill
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


