CREATE OR REPLACE VIEW dbo.SENTRY_RULE
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULEID
		,NAME
		,DESCRIPTION
		,CREATEDBY
		,CREATIONDATE
		,POSTFIXNOTATION
		,PRIORITY
		,RULETYPEID
FROM src.SENTRY_RULE
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


