CREATE OR REPLACE VIEW dbo.StateSettingsOregonCoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSOREGONID
		,COVERAGETYPE
FROM src.StateSettingsOregonCoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


