CREATE OR REPLACE VIEW dbo.Bill_Pharm_ApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,LINENUMBER
		,ENDNOTE
FROM src.Bill_Pharm_ApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


