CREATE OR REPLACE VIEW dbo.DeductibleRuleCriteria
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEDUCTIBLERULECRITERIAID
		,PRICINGRULEDATECRITERIAID
		,STARTDATE
		,ENDDATE
FROM src.DeductibleRuleCriteria
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


