CREATE OR REPLACE VIEW dbo.Adjustment360SubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ADJUSTMENT360SUBCATEGORYID
		,NAME
		,ADJUSTMENT360CATEGORYID
FROM src.Adjustment360SubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


