CREATE OR REPLACE VIEW dbo.CreditReasonOverrideENMap
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CREDITREASONOVERRIDEENMAPID
		,CREDITREASONID
		,OVERRIDEENDNOTEID
FROM src.CreditReasonOverrideENMap
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


