CREATE OR REPLACE VIEW dbo.Prf_CustomIcdAction
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CUSTOMICDACTIONID
		,PROFILEID
		,ICDVERSIONID
		,ACTION
		,STARTDATE
		,ENDDATE
FROM src.Prf_CustomIcdAction
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


