CREATE OR REPLACE VIEW dbo.BillAdjustment
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLLINEADJUSTMENTID
		,BILLIDNO
		,LINENUMBER
		,ADJUSTMENT
		,ENDNOTE
		,ENDNOTETYPEID
FROM src.BillAdjustment
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


