CREATE OR REPLACE VIEW dbo.SENTRY_RULE_CONDITION
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULEID
		,LINENUMBER
		,GROUPFLAG
		,CRITERIAID
		,OPERATOR
		,CONDITIONVALUE
		,ANDOR
		,UDFCONDITIONID
FROM src.SENTRY_RULE_CONDITION
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


