CREATE OR REPLACE VIEW dbo.SENTRY_RULE_ACTION_HEADER
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULEID
		,ENDNOTESHORT
		,ENDNOTELONG
FROM src.SENTRY_RULE_ACTION_HEADER
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


