CREATE OR REPLACE VIEW dbo.UDFLevelChangeTracking
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,UDFLEVELCHANGETRACKINGID
		,ENTITYTYPE
		,ENTITYID
		,CORRELATIONID
		,UDFID
		,PREVIOUSVALUE
		,UPDATEDVALUE
		,USERID
		,CHANGEDATE
FROM src.UDFLevelChangeTracking
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


