CREATE OR REPLACE VIEW dbo.CLAIMS
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMIDNO
		,CLAIMNO
		,DATELOSS
		,CV_CODE
		,DIARYINDEX
		,LASTSAVED
		,POLICYNUMBER
		,POLICYHOLDERSNAME
		,PAIDDEDUCTIBLE
		,STATUS
		,INUSE
		,COMPANYID
		,OFFICEINDEX
		,ADJIDNO
		,PAIDCOPAY
		,ASSIGNEDUSER
		,PRIVATIZED
		,POLICYEFFDATE
		,DEDUCTIBLE
		,LOSSSTATE
		,ASSIGNEDGROUP
		,CREATEDATE
		,LASTCHANGEDON
		,ALLOWMULTICOVERAGE
FROM src.CLAIMS
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


