CREATE OR REPLACE VIEW dbo.prf_CTGPenaltyLines
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CTGPENLINEID
		,PROFILEID
		,PENALTYTYPE
		,FEESCHEDULEPERCENT
		,STARTDATE
		,ENDDATE
		,TURNAROUNDTIME
FROM src.prf_CTGPenaltyLines
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


