CREATE OR REPLACE VIEW dbo.BillsOverride
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLSOVERRIDEID
		,BILLIDNO
		,LINE_NO
		,USERID
		,DATESAVED
		,AMOUNTBEFORE
		,AMOUNTAFTER
		,CODESOVERRODE
		,SEQNO
FROM src.BillsOverride
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


