CREATE OR REPLACE VIEW dbo.VpnSavingTransactionType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,VPNSAVINGTRANSACTIONTYPEID
		,VPNSAVINGTRANSACTIONTYPE
FROM src.VpnSavingTransactionType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


