CREATE OR REPLACE VIEW dbo.rsn_REASONS
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,CV_TYPE
		,SHORTDESC
		,LONGDESC
		,CATEGORYIDNO
		,COAINDEX
		,OVERRIDEENDNOTE
		,HARDEDIT
		,SPECIALPROCESSING
		,ENDNOTEACTIONID
		,RETAINFOREAPG
FROM src.rsn_REASONS
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


