CREATE OR REPLACE VIEW dbo.BILLS_Endnotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,ENDNOTE
		,REFERRAL
		,PERCENTDISCOUNT
		,ACTIONID
		,ENDNOTETYPEID
FROM src.BILLS_Endnotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


