CREATE OR REPLACE VIEW dbo.RevenueCodeCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REVENUECODECATEGORYID
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.RevenueCodeCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


