CREATE OR REPLACE VIEW dbo.ScriptAdvisorSettingsCoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SCRIPTADVISORSETTINGSID
		,COVERAGETYPE
FROM src.ScriptAdvisorSettingsCoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


