CREATE OR REPLACE VIEW dbo.Adjustment360Category
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ADJUSTMENT360CATEGORYID
		,NAME
FROM src.Adjustment360Category
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


