CREATE OR REPLACE VIEW dbo.ModifierByState
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATE
		,PROCEDURESERVICECATEGORYID
		,MODIFIERDICTIONARYID
FROM src.ModifierByState
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


