CREATE OR REPLACE TASK ADM.ETL_Snowflake_Ods_Load
  WAREHOUSE = &DWSIZE
  SCHEDULE = 'USING CRON 0 18 * * * America/Los_Angeles'
AS
CALL ADM.ETL_MASTER_SNOWFLAKE_ODS_LOAD_multithread (20,'&DWSIZE',120,60,'@WCSODS.STG.s3_etl_PROD/WCS','WCSODS.STG.FORMAT_FILE_DEL_COMMA',FALSE);
CREATE OR REPLACE TASK ADM.TASK_ETL_LOG_ERRORS
  WAREHOUSE = &DWSIZE
  SCHEDULE = 'USING CRON 10,20,30,40,50 18-22 * * * America/Los_Angeles'
AS
CALL ADM.ETL_LOG_ERRORS ('ETL_Snowflake_Ods_Load','ADM','TASK_ETL_LOG_ERRORS','ADM','false');
