CREATE TABLE IF NOT EXISTS CNFG.REPORT_TASKS (
	REPORT_ID int NOT NULL,
	REPORT_TASK_NAME varchar(255) NULL,
	SOURCE_DATABASE_NAME varchar(255) NOT NULL,
	TARGET_DATABASE_NAME varchar(255) NOT NULL,
	EMAIL_TO varchar(255) NOT NULL,
	CUSTOMER_LIST_TYPE int NOT NULL,
	RUN_TYPE int NOT NULL,
	SNAPSHOT_DATE datetime NULL,
	PRIORITY int NOT NULL,
	ENABLED int NOT NULL,
	RUN_WEEK_DAY int NULL,
	IS_DAILY int NULL,
	IS_WEEKLY int NULL,
	IS_MONTHLY int NULL,
	IS_QUATERLY int NULL
)
;

