CREATE OR REPLACE FUNCTION dbo.if_Esp_Ppo_Billing_Data_Self_Bill(
		if_OdsPostingGroupAuditId INT
)
RETURNS TABLE  (
		 OdsPostingGroupAuditId NUMBER(10,0)
		,OdsCustomerId NUMBER(10,0)
		,OdsCreateDate DATETIME
		,OdsSnapshotDate DATETIME
		,OdsRowIsCurrent INT
		,OdsHashbytesValue BINARY(8000)
		,DmlOperation VARCHAR(1)
		,COMPANYCODE VARCHAR(10)
		,TRANSACTIONTYPE VARCHAR(10)
		,BILL_HDR_AMTALLOWED NUMBER(15,2)
		,BILL_HDR_AMTCHARGED NUMBER(15,2)
		,BILL_HDR_BILLIDNO NUMBER(10,0)
		,BILL_HDR_CMT_HDR_IDNO NUMBER(10,0)
		,BILL_HDR_CREATEDATE DATETIME
		,BILL_HDR_CV_TYPE VARCHAR(5)
		,BILL_HDR_FORM_TYPE VARCHAR(8)
		,BILL_HDR_NOLINES NUMBER(10,0)
		,BILLS_ALLOWED NUMBER(15,2)
		,BILLS_ANALYZED NUMBER(15,2)
		,BILLS_CHARGED NUMBER(15,2)
		,BILLS_DT_SVC DATETIME
		,BILLS_LINE_NO NUMBER(10,0)
		,CLAIMANT_CLIENTREF_CMTSUFFIX VARCHAR(50)
		,CLAIMANT_CMTFIRST_NAME VARCHAR(50)
		,CLAIMANT_CMTIDNO VARCHAR(20)
		,CLAIMANT_CMTLASTNAME VARCHAR(60)
		,CMTSTATEOFJURISDICTION VARCHAR(2)
		,CLAIMS_COMPANYID NUMBER(10,0)
		,CLAIMS_CLAIMNO VARCHAR(50)
		,CLAIMS_DATELOSS DATETIME
		,CLAIMS_OFFICEINDEX NUMBER(10,0)
		,CLAIMS_POLICYHOLDERSNAME VARCHAR(100)
		,CLAIMS_POLICYNUMBER VARCHAR(50)
		,PNETWKEVENTLOG_EVENTID NUMBER(10,0)
		,PNETWKEVENTLOG_LOGDATE DATETIME
		,PNETWKEVENTLOG_NETWORKID NUMBER(10,0)
		,ACTIVITY_FLAG VARCHAR(1)
		,PPO_AMTALLOWED NUMBER(15,2)
		,PREPPO_AMTALLOWED NUMBER(15,2)
		,PREPPO_ALLOWED_FS VARCHAR(1)
		,PRF_COMPANY_COMPANYNAME VARCHAR(50)
		,PRF_OFFICE_OFCNAME VARCHAR(50)
		,PRF_OFFICE_OFCNO VARCHAR(25)
		,PROVIDER_PVDFIRSTNAME VARCHAR(60)
		,PROVIDER_PVDGROUP VARCHAR(60)
		,PROVIDER_PVDLASTNAME VARCHAR(60)
		,PROVIDER_PVDTIN VARCHAR(15)
		,PROVIDER_STATE VARCHAR(5)
		,UDFCLAIM_UDFVALUETEXT VARCHAR(255)
		,ENTRY_DATE DATETIME
		,UDFCLAIMANT_UDFVALUETEXT VARCHAR(255)
		,SOURCE_DB VARCHAR(20)
		,CLAIMS_CV_CODE VARCHAR(5)
		,VPN_TRANSACTIONID NUMBER(19,0)
		,VPN_TRANSACTIONTYPEID NUMBER(10,0)
		,VPN_BILLIDNO NUMBER(10,0)
		,VPN_LINE_NO NUMBER(5,0)
		,VPN_CHARGED NUMBER(19,4)
		,VPN_DPALLOWED NUMBER(19,4)
		,VPN_VPNALLOWED NUMBER(19,4)
		,VPN_SAVINGS NUMBER(19,4)
		,VPN_CREDITS NUMBER(19,4)
		,VPN_HASOVERRIDE BOOLEAN
		,VPN_ENDNOTES VARCHAR(200)
		,VPN_NETWORKIDNO NUMBER(10,0)
		,VPN_PROCESSFLAG NUMBER(5,0)
		,VPN_LINETYPE NUMBER(10,0)
		,VPN_DATETIMESTAMP DATETIME
		,VPN_SEQNO NUMBER(10,0)
		,VPN_VPN_REF_LINE_NO NUMBER(5,0)
		,VPN_NETWORKNAME VARCHAR(50)
		,VPN_SOJ VARCHAR(2)
		,VPN_CAT3 NUMBER(10,0)
		,VPN_PPODATESTAMP DATETIME
		,VPN_NINTEYDAYS NUMBER(10,0)
		,VPN_BILL_TYPE VARCHAR(1)
		,VPN_NET_SAVINGS NUMBER(19,4)
		,CREDIT BOOLEAN
		,RECON BOOLEAN
		,DELETED BOOLEAN
		,STATUS_FLAG VARCHAR(2)
		,DATE_SAVED DATETIME
		,SUB_NETWORK VARCHAR(50)
		,INVALID_CREDIT BOOLEAN
		,PROVIDER_SPECIALTY VARCHAR(50)
		,ADJUSTOR_IDNUMBER VARCHAR(25)
		,ACP_FLAG VARCHAR(1)
		,OVERRIDE_ENDNOTES VARCHAR
		,OVERRIDE_ENDNOTES_DESC VARCHAR )
AS
$$
SELECT t.OdsPostingGroupAuditId
		,t.OdsCustomerId
		,t.OdsCreateDate
		,t.OdsSnapshotDate
		,t.OdsRowIsCurrent
		,t.OdsHashbytesValue
		,t.DmlOperation
		,t.COMPANYCODE
		,t.TRANSACTIONTYPE
		,t.BILL_HDR_AMTALLOWED
		,t.BILL_HDR_AMTCHARGED
		,t.BILL_HDR_BILLIDNO
		,t.BILL_HDR_CMT_HDR_IDNO
		,t.BILL_HDR_CREATEDATE
		,t.BILL_HDR_CV_TYPE
		,t.BILL_HDR_FORM_TYPE
		,t.BILL_HDR_NOLINES
		,t.BILLS_ALLOWED
		,t.BILLS_ANALYZED
		,t.BILLS_CHARGED
		,t.BILLS_DT_SVC
		,t.BILLS_LINE_NO
		,t.CLAIMANT_CLIENTREF_CMTSUFFIX
		,t.CLAIMANT_CMTFIRST_NAME
		,t.CLAIMANT_CMTIDNO
		,t.CLAIMANT_CMTLASTNAME
		,t.CMTSTATEOFJURISDICTION
		,t.CLAIMS_COMPANYID
		,t.CLAIMS_CLAIMNO
		,t.CLAIMS_DATELOSS
		,t.CLAIMS_OFFICEINDEX
		,t.CLAIMS_POLICYHOLDERSNAME
		,t.CLAIMS_POLICYNUMBER
		,t.PNETWKEVENTLOG_EVENTID
		,t.PNETWKEVENTLOG_LOGDATE
		,t.PNETWKEVENTLOG_NETWORKID
		,t.ACTIVITY_FLAG
		,t.PPO_AMTALLOWED
		,t.PREPPO_AMTALLOWED
		,t.PREPPO_ALLOWED_FS
		,t.PRF_COMPANY_COMPANYNAME
		,t.PRF_OFFICE_OFCNAME
		,t.PRF_OFFICE_OFCNO
		,t.PROVIDER_PVDFIRSTNAME
		,t.PROVIDER_PVDGROUP
		,t.PROVIDER_PVDLASTNAME
		,t.PROVIDER_PVDTIN
		,t.PROVIDER_STATE
		,t.UDFCLAIM_UDFVALUETEXT
		,t.ENTRY_DATE
		,t.UDFCLAIMANT_UDFVALUETEXT
		,t.SOURCE_DB
		,t.CLAIMS_CV_CODE
		,t.VPN_TRANSACTIONID
		,t.VPN_TRANSACTIONTYPEID
		,t.VPN_BILLIDNO
		,t.VPN_LINE_NO
		,t.VPN_CHARGED
		,t.VPN_DPALLOWED
		,t.VPN_VPNALLOWED
		,t.VPN_SAVINGS
		,t.VPN_CREDITS
		,t.VPN_HASOVERRIDE
		,t.VPN_ENDNOTES
		,t.VPN_NETWORKIDNO
		,t.VPN_PROCESSFLAG
		,t.VPN_LINETYPE
		,t.VPN_DATETIMESTAMP
		,t.VPN_SEQNO
		,t.VPN_VPN_REF_LINE_NO
		,t.VPN_NETWORKNAME
		,t.VPN_SOJ
		,t.VPN_CAT3
		,t.VPN_PPODATESTAMP
		,t.VPN_NINTEYDAYS
		,t.VPN_BILL_TYPE
		,t.VPN_NET_SAVINGS
		,t.CREDIT
		,t.RECON
		,t.DELETED
		,t.STATUS_FLAG
		,t.DATE_SAVED
		,t.SUB_NETWORK
		,t.INVALID_CREDIT
		,t.PROVIDER_SPECIALTY
		,t.ADJUSTOR_IDNUMBER
		,t.ACP_FLAG
		,t.OVERRIDE_ENDNOTES
		,t.OVERRIDE_ENDNOTES_DESC
FROM src.Esp_Ppo_Billing_Data_Self_Bill t
INNER JOIN (
	SELECT 
		OdsCustomerId,
		VPN_TRANSACTIONID,
		MAX(OdsPostingGroupAuditId) AS OdsPostingGroupAuditId
	FROM src.Esp_Ppo_Billing_Data_Self_Bill
	WHERE OdsPostingGroupAuditId <= if_OdsPostingGroupAuditId
	GROUP BY OdsCustomerId,
		VPN_TRANSACTIONID) s
ON t.OdsPostingGroupAuditId = s.OdsPostingGroupAuditId
	AND t.OdsCustomerId = s.OdsCustomerId
	AND t.VPN_TRANSACTIONID = s.VPN_TRANSACTIONID
WHERE t.DmlOperation <> 'D'

$$;


