CREATE OR REPLACE VIEW aw.AcceptedTreatmentDate
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ACCEPTEDTREATMENTDATEID
		,DEMANDCLAIMANTID
		,TREATMENTDATE
		,COMMENTS
		,TREATMENTCATEGORYID
		,LASTUPDATEDBY
		,LASTUPDATEDDATE
FROM src.AcceptedTreatmentDate
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.AnalysisGroup
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ANALYSISGROUPID
		,GROUPNAME
FROM src.AnalysisGroup
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.AnalysisRule
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ANALYSISRULEID
		,TITLE
		,ASSEMBLYQUALIFIEDNAME
		,METHODTOINVOKE
		,DISPLAYMESSAGE
		,DISPLAYORDER
		,ISACTIVE
		,CREATEDATE
		,LASTCHANGEDON
		,MESSAGETOKEN
FROM src.AnalysisRule
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.AnalysisRuleGroup
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ANALYSISRULEGROUPID
		,ANALYSISRULEID
		,ANALYSISGROUPID
FROM src.AnalysisRuleGroup
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.AnalysisRuleThreshold
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ANALYSISRULETHRESHOLDID
		,ANALYSISRULEID
		,THRESHOLDKEY
		,THRESHOLDVALUE
		,CREATEDATE
		,LASTCHANGEDON
FROM src.AnalysisRuleThreshold
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.ClaimantManualProviderSummary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MANUALPROVIDERID
		,DEMANDCLAIMANTID
		,FIRSTDATEOFSERVICE
		,LASTDATEOFSERVICE
		,VISITS
		,CHARGEDAMOUNT
		,EVALUATEDAMOUNT
		,MINIMUMEVALUATEDAMOUNT
		,MAXIMUMEVALUATEDAMOUNT
		,COMMENTS
FROM src.ClaimantManualProviderSummary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.ClaimantProviderSummaryEvaluation
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMANTPROVIDERSUMMARYEVALUATIONID
		,CLAIMANTHEADERID
		,EVALUATEDAMOUNT
		,MINIMUMEVALUATEDAMOUNT
		,MAXIMUMEVALUATEDAMOUNT
		,COMMENTS
FROM src.ClaimantProviderSummaryEvaluation
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.DemandClaimant
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDCLAIMANTID
		,EXTERNALCLAIMANTID
		,ORGANIZATIONID
		,HEIGHTININCHES
		,WEIGHT
		,OCCUPATION
		,BIREPORTSTATUS
		,HASDEMANDPACKAGE
		,FACTSOFLOSS
		,PREEXISTINGCONDITIONS
		,ARCHIVED
FROM src.DemandClaimant
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.DemandPackage
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDPACKAGEID
		,DEMANDCLAIMANTID
		,REQUESTEDBYUSERNAME
		,DATETIMERECEIVED
		,CORRELATIONID
		,PAGECOUNT
FROM src.DemandPackage
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.DemandPackageRequestedService
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDPACKAGEREQUESTEDSERVICEID
		,DEMANDPACKAGEID
		,REVIEWREQUESTOPTIONS
FROM src.DemandPackageRequestedService
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.DemandPackageUploadedFile
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDPACKAGEUPLOADEDFILEID
		,DEMANDPACKAGEID
		,FILENAME
		,SIZE
		,DOCSTOREID
FROM src.DemandPackageUploadedFile
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.EvaluationSummary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEMANDCLAIMANTID
		,DETAILS
		,CREATEDBY
		,CREATEDDATE
		,MODIFIEDBY
		,MODIFIEDDATE
		,EVALUATIONSUMMARYTEMPLATEVERSIONID
FROM src.EvaluationSummary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.EvaluationSummaryHistory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EVALUATIONSUMMARYHISTORYID
		,DEMANDCLAIMANTID
		,EVALUATIONSUMMARY
		,CREATEDBY
		,CREATEDDATE
FROM src.EvaluationSummaryHistory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.EvaluationSummaryTemplateVersion
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EVALUATIONSUMMARYTEMPLATEVERSIONID
		,TEMPLATE
		,TEMPLATEHASH
		,CREATEDDATE
FROM src.EvaluationSummaryTemplateVersion
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.EventLog
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EVENTLOGID
		,OBJECTNAME
		,OBJECTID
		,USERNAME
		,LOGDATE
		,ACTIONNAME
		,ORGANIZATIONID
FROM src.EventLog
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.EventLogDetail
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EVENTLOGDETAILID
		,EVENTLOGID
		,PROPERTYNAME
		,OLDVALUE
		,NEWVALUE
FROM src.EventLogDetail
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.ManualProvider
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MANUALPROVIDERID
		,TIN
		,LASTNAME
		,FIRSTNAME
		,GROUPNAME
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
FROM src.ManualProvider
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.ManualProviderSpecialty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MANUALPROVIDERID
		,SPECIALTY
FROM src.ManualProviderSpecialty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.Note
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,NOTEID
		,DATECREATED
		,DATEMODIFIED
		,CREATEDBY
		,MODIFIEDBY
		,FLAG
		,CONTENT
		,NOTECONTEXT
		,DEMANDCLAIMANTID
FROM src.Note
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.PROVIDEDLINK
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDEDLINKID
		,TITLE
		,URL
		,ORDERINDEX
FROM src.PROVIDEDLINK
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';

CREATE OR REPLACE VIEW aw.Tag
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TAGID
		,NAME
		,DATECREATED
		,DATEMODIFIED
		,CREATEDBY
		,MODIFIEDBY
FROM src.Tag
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.TreatmentCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TREATMENTCATEGORYID
		,CATEGORY
		,METADATA
FROM src.TreatmentCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW aw.TreatmentCategoryRange
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TREATMENTCATEGORYRANGEID
		,TREATMENTCATEGORYID
		,STARTRANGE
		,ENDRANGE
FROM src.TreatmentCategoryRange
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Adjustment3603rdPartyEndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.Adjustment3603rdPartyEndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Adjustment360ApcEndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.Adjustment360ApcEndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Adjustment360Category
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ADJUSTMENT360CATEGORYID
		,NAME
FROM src.Adjustment360Category
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Adjustment360EndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
		,ENDNOTETYPEID
FROM src.Adjustment360EndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Adjustment360OverrideEndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.Adjustment360OverrideEndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Adjustment360SubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ADJUSTMENT360SUBCATEGORYID
		,NAME
		,ADJUSTMENT360CATEGORYID
FROM src.Adjustment360SubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Adjustment3rdPartyEndnoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.Adjustment3rdPartyEndnoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.AdjustmentApcEndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.AdjustmentApcEndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.AdjustmentEndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.AdjustmentEndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.AdjustmentOverrideEndNoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SUBCATEGORYID
FROM src.AdjustmentOverrideEndNoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Adjustor
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,LADJIDNO
		,IDNUMBER
		,LASTNAME
		,FIRSTNAME
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIPCODE
		,PHONE
		,FAX
		,OFFICE
		,EMAIL
		,INUSE
		,OFFICEIDNO
		,USERID
		,CREATEDATE
		,LASTCHANGEDON
FROM src.Adjustor
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,APPORTIONMENTENDNOTE
		,SHORTDESCRIPTION
		,LONGDESCRIPTION
FROM src.ApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillAdjustment
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLLINEADJUSTMENTID
		,BILLIDNO
		,LINENUMBER
		,ADJUSTMENT
		,ENDNOTE
		,ENDNOTETYPEID
FROM src.BillAdjustment
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,LINENUMBER
		,ENDNOTE
FROM src.BillApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillCustomEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,LINENUMBER
		,ENDNOTE
FROM src.BillCustomEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillExclusionLookUpTable
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REPORTID
		,REPORTNAME
FROM src.BillExclusionLookUpTable
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BILLS
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,LINE_NO_DISP
		,OVER_RIDE
		,DT_SVC
		,PRC_CD
		,UNITS
		,TS_CD
		,CHARGED
		,ALLOWED
		,ANALYZED
		,REASON1
		,REASON2
		,REASON3
		,REASON4
		,REASON5
		,REASON6
		,REASON7
		,REASON8
		,REF_LINE_NO
		,SUBNET
		,OVERRIDEREASON
		,FEE_SCHEDULE
		,POS_REVCODE
		,CTGPENALTY
		,PREPPOALLOWED
		,PPODATE
		,PPOCTGPENALTY
		,UCRPERUNIT
		,FSPERUNIT
		,HCRA_SURCHARGE
		,ELIGIBLEAMT
		,DPALLOWED
		,ENDDATEOFSERVICE
		,ANALYZEDCTGPENALTY
		,ANALYZEDCTGPPOPENALTY
		,REPACKAGEDNDC
		,ORIGINALNDC
		,UNITOFMEASUREID
		,PACKAGETYPEORIGINALNDC
		,SERVICECODE
		,PREAPPORTIONEDAMOUNT
		,DEDUCTIBLEAPPLIED
		,BILLREVIEWRESULTS
		,PREOVERRIDDENDEDUCTIBLE
		,REMAININGBALANCE
		,CTGCOPAYPENALTY
		,PPOCTGCOPAYPENALTYPERCENTAGE
		,ANALYZEDCTGCOPAYPENALTY
		,ANALYZEDPPOCTGCOPAYPENALTYPERCENTAGE
		,CTGVUNPENALTY
		,PPOCTGVUNPENALTYPERCENTAGE
		,ANALYZEDCTGVUNPENALTY
		,ANALYZEDPPOCTGVUNPENALTYPERCENTAGE
		,RENDERINGNPI
FROM src.BILLS
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillsOverride
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLSOVERRIDEID
		,BILLIDNO
		,LINE_NO
		,USERID
		,DATESAVED
		,AMOUNTBEFORE
		,AMOUNTAFTER
		,CODESOVERRODE
		,SEQNO
FROM src.BillsOverride
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillsProviderNetwork
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,NETWORKID
		,NETWORKNAME
FROM src.BillsProviderNetwork
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BILLS_CTG_Endnotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,ENDNOTE
		,RULETYPE
		,RULEID
		,PRECERTACTION
		,PERCENTDISCOUNT
		,ACTIONID
FROM src.BILLS_CTG_Endnotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BILLS_DRG
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,PRICERPASSTHRU
		,PRICERCAPITAL_OUTLIER_AMT
		,PRICERCAPITAL_OLDHARM_AMT
		,PRICERCAPITAL_IME_AMT
		,PRICERCAPITAL_HSP_AMT
		,PRICERCAPITAL_FSP_AMT
		,PRICERCAPITAL_EXCEPTIONS_AMT
		,PRICERCAPITAL_DSH_AMT
		,PRICERCAPITALPAYMENT
		,PRICERDSH
		,PRICERIME
		,PRICERCOSTOUTLIER
		,PRICERHSP
		,PRICERFSP
		,PRICERTOTALPAYMENT
		,PRICERRETURNMSG
		,RETURNDRG
		,RETURNDRGDESC
		,RETURNMDC
		,RETURNMDCDESC
		,RETURNDRGWT
		,RETURNDRGALOS
		,RETURNADX
		,RETURNSDX
		,RETURNMPR
		,RETURNPR2
		,RETURNPR3
		,RETURNNOR
		,RETURNNO2
		,RETURNCOM
		,RETURNCMI
		,RETURNDCC
		,RETURNDX1
		,RETURNDX2
		,RETURNDX3
		,RETURNMCI
		,RETURNOR1
		,RETURNOR2
		,RETURNOR3
		,RETURNTRI
		,SOJ
		,OPCERT
		,BLENDCASEINCLMALP
		,CAPITALCOST
		,HOSPBADDEBT
		,EXCESSPHYSMALP
		,SPARCSPERCASE
		,ALTLEVELOFCARE
		,DRGWGT
		,TRANSFERCAPITAL
		,NYDRGTYPE
		,LOS
		,TRIMPOINT
		,GROUPBLENDPERCENTAGE
		,ADJUSTMENTFACTOR
		,HOSPLONGSTAYGROUPPRICE
		,TOTALDRGCHARGE
		,BLENDCASEADJ
		,CAPITALCOSTADJ
		,NONMEDICARECASEMIX
		,HIGHCOSTCHARGECONVERTER
		,DISCHARGECASEPAYMENTRATE
		,DIRECTMEDICALEDUCATION
		,CASEPAYMENTCAPITALPERDIEM
		,HIGHCOSTOUTLIERTHRESHOLD
		,ISAF
		,RETURNSOI
		,CAPITALCOSTPERDISCHARGE
		,RETURNSOIDESC
FROM src.BILLS_DRG
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BILLS_Endnotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,ENDNOTE
		,REFERRAL
		,PERCENTDISCOUNT
		,ACTIONID
		,ENDNOTETYPEID
FROM src.BILLS_Endnotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bills_OverrideEndNotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,OVERRIDEENDNOTEID
		,BILLIDNO
		,LINE_NO
		,OVERRIDEENDNOTE
		,PERCENTDISCOUNT
		,ACTIONID
FROM src.Bills_OverrideEndNotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bills_Pharm
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,LINE_NO_DISP
		,DATEOFSERVICE
		,NDC
		,PRICETYPECODE
		,UNITS
		,CHARGED
		,ALLOWED
		,ENDNOTE
		,OVERRIDE
		,OVERRIDE_RSN
		,ANALYZED
		,CTGPENALTY
		,PREPPOALLOWED
		,PPODATE
		,POS_REVCODE
		,DPALLOWED
		,HCRA_SURCHARGE
		,ENDDATEOFSERVICE
		,REPACKAGEDNDC
		,ORIGINALNDC
		,UNITOFMEASUREID
		,PACKAGETYPEORIGINALNDC
		,PPOCTGPENALTY
		,SERVICECODE
		,PREAPPORTIONEDAMOUNT
		,DEDUCTIBLEAPPLIED
		,BILLREVIEWRESULTS
		,PREOVERRIDDENDEDUCTIBLE
		,REMAININGBALANCE
		,CTGCOPAYPENALTY
		,PPOCTGCOPAYPENALTYPERCENTAGE
		,CTGVUNPENALTY
		,PPOCTGVUNPENALTYPERCENTAGE
		,RENDERINGNPI
FROM src.Bills_Pharm
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bills_Pharm_CTG_Endnotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,ENDNOTE
		,RULETYPE
		,RULEID
		,PRECERTACTION
		,PERCENTDISCOUNT
		,ACTIONID
FROM src.Bills_Pharm_CTG_Endnotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bills_Pharm_Endnotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,ENDNOTE
		,REFERRAL
		,PERCENTDISCOUNT
		,ACTIONID
		,ENDNOTETYPEID
FROM src.Bills_Pharm_Endnotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bills_Pharm_OverrideEndNotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,OVERRIDEENDNOTEID
		,BILLIDNO
		,LINE_NO
		,OVERRIDEENDNOTE
		,PERCENTDISCOUNT
		,ACTIONID
FROM src.Bills_Pharm_OverrideEndNotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bills_Tax
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLSTAXID
		,TABLETYPE
		,BILLIDNO
		,LINE_NO
		,SEQNO
		,TAXTYPEID
		,IMPORTTAXRATE
		,TAX
		,OVERRIDENTAX
		,IMPORTTAXAMOUNT
FROM src.Bills_Tax
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BILL_HDR
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,CMT_HDR_IDNO
		,DATESAVED
		,DATERCV
		,INVOICENUMBER
		,INVOICEDATE
		,FILENUMBER
		,NOTE
		,NOLINES
		,AMTCHARGED
		,AMTALLOWED
		,REASONVERSION
		,REGION
		,PVDUPDATECOUNTER
		,FEATUREID
		,CLAIMDATELOSS
		,CV_TYPE
		,FLAGS
		,WHOCREATE
		,WHOLAST
		,ACCEPTASSIGNMENT
		,EMERGENCYSERVICE
		,CMTPAIDDEDUCTIBLE
		,INSPAIDLIMIT
		,STATUSFLAG
		,OFFICEID
		,CMTPAIDCOPAY
		,AMBULANCEMETHOD
		,STATUSDATE
		,CATEGORY
		,CATDESC
		,ASSIGNEDUSER
		,CREATEDATE
		,PVDZOS
		,PPONUMBERSENT
		,ADMISSIONDATE
		,DISCHARGEDATE
		,DISCHARGESTATUS
		,TYPEOFBILL
		,SENTRYMESSAGE
		,AMBULANCEZIPOFPICKUP
		,AMBULANCENUMBEROFPATIENTS
		,WHOCREATEID
		,WHOLASTID
		,NYREQUESTDATE
		,NYRECEIVEDDATE
		,IMGDOCID
		,PAYMENTDECISION
		,PVDCMSID
		,PVDNPINO
		,DISCHARGEHOUR
		,PRECERTCHANGED
		,DUEDATE
		,ATTORNEYIDNO
		,ASSIGNEDGROUP
		,LASTCHANGEDON
		,PREPPOALLOWED
		,PPSCODE
		,SOI
		,STATEMENTSTARTDATE
		,STATEMENTENDDATE
		,DEDUCTIBLEOVERRIDE
		,ADMISSIONTYPE
		,COVERAGETYPE
		,PRICINGPROFILEID
		,DESIGNATEDPRICINGSTATE
		,DATEANALYZED
		,SENTTOPPOSYSID
		,PRICINGSTATE
		,BILLVPNELIGIBLE
		,APPORTIONMENTPERCENTAGE
		,BILLSOURCEID
		,OUTOFSTATEPROVIDERNUMBER
		,FLORIDADEDUCTIBLERULEELIGIBLE
FROM src.BILL_HDR
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bill_History
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,SEQNO
		,DATECOMMITTED
		,AMTCOMMITTED
		,USERID
		,AMTCOPAY
		,AMTDEDUCTIBLE
		,FLAGS
		,AMTSALESTAX
		,AMTOTHERTAX
		,DEDUCTIBLEOVERRIDE
		,PRICINGSTATE
		,APPORTIONMENTPERCENTAGE
		,FLORIDADEDUCTIBLERULEELIGIBLE
FROM src.Bill_History
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bill_Payment_Adjustments
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILL_PAYMENT_ADJUSTMENT_ID
		,BILLIDNO
		,SEQNO
		,INTERESTFLAGS
		,DATEINTERESTSTARTS
		,DATEINTERESTENDS
		,INTERESTADDITIONALINFORECEIVED
		,INTEREST
		,COMMENTS
FROM src.Bill_Payment_Adjustments
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bill_Pharm_ApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,LINENUMBER
		,ENDNOTE
FROM src.Bill_Pharm_ApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bill_Sentry_Endnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,LINE
		,RULEID
		,PERCENTDISCOUNT
		,ACTIONID
FROM src.Bill_Sentry_Endnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BIReportAdjustmentCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BIREPORTADJUSTMENTCATEGORYID
		,NAME
		,DESCRIPTION
		,DISPLAYPRIORITY
FROM src.BIReportAdjustmentCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BIReportAdjustmentCategoryMapping
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BIREPORTADJUSTMENTCATEGORYID
		,ADJUSTMENT360SUBCATEGORYID
FROM src.BIReportAdjustmentCategoryMapping
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bitmasks
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TABLEPROGRAMUSED
		,ATTRIBUTEUSED
		,DECIMAL
		,CONSTANTNAME
		,BIT
		,HEX
		,DESCRIPTION
FROM src.Bitmasks
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW DBO.CBRETODPENDNOTEMAPPING
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENDNOTE
		,ENDNOTETYPEID
		,CBREENDNOTE
		,PRICINGSTATE
		,PRICINGMETHODID
FROM src.CBRETODPENDNOTEMAPPING
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';CREATE OR REPLACE VIEW dbo.CLAIMANT
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CMTIDNO
		,CLAIMIDNO
		,CMTSSN
		,CMTLASTNAME
		,CMTFIRSTNAME
		,CMTMI
		,CMTDOB
		,CMTSEX
		,CMTADDR1
		,CMTADDR2
		,CMTCITY
		,CMTSTATE
		,CMTZIP
		,CMTPHONE
		,CMTOCCNO
		,CMTATTORNEYNO
		,CMTPOLICYLIMIT
		,CMTSTATEOFJURISDICTION
		,CMTDEDUCTIBLE
		,CMTCOPAYMENTPERCENTAGE
		,CMTCOPAYMENTMAX
		,CMTPPO_ELIGIBLE
		,CMTCOORDBENEFITS
		,CMTFLCOPAY
		,CMTCOAEXPORT
		,CMTPGFIRSTNAME
		,CMTPGLASTNAME
		,CMTDEDTYPE
		,EXPORTTOCLAIMIQ
		,CMTINACTIVE
		,CMTPRECERTOPTION
		,CMTPRECERTSTATE
		,CREATEDATE
		,LASTCHANGEDON
		,ODSPARTICIPANT
		,COVERAGETYPE
		,DONOTDISPLAYCOVERAGETYPEONEOB
		,SHOWALLOCATIONSONEOB
		,SETPREALLOCATION
		,PHARMACYELIGIBLE
		,SENDCARDTOCLAIMANT
		,SHARECOPAYMAXIMUM
FROM src.CLAIMANT
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Claimant_ClientRef
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CMTIDNO
		,CMTSUFFIX
		,CLAIMIDNO
FROM src.Claimant_ClientRef
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CLAIMS
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMIDNO
		,CLAIMNO
		,DATELOSS
		,CV_CODE
		,DIARYINDEX
		,LASTSAVED
		,POLICYNUMBER
		,POLICYHOLDERSNAME
		,PAIDDEDUCTIBLE
		,STATUS
		,INUSE
		,COMPANYID
		,OFFICEINDEX
		,ADJIDNO
		,PAIDCOPAY
		,ASSIGNEDUSER
		,PRIVATIZED
		,POLICYEFFDATE
		,DEDUCTIBLE
		,LOSSSTATE
		,ASSIGNEDGROUP
		,CREATEDATE
		,LASTCHANGEDON
		,ALLOWMULTICOVERAGE
FROM src.CLAIMS
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Claims_ClientRef
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMIDNO
		,CLIENTREFID
FROM src.Claims_ClientRef
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CMS_Zip2Region
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STARTDATE
		,ENDDATE
		,ZIP_CODE
		,STATE
		,REGION
		,AMBREGION
		,RURALFLAG
		,ASCREGION
		,PLUSFOUR
		,CARRIERID
FROM src.CMS_Zip2Region
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CMT_DX
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,DX
		,SEQNUM
		,POA
		,ICDVERSION
FROM src.CMT_DX
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CMT_HDR
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CMT_HDR_IDNO
		,CMTIDNO
		,PVDIDNO
		,LASTCHANGEDON
FROM src.CMT_HDR
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CMT_ICD9
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,SEQNO
		,ICD9
		,ICDVERSION
FROM src.CMT_ICD9
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,LONGNAME
		,SHORTNAME
		,CBRECOVERAGETYPECODE
		,COVERAGETYPECATEGORYCODE
		,PRICINGMETHODID
FROM src.CoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.cpt_DX_DICT
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ICD9
		,STARTDATE
		,ENDDATE
		,FLAGS
		,NONSPECIFIC
		,ADDITIONALDIGITS
		,TRAUMATIC
		,DX_DESC
		,DURATION
		,COLOSSUS
		,DIAGNOSISFAMILYID
FROM src.cpt_DX_DICT
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.cpt_PRC_DICT
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PRC_CD
		,STARTDATE
		,ENDDATE
		,PRC_DESC
		,FLAGS
		,VAGUE
		,PERVISIT
		,PERCLAIMANT
		,PERPROVIDER
		,BODYFLAGS
		,COLOSSUS
		,CMS_STATUS
		,DRUGFLAG
		,CURATIVEFLAG
		,EXCLPOLICYLIMIT
		,SPECNETFLAG
FROM src.cpt_PRC_DICT
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CreditReason
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CREDITREASONID
		,CREDITREASONDESC
		,ISVISIBLE
FROM src.CreditReason
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CreditReasonOverrideENMap
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CREDITREASONOVERRIDEENMAPID
		,CREDITREASONID
		,OVERRIDEENDNOTEID
FROM src.CreditReasonOverrideENMap
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CriticalAccessHospitalInpatientRevenueCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REVENUECODE
FROM src.CriticalAccessHospitalInpatientRevenueCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CTG_Endnotes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENDNOTE
		,SHORTDESC
		,LONGDESC
FROM src.CTG_Endnotes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CustomBillStatuses
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATUSID
		,STATUSNAME
		,STATUSDESCRIPTION
FROM src.CustomBillStatuses
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CustomEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CUSTOMENDNOTE
		,SHORTDESCRIPTION
		,LONGDESCRIPTION
FROM src.CustomEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CustomerBillExclusion
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,CUSTOMER
		,REPORTID
		,CREATEDATE
FROM src.CustomerBillExclusion
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.DeductibleRuleCriteria
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEDUCTIBLERULECRITERIAID
		,PRICINGRULEDATECRITERIAID
		,STARTDATE
		,ENDDATE
FROM src.DeductibleRuleCriteria
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.DeductibleRuleCriteriaCoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DEDUCTIBLERULECRITERIAID
		,COVERAGETYPE
FROM src.DeductibleRuleCriteriaCoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.DeductibleRuleExemptEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENDNOTE
		,ENDNOTETYPEID
FROM src.DeductibleRuleExemptEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.DiagnosisCodeGroup
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DIAGNOSISCODE
		,STARTDATE
		,ENDDATE
		,MAJORCATEGORY
		,MINORCATEGORY
FROM src.DiagnosisCodeGroup
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.EncounterType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENCOUNTERTYPEID
		,ENCOUNTERTYPEPRIORITY
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.EncounterType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.EndnoteSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENDNOTESUBCATEGORYID
		,DESCRIPTION
FROM src.EndnoteSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Esp_Ppo_Billing_Data_Self_Bill
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,COMPANYCODE
		,TRANSACTIONTYPE
		,BILL_HDR_AMTALLOWED
		,BILL_HDR_AMTCHARGED
		,BILL_HDR_BILLIDNO
		,BILL_HDR_CMT_HDR_IDNO
		,BILL_HDR_CREATEDATE
		,BILL_HDR_CV_TYPE
		,BILL_HDR_FORM_TYPE
		,BILL_HDR_NOLINES
		,BILLS_ALLOWED
		,BILLS_ANALYZED
		,BILLS_CHARGED
		,BILLS_DT_SVC
		,BILLS_LINE_NO
		,CLAIMANT_CLIENTREF_CMTSUFFIX
		,CLAIMANT_CMTFIRST_NAME
		,CLAIMANT_CMTIDNO
		,CLAIMANT_CMTLASTNAME
		,CMTSTATEOFJURISDICTION
		,CLAIMS_COMPANYID
		,CLAIMS_CLAIMNO
		,CLAIMS_DATELOSS
		,CLAIMS_OFFICEINDEX
		,CLAIMS_POLICYHOLDERSNAME
		,CLAIMS_POLICYNUMBER
		,PNETWKEVENTLOG_EVENTID
		,PNETWKEVENTLOG_LOGDATE
		,PNETWKEVENTLOG_NETWORKID
		,ACTIVITY_FLAG
		,PPO_AMTALLOWED
		,PREPPO_AMTALLOWED
		,PREPPO_ALLOWED_FS
		,PRF_COMPANY_COMPANYNAME
		,PRF_OFFICE_OFCNAME
		,PRF_OFFICE_OFCNO
		,PROVIDER_PVDFIRSTNAME
		,PROVIDER_PVDGROUP
		,PROVIDER_PVDLASTNAME
		,PROVIDER_PVDTIN
		,PROVIDER_STATE
		,UDFCLAIM_UDFVALUETEXT
		,ENTRY_DATE
		,UDFCLAIMANT_UDFVALUETEXT
		,SOURCE_DB
		,CLAIMS_CV_CODE
		,VPN_TRANSACTIONID
		,VPN_TRANSACTIONTYPEID
		,VPN_BILLIDNO
		,VPN_LINE_NO
		,VPN_CHARGED
		,VPN_DPALLOWED
		,VPN_VPNALLOWED
		,VPN_SAVINGS
		,VPN_CREDITS
		,VPN_HASOVERRIDE
		,VPN_ENDNOTES
		,VPN_NETWORKIDNO
		,VPN_PROCESSFLAG
		,VPN_LINETYPE
		,VPN_DATETIMESTAMP
		,VPN_SEQNO
		,VPN_VPN_REF_LINE_NO
		,VPN_NETWORKNAME
		,VPN_SOJ
		,VPN_CAT3
		,VPN_PPODATESTAMP
		,VPN_NINTEYDAYS
		,VPN_BILL_TYPE
		,VPN_NET_SAVINGS
		,CREDIT
		,RECON
		,DELETED
		,STATUS_FLAG
		,DATE_SAVED
		,SUB_NETWORK
		,INVALID_CREDIT
		,PROVIDER_SPECIALTY
		,ADJUSTOR_IDNUMBER
		,ACP_FLAG
		,OVERRIDE_ENDNOTES
		,OVERRIDE_ENDNOTES_DESC
FROM src.Esp_Ppo_Billing_Data_Self_Bill
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ExtractCat
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CATIDNO
		,DESCRIPTION
FROM src.ExtractCat
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.GeneralInterestRuleBaseType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,GENERALINTERESTRULEBASETYPEID
		,GENERALINTERESTRULEBASETYPENAME
FROM src.GeneralInterestRuleBaseType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.GeneralInterestRuleSetting
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,GENERALINTERESTRULEBASETYPEID
FROM src.GeneralInterestRuleSetting
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Icd10DiagnosisVersion
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DIAGNOSISCODE
		,STARTDATE
		,ENDDATE
		,NONSPECIFIC
		,TRAUMATIC
		,DURATION
		,DESCRIPTION
		,DIAGNOSISFAMILYID
		,TOTALCHARACTERSREQUIRED
		,PLACEHOLDERREQUIRED
FROM src.Icd10DiagnosisVersion
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ICD10ProcedureCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ICDPROCEDURECODE
		,STARTDATE
		,ENDDATE
		,DESCRIPTION
		,PASGRPNO
FROM src.ICD10ProcedureCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.IcdDiagnosisCodeDictionary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DIAGNOSISCODE
		,ICDVERSION
		,STARTDATE
		,ENDDATE
		,NONSPECIFIC
		,TRAUMATIC
		,DURATION
		,DESCRIPTION
		,DIAGNOSISFAMILYID
		,DIAGNOSISSEVERITYID
		,LATERALITYID
		,TOTALCHARACTERSREQUIRED
		,PLACEHOLDERREQUIRED
		,FLAGS
		,ADDITIONALDIGITS
		,COLOSSUS
		,INJURYNATUREID
		,ENCOUNTERSUBCATEGORYID
FROM src.IcdDiagnosisCodeDictionary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.IcdDiagnosisCodeDictionaryBodyPart
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DIAGNOSISCODE
		,ICDVERSION
		,STARTDATE
		,NCCIBODYPARTID
FROM src.IcdDiagnosisCodeDictionaryBodyPart
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.InjuryNature
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,INJURYNATUREID
		,INJURYNATUREPRIORITY
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.InjuryNature
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.lkp_SPC
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,LKP_SPCID
		,LONGNAME
		,SHORTNAME
		,MULT
		,NCD92
		,NCD93
		,PLUSFOUR
		,CBRESPECIALTYCODE
FROM src.lkp_SPC
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.lkp_TS
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SHORTNAME
		,STARTDATE
		,ENDDATE
		,LONGNAME
		,GLOBAL
		,ANESMEDDIRECT
		,AFFECTSPRICING
		,ISASSISTANTSURGERY
		,ISCOSURGEON
FROM src.lkp_TS
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.MedicalCodeCutOffs
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CODETYPEID
		,CODETYPE
		,CODE
		,FORMTYPE
		,MAXCHARGEDPERUNIT
		,MAXUNITSPERENCOUNTER
FROM src.MedicalCodeCutOffs
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.MedicareStatusIndicatorRule
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MEDICARESTATUSINDICATORRULEID
		,MEDICARESTATUSINDICATORRULENAME
		,STATUSINDICATOR
		,STARTDATE
		,ENDDATE
		,ENDNOTE
		,EDITACTIONID
		,COMMENTS
FROM src.MedicareStatusIndicatorRule
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.MedicareStatusIndicatorRuleCoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MEDICARESTATUSINDICATORRULEID
		,SHORTNAME
FROM src.MedicareStatusIndicatorRuleCoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.MedicareStatusIndicatorRulePlaceOfService
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MEDICARESTATUSINDICATORRULEID
		,PLACEOFSERVICE
FROM src.MedicareStatusIndicatorRulePlaceOfService
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.MedicareStatusIndicatorRuleProcedureCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MEDICARESTATUSINDICATORRULEID
		,PROCEDURECODE
FROM src.MedicareStatusIndicatorRuleProcedureCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.MedicareStatusIndicatorRuleProviderSpecialty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MEDICARESTATUSINDICATORRULEID
		,PROVIDERSPECIALTY
FROM src.MedicareStatusIndicatorRuleProviderSpecialty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ModifierByState
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATE
		,PROCEDURESERVICECATEGORYID
		,MODIFIERDICTIONARYID
FROM src.ModifierByState
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ModifierDictionary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MODIFIERDICTIONARYID
		,MODIFIER
		,STARTDATE
		,ENDDATE
		,DESCRIPTION
		,GLOBAL
		,ANESMEDDIRECT
		,AFFECTSPRICING
		,ISCOSURGEON
		,ISASSISTANTSURGERY
FROM src.ModifierDictionary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ModifierToProcedureCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROCEDURECODE
		,MODIFIER
		,STARTDATE
		,ENDDATE
		,SOJFLAG
		,REQUIRESGUIDELINEREVIEW
		,REFERENCE
		,COMMENTS
FROM src.ModifierToProcedureCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.NcciBodyPart
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,NCCIBODYPARTID
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.NcciBodyPart
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.NcciBodyPartToHybridBodyPartTranslation
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,NCCIBODYPARTID
		,HYBRIDBODYPARTID
FROM src.NcciBodyPartToHybridBodyPartTranslation
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ny_pharmacy
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,NDCCODE
		,STARTDATE
		,ENDDATE
		,DESCRIPTION
		,FEE
		,TYPEOFDRUG
FROM src.ny_pharmacy
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ny_specialty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RATINGCODE
		,DESC_
		,CBRESPECIALTYCODE
FROM src.ny_specialty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.pa_PlaceOfService
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,POS
		,DESCRIPTION
		,FACILITY
		,MHL
		,PLUSFOUR
		,INSTITUTION
FROM src.pa_PlaceOfService
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PlaceOfServiceDictionary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PLACEOFSERVICECODE
		,DESCRIPTION
		,FACILITY
		,MHL
		,PLUSFOUR
		,INSTITUTION
		,STARTDATE
		,ENDDATE
FROM src.PlaceOfServiceDictionary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PrePpoBillInfo
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DATESENTTOPPO
		,CLAIMNO
		,CLAIMIDNO
		,COMPANYID
		,OFFICEINDEX
		,CV_CODE
		,DATELOSS
		,DEDUCTIBLE
		,PAIDCOPAY
		,PAIDDEDUCTIBLE
		,LOSSSTATE
		,CMTIDNO
		,CMTCOPAYMENTMAX
		,CMTCOPAYMENTPERCENTAGE
		,CMTDEDTYPE
		,CMTDEDUCTIBLE
		,CMTFLCOPAY
		,CMTPOLICYLIMIT
		,CMTSTATEOFJURISDICTION
		,PVDIDNO
		,PVDTIN
		,PVDSPC_LIST
		,PVDTITLE
		,PVDFLAGS
		,DATESAVED
		,DATERCV
		,INVOICEDATE
		,NOLINES
		,AMTCHARGED
		,AMTALLOWED
		,REGION
		,FEATUREID
		,FLAGS
		,WHOCREATE
		,WHOLAST
		,CMTPAIDDEDUCTIBLE
		,INSPAIDLIMIT
		,STATUSFLAG
		,CMTPAIDCOPAY
		,CATEGORY
		,CATDESC
		,CREATEDATE
		,PVDZOS
		,ADMISSIONDATE
		,DISCHARGEDATE
		,DISCHARGESTATUS
		,TYPEOFBILL
		,PAYMENTDECISION
		,PPONUMBERSENT
		,BILLIDNO
		,LINE_NO
		,LINE_NO_DISP
		,OVER_RIDE
		,DT_SVC
		,PRC_CD
		,UNITS
		,TS_CD
		,CHARGED
		,ALLOWED
		,ANALYZED
		,REF_LINE_NO
		,SUBNET
		,FEE_SCHEDULE
		,POS_REVCODE
		,CTGPENALTY
		,PREPPOALLOWED
		,PPODATE
		,PPOCTGPENALTY
		,UCRPERUNIT
		,FSPERUNIT
		,HCRA_SURCHARGE
		,NDC
		,PRICETYPECODE
		,PHARMACYLINE
		,ENDNOTES
		,SENTRYEN
		,CTGEN
		,CTGRULETYPE
		,CTGRULEID
		,OVERRIDEEN
		,USERID
		,DATEOVERRIDEN
		,AMOUNTBEFOREOVERRIDE
		,AMOUNTAFTEROVERRIDE
		,CODESOVERRIDEN
		,NETWORKID
		,BILLSNAPSHOT
		,PPOSAVINGS
		,REVISEDDATE
		,RECONSIDEREDDATE
		,TIERNUMBER
		,PPOBILLINFOID
		,PREPPOBILLINFOID
		,CTGCOPAYPENALTY
		,PPOCTGCOPAYPENALTYPERCENTAGE
		,CTGVUNPENALTY
		,PPOCTGVUNPENALTYPERCENTAGE
FROM src.PrePpoBillInfo
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.prf_COMPANY
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,COMPANYID
		,COMPANYNAME
		,LASTCHANGEDON
FROM src.prf_COMPANY
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.prf_CTGMaxPenaltyLines
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CTGMAXPENLINEID
		,PROFILEID
		,DATESBASEDON
		,MAXPENALTYPERCENT
		,STARTDATE
		,ENDDATE
FROM src.prf_CTGMaxPenaltyLines
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.prf_CTGPenalty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CTGPENID
		,PROFILEID
		,APPLYPRECERTS
		,NOPRECERTLOGGED
		,MAXTOTALPENALTY
		,TURNTIMEFORAPPEALS
		,APPLYENDNOTEFORPERCERT
		,APPLYENDNOTEFORCAREPATH
		,EXEMPTPRECERTPENALTY
		,APPLYNETWORKPENALTY
FROM src.prf_CTGPenalty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.prf_CTGPenaltyHdr
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CTGPENHDRID
		,PROFILEID
		,PENALTYTYPE
		,PAYNEGRATE
		,PAYPPORATE
		,DATESBASEDON
		,APPLYPENALTYTOPHARMACY
		,APPLYPENALTYCONDITION
FROM src.prf_CTGPenaltyHdr
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.prf_CTGPenaltyLines
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CTGPENLINEID
		,PROFILEID
		,PENALTYTYPE
		,FEESCHEDULEPERCENT
		,STARTDATE
		,ENDDATE
		,TURNAROUNDTIME
FROM src.prf_CTGPenaltyLines
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Prf_CustomIcdAction
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CUSTOMICDACTIONID
		,PROFILEID
		,ICDVERSIONID
		,ACTION
		,STARTDATE
		,ENDDATE
FROM src.Prf_CustomIcdAction
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.prf_Office
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,COMPANYID
		,OFFICEID
		,OFCNO
		,OFCNAME
		,OFCADDR1
		,OFCADDR2
		,OFCCITY
		,OFCSTATE
		,OFCZIP
		,OFCPHONE
		,OFCDEFAULT
		,OFCCLAIMMASK
		,OFCTINMASK
		,VERSION
		,OFCEDITS
		,OFCCOAENABLED
		,CTGENABLED
		,LASTCHANGEDON
		,ALLOWMULTICOVERAGE
FROM src.prf_Office
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Prf_OfficeUDF
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,OFFICEID
		,UDFIDNO
FROM src.Prf_OfficeUDF
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.prf_PPO
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPOSYSID
		,PROFILEID
		,PPOID
		,BSTATUS
		,STARTDATE
		,ENDDATE
		,AUTOSEND
		,AUTORESEND
		,BYPASSMATCHING
		,USEPROVIDERNETWORKENROLLMENT
		,TIEREDTYPEID
		,PRIORITY
		,POLICYEFFECTIVEDATE
		,BILLFORMTYPE
FROM src.prf_PPO
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.prf_Profile
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROFILEID
		,OFFICEID
		,COVERAGEID
		,STATEID
		,ANHEADER
		,ANFOOTER
		,EXHEADER
		,EXFOOTER
		,ANALYSTEDITS
		,DXEDITS
		,DXNONTRAUMADAYS
		,DXNONSPECDAYS
		,PRINTCOPIES
		,NEWPVDSTATE
		,BDURATION
		,BLIMITS
		,IDURPCT
		,ILIMITPCT
		,POLICYLIMIT
		,COPAYPERCENT
		,COPAYMAX
		,DEDUCTIBLE
		,POLICYWARN
		,POLICYWARNPERC
		,FEESCHEDULES
		,DEFAULTPROFILE
		,FEEANCILLARYPCT
		,IGAPDOL
		,IGAPTREATMNT
		,BGAPTREATMNT
		,BGAPDOL
		,BPRINTADJUSTOR
		,SPRINTERNAME
		,EREDITS
		,ERALLOWEDDAYS
		,UCRFSRULES
		,LOGOIDNO
		,LOGOJUSTIFY
		,BILLLINE
		,VERSION
		,CLAIMDEDUCTIBLE
		,INCLUDECOMMITTED
		,FLMEDICAREPERCENT
		,USELEVELOFSERVICEURL
		,LEVELOFSERVICEURL
		,CCIPRIMARY
		,CCISECONDARY
		,CCIMUTUALLYEXCLUSIVE
		,CCICOMPREHENSIVECOMPONENT
		,PAYDRGALLOWANCE
		,FLHOSPEMPRICEON
		,ENABLEBILLRELEASE
		,DISABLESUBMITBILL
		,MAXPAYMENTSPERBILL
		,NOOFPMTPERBILL
		,DEFAULTDUEDATE
		,CHECKFORNJCAREPATHS
		,NJCAREPATHPERCENTFS
		,APPLYENDNOTEFORNJCAREPATHS
		,FLMEDICAREPERCENT2008
		,REQUIREENDNOTEDURINGOVERRIDE
		,STOREPERUNITFSANDUCR
		,USEPROVIDERNETWORKENROLLMENT
		,USEASCRULE
		,ASSTCOSURGEONELIGIBLE
		,LASTCHANGEDON
		,ISNJPHYSMEDCAPAFTERCTG
		,ISELIGIBLEAMTFEEBASED
		,HIDECLAIMTREETOTALSGRID
		,SORTBILLSBY
		,SORTBILLSBYORDER
		,APPLYNJEMERGENCYROOMBENCHMARKFEE
		,ALLOWICD10FORNJCAREPATHS
		,ENABLEOVERRIDEDEDUCTIBLE
		,ANALYZEDIAGNOSISPOINTERS
		,MEDICAREFEEPERCENT
		,ENABLESUPPLEMENTALNDCDATA
		,APPLYORIGINALNDCAWP
		,NDCAWPNOTAVAILABLE
		,PAYEAPGALLOWANCE
		,MEDICAREINPATIENTAPCENABLED
		,MEDICAREOUTPATIENTASCENABLED
		,MEDICAREASCENABLED
		,USEMEDICAREINPATIENTAPCFEE
		,MEDICAREINPATIENTDRGENABLED
		,MEDICAREINPATIENTDRGPRICINGTYPE
		,MEDICAREPHYSICIANENABLED
		,MEDICAREAMBULANCEENABLED
		,MEDICAREDMEPOSENABLED
		,MEDICAREASPDRUGANDCLINICALENABLED
		,MEDICAREINPATIENTPRICINGTYPE
		,MEDICAREOUTPATIENTPRICINGRULESENABLED
		,MEDICAREASCPRICINGRULESENABLED
		,NJUSEADMITTYPEENABLED
		,MEDICARECLINICALLABENABLED
		,MEDICAREINPATIENTENABLED
		,MEDICAREOUTPATIENTAPCENABLED
		,MEDICAREASPDRUGENABLED
		,SHOWALLOCATIONSONEOB
		,EMERGENCYCAREPRICINGRULEID
		,OUTOFSTATEPRICINGEFFECTIVEDATEID
		,PREALLOCATION
		,ASSISTANTCOSURGEONMODIFIERS
		,ASSISTANTSURGERYMODIFIERNOTMEDICALLYNECESSARY
		,ASSISTANTSURGERYMODIFIERREQUIREADDITIONALDOCUMENT
		,COSURGERYMODIFIERNOTMEDICALLYNECESSARY
		,COSURGERYMODIFIERREQUIREADDITIONALDOCUMENT
		,DXNODIAGNOSISDAYS
		,MODIFIEREXEMPTED
FROM src.prf_Profile
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProcedureCodeGroup
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROCEDURECODE
		,MAJORCATEGORY
		,MINORCATEGORY
FROM src.ProcedureCodeGroup
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProcedureServiceCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROCEDURESERVICECATEGORYID
		,PROCEDURESERVICECATEGORYNAME
		,PROCEDURESERVICECATEGORYDESCRIPTION
		,LEGACYTABLENAME
		,LEGACYBITVALUE
FROM src.ProcedureServiceCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PROVIDER
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,PVDMID
		,PVDSOURCE
		,PVDTIN
		,PVDLICNO
		,PVDCERTNO
		,PVDLASTNAME
		,PVDFIRSTNAME
		,PVDMI
		,PVDTITLE
		,PVDGROUP
		,PVDADDR1
		,PVDADDR2
		,PVDCITY
		,PVDSTATE
		,PVDZIP
		,PVDZIPPERF
		,PVDPHONE
		,PVDFAX
		,PVDSPC_LIST
		,PVDAUTHNO
		,PVDSPC_ACD
		,PVDUPDATECOUNTER
		,PVDPPO_PROVIDER
		,PVDFLAGS
		,PVDERRATE
		,PVDSUBNET
		,INUSE
		,PVDSTATUS
		,PVDELECTROSTARTDATE
		,PVDELECTROENDDATE
		,PVDACCREDSTARTDATE
		,PVDACCREDENDDATE
		,PVDREHABSTARTDATE
		,PVDREHABENDDATE
		,PVDTRAUMASTARTDATE
		,PVDTRAUMAENDDATE
		,OPCERT
		,PVDDENTALSTARTDATE
		,PVDDENTALENDDATE
		,PVDNPINO
		,PVDCMSID
		,CREATEDATE
		,LASTCHANGEDON
FROM src.PROVIDER
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderCluster
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,ORGODSCUSTOMERID
		,MITCHELLPROVIDERKEY
		,PROVIDERCLUSTERKEY
		,PROVIDERTYPE
FROM src.ProviderCluster
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderNetworkEventLog
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,IDFIELD
		,LOGDATE
		,EVENTID
		,CLAIMIDNO
		,BILLIDNO
		,USERID
		,NETWORKID
		,FILENAME
		,EXTRATEXT
		,PROCESSINFO
		,TIEREDTYPEID
		,TIERNUMBER
FROM src.ProviderNetworkEventLog
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderNumberCriteria
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERNUMBERCRITERIAID
		,PROVIDERNUMBER
		,PRIORITY
		,FEESCHEDULETABLE
		,STARTDATE
		,ENDDATE
FROM src.ProviderNumberCriteria
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderNumberCriteriaRevenueCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERNUMBERCRITERIAID
		,REVENUECODE
		,MATCHINGPROFILENUMBER
		,ATTRIBUTEMATCHTYPEID
FROM src.ProviderNumberCriteriaRevenueCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderNumberCriteriaTypeOfBill
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERNUMBERCRITERIAID
		,TYPEOFBILL
		,MATCHINGPROFILENUMBER
		,ATTRIBUTEMATCHTYPEID
FROM src.ProviderNumberCriteriaTypeOfBill
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderSpecialty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERID
		,SPECIALTYCODE
FROM src.ProviderSpecialty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderSpecialtyToProvType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERTYPE
		,PROVIDERTYPE_DESC
		,SPECIALTY
		,SPECIALTY_DESC
		,CREATEDATE
		,MODIFYDATE
		,LOGICALDELETE
FROM src.ProviderSpecialtyToProvType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Provider_ClientRef
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,CLIENTREFID
		,CLIENTREFID2
FROM src.Provider_ClientRef
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Provider_Rendering
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,RENDERINGADDR1
		,RENDERINGADDR2
		,RENDERINGCITY
		,RENDERINGSTATE
		,RENDERINGZIP
FROM src.Provider_Rendering
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ReferenceBillApcLines
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINE_NO
		,PAYMENTAPC
		,SERVICEINDICATOR
		,PAYMENTINDICATOR
		,OUTLIERAMOUNT
		,PRICERALLOWED
		,MEDICAREAMOUNT
FROM src.ReferenceBillApcLines
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ReferenceSupplementBillApcLines
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,SEQNO
		,LINE_NO
		,PAYMENTAPC
		,SERVICEINDICATOR
		,PAYMENTINDICATOR
		,OUTLIERAMOUNT
		,PRICERALLOWED
		,MEDICAREAMOUNT
FROM src.ReferenceSupplementBillApcLines
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.RENDERINGNPISTATES
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,APPLICATIONSETTINGSID
		,STATE
FROM src.RENDERINGNPISTATES
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';
CREATE OR REPLACE VIEW dbo.RevenueCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REVENUECODE
		,REVENUECODESUBCATEGORYID
FROM src.RevenueCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.RevenueCodeCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REVENUECODECATEGORYID
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.RevenueCodeCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.RevenueCodeSubCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REVENUECODESUBCATEGORYID
		,REVENUECODECATEGORYID
		,DESCRIPTION
		,NARRATIVEINFORMATION
FROM src.RevenueCodeSubCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.RPT_RsnCategories
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CATEGORYIDNO
		,CATDESC
		,PRIORITY
FROM src.RPT_RsnCategories
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Rsn_Override
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SHORTDESC
		,LONGDESC
		,CATEGORYIDNO
		,CLIENTSPEC
		,COAINDEX
		,NJPENALTYPCT
		,NETWORKID
		,SPECIALPROCESSING
FROM src.Rsn_Override
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.rsn_REASONS
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,CV_TYPE
		,SHORTDESC
		,LONGDESC
		,CATEGORYIDNO
		,COAINDEX
		,OVERRIDEENDNOTE
		,HARDEDIT
		,SPECIALPROCESSING
		,ENDNOTEACTIONID
		,RETAINFOREAPG
FROM src.rsn_REASONS
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Rsn_Reasons_3rdParty
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REASONNUMBER
		,SHORTDESC
		,LONGDESC
FROM src.Rsn_Reasons_3rdParty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.RuleType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULETYPEID
		,NAME
		,DESCRIPTION
FROM src.RuleType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ScriptAdvisorBillSource
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLSOURCEID
		,BILLSOURCE
FROM src.ScriptAdvisorBillSource
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ScriptAdvisorSettings
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SCRIPTADVISORSETTINGSID
		,ISPHARMACYELIGIBLE
		,ENABLESENDCARDTOCLAIMANT
		,ENABLEBILLSOURCE
FROM src.ScriptAdvisorSettings
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ScriptAdvisorSettingsCoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SCRIPTADVISORSETTINGSID
		,COVERAGETYPE
FROM src.ScriptAdvisorSettingsCoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SEC_RightGroups
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RIGHTGROUPID
		,RIGHTGROUPNAME
		,RIGHTGROUPDESCRIPTION
		,CREATEDDATE
		,CREATEDBY
FROM src.SEC_RightGroups
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SEC_Users
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,USERID
		,LOGINNAME
		,PASSWORD
		,CREATEDBY
		,CREATEDDATE
		,USERSTATUS
		,FIRSTNAME
		,LASTNAME
		,ACCOUNTLOCKED
		,LOCKEDCOUNTER
		,PASSWORDCREATEDATE
		,PASSWORDCASEFLAG
		,EPASSWORD
		,CURRENTSETTINGS
FROM src.SEC_Users
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SEC_User_OfficeGroups
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SECUSEROFFICEGROUPID
		,USERID
		,OFFCGROUPID
FROM src.SEC_User_OfficeGroups
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SEC_User_RightGroups
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SECUSERRIGHTGROUPID
		,USERID
		,RIGHTGROUPID
FROM src.SEC_User_RightGroups
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SentryRuleTypeCriteria
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULETYPEID
		,CRITERIAID
FROM src.SentryRuleTypeCriteria
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SENTRY_ACTION
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ACTIONID
		,NAME
		,DESCRIPTION
		,COMPATIBILITYKEY
		,PREDEFINEDVALUES
		,VALUEDATATYPE
		,VALUEFORMAT
		,BILLLINEACTION
		,ANALYZEFLAG
		,ACTIONCATEGORYIDNO
FROM src.SENTRY_ACTION
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SENTRY_ACTION_CATEGORY
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ACTIONCATEGORYIDNO
		,DESCRIPTION
FROM src.SENTRY_ACTION_CATEGORY
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SENTRY_CRITERIA
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CRITERIAID
		,PARENTNAME
		,NAME
		,DESCRIPTION
		,OPERATORS
		,PREDEFINEDVALUES
		,VALUEDATATYPE
		,VALUEFORMAT
		,NULLALLOWED
FROM src.SENTRY_CRITERIA
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SENTRY_PROFILE_RULE
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROFILEID
		,RULEID
		,PRIORITY
FROM src.SENTRY_PROFILE_RULE
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SENTRY_RULE
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULEID
		,NAME
		,DESCRIPTION
		,CREATEDBY
		,CREATIONDATE
		,POSTFIXNOTATION
		,PRIORITY
		,RULETYPEID
FROM src.SENTRY_RULE
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SENTRY_RULE_ACTION_DETAIL
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULEID
		,LINENUMBER
		,ACTIONID
		,ACTIONVALUE
FROM src.SENTRY_RULE_ACTION_DETAIL
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SENTRY_RULE_ACTION_HEADER
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULEID
		,ENDNOTESHORT
		,ENDNOTELONG
FROM src.SENTRY_RULE_ACTION_HEADER
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SENTRY_RULE_CONDITION
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RULEID
		,LINENUMBER
		,GROUPFLAG
		,CRITERIAID
		,OPERATOR
		,CONDITIONVALUE
		,ANDOR
		,UDFCONDITIONID
FROM src.SENTRY_RULE_CONDITION
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SPECIALTY
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SPCIDNO
		,CODE
		,DESCRIPTION
		,PAYEESUBTYPEID
		,TIEREDTYPEID
FROM src.SPECIALTY
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingMedicare
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGMEDICAREID
		,PAYPERCENTOFMEDICAREFEE
FROM src.StateSettingMedicare
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsFlorida
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSFLORIDAID
		,CLAIMANTINITIALSERVICEOPTION
		,CLAIMANTINITIALSERVICEDAYS
FROM src.StateSettingsFlorida
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsHawaii
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSHAWAIIID
		,PHYSICALMEDICINELIMITOPTION
FROM src.StateSettingsHawaii
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsNewJersey
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSNEWJERSEYID
		,BYPASSEMERGENCYSERVICES
FROM src.StateSettingsNewJersey
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsNewJerseyPolicyPreference
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,POLICYPREFERENCEID
		,SHARECOPAYMAXIMUM
FROM src.StateSettingsNewJerseyPolicyPreference
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsNewYorkPolicyPreference
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,POLICYPREFERENCEID
		,SHARECOPAYMAXIMUM
FROM src.StateSettingsNewYorkPolicyPreference
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsNY
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSNYID
		,NF10PRINTDATE
		,NF10CHECKBOX1
		,NF10CHECKBOX18
		,NF10USEUNDERWRITINGCOMPANY
		,UNDERWRITINGCOMPANYUDFID
		,NAICUDFID
		,DISPLAYNYPRINTOPTIONSWHENZOSORSOJISNY
		,NF10DUPLICATEPRINT
FROM src.StateSettingsNY
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsNyRoomRate
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSNYROOMRATEID
		,STARTDATE
		,ENDDATE
		,ROOMRATE
FROM src.StateSettingsNyRoomRate
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsOregon
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSOREGONID
		,APPLYOREGONFEESCHEDULE
FROM src.StateSettingsOregon
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.StateSettingsOregonCoverageType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STATESETTINGSOREGONID
		,COVERAGETYPE
FROM src.StateSettingsOregonCoverageType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SupplementBillApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,SEQUENCENUMBER
		,LINENUMBER
		,ENDNOTE
FROM src.SupplementBillApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SupplementBillCustomEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,SEQUENCENUMBER
		,LINENUMBER
		,ENDNOTE
FROM src.SupplementBillCustomEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SupplementBill_Pharm_ApportionmentEndnote
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLID
		,SEQUENCENUMBER
		,LINENUMBER
		,ENDNOTE
FROM src.SupplementBill_Pharm_ApportionmentEndnote
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.SUPPLEMENTPRECTGDENIEDLINESELIGIBLETOPENALTY
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,LINENUMBER
		,CTGPENALTYTYPEID
		,SEQNO
FROM src.SUPPLEMENTPRECTGDENIEDLINESELIGIBLETOPENALTY
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';
CREATE OR REPLACE VIEW dbo.SurgicalModifierException
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,MODIFIER
		,STATE
		,COVERAGETYPE
		,STARTDATE
		,ENDDATE
FROM src.SurgicalModifierException
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UB_APC_DICT
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,STARTDATE
		,ENDDATE
		,APC
		,DESCRIPTION
FROM src.UB_APC_DICT
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UB_BillType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TOB
		,DESCRIPTION
		,FLAG
		,UB_BILLTYPEID
FROM src.UB_BillType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UB_RevenueCodes
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REVENUECODE
		,STARTDATE
		,ENDDATE
		,PRC_DESC
		,FLAGS
		,VAGUE
		,PERVISIT
		,PERCLAIMANT
		,PERPROVIDER
		,BODYFLAGS
		,DRUGFLAG
		,CURATIVEFLAG
		,REVENUECODESUBCATEGORYID
FROM src.UB_RevenueCodes
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDFBill
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLIDNO
		,UDFIDNO
		,UDFVALUETEXT
		,UDFVALUEDECIMAL
		,UDFVALUEDATE
FROM src.UDFBill
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDFClaim
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMIDNO
		,UDFIDNO
		,UDFVALUETEXT
		,UDFVALUEDECIMAL
		,UDFVALUEDATE
FROM src.UDFClaim
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDFClaimant
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CMTIDNO
		,UDFIDNO
		,UDFVALUETEXT
		,UDFVALUEDECIMAL
		,UDFVALUEDATE
FROM src.UDFClaimant
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UdfDataFormat
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,UDFDATAFORMATID
		,DATAFORMATNAME
FROM src.UdfDataFormat
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDFLevelChangeTracking
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,UDFLEVELCHANGETRACKINGID
		,ENTITYTYPE
		,ENTITYID
		,CORRELATIONID
		,UDFID
		,PREVIOUSVALUE
		,UPDATEDVALUE
		,USERID
		,CHANGEDATE
FROM src.UDFLevelChangeTracking
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDFLibrary
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,UDFIDNO
		,UDFNAME
		,SCREENTYPE
		,UDFDESCRIPTION
		,DATAFORMAT
		,REQUIREDFIELD
		,READONLY
		,INVISIBLE
		,TEXTMAXLENGTH
		,TEXTMASK
		,TEXTENFORCELENGTH
		,RESTRICTRANGE
		,MINVALDECIMAL
		,MAXVALDECIMAL
		,MINVALDATE
		,MAXVALDATE
		,LISTALLOWMULTIPLE
		,DEFAULTVALUETEXT
		,DEFAULTVALUEDECIMAL
		,DEFAULTVALUEDATE
		,USEDEFAULT
		,REQONSUBMIT
		,INCLUDEDATEBUTTON
FROM src.UDFLibrary
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDFListValues
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,LISTVALUEIDNO
		,UDFIDNO
		,SEQNO
		,LISTVALUE
		,DEFAULTVALUE
FROM src.UDFListValues
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDFProvider
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PVDIDNO
		,UDFIDNO
		,UDFVALUETEXT
		,UDFVALUEDECIMAL
		,UDFVALUEDATE
FROM src.UDFProvider
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDFViewOrder
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,OFFICEID
		,UDFIDNO
		,VIEWORDER
FROM src.UDFViewOrder
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UDF_Sentry_Criteria
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,UDFIDNO
		,CRITERIAID
		,PARENTNAME
		,NAME
		,DESCRIPTION
		,OPERATORS
		,PREDEFINEDVALUES
		,VALUEDATATYPE
		,VALUEFORMAT
FROM src.UDF_Sentry_Criteria
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Vpn
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,VPNID
		,NETWORKNAME
		,PENDANDSEND
		,BYPASSMATCHING
		,ALLOWSRESENDS
		,ODSELIGIBLE
FROM src.Vpn
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.VPNActivityFlag
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ACTIVITY_FLAG
		,AF_DESCRIPTION
		,AF_SHORTDESC
		,DATA_SOURCE
		,DEFAULT_BILLABLE
		,CREDIT
FROM src.VPNActivityFlag
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.VpnBillableFlags
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SOJ
		,NETWORKID
		,ACTIVITYFLAG
		,BILLABLE
		,COMPANYCODE
		,COMPANYNAME
FROM src.VpnBillableFlags
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.VpnBillingCategory
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,VPNBILLINGCATEGORYCODE
		,VPNBILLINGCATEGORYDESCRIPTION
FROM src.VpnBillingCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.VpnLedger
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TRANSACTIONID
		,TRANSACTIONTYPEID
		,BILLIDNO
		,LINE_NO
		,CHARGED
		,DPALLOWED
		,VPNALLOWED
		,SAVINGS
		,CREDITS
		,HASOVERRIDE
		,ENDNOTES
		,NETWORKIDNO
		,PROCESSFLAG
		,LINETYPE
		,DATETIMESTAMP
		,SEQNO
		,VPN_REF_LINE_NO
		,SPECIALPROCESSING
		,CREATEDATE
		,LASTCHANGEDON
		,ADJUSTEDCHARGED
FROM src.VpnLedger
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.VpnProcessFlagType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,VPNPROCESSFLAGTYPEID
		,VPNPROCESSFLAGTYPE
FROM src.VpnProcessFlagType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.VpnSavingTransactionType
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,VPNSAVINGTRANSACTIONTYPEID
		,VPNSAVINGTRANSACTIONTYPE
FROM src.VpnSavingTransactionType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Vpn_Billing_History
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CUSTOMER
		,TRANSACTIONID
		,PERIOD
		,ACTIVITYFLAG
		,BILLABLEFLAG
		,VOID
		,CREDITTYPE
		,NETWORK
		,BILLIDNO
		,LINE_NO
		,TRANSACTIONDATE
		,REPRICEDATE
		,CLAIMNO
		,PROVIDERCHARGES
		,DPALLOWED
		,VPNALLOWED
		,SAVINGS
		,CREDITS
		,NETSAVINGS
		,SOJ
		,SEQNO
		,COMPANYCODE
		,VPNID
		,PROCESSFLAG
		,SK
		,DATABASE_NAME
		,SUBMITTEDTOFINANCE
		,ISINITIALLOAD
		,VPNBILLINGCATEGORYCODE
FROM src.Vpn_Billing_History
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.WeekEndsAndHolidays
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DAYOFWEEKDATE
		,DAYNAME
		,WEEKENDSANDHOLIDAYID
FROM src.WeekEndsAndHolidays
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Zip2County
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ZIP
		,COUNTY
		,STATE
FROM src.Zip2County
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ZipCode
AS
SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ZIPCODE
		,PRIMARYRECORD
		,STATE
		,CITY
		,CITYALIAS
		,COUNTY
		,CBSA
		,CBSATYPE
		,ZIPCODEREGIONID
FROM src.ZipCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


