CREATE OR REPLACE FUNCTION dbo.if_WFTaskLink(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,FROMTASKSEQ NUMBER(10,0)
		,LINKWHEN NUMBER(5,0)
		,TOTASKSEQ NUMBER(10,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.FROMTASKSEQ
		,T.LINKWHEN
		,T.TOTASKSEQ
FROM src.WFTaskLink T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		FROMTASKSEQ,
		LINKWHEN,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.WFTaskLink
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		FROMTASKSEQ,
		LINKWHEN) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.FROMTASKSEQ = S.FROMTASKSEQ
	AND T.LINKWHEN = S.LINKWHEN
WHERE T.DMLOPERATION <> 'D'

$$;


