CREATE OR REPLACE FUNCTION dbo.if_BillData(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,TYPECODE VARCHAR(6)
		,SUBTYPE VARCHAR(12)
		,SUBSEQ NUMBER(5,0)
		,NUMDATA NUMBER(18,6)
		,TEXTDATA VARCHAR(6000)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2)
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.TYPECODE
		,T.SUBTYPE
		,T.SUBSEQ
		,T.NUMDATA
		,T.TEXTDATA
		,T.MODDATE
		,T.MODUSERID
		,T.CREATEDATE
		,T.CREATEUSERID
FROM src.BillData T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		TYPECODE,
		SUBTYPE,
		SUBSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.BillData
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		TYPECODE,
		SUBTYPE,
		SUBSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.TYPECODE = S.TYPECODE
	AND T.SUBTYPE = S.SUBTYPE
	AND T.SUBSEQ = S.SUBSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


