CREATE OR REPLACE FUNCTION dbo.if_Bill(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,CLAIMSEQ NUMBER(10,0)
		,CLAIMSYSSUBSET VARCHAR(4)
		,PROVIDERSEQ NUMBER(19,0)
		,PROVIDERSUBSET VARCHAR(4)
		,POSTDATE DATETIME
		,DOSFIRST DATETIME
		,INVOICED VARCHAR(1)
		,INVOICEDPPO VARCHAR(1)
		,CREATEUSERID VARCHAR(2)
		,CARRIERSEQNEW VARCHAR(30)
		,DOCCTRLTYPE VARCHAR(2)
		,DOSLAST DATETIME
		,PPONETWORKID VARCHAR(2)
		,POS VARCHAR(2)
		,PROVTYPE VARCHAR(3)
		,PROVSPECIALTY1 VARCHAR(8)
		,PROVZIP VARCHAR(9)
		,PROVSTATE VARCHAR(2)
		,SUBMITDATE DATETIME
		,PROVINVOICE VARCHAR(14)
		,REGION NUMBER(5,0)
		,HOSPITALSEQ NUMBER(10,0)
		,MODUSERID VARCHAR(2)
		,STATUS NUMBER(5,0)
		,STATUSPRIOR NUMBER(5,0)
		,BILLABLELINES NUMBER(5,0)
		,TOTALCHARGE NUMBER(19,4)
		,BRREDUCTION NUMBER(19,4)
		,BRFEE NUMBER(19,4)
		,TOTALALLOW NUMBER(19,4)
		,TOTALFEE NUMBER(19,4)
		,DUPCLIENTCODE VARCHAR(4)
		,DUPBILLSEQ NUMBER(10,0)
		,FUPSTARTDATE DATETIME
		,FUPENDDATE DATETIME
		,SENDBACKMSG1SITECODE VARCHAR(3)
		,SENDBACKMSG1 VARCHAR(6)
		,SENDBACKMSG2SITECODE VARCHAR(3)
		,SENDBACKMSG2 VARCHAR(6)
		,PPOREDUCTION NUMBER(19,4)
		,PPOPRC NUMBER(5,0)
		,PPOCONTRACTID VARCHAR(30)
		,PPOSTATUS VARCHAR(1)
		,PPOFEE NUMBER(19,4)
		,NGDREDUCTION NUMBER(19,4)
		,NGDFEE NUMBER(19,4)
		,URFEE NUMBER(19,4)
		,OTHERDATA VARCHAR(30)
		,EXTERNALSTATUS VARCHAR(1)
		,URFLAG VARCHAR(1)
		,VISITS NUMBER(5,0)
		,TOS VARCHAR(2)
		,TOB VARCHAR(1)
		,SUBPRODUCTCODE VARCHAR(1)
		,FORCEPAY VARCHAR(1)
		,PMTAUTH VARCHAR(4)
		,FLOWSTATUS VARCHAR(1)
		,CONSULTDATE DATETIME
		,RCVDDATE DATETIME
		,ADMISSIONTYPE VARCHAR(1)
		,PAIDDATE DATETIME
		,ADMITDATE DATETIME
		,DISCHARGEDATE DATETIME
		,TXBILLTYPE VARCHAR(1)
		,RCVDBRDATE DATETIME
		,DUEDATE DATETIME
		,ADJUSTER VARCHAR(25)
		,DOI DATETIME
		,RETCTRLFLG VARCHAR(1)
		,RETCTRLNUM VARCHAR(9)
		,SITECODE VARCHAR(3)
		,SOURCEID VARCHAR(2)
		,CASETYPE VARCHAR(1)
		,SUBPRODUCTID VARCHAR(30)
		,SUBPRODUCTPRICE NUMBER(19,4)
		,URREDUCTION NUMBER(19,4)
		,PROVLICENSENUM VARCHAR(30)
		,PROVMEDICARENUM VARCHAR(20)
		,PROVSPECIALTY2 VARCHAR(8)
		,PMTEXPORTDATE DATETIME
		,PMTACCEPTDATE DATETIME
		,CLIENTTOB VARCHAR(5)
		,BRFEENET NUMBER(19,4)
		,PPOFEENET NUMBER(19,4)
		,NGDFEENET NUMBER(19,4)
		,URFEENET NUMBER(19,4)
		,SUBPRODUCTPRICENET NUMBER(19,4)
		,BILLSEQNEWREV NUMBER(10,0)
		,BILLSEQORGREV NUMBER(10,0)
		,VOCPLANSEQ NUMBER(5,0)
		,REVIEWDATE DATETIME
		,AUDITDATE DATETIME
		,REEVALALLOW NUMBER(19,4)
		,CHECKNUM VARCHAR(30)
		,NEGOTYPE VARCHAR(2)
		,DISCHARGEHOUR VARCHAR(2)
		,UB92TOB VARCHAR(3)
		,MCO VARCHAR(10)
		,DRG VARCHAR(3)
		,PATIENTACCOUNT VARCHAR(20)
		,EXAMINERREVFLAG VARCHAR(1)
		,REFPROVNAME VARCHAR(40)
		,PAIDAMOUNT NUMBER(19,4)
		,ADMISSIONSOURCE VARCHAR(1)
		,ADMITHOUR VARCHAR(2)
		,PATIENTSTATUS VARCHAR(2)
		,DRGVALUE NUMBER(19,4)
		,COMPANYSEQ NUMBER(5,0)
		,TOTALCOPAY NUMBER(19,4)
		,UB92PROCMETHOD VARCHAR(1)
		,TOTALDEDUCTIBLE NUMBER(19,4)
		,POLICYCOPAYAMOUNT NUMBER(19,4)
		,POLICYCOPAYPCT NUMBER(5,0)
		,DOCCTRLID VARCHAR(50)
		,RESOURCEUTILGROUP VARCHAR(4)
		,POLICYDEDUCTIBLE NUMBER(19,4)
		,POLICYLIMIT NUMBER(19,4)
		,POLICYTIMELIMIT NUMBER(5,0)
		,POLICYWARNINGPCT NUMBER(5,0)
		,APPBENEFITS VARCHAR(1)
		,APPASSIGNEE VARCHAR(1)
		,CREATEDATE DATETIME
		,MODDATE DATETIME
		,INCREMENTVALUE NUMBER(5,0)
		,ADJVERIFREQUESTDATE DATETIME
		,ADJVERIFRCVDDATE DATETIME
		,RENDERINGPROVLASTNAME VARCHAR(35)
		,RENDERINGPROVFIRSTNAME VARCHAR(25)
		,RENDERINGPROVMIDDLENAME VARCHAR(25)
		,RENDERINGPROVSUFFIX VARCHAR(10)
		,REREVIEWCOUNT NUMBER(5,0)
		,DRGBILLED VARCHAR(3)
		,DRGCALCULATED VARCHAR(3)
		,PROVRXLICENSENUM VARCHAR(30)
		,PROVSIGONFILE VARCHAR(1)
		,REFPROVFIRSTNAME VARCHAR(30)
		,REFPROVMIDDLENAME VARCHAR(25)
		,REFPROVSUFFIX VARCHAR(10)
		,REFPROVDEANUM VARCHAR(9)
		,SENDBACKMSG1SUBSET VARCHAR(2)
		,SENDBACKMSG2SUBSET VARCHAR(2)
		,PPONETWORKJURISDICTIONIND VARCHAR(1)
		,MANUALREDUCTIONMODE NUMBER(5,0)
		,WHOLESALESALESTAXZIP VARCHAR(9)
		,RETAILSALESTAXZIP VARCHAR(9)
		,PPONETWORKJURISDICTIONINSURERSEQ NUMBER(10,0)
		,INVOICEDWHOLESALE VARCHAR(1)
		,INVOICEDPPOWHOLESALE VARCHAR(1)
		,ADMITTINGDXREF NUMBER(5,0)
		,ADMITTINGDXCODE VARCHAR(8)
		,PROVFACILITYNPI VARCHAR(10)
		,PROVBILLINGNPI VARCHAR(10)
		,PROVRENDERINGNPI VARCHAR(10)
		,PROVOPERATINGNPI VARCHAR(10)
		,PROVREFERRINGNPI VARCHAR(10)
		,PROVOTHER1NPI VARCHAR(10)
		,PROVOTHER2NPI VARCHAR(10)
		,PROVOPERATINGLICENSENUM VARCHAR(30)
		,EHUBID VARCHAR(50)
		,OTHERBILLINGPROVIDERSUBSET VARCHAR(4)
		,OTHERBILLINGPROVIDERSEQ NUMBER(19,0)
		,RESUBMISSIONREASONCODE VARCHAR(2)
		,CONTRACTTYPE VARCHAR(2)
		,CONTRACTAMOUNT NUMBER(19,4)
		,PRIORAUTHREFERRALNUM1 VARCHAR(30)
		,PRIORAUTHREFERRALNUM2 VARCHAR(30)
		,DRGCOMPOSITEFACTOR NUMBER(19,4)
		,DRGDISCHARGEFRACTION NUMBER(19,4)
		,DRGINPATIENTMULTIPLIER NUMBER(19,4)
		,DRGWEIGHT NUMBER(19,4)
		,EFTPMTMETHODCODE VARCHAR(3)
		,EFTPMTFORMATCODE VARCHAR(10)
		,EFTSENDERDFIID VARCHAR(27)
		,EFTSENDERACCTNUM VARCHAR(50)
		,EFTORIGCOSUPPLCODE VARCHAR(24)
		,EFTRECEIVERDFIID VARCHAR(27)
		,EFTRECEIVERACCTQUAL VARCHAR(3)
		,EFTRECEIVERACCTNUM VARCHAR(50)
		,POLICYLIMITRESULT VARCHAR(1)
		,HISTORYBATCHNUMBER NUMBER(10,0)
		,PROVBILLINGTAXONOMY VARCHAR(11)
		,PROVFACILITYTAXONOMY VARCHAR(11)
		,PROVRENDERINGTAXONOMY VARCHAR(11)
		,PPOSTACKLIST VARCHAR(255)
		,ICDVERSION NUMBER(5,0)
		,ODGFLAG NUMBER(5,0)
		,PROVBILLLICENSENUM VARCHAR(30)
		,PROVFACILITYLICENSENUM VARCHAR(30)
		,PROVVENDOREXTERNALID VARCHAR(30)
		,BRACTUALCLIENTCODE VARCHAR(4)
		,BROVERRIDECLIENTCODE VARCHAR(4)
		,BILLREEVALREASONCODE VARCHAR(30)
		,PAYMENTCLEAREDDATE DATETIME
		,ESTIMATEDBRCLIENTCODE VARCHAR(4)
		,ESTIMATEDBRJURIS VARCHAR(2)
		,OVERRIDEFEECONTROLRETAIL VARCHAR(4)
		,OVERRIDEFEECONTROLWHOLESALE VARCHAR(4) 
		,STATEMENTFROMDATE DATETIME
		,STATEMENTTHROUGHDATE DATETIME)
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.CLAIMSEQ
		,T.CLAIMSYSSUBSET
		,T.PROVIDERSEQ
		,T.PROVIDERSUBSET
		,T.POSTDATE
		,T.DOSFIRST
		,T.INVOICED
		,T.INVOICEDPPO
		,T.CREATEUSERID
		,T.CARRIERSEQNEW
		,T.DOCCTRLTYPE
		,T.DOSLAST
		,T.PPONETWORKID
		,T.POS
		,T.PROVTYPE
		,T.PROVSPECIALTY1
		,T.PROVZIP
		,T.PROVSTATE
		,T.SUBMITDATE
		,T.PROVINVOICE
		,T.REGION
		,T.HOSPITALSEQ
		,T.MODUSERID
		,T.STATUS
		,T.STATUSPRIOR
		,T.BILLABLELINES
		,T.TOTALCHARGE
		,T.BRREDUCTION
		,T.BRFEE
		,T.TOTALALLOW
		,T.TOTALFEE
		,T.DUPCLIENTCODE
		,T.DUPBILLSEQ
		,T.FUPSTARTDATE
		,T.FUPENDDATE
		,T.SENDBACKMSG1SITECODE
		,T.SENDBACKMSG1
		,T.SENDBACKMSG2SITECODE
		,T.SENDBACKMSG2
		,T.PPOREDUCTION
		,T.PPOPRC
		,T.PPOCONTRACTID
		,T.PPOSTATUS
		,T.PPOFEE
		,T.NGDREDUCTION
		,T.NGDFEE
		,T.URFEE
		,T.OTHERDATA
		,T.EXTERNALSTATUS
		,T.URFLAG
		,T.VISITS
		,T.TOS
		,T.TOB
		,T.SUBPRODUCTCODE
		,T.FORCEPAY
		,T.PMTAUTH
		,T.FLOWSTATUS
		,T.CONSULTDATE
		,T.RCVDDATE
		,T.ADMISSIONTYPE
		,T.PAIDDATE
		,T.ADMITDATE
		,T.DISCHARGEDATE
		,T.TXBILLTYPE
		,T.RCVDBRDATE
		,T.DUEDATE
		,T.ADJUSTER
		,T.DOI
		,T.RETCTRLFLG
		,T.RETCTRLNUM
		,T.SITECODE
		,T.SOURCEID
		,T.CASETYPE
		,T.SUBPRODUCTID
		,T.SUBPRODUCTPRICE
		,T.URREDUCTION
		,T.PROVLICENSENUM
		,T.PROVMEDICARENUM
		,T.PROVSPECIALTY2
		,T.PMTEXPORTDATE
		,T.PMTACCEPTDATE
		,T.CLIENTTOB
		,T.BRFEENET
		,T.PPOFEENET
		,T.NGDFEENET
		,T.URFEENET
		,T.SUBPRODUCTPRICENET
		,T.BILLSEQNEWREV
		,T.BILLSEQORGREV
		,T.VOCPLANSEQ
		,T.REVIEWDATE
		,T.AUDITDATE
		,T.REEVALALLOW
		,T.CHECKNUM
		,T.NEGOTYPE
		,T.DISCHARGEHOUR
		,T.UB92TOB
		,T.MCO
		,T.DRG
		,T.PATIENTACCOUNT
		,T.EXAMINERREVFLAG
		,T.REFPROVNAME
		,T.PAIDAMOUNT
		,T.ADMISSIONSOURCE
		,T.ADMITHOUR
		,T.PATIENTSTATUS
		,T.DRGVALUE
		,T.COMPANYSEQ
		,T.TOTALCOPAY
		,T.UB92PROCMETHOD
		,T.TOTALDEDUCTIBLE
		,T.POLICYCOPAYAMOUNT
		,T.POLICYCOPAYPCT
		,T.DOCCTRLID
		,T.RESOURCEUTILGROUP
		,T.POLICYDEDUCTIBLE
		,T.POLICYLIMIT
		,T.POLICYTIMELIMIT
		,T.POLICYWARNINGPCT
		,T.APPBENEFITS
		,T.APPASSIGNEE
		,T.CREATEDATE
		,T.MODDATE
		,T.INCREMENTVALUE
		,T.ADJVERIFREQUESTDATE
		,T.ADJVERIFRCVDDATE
		,T.RENDERINGPROVLASTNAME
		,T.RENDERINGPROVFIRSTNAME
		,T.RENDERINGPROVMIDDLENAME
		,T.RENDERINGPROVSUFFIX
		,T.REREVIEWCOUNT
		,T.DRGBILLED
		,T.DRGCALCULATED
		,T.PROVRXLICENSENUM
		,T.PROVSIGONFILE
		,T.REFPROVFIRSTNAME
		,T.REFPROVMIDDLENAME
		,T.REFPROVSUFFIX
		,T.REFPROVDEANUM
		,T.SENDBACKMSG1SUBSET
		,T.SENDBACKMSG2SUBSET
		,T.PPONETWORKJURISDICTIONIND
		,T.MANUALREDUCTIONMODE
		,T.WHOLESALESALESTAXZIP
		,T.RETAILSALESTAXZIP
		,T.PPONETWORKJURISDICTIONINSURERSEQ
		,T.INVOICEDWHOLESALE
		,T.INVOICEDPPOWHOLESALE
		,T.ADMITTINGDXREF
		,T.ADMITTINGDXCODE
		,T.PROVFACILITYNPI
		,T.PROVBILLINGNPI
		,T.PROVRENDERINGNPI
		,T.PROVOPERATINGNPI
		,T.PROVREFERRINGNPI
		,T.PROVOTHER1NPI
		,T.PROVOTHER2NPI
		,T.PROVOPERATINGLICENSENUM
		,T.EHUBID
		,T.OTHERBILLINGPROVIDERSUBSET
		,T.OTHERBILLINGPROVIDERSEQ
		,T.RESUBMISSIONREASONCODE
		,T.CONTRACTTYPE
		,T.CONTRACTAMOUNT
		,T.PRIORAUTHREFERRALNUM1
		,T.PRIORAUTHREFERRALNUM2
		,T.DRGCOMPOSITEFACTOR
		,T.DRGDISCHARGEFRACTION
		,T.DRGINPATIENTMULTIPLIER
		,T.DRGWEIGHT
		,T.EFTPMTMETHODCODE
		,T.EFTPMTFORMATCODE
		,T.EFTSENDERDFIID
		,T.EFTSENDERACCTNUM
		,T.EFTORIGCOSUPPLCODE
		,T.EFTRECEIVERDFIID
		,T.EFTRECEIVERACCTQUAL
		,T.EFTRECEIVERACCTNUM
		,T.POLICYLIMITRESULT
		,T.HISTORYBATCHNUMBER
		,T.PROVBILLINGTAXONOMY
		,T.PROVFACILITYTAXONOMY
		,T.PROVRENDERINGTAXONOMY
		,T.PPOSTACKLIST
		,T.ICDVERSION
		,T.ODGFLAG
		,T.PROVBILLLICENSENUM
		,T.PROVFACILITYLICENSENUM
		,T.PROVVENDOREXTERNALID
		,T.BRACTUALCLIENTCODE
		,T.BROVERRIDECLIENTCODE
		,T.BILLREEVALREASONCODE
		,T.PAYMENTCLEAREDDATE
		,T.ESTIMATEDBRCLIENTCODE
		,T.ESTIMATEDBRJURIS
		,T.OVERRIDEFEECONTROLRETAIL
		,T.OVERRIDEFEECONTROLWHOLESALE
		,T.STATEMENTFROMDATE
		,T.STATEMENTTHROUGHDATE
FROM src.Bill T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Bill
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


