CREATE OR REPLACE FUNCTION dbo.if_PPONetwork(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,PPONETWORKID VARCHAR(2)
		,NAME VARCHAR(30)
		,TIN VARCHAR(10)
		,ZIP VARCHAR(10)
		,STATE VARCHAR(2)
		,CITY VARCHAR(15)
		,STREET VARCHAR(30)
		,PHONENUM VARCHAR(20)
		,PPONETWORKCOMMENT VARCHAR(6000)
		,ALLOWMAINT VARCHAR(1)
		,REQEXTPPO VARCHAR(1)
		,DEMORATES VARCHAR(1)
		,PRINTASPROVIDER VARCHAR(1)
		,PPOTYPE VARCHAR(3)
		,PPOVERSION VARCHAR(1)
		,PPOBRIDGEEXISTS VARCHAR(1)
		,USESDRG VARCHAR(1)
		,PPOTOOTHER VARCHAR(1)
		,SUBNETWORKINDICATOR VARCHAR(1)
		,EMAILADDRESS VARCHAR(255)
		,WEBSITE VARCHAR(255)
		,BILLCONTROLSEQ NUMBER(5,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.PPONETWORKID
		,T.NAME
		,T.TIN
		,T.ZIP
		,T.STATE
		,T.CITY
		,T.STREET
		,T.PHONENUM
		,T.PPONETWORKCOMMENT
		,T.ALLOWMAINT
		,T.REQEXTPPO
		,T.DEMORATES
		,T.PRINTASPROVIDER
		,T.PPOTYPE
		,T.PPOVERSION
		,T.PPOBRIDGEEXISTS
		,T.USESDRG
		,T.PPOTOOTHER
		,T.SUBNETWORKINDICATOR
		,T.EMAILADDRESS
		,T.WEBSITE
		,T.BILLCONTROLSEQ
FROM src.PPONetwork T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		PPONETWORKID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.PPONetwork
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		PPONETWORKID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.PPONETWORKID = S.PPONETWORKID
WHERE T.DMLOPERATION <> 'D'

$$;


