CREATE OR REPLACE FUNCTION dbo.if_BillControl(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,BILLCONTROLSEQ NUMBER(5,0)
		,MODDATE DATETIME
		,CREATEDATE DATETIME
		,CONTROL VARCHAR(1)
		,EXTERNALID VARCHAR(50)
		,BATCHNUMBER NUMBER(19,0)
		,MODUSERID VARCHAR(2)
		,EXTERNALID2 VARCHAR(50)
		,MESSAGE VARCHAR(500) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.BILLCONTROLSEQ
		,T.MODDATE
		,T.CREATEDATE
		,T.CONTROL
		,T.EXTERNALID
		,T.BATCHNUMBER
		,T.MODUSERID
		,T.EXTERNALID2
		,T.MESSAGE
FROM src.BillControl T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		BILLCONTROLSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.BillControl
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		BILLCONTROLSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.BILLCONTROLSEQ = S.BILLCONTROLSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


