CREATE OR REPLACE FUNCTION dbo.if_Drugs(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,DRUGCODE VARCHAR(4)
		,DRUGSDESCRIPTION VARCHAR(20)
		,DISP VARCHAR(20)
		,DRUGTYPE VARCHAR(1)
		,CAT VARCHAR(1)
		,UPDATEFLAG VARCHAR(1)
		,UV NUMBER(10,0)
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.DRUGCODE
		,T.DRUGSDESCRIPTION
		,T.DISP
		,T.DRUGTYPE
		,T.CAT
		,T.UPDATEFLAG
		,T.UV
		,T.CREATEDATE
		,T.CREATEUSERID
		,T.MODDATE
		,T.MODUSERID
FROM src.Drugs T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		DRUGCODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Drugs
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		DRUGCODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.DRUGCODE = S.DRUGCODE
WHERE T.DMLOPERATION <> 'D'

$$;


