CREATE OR REPLACE FUNCTION dbo.if_ProviderAddress(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,PROVIDERSUBSET VARCHAR(4)
		,PROVIDERADDRESSSEQ NUMBER(10,0)
		,RECTYPE VARCHAR(2)
		,ADDRESS1 VARCHAR(30)
		,ADDRESS2 VARCHAR(30)
		,CITY VARCHAR(30)
		,STATE VARCHAR(2)
		,ZIP VARCHAR(9)
		,PHONENUM VARCHAR(20)
		,FAXNUM VARCHAR(20)
		,CONTACTFIRSTNAME VARCHAR(20)
		,CONTACTLASTNAME VARCHAR(20)
		,CONTACTMIDDLEINITIAL VARCHAR(1)
		,URFIRSTNAME VARCHAR(20)
		,URLASTNAME VARCHAR(20)
		,URMIDDLEINITIAL VARCHAR(1)
		,FACILITYNAME VARCHAR(30)
		,COUNTRYCODE VARCHAR(3)
		,MAILCODE VARCHAR(20) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.PROVIDERSUBSET
		,T.PROVIDERADDRESSSEQ
		,T.RECTYPE
		,T.ADDRESS1
		,T.ADDRESS2
		,T.CITY
		,T.STATE
		,T.ZIP
		,T.PHONENUM
		,T.FAXNUM
		,T.CONTACTFIRSTNAME
		,T.CONTACTLASTNAME
		,T.CONTACTMIDDLEINITIAL
		,T.URFIRSTNAME
		,T.URLASTNAME
		,T.URMIDDLEINITIAL
		,T.FACILITYNAME
		,T.COUNTRYCODE
		,T.MAILCODE
FROM src.ProviderAddress T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		PROVIDERSUBSET,
		PROVIDERADDRESSSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ProviderAddress
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		PROVIDERSUBSET,
		PROVIDERADDRESSSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.PROVIDERSUBSET = S.PROVIDERSUBSET
	AND T.PROVIDERADDRESSSEQ = S.PROVIDERADDRESSSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


