CREATE OR REPLACE FUNCTION dbo.if_ReductionType(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,REDUCTIONCODE NUMBER(5,0)
		,REDUCTIONDESCRIPTION VARCHAR(50)
		,BEOVERRIDE VARCHAR(1)
		,BEMSG VARCHAR(1)
		,ABBREVIATION VARCHAR(8)
		,DEFAULTMESSAGECODE VARCHAR(6)
		,DEFAULTDENIALMESSAGECODE VARCHAR(6) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.REDUCTIONCODE
		,T.REDUCTIONDESCRIPTION
		,T.BEOVERRIDE
		,T.BEMSG
		,T.ABBREVIATION
		,T.DEFAULTMESSAGECODE
		,T.DEFAULTDENIALMESSAGECODE
FROM src.ReductionType T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		REDUCTIONCODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ReductionType
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		REDUCTIONCODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.REDUCTIONCODE = S.REDUCTIONCODE
WHERE T.DMLOPERATION <> 'D'

$$;


