CREATE OR REPLACE FUNCTION dbo.if_Pend(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,PENDSEQ NUMBER(5,0)
		,PENDDATE DATETIME
		,RELEASEFLAG VARCHAR(1)
		,PENDTOID VARCHAR(13)
		,PRIORITY VARCHAR(1)
		,RELEASEDATE DATETIME
		,REASONCODE VARCHAR(8)
		,PENDBYUSERID VARCHAR(2)
		,RELEASEBYUSERID VARCHAR(2)
		,AUTOPENDFLAG VARCHAR(1)
		,RULEID VARCHAR(5)
		,WFTASKSEQ NUMBER(10,0)
		,RELEASEDBYEXTERNALUSERNAME VARCHAR(128) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.PENDSEQ
		,T.PENDDATE
		,T.RELEASEFLAG
		,T.PENDTOID
		,T.PRIORITY
		,T.RELEASEDATE
		,T.REASONCODE
		,T.PENDBYUSERID
		,T.RELEASEBYUSERID
		,T.AUTOPENDFLAG
		,T.RULEID
		,T.WFTASKSEQ
		,T.RELEASEDBYEXTERNALUSERNAME
FROM src.Pend T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		PENDSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Pend
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		PENDSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.PENDSEQ = S.PENDSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


