CREATE OR REPLACE FUNCTION dbo.if_TableLookUp(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,TABLECODE VARCHAR(4)
		,TYPECODE VARCHAR(4)
		,CODE VARCHAR(12)
		,SITECODE VARCHAR(3)
		,OLDCODE VARCHAR(12)
		,SHORTDESC VARCHAR(40)
		,SOURCE VARCHAR(1)
		,PRIORITY NUMBER(5,0)
		,LONGDESC VARCHAR(6000)
		,OWNERAPP VARCHAR(1)
		,RECORDSTATUS VARCHAR(1)
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.TABLECODE
		,T.TYPECODE
		,T.CODE
		,T.SITECODE
		,T.OLDCODE
		,T.SHORTDESC
		,T.SOURCE
		,T.PRIORITY
		,T.LONGDESC
		,T.OWNERAPP
		,T.RECORDSTATUS
		,T.CREATEDATE
		,T.CREATEUSERID
		,T.MODDATE
		,T.MODUSERID
FROM src.TableLookUp T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		TABLECODE,
		TYPECODE,
		CODE,
		SITECODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.TableLookUp
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		TABLECODE,
		TYPECODE,
		CODE,
		SITECODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.TABLECODE = S.TABLECODE
	AND T.TYPECODE = S.TYPECODE
	AND T.CODE = S.CODE
	AND T.SITECODE = S.SITECODE
WHERE T.DMLOPERATION <> 'D'

$$;


