CREATE OR REPLACE FUNCTION dbo.if_ClaimInsurer(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,CLAIMSEQ NUMBER(10,0)
		,INSURERTYPE VARCHAR(1)
		,EFFECTIVEDATE DATETIME
		,INSURERSEQ NUMBER(10,0)
		,TERMINATIONDATE DATETIME
		,EXTERNALPOLICYNUMBER VARCHAR(30)
		,UNITSTATCLAIMID VARCHAR(35)
		,UNITSTATPOLICYID VARCHAR(30)
		,POLICYEFFECTIVEDATE DATETIME
		,SELFINSURED VARCHAR(1)
		,CLAIMADMINCLAIMNUM VARCHAR(35) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.CLAIMSEQ
		,T.INSURERTYPE
		,T.EFFECTIVEDATE
		,T.INSURERSEQ
		,T.TERMINATIONDATE
		,T.EXTERNALPOLICYNUMBER
		,T.UNITSTATCLAIMID
		,T.UNITSTATPOLICYID
		,T.POLICYEFFECTIVEDATE
		,T.SELFINSURED
		,T.CLAIMADMINCLAIMNUM
FROM src.ClaimInsurer T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		CLAIMSEQ,
		INSURERTYPE,
		EFFECTIVEDATE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ClaimInsurer
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		CLAIMSEQ,
		INSURERTYPE,
		EFFECTIVEDATE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.CLAIMSEQ = S.CLAIMSEQ
	AND T.INSURERTYPE = S.INSURERTYPE
	AND T.EFFECTIVEDATE = S.EFFECTIVEDATE
WHERE T.DMLOPERATION <> 'D'

$$;


