CREATE OR REPLACE FUNCTION dbo.if_Client(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,NAME VARCHAR(30)
		,JURISDICTION VARCHAR(2)
		,CONTROLNUM VARCHAR(20)
		,POLICYTIMELIMIT NUMBER(5,0)
		,POLICYLIMITWARNINGPCT NUMBER(5,0)
		,POLICYLIMIT NUMBER(19,4)
		,POLICYDEDUCTIBLE NUMBER(19,4)
		,POLICYCOPAYPCT NUMBER(5,0)
		,POLICYCOPAYAMOUNT NUMBER(19,4)
		,BEDIAGNOSIS VARCHAR(1)
		,INVOICEBRCYCLE VARCHAR(1)
		,STATUS VARCHAR(1)
		,INVOICEGROUPBY VARCHAR(1)
		,BEDOI VARCHAR(1)
		,DRUGMARKUPBRAND NUMBER(5,0)
		,SUPPLYLIMIT NUMBER(5,0)
		,INVOICEPPOCYCLE VARCHAR(1)
		,INVOICEPPOTAX NUMBER(5,0)
		,DRUGMARKUPGEN NUMBER(5,0)
		,DRUGDISPGEN NUMBER(5,0)
		,DRUGDISPBRAND NUMBER(5,0)
		,BEADJUSTER VARCHAR(1)
		,INVOICETAX NUMBER(5,0)
		,COMPANYSEQ NUMBER(5,0)
		,BEMEDALERT VARCHAR(1)
		,UCRPERCENTILE NUMBER(5,0)
		,CLIENTCOMMENT VARCHAR(6000)
		,REMITATTENTION VARCHAR(30)
		,REMITADDRESS1 VARCHAR(30)
		,REMITADDRESS2 VARCHAR(30)
		,REMITCITYSTATEZIP VARCHAR(30)
		,REMITPHONE VARCHAR(12)
		,EXTERNALID VARCHAR(10)
		,BEOTHER VARCHAR(1)
		,MEDALERTDAYS NUMBER(5,0)
		,MEDALERTVISITS NUMBER(5,0)
		,MEDALERTMAXCHARGE NUMBER(19,4)
		,MEDALERTWARNVISITS NUMBER(5,0)
		,PROVIDERSUBSET VARCHAR(4)
		,ALLOWREREVIEW VARCHAR(1)
		,ACCTREP VARCHAR(2)
		,CLIENTTYPE VARCHAR(1)
		,UCRMARKUP NUMBER(5,0)
		,INVOICECOMBINED VARCHAR(1)
		,BESUBMITDT VARCHAR(1)
		,BERCVDCARRIERDATE VARCHAR(1)
		,BERCVDBILLREVIEWDATE VARCHAR(1)
		,BEDUEDATE VARCHAR(1)
		,PRODUCTCODE VARCHAR(1)
		,BEPROVINVOICE VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,DEFAULTBRTOUCR VARCHAR(1)
		,BASEPPOFEESOFFFS VARCHAR(1)
		,BECLIENTTOBTABLECODE VARCHAR(2)
		,BEFORCEPAY VARCHAR(1)
		,BEPAYAUTHORIZATION VARCHAR(1)
		,BECARRIERSEQFLAG VARCHAR(1)
		,BEPROVTYPETABLECODE VARCHAR(2)
		,BEPROVSPCL1TABLECODE VARCHAR(2)
		,BEPROVLICENSE VARCHAR(1)
		,BEPAYAUTHTABLECODE VARCHAR(2)
		,PENDREASONTABLECODE VARCHAR(2)
		,VOCREHAB VARCHAR(1)
		,EDIACKREQUIRED VARCHAR(1)
		,STATERPTIND VARCHAR(1)
		,BEPATIENTACCTNUM VARCHAR(1)
		,AUTODUP VARCHAR(1)
		,USEALLOWONDUP VARCHAR(1)
		,URIMPORTUSED VARCHAR(1)
		,URPROGSTARTDATE VARCHAR(1)
		,URIMPORTCTRLNUM VARCHAR(4)
		,URIMPORTCTRLGROUP VARCHAR(4)
		,UCRSOURCE VARCHAR(1)
		,UCRMARKUP2 NUMBER(5,0)
		,NGDTABLECODE VARCHAR(2)
		,BESUBPRODUCTTABLECODE VARCHAR(2)
		,COUNTRYTABLECODE VARCHAR(2)
		,BEREFPHYS VARCHAR(1)
		,BEPMTWARNDAYS NUMBER(5,0)
		,GEOSTATE VARCHAR(2)
		,BEDISABLEDOICHECK VARCHAR(1)
		,DELAYDAYS NUMBER(5,0)
		,BEVALIDATETOTAL VARCHAR(1)
		,BEFASTMATCH VARCHAR(1)
		,BEPRIORBILLDEFAULT VARCHAR(1)
		,BECLIENTDUEDAYS NUMBER(5,0)
		,BEAUTOCALCDUEDATE VARCHAR(1)
		,UCRSOURCE2 VARCHAR(1)
		,UCRPERCENTILE2 NUMBER(5,0)
		,BEPROVSPCL2TABLECODE VARCHAR(2)
		,FEERATECNTRLEX VARCHAR(4)
		,FEERATECNTRLIN VARCHAR(4)
		,BECOLLISIONPROVBILLS VARCHAR(1)
		,BECOLLISIONBILLS VARCHAR(1)
		,SUPPLYMARKUP NUMBER(5,0)
		,BECOLLISIONPROVIDERS VARCHAR(1)
		,DEFAULTCOPAYDEDUCT VARCHAR(1)
		,AUTOBUNDLING VARCHAR(1)
		,BEVALIDATEBILLCLAIMICD9 VARCHAR(1)
		,ENABLEGENERICREPRICE VARCHAR(1)
		,BESUBPRODFEEINFO VARCHAR(1)
		,DENYNONINJDRUGS VARCHAR(1)
		,BECOLLISIONDOSLINES VARCHAR(1)
		,PPOPROFILESITECODE VARCHAR(3)
		,PPOPROFILEID NUMBER(10,0)
		,BESHOWDEAWARNING VARCHAR(1)
		,BEHIDEADJUSTERCOLUMN VARCHAR(1)
		,BEHIDECOPAYCOLUMN VARCHAR(1)
		,BEHIDEDEDUCTCOLUMN VARCHAR(1)
		,BEPAIDDATE VARCHAR(1)
		,BEPROCCROSSWALK VARCHAR(1)
		,CREATEUSERID VARCHAR(2)
		,CREATEDATE DATETIME
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,BECONSULTDATE VARCHAR(1)
		,BESHOWPHARMACYCOLUMNS VARCHAR(1)
		,BEADJVERIFDATES VARCHAR(1)
		,FUTUREDOSMONTHLIMIT NUMBER(5,0)
		,BESTOPATLINEUNITS VARCHAR(1)
		,BENYNF10FIELDS VARCHAR(1)
		,ENABLEDRGGROUPER VARCHAR(1)
		,APPLYCPTAMAUCRRULES VARCHAR(1)
		,BEPROVSIGONFILE VARCHAR(1)
		,BETIMEENTRY VARCHAR(1)
		,SALESTAXEXEMPT VARCHAR(1)
		,INVOICERETAILPROFILE VARCHAR(4)
		,INVOICEWHOLESALEPROFILE VARCHAR(4)
		,BEDEFAULTTAXZIP VARCHAR(1)
		,RECEIPTHANDLINGCODE VARCHAR(1)
		,PAYMENTHANDLINGCODE VARCHAR(1)
		,DEFAULTRETAILSALESTAXZIP VARCHAR(9)
		,DEFAULTWHOLESALESALESTAXZIP VARCHAR(9)
		,TXNONSUBSCRIB VARCHAR(1)
		,ROOTCLAIMLENGTH NUMBER(5,0)
		,BEDAWTABLECODE VARCHAR(4)
		,EORPROFILESEQ NUMBER(10,0)
		,BEOTHERBILLINGPROVIDER VARCHAR(1)
		,BEDOCCTRLID VARCHAR(1)
		,REPORTINGETL VARCHAR(1)
		,CLAIMVERIFICATION VARCHAR(1)
		,PROVVERIFICATION VARCHAR(1)
		,BEPERMITALLOWOVER VARCHAR(1)
		,BESTOPATLINEDXREF VARCHAR(1)
		,BEQUICKINFOCODE VARCHAR(12)
		,EXCLUDEDSMARTCLIENTSELECT VARCHAR(1)
		,COLLISIONSSEARCHBY VARCHAR(1)
		,AUTODUPINCLUDEPROV VARCHAR(1)
		,URPROFILEID VARCHAR(8)
		,EXCLUDEURDM VARCHAR(1)
		,BECOLLISIONURCASES VARCHAR(1)
		,MUEEDITS VARCHAR(1)
		,CPTRARITY NUMBER(5,2)
		,ICDRARITY NUMBER(5,2)
		,ICDTOCPTRARITY NUMBER(5,2)
		,BEDISABLEPPOSEARCH VARCHAR(1)
		,BESHOWLINEEXTERNALIDCOLUMN VARCHAR(1)
		,BESHOWLINEPRIORAUTHCOLUMN VARCHAR(1)
		,SMARTGUIDELINESFLAG VARCHAR(1)
		,BEPROVBILLINGLICENSE VARCHAR(1)
		,BEPROVFACILITYLICENSE VARCHAR(1)
		,VENDORPROVIDERSUBSET VARCHAR(4)
		,DEFAULTJURISCLIENTCODE VARCHAR(1)
		,CLIENTGROUPID NUMBER(10,0) 
		,DRUGDISPFEEAPPLYTO VARCHAR(1) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.NAME
		,T.JURISDICTION
		,T.CONTROLNUM
		,T.POLICYTIMELIMIT
		,T.POLICYLIMITWARNINGPCT
		,T.POLICYLIMIT
		,T.POLICYDEDUCTIBLE
		,T.POLICYCOPAYPCT
		,T.POLICYCOPAYAMOUNT
		,T.BEDIAGNOSIS
		,T.INVOICEBRCYCLE
		,T.STATUS
		,T.INVOICEGROUPBY
		,T.BEDOI
		,T.DRUGMARKUPBRAND
		,T.SUPPLYLIMIT
		,T.INVOICEPPOCYCLE
		,T.INVOICEPPOTAX
		,T.DRUGMARKUPGEN
		,T.DRUGDISPGEN
		,T.DRUGDISPBRAND
		,T.BEADJUSTER
		,T.INVOICETAX
		,T.COMPANYSEQ
		,T.BEMEDALERT
		,T.UCRPERCENTILE
		,T.CLIENTCOMMENT
		,T.REMITATTENTION
		,T.REMITADDRESS1
		,T.REMITADDRESS2
		,T.REMITCITYSTATEZIP
		,T.REMITPHONE
		,T.EXTERNALID
		,T.BEOTHER
		,T.MEDALERTDAYS
		,T.MEDALERTVISITS
		,T.MEDALERTMAXCHARGE
		,T.MEDALERTWARNVISITS
		,T.PROVIDERSUBSET
		,T.ALLOWREREVIEW
		,T.ACCTREP
		,T.CLIENTTYPE
		,T.UCRMARKUP
		,T.INVOICECOMBINED
		,T.BESUBMITDT
		,T.BERCVDCARRIERDATE
		,T.BERCVDBILLREVIEWDATE
		,T.BEDUEDATE
		,T.PRODUCTCODE
		,T.BEPROVINVOICE
		,T.CLAIMSYSSUBSET
		,T.DEFAULTBRTOUCR
		,T.BASEPPOFEESOFFFS
		,T.BECLIENTTOBTABLECODE
		,T.BEFORCEPAY
		,T.BEPAYAUTHORIZATION
		,T.BECARRIERSEQFLAG
		,T.BEPROVTYPETABLECODE
		,T.BEPROVSPCL1TABLECODE
		,T.BEPROVLICENSE
		,T.BEPAYAUTHTABLECODE
		,T.PENDREASONTABLECODE
		,T.VOCREHAB
		,T.EDIACKREQUIRED
		,T.STATERPTIND
		,T.BEPATIENTACCTNUM
		,T.AUTODUP
		,T.USEALLOWONDUP
		,T.URIMPORTUSED
		,T.URPROGSTARTDATE
		,T.URIMPORTCTRLNUM
		,T.URIMPORTCTRLGROUP
		,T.UCRSOURCE
		,T.UCRMARKUP2
		,T.NGDTABLECODE
		,T.BESUBPRODUCTTABLECODE
		,T.COUNTRYTABLECODE
		,T.BEREFPHYS
		,T.BEPMTWARNDAYS
		,T.GEOSTATE
		,T.BEDISABLEDOICHECK
		,T.DELAYDAYS
		,T.BEVALIDATETOTAL
		,T.BEFASTMATCH
		,T.BEPRIORBILLDEFAULT
		,T.BECLIENTDUEDAYS
		,T.BEAUTOCALCDUEDATE
		,T.UCRSOURCE2
		,T.UCRPERCENTILE2
		,T.BEPROVSPCL2TABLECODE
		,T.FEERATECNTRLEX
		,T.FEERATECNTRLIN
		,T.BECOLLISIONPROVBILLS
		,T.BECOLLISIONBILLS
		,T.SUPPLYMARKUP
		,T.BECOLLISIONPROVIDERS
		,T.DEFAULTCOPAYDEDUCT
		,T.AUTOBUNDLING
		,T.BEVALIDATEBILLCLAIMICD9
		,T.ENABLEGENERICREPRICE
		,T.BESUBPRODFEEINFO
		,T.DENYNONINJDRUGS
		,T.BECOLLISIONDOSLINES
		,T.PPOPROFILESITECODE
		,T.PPOPROFILEID
		,T.BESHOWDEAWARNING
		,T.BEHIDEADJUSTERCOLUMN
		,T.BEHIDECOPAYCOLUMN
		,T.BEHIDEDEDUCTCOLUMN
		,T.BEPAIDDATE
		,T.BEPROCCROSSWALK
		,T.CREATEUSERID
		,T.CREATEDATE
		,T.MODUSERID
		,T.MODDATE
		,T.BECONSULTDATE
		,T.BESHOWPHARMACYCOLUMNS
		,T.BEADJVERIFDATES
		,T.FUTUREDOSMONTHLIMIT
		,T.BESTOPATLINEUNITS
		,T.BENYNF10FIELDS
		,T.ENABLEDRGGROUPER
		,T.APPLYCPTAMAUCRRULES
		,T.BEPROVSIGONFILE
		,T.BETIMEENTRY
		,T.SALESTAXEXEMPT
		,T.INVOICERETAILPROFILE
		,T.INVOICEWHOLESALEPROFILE
		,T.BEDEFAULTTAXZIP
		,T.RECEIPTHANDLINGCODE
		,T.PAYMENTHANDLINGCODE
		,T.DEFAULTRETAILSALESTAXZIP
		,T.DEFAULTWHOLESALESALESTAXZIP
		,T.TXNONSUBSCRIB
		,T.ROOTCLAIMLENGTH
		,T.BEDAWTABLECODE
		,T.EORPROFILESEQ
		,T.BEOTHERBILLINGPROVIDER
		,T.BEDOCCTRLID
		,T.REPORTINGETL
		,T.CLAIMVERIFICATION
		,T.PROVVERIFICATION
		,T.BEPERMITALLOWOVER
		,T.BESTOPATLINEDXREF
		,T.BEQUICKINFOCODE
		,T.EXCLUDEDSMARTCLIENTSELECT
		,T.COLLISIONSSEARCHBY
		,T.AUTODUPINCLUDEPROV
		,T.URPROFILEID
		,T.EXCLUDEURDM
		,T.BECOLLISIONURCASES
		,T.MUEEDITS
		,T.CPTRARITY
		,T.ICDRARITY
		,T.ICDTOCPTRARITY
		,T.BEDISABLEPPOSEARCH
		,T.BESHOWLINEEXTERNALIDCOLUMN
		,T.BESHOWLINEPRIORAUTHCOLUMN
		,T.SMARTGUIDELINESFLAG
		,T.BEPROVBILLINGLICENSE
		,T.BEPROVFACILITYLICENSE
		,T.VENDORPROVIDERSUBSET
		,T.DEFAULTJURISCLIENTCODE
		,T.CLIENTGROUPID
		,T.DRUGDISPFEEAPPLYTO
FROM src.Client T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Client
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
WHERE T.DMLOPERATION <> 'D'

$$;


