CREATE OR REPLACE FUNCTION dbo.if_Modifier(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,JURISDICTION VARCHAR(2)
		,CODE VARCHAR(6)
		,SITECODE VARCHAR(3)
		,FUNC VARCHAR(1)
		,VAL VARCHAR(3)
		,MODTYPE VARCHAR(1)
		,GROUPCODE VARCHAR(2)
		,MODDESCRIPTION VARCHAR(30)
		,MODCOMMENT1 VARCHAR(70)
		,MODCOMMENT2 VARCHAR(70)
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2)
		,STATUTE VARCHAR(30)
		,REMARK1 VARCHAR(6)
		,REMARKQUALIFIER1 VARCHAR(2)
		,REMARK2 VARCHAR(6)
		,REMARKQUALIFIER2 VARCHAR(2)
		,REMARK3 VARCHAR(6)
		,REMARKQUALIFIER3 VARCHAR(2)
		,REMARK4 VARCHAR(6)
		,REMARKQUALIFIER4 VARCHAR(2)
		,CBREREASONID NUMBER(10,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.JURISDICTION
		,T.CODE
		,T.SITECODE
		,T.FUNC
		,T.VAL
		,T.MODTYPE
		,T.GROUPCODE
		,T.MODDESCRIPTION
		,T.MODCOMMENT1
		,T.MODCOMMENT2
		,T.CREATEDATE
		,T.CREATEUSERID
		,T.MODDATE
		,T.MODUSERID
		,T.STATUTE
		,T.REMARK1
		,T.REMARKQUALIFIER1
		,T.REMARK2
		,T.REMARKQUALIFIER2
		,T.REMARK3
		,T.REMARKQUALIFIER3
		,T.REMARK4
		,T.REMARKQUALIFIER4
		,T.CBREREASONID
FROM src.Modifier T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		JURISDICTION,
		CODE,
		SITECODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Modifier
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		JURISDICTION,
		CODE,
		SITECODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.JURISDICTION = S.JURISDICTION
	AND T.CODE = S.CODE
	AND T.SITECODE = S.SITECODE
WHERE T.DMLOPERATION <> 'D'

$$;


