CREATE OR REPLACE FUNCTION dbo.if_EDIControl(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,EDICONTROLSEQ NUMBER(10,0)
		,EDIMAPTOOLSITECODE VARCHAR(3)
		,EDIPORTTYPE VARCHAR(1)
		,EDIMAPTOOLID NUMBER(10,0)
		,NAME VARCHAR(50)
		,LASTTAPEDATE DATETIME
		,LASTSTARTDATE DATETIME
		,LASTENDDATE DATETIME
		,DAYCOUNTER NUMBER(5,0)
		,TOTALCOUNTER NUMBER(10,0)
		,VENDORNUM VARCHAR(20)
		,VENDORCONTACT VARCHAR(50)
		,VENDORPHONE VARCHAR(10)
		,ACCOUNTNUM VARCHAR(20)
		,OFFICENUM VARCHAR(20)
		,EDISENDERQUALIFIER VARCHAR(2)
		,EDISENDERIDENTIFIER VARCHAR(15)
		,EDIRECEIVERQUALIFIER VARCHAR(2)
		,EDIRECEIVERIDENTIFIER VARCHAR(15)
		,EDIACKNOWLEDGEMENT VARCHAR(1)
		,EDITESTINDICATOR VARCHAR(1)
		,EXPORTCREDITS VARCHAR(1)
		,EXPORTNEGATIVES VARCHAR(1)
		,CREATEEORS VARCHAR(1)
		,SPECIALPROCESSFLAG VARCHAR(120)
		,ARCOMPANY VARCHAR(20)
		,ARCONTACT VARCHAR(30)
		,ARADDR1 VARCHAR(30)
		,ARADDR2 VARCHAR(30)
		,ARCITY VARCHAR(30)
		,ARSTATE VARCHAR(2)
		,ARZIP VARCHAR(9)
		,ARPHONE VARCHAR(10)
		,EDISENDERZIP VARCHAR(9)
		,EDIRECEIVERZIP VARCHAR(9)
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2)
		,PENDUSERGROUP VARCHAR(12)
		,DAYBILLCOUNT NUMBER(10,0)
		,TOTALBILLCOUNT NUMBER(19,0)
		,EXPORTZEROALLOWBILLS VARCHAR(1)
		,CREATENF10S VARCHAR(1)
		,PRINTNF10IDENTIFIER VARCHAR(1)
		,NF10FILEFORMAT VARCHAR(3)
		,EORFILEFORMAT VARCHAR(3)
		,PRINTEORIDENTIFIER VARCHAR(1)
		,CREATEEORWITHNF10 VARCHAR(1)
		,EXCLUDEADJUSTER VARCHAR(1)
		,EXCLUDEATTORNEY VARCHAR(1)
		,EXCLUDEBRANCH VARCHAR(1)
		,EXCLUDECLAIM VARCHAR(1)
		,EXCLUDEINSURER VARCHAR(1)
		,EXCLUDEPOLICY VARCHAR(1)
		,DAYSPAST NUMBER(5,0)
		,EMAILNOTIFICATIONLIST VARCHAR(255)
		,WFVALIDATIONFLAG VARCHAR(1)
		,PRINTNF10PROVBILLINGADDR VARCHAR(1)
		,BATCHACKSLA NUMBER(10,0)
		,DETAILACKSLA NUMBER(10,0)
		,EXPORTOTHERBILLINGPROVIDER VARCHAR(1)
		,FORMATREVENUECODES VARCHAR(1)
		,CREATEC8S VARCHAR(1)
		,PRINTC8IDENTIFIER VARCHAR(1)
		,CREATEEORWITHC8 VARCHAR(1)
		,NYPROVIDERC81 VARCHAR(1)
		,NYPROVIDERC84 VARCHAR(1)
		,NYPROVIDERC8IDENTIFIER VARCHAR(1)
		,NYPROVIDERC8EOR VARCHAR(1)
		,NYBOARDC81 VARCHAR(1)
		,NYBOARDC84 VARCHAR(1)
		,NYBOARDC8IDENTIFIER VARCHAR(1)
		,NYBOARDC8EOR VARCHAR(1)
		,NYCLAIMANTC81 VARCHAR(1)
		,NYCLAIMANTC8IDENTIFIER VARCHAR(1)
		,NYCLAIMANTC8EOR VARCHAR(1)
		,NYCLAIMANTC8EORCOVER VARCHAR(1)
		,NYATTORNEYC81 VARCHAR(1)
		,NYATTORNEYC8IDENTIFIER VARCHAR(1)
		,NYATTORNEYC8EOR VARCHAR(1)
		,NYATTORNEYC8EORCOVER VARCHAR(1)
		,NYPROVIDERFORMAT VARCHAR(3)
		,NYBOARDFORMAT VARCHAR(3)
		,NYCLAIMANTFORMAT VARCHAR(3)
		,NYATTORNEYFORMAT VARCHAR(3)
		,EXPORTPPOBILLCOMMENT VARCHAR(1)
		,INCLUDENETWORK VARCHAR(1)
		,INCLUDECLAIMUDF VARCHAR(1)
		,INCLUDEPROVIDERUDF VARCHAR(1)
		,INCLUDEBILLUDF VARCHAR(1)
		,NETREEVALFEES VARCHAR(1)
		,EXPORTCARCS VARCHAR(1)
		,EXTENDEDHEADER VARCHAR(1)
		,EXTENDEDTRAILER VARCHAR(1)
		,SUBMISSIONREASONCODE VARCHAR(50)
		,INCLUDEBILLATTACHMENT VARCHAR(1)
		,USEEXTENDEDLAYOUT VARCHAR(120)
		,EXCLUDEBILLATTACHMENT VARCHAR(500)
		,EXPORTDIARYNOTES VARCHAR(1)
		,UPDATEZABILLCONTROLTOACCEPTED VARCHAR(1)
		,UPDATEZAPAIDDATETOPOSTDATE VARCHAR(1)
		,SETZAPAIDDATETOPOSTDATEDAYS NUMBER(10,0)
		,INCLUDEADJUSTERUDF VARCHAR(1)
		,INCLUDEPOLICYUDF VARCHAR(1)
		,EXPORTZEROALLOWREEVALS VARCHAR(1)
		,UPDATEREVALBILLCONTROLTOACCEPTED VARCHAR(1)
		,UPDATEREVALPAIDDATETOPOSTDATE VARCHAR(1)
		,SETREVALPAIDDATETOPOSTDATEDAYS NUMBER(10,0)
		,REDUCTIONSPEREORPROFILE VARCHAR(1)
		,INCLUDEBILLIMAGE VARCHAR(1)
		,NYCLAIMANTC84 VARCHAR(1)
		,NYATTORNEYC84 VARCHAR(1)
		,EDIJURISDICTION VARCHAR(20) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.EDICONTROLSEQ
		,T.EDIMAPTOOLSITECODE
		,T.EDIPORTTYPE
		,T.EDIMAPTOOLID
		,T.NAME
		,T.LASTTAPEDATE
		,T.LASTSTARTDATE
		,T.LASTENDDATE
		,T.DAYCOUNTER
		,T.TOTALCOUNTER
		,T.VENDORNUM
		,T.VENDORCONTACT
		,T.VENDORPHONE
		,T.ACCOUNTNUM
		,T.OFFICENUM
		,T.EDISENDERQUALIFIER
		,T.EDISENDERIDENTIFIER
		,T.EDIRECEIVERQUALIFIER
		,T.EDIRECEIVERIDENTIFIER
		,T.EDIACKNOWLEDGEMENT
		,T.EDITESTINDICATOR
		,T.EXPORTCREDITS
		,T.EXPORTNEGATIVES
		,T.CREATEEORS
		,T.SPECIALPROCESSFLAG
		,T.ARCOMPANY
		,T.ARCONTACT
		,T.ARADDR1
		,T.ARADDR2
		,T.ARCITY
		,T.ARSTATE
		,T.ARZIP
		,T.ARPHONE
		,T.EDISENDERZIP
		,T.EDIRECEIVERZIP
		,T.CREATEDATE
		,T.CREATEUSERID
		,T.MODDATE
		,T.MODUSERID
		,T.PENDUSERGROUP
		,T.DAYBILLCOUNT
		,T.TOTALBILLCOUNT
		,T.EXPORTZEROALLOWBILLS
		,T.CREATENF10S
		,T.PRINTNF10IDENTIFIER
		,T.NF10FILEFORMAT
		,T.EORFILEFORMAT
		,T.PRINTEORIDENTIFIER
		,T.CREATEEORWITHNF10
		,T.EXCLUDEADJUSTER
		,T.EXCLUDEATTORNEY
		,T.EXCLUDEBRANCH
		,T.EXCLUDECLAIM
		,T.EXCLUDEINSURER
		,T.EXCLUDEPOLICY
		,T.DAYSPAST
		,T.EMAILNOTIFICATIONLIST
		,T.WFVALIDATIONFLAG
		,T.PRINTNF10PROVBILLINGADDR
		,T.BATCHACKSLA
		,T.DETAILACKSLA
		,T.EXPORTOTHERBILLINGPROVIDER
		,T.FORMATREVENUECODES
		,T.CREATEC8S
		,T.PRINTC8IDENTIFIER
		,T.CREATEEORWITHC8
		,T.NYPROVIDERC81
		,T.NYPROVIDERC84
		,T.NYPROVIDERC8IDENTIFIER
		,T.NYPROVIDERC8EOR
		,T.NYBOARDC81
		,T.NYBOARDC84
		,T.NYBOARDC8IDENTIFIER
		,T.NYBOARDC8EOR
		,T.NYCLAIMANTC81
		,T.NYCLAIMANTC8IDENTIFIER
		,T.NYCLAIMANTC8EOR
		,T.NYCLAIMANTC8EORCOVER
		,T.NYATTORNEYC81
		,T.NYATTORNEYC8IDENTIFIER
		,T.NYATTORNEYC8EOR
		,T.NYATTORNEYC8EORCOVER
		,T.NYPROVIDERFORMAT
		,T.NYBOARDFORMAT
		,T.NYCLAIMANTFORMAT
		,T.NYATTORNEYFORMAT
		,T.EXPORTPPOBILLCOMMENT
		,T.INCLUDENETWORK
		,T.INCLUDECLAIMUDF
		,T.INCLUDEPROVIDERUDF
		,T.INCLUDEBILLUDF
		,T.NETREEVALFEES
		,T.EXPORTCARCS
		,T.EXTENDEDHEADER
		,T.EXTENDEDTRAILER
		,T.SUBMISSIONREASONCODE
		,T.INCLUDEBILLATTACHMENT
		,T.USEEXTENDEDLAYOUT
		,T.EXCLUDEBILLATTACHMENT
		,T.EXPORTDIARYNOTES
		,T.UPDATEZABILLCONTROLTOACCEPTED
		,T.UPDATEZAPAIDDATETOPOSTDATE
		,T.SETZAPAIDDATETOPOSTDATEDAYS
		,T.INCLUDEADJUSTERUDF
		,T.INCLUDEPOLICYUDF
		,T.EXPORTZEROALLOWREEVALS
		,T.UPDATEREVALBILLCONTROLTOACCEPTED
		,T.UPDATEREVALPAIDDATETOPOSTDATE
		,T.SETREVALPAIDDATETOPOSTDATEDAYS
		,T.REDUCTIONSPEREORPROFILE
		,T.INCLUDEBILLIMAGE
		,T.NYCLAIMANTC84
		,T.NYATTORNEYC84
		,T.EDIJURISDICTION 
FROM src.EDIControl T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		EDICONTROLSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.EDIControl
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		EDICONTROLSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.EDICONTROLSEQ = S.EDICONTROLSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


