CREATE OR REPLACE FUNCTION dbo.if_BillICDProcedure(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,BILLPROCEDURESEQ NUMBER(5,0)
		,ICDPROCEDUREID NUMBER(10,0)
		,CODEDATE DATETIME
		,BILLEDICDPROCEDURE VARCHAR(8)
		,ICDBILLUSAGETYPEID NUMBER(5,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.BILLPROCEDURESEQ
		,T.ICDPROCEDUREID
		,T.CODEDATE
		,T.BILLEDICDPROCEDURE
		,T.ICDBILLUSAGETYPEID
FROM src.BillICDProcedure T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		BILLPROCEDURESEQ,
		ICDBILLUSAGETYPEID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.BillICDProcedure
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		BILLPROCEDURESEQ,
		ICDBILLUSAGETYPEID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.BILLPROCEDURESEQ = S.BILLPROCEDURESEQ
	AND T.ICDBILLUSAGETYPEID = S.ICDBILLUSAGETYPEID
WHERE T.DMLOPERATION <> 'D'

$$;


