CREATE OR REPLACE FUNCTION dbo.if_MedicareICQM(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,JURISDICTION VARCHAR(2)
		,MDICQMSEQ NUMBER(10,0)
		,PROVIDERNUM VARCHAR(6)
		,PROVSUFFIX VARCHAR(1)
		,SERVICECODE VARCHAR(25)
		,HCPCS VARCHAR(5)
		,REVENUE VARCHAR(3)
		,MEDICAREICQMDESCRIPTION VARCHAR(40)
		,IP1995 NUMBER(10,0)
		,OP1995 NUMBER(10,0)
		,IP1996 NUMBER(10,0)
		,OP1996 NUMBER(10,0)
		,IP1997 NUMBER(10,0)
		,OP1997 NUMBER(10,0)
		,IP1998 NUMBER(10,0)
		,OP1998 NUMBER(10,0)
		,NPI VARCHAR(10) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.JURISDICTION
		,T.MDICQMSEQ
		,T.PROVIDERNUM
		,T.PROVSUFFIX
		,T.SERVICECODE
		,T.HCPCS
		,T.REVENUE
		,T.MEDICAREICQMDESCRIPTION
		,T.IP1995
		,T.OP1995
		,T.IP1996
		,T.OP1996
		,T.IP1997
		,T.OP1997
		,T.IP1998
		,T.OP1998
		,T.NPI
FROM src.MedicareICQM T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		JURISDICTION,
		MDICQMSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.MedicareICQM
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		JURISDICTION,
		MDICQMSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.JURISDICTION = S.JURISDICTION
	AND T.MDICQMSEQ = S.MDICQMSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


