CREATE OR REPLACE FUNCTION dbo.if_AttorneyAddress(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,ATTORNEYADDRESSSEQ NUMBER(10,0)
		,RECTYPE VARCHAR(2)
		,ADDRESS1 VARCHAR(30)
		,ADDRESS2 VARCHAR(30)
		,CITY VARCHAR(30)
		,STATE VARCHAR(2)
		,ZIP VARCHAR(9)
		,PHONENUM VARCHAR(20)
		,FAXNUM VARCHAR(20)
		,CONTACTFIRSTNAME VARCHAR(20)
		,CONTACTLASTNAME VARCHAR(20)
		,CONTACTMIDDLEINITIAL VARCHAR(1)
		,URFIRSTNAME VARCHAR(20)
		,URLASTNAME VARCHAR(20)
		,URMIDDLEINITIAL VARCHAR(1)
		,FACILITYNAME VARCHAR(30)
		,COUNTRYCODE VARCHAR(3)
		,MAILCODE VARCHAR(20) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.ATTORNEYADDRESSSEQ
		,T.RECTYPE
		,T.ADDRESS1
		,T.ADDRESS2
		,T.CITY
		,T.STATE
		,T.ZIP
		,T.PHONENUM
		,T.FAXNUM
		,T.CONTACTFIRSTNAME
		,T.CONTACTLASTNAME
		,T.CONTACTMIDDLEINITIAL
		,T.URFIRSTNAME
		,T.URLASTNAME
		,T.URMIDDLEINITIAL
		,T.FACILITYNAME
		,T.COUNTRYCODE
		,T.MAILCODE
FROM src.AttorneyAddress T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		ATTORNEYADDRESSSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.AttorneyAddress
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		ATTORNEYADDRESSSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.ATTORNEYADDRESSSEQ = S.ATTORNEYADDRESSSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


