CREATE OR REPLACE FUNCTION dbo.if_WFTaskRegistry(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,WFTASKREGISTRYSEQ NUMBER(10,0)
		,ENTITYTYPECODE VARCHAR(2)
		,DESCRIPTION VARCHAR(50)
		,ACTION VARCHAR(50)
		,SMALLIMAGERESID NUMBER(10,0)
		,LARGEIMAGERESID NUMBER(10,0)
		,PERSISTBEFORE VARCHAR(1)
		,NACTION VARCHAR(512) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.WFTASKREGISTRYSEQ
		,T.ENTITYTYPECODE
		,T.DESCRIPTION
		,T.ACTION
		,T.SMALLIMAGERESID
		,T.LARGEIMAGERESID
		,T.PERSISTBEFORE
		,T.NACTION
FROM src.WFTaskRegistry T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		WFTASKREGISTRYSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.WFTaskRegistry
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		WFTASKREGISTRYSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.WFTASKREGISTRYSEQ = S.WFTASKREGISTRYSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


