CREATE OR REPLACE FUNCTION dbo.if_BillRuleFire(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,LINESEQ NUMBER(5,0)
		,RULEID VARCHAR(5)
		,RULETYPE VARCHAR(1)
		,DATERULEFIRED DATETIME
		,VALIDATED VARCHAR(1)
		,VALIDATEDUSERID VARCHAR(2)
		,DATEVALIDATED DATETIME
		,PENDTOID VARCHAR(13)
		,RULESEVERITY VARCHAR(1)
		,WFTASKSEQ NUMBER(10,0)
		,CHILDTARGETSUBSET VARCHAR(4)
		,CHILDTARGETSEQ NUMBER(10,0)
		,CAPSTONERULEID NUMBER(10,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.LINESEQ
		,T.RULEID
		,T.RULETYPE
		,T.DATERULEFIRED
		,T.VALIDATED
		,T.VALIDATEDUSERID
		,T.DATEVALIDATED
		,T.PENDTOID
		,T.RULESEVERITY
		,T.WFTASKSEQ
		,T.CHILDTARGETSUBSET
		,T.CHILDTARGETSEQ
		,T.CAPSTONERULEID
FROM src.BillRuleFire T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		LINESEQ,
		RULEID,
		CHILDTARGETSUBSET,
		CHILDTARGETSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.BillRuleFire
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		LINESEQ,
		RULEID,
		CHILDTARGETSUBSET,
		CHILDTARGETSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.LINESEQ = S.LINESEQ
	AND T.RULEID = S.RULEID
	AND T.CHILDTARGETSUBSET = S.CHILDTARGETSUBSET
	AND T.CHILDTARGETSEQ = S.CHILDTARGETSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


