CREATE OR REPLACE FUNCTION dbo.if_ClientData(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,TYPECODE VARCHAR(6)
		,SUBTYPE VARCHAR(12)
		,SUBSEQ NUMBER(5,0)
		,NUMDATA NUMBER(18,6)
		,TEXTDATA VARCHAR(6000)
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.TYPECODE
		,T.SUBTYPE
		,T.SUBSEQ
		,T.NUMDATA
		,T.TEXTDATA
		,T.CREATEDATE
		,T.CREATEUSERID
		,T.MODDATE
		,T.MODUSERID
FROM src.ClientData T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		TYPECODE,
		SUBTYPE,
		SUBSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ClientData
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		TYPECODE,
		SUBTYPE,
		SUBSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.TYPECODE = S.TYPECODE
	AND T.SUBTYPE = S.SUBTYPE
	AND T.SUBSEQ = S.SUBSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


