CREATE OR REPLACE FUNCTION dbo.if_PPOContract(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,PPONETWORKID VARCHAR(2)
		,PPOCONTRACTID VARCHAR(30)
		,SITECODE VARCHAR(3)
		,TIN VARCHAR(9)
		,ALTERNATETIN VARCHAR(9)
		,STARTDATE DATETIME
		,ENDDATE DATETIME
		,OPLINEITEMDEFAULTDISCOUNT NUMBER(5,0)
		,COMPANYNAME VARCHAR(35)
		,FIRST VARCHAR(35)
		,GROUPCODE VARCHAR(3)
		,GROUPNAME VARCHAR(40)
		,OPDISCOUNTBASEVALUE VARCHAR(1)
		,OPOFFFS NUMBER(5,0)
		,OPOFFUCR NUMBER(5,0)
		,OPOFFCHARGE NUMBER(5,0)
		,OPEFFECTIVEDATE DATETIME
		,OPADDITIONALDISCOUNTOFFLINK NUMBER(5,0)
		,OPTERMINATIONDATE DATETIME
		,OPUCRPERCENTILE NUMBER(5,0)
		,OPCONDITION VARCHAR(2)
		,IPDISCOUNTBASEVALUE VARCHAR(1)
		,IPOFFFS NUMBER(5,0)
		,IPOFFUCR NUMBER(5,0)
		,IPOFFCHARGE NUMBER(5,0)
		,IPEFFECTIVEDATE DATETIME
		,IPTERMINATIONDATE DATETIME
		,IPCONDITION VARCHAR(2)
		,IPSTOPCAPAMOUNT NUMBER(19,4)
		,IPSTOPCAPRATE NUMBER(5,0)
		,MINDISC NUMBER(10,4)
		,MAXDISC NUMBER(10,4)
		,MEDICALPERDIEM NUMBER(10,4)
		,SURGICALPERDIEM NUMBER(10,4)
		,ICUPERDIEM NUMBER(10,4)
		,PSYCHIATRICPERDIEM NUMBER(10,4)
		,MISCPARM VARCHAR(2)
		,SPCCODE VARCHAR(1)
		,PPOTYPE VARCHAR(1)
		,BILLINGADDRESS1 VARCHAR(30)
		,BILLINGADDRESS2 VARCHAR(30)
		,BILLINGCITY VARCHAR(20)
		,BILLINGSTATE VARCHAR(2)
		,BILLINGZIP VARCHAR(9)
		,PRACTICEADDRESS1 VARCHAR(30)
		,PRACTICEADDRESS2 VARCHAR(30)
		,PRACTICECITY VARCHAR(20)
		,PRACTICESTATE VARCHAR(2)
		,PRACTICEZIP VARCHAR(9)
		,PHONENUM VARCHAR(10)
		,OUTFILE VARCHAR(12)
		,INPATFILE VARCHAR(12)
		,URCOORDINATORFLAG VARCHAR(1)
		,EXCLUSIVEPPOORGFLAG VARCHAR(1)
		,STOPLOSSTYPECODE VARCHAR(4)
		,BR_RNEDISCOUNT NUMBER(5,0)
		,MODDATE DATETIME
		,EXPORTFLAG VARCHAR(1)
		,OPMANUALINDICATOR VARCHAR(1)
		,OPSTOPCAPAMOUNT NUMBER(19,4)
		,OPSTOPCAPRATE NUMBER(5,0)
		,SPECIALTY1 VARCHAR(4)
		,SPECIALTY2 VARCHAR(4)
		,LESSOROFTHRESHOLD NUMBER(5,0)
		,BILATERALDISCOUNT NUMBER(5,0)
		,SURGERYDISCOUNT2 NUMBER(5,0)
		,SURGERYDISCOUNT3 NUMBER(5,0)
		,SURGERYDISCOUNT4 NUMBER(5,0)
		,SURGERYDISCOUNT5 NUMBER(5,0)
		,MATRIX VARCHAR(1)
		,PROVTYPE VARCHAR(5)
		,ALLINCLUSIVE VARCHAR(1)
		,REGION VARCHAR(4)
		,PAYMENTADDRESSFLAG VARCHAR(1)
		,MEDICALGROUP VARCHAR(1)
		,MEDICALGROUPCODE VARCHAR(4)
		,RATEMODE VARCHAR(1)
		,PRACTICECOUNTY VARCHAR(25)
		,FIPSCOUNTYCODE VARCHAR(3)
		,PRIMARYCAREFLAG VARCHAR(1)
		,PPOCONTRACTIDOLD VARCHAR(14)
		,MULTISURG VARCHAR(1)
		,BILEVEL VARCHAR(1)
		,DRGRATE NUMBER(10,4)
		,DRGGREATERTHANBC NUMBER(5,0)
		,DRGMINPERCENTBC NUMBER(5,0)
		,CARVEOUT VARCHAR(1)
		,PPOTOFSSEQ NUMBER(10,0)
		,LICENSENUM VARCHAR(30)
		,MEDICARENUM VARCHAR(20)
		,NPI VARCHAR(10) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.PPONETWORKID
		,T.PPOCONTRACTID
		,T.SITECODE
		,T.TIN
		,T.ALTERNATETIN
		,T.STARTDATE
		,T.ENDDATE
		,T.OPLINEITEMDEFAULTDISCOUNT
		,T.COMPANYNAME
		,T.FIRST
		,T.GROUPCODE
		,T.GROUPNAME
		,T.OPDISCOUNTBASEVALUE
		,T.OPOFFFS
		,T.OPOFFUCR
		,T.OPOFFCHARGE
		,T.OPEFFECTIVEDATE
		,T.OPADDITIONALDISCOUNTOFFLINK
		,T.OPTERMINATIONDATE
		,T.OPUCRPERCENTILE
		,T.OPCONDITION
		,T.IPDISCOUNTBASEVALUE
		,T.IPOFFFS
		,T.IPOFFUCR
		,T.IPOFFCHARGE
		,T.IPEFFECTIVEDATE
		,T.IPTERMINATIONDATE
		,T.IPCONDITION
		,T.IPSTOPCAPAMOUNT
		,T.IPSTOPCAPRATE
		,T.MINDISC
		,T.MAXDISC
		,T.MEDICALPERDIEM
		,T.SURGICALPERDIEM
		,T.ICUPERDIEM
		,T.PSYCHIATRICPERDIEM
		,T.MISCPARM
		,T.SPCCODE
		,T.PPOTYPE
		,T.BILLINGADDRESS1
		,T.BILLINGADDRESS2
		,T.BILLINGCITY
		,T.BILLINGSTATE
		,T.BILLINGZIP
		,T.PRACTICEADDRESS1
		,T.PRACTICEADDRESS2
		,T.PRACTICECITY
		,T.PRACTICESTATE
		,T.PRACTICEZIP
		,T.PHONENUM
		,T.OUTFILE
		,T.INPATFILE
		,T.URCOORDINATORFLAG
		,T.EXCLUSIVEPPOORGFLAG
		,T.STOPLOSSTYPECODE
		,T.BR_RNEDISCOUNT
		,T.MODDATE
		,T.EXPORTFLAG
		,T.OPMANUALINDICATOR
		,T.OPSTOPCAPAMOUNT
		,T.OPSTOPCAPRATE
		,T.SPECIALTY1
		,T.SPECIALTY2
		,T.LESSOROFTHRESHOLD
		,T.BILATERALDISCOUNT
		,T.SURGERYDISCOUNT2
		,T.SURGERYDISCOUNT3
		,T.SURGERYDISCOUNT4
		,T.SURGERYDISCOUNT5
		,T.MATRIX
		,T.PROVTYPE
		,T.ALLINCLUSIVE
		,T.REGION
		,T.PAYMENTADDRESSFLAG
		,T.MEDICALGROUP
		,T.MEDICALGROUPCODE
		,T.RATEMODE
		,T.PRACTICECOUNTY
		,T.FIPSCOUNTYCODE
		,T.PRIMARYCAREFLAG
		,T.PPOCONTRACTIDOLD
		,T.MULTISURG
		,T.BILEVEL
		,T.DRGRATE
		,T.DRGGREATERTHANBC
		,T.DRGMINPERCENTBC
		,T.CARVEOUT
		,T.PPOTOFSSEQ
		,T.LICENSENUM
		,T.MEDICARENUM
		,T.NPI
FROM src.PPOContract T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		PPONETWORKID,
		PPOCONTRACTID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.PPOContract
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		PPONETWORKID,
		PPOCONTRACTID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.PPONETWORKID = S.PPONETWORKID
	AND T.PPOCONTRACTID = S.PPOCONTRACTID
WHERE T.DMLOPERATION <> 'D'

$$;


