CREATE OR REPLACE FUNCTION dbo.if_FSProcedure(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,JURISDICTION VARCHAR(2)
		,EXTENSION VARCHAR(3)
		,PROCEDURECODE VARCHAR(6)
		,FSPROCDESCRIPTION VARCHAR(24)
		,SV VARCHAR(1)
		,STAR VARCHAR(1)
		,PANEL VARCHAR(1)
		,IP VARCHAR(1)
		,MULT VARCHAR(1)
		,ASSTSURGEON VARCHAR(1)
		,SECTIONFLAG VARCHAR(1)
		,FUP VARCHAR(3)
		,BAV NUMBER(5,0)
		,PROCGROUP VARCHAR(4)
		,VIEWTYPE NUMBER(5,0)
		,UNITVALUE1 NUMBER(19,4)
		,UNITVALUE2 NUMBER(19,4)
		,UNITVALUE3 NUMBER(19,4)
		,UNITVALUE4 NUMBER(19,4)
		,UNITVALUE5 NUMBER(19,4)
		,UNITVALUE6 NUMBER(19,4)
		,UNITVALUE7 NUMBER(19,4)
		,UNITVALUE8 NUMBER(19,4)
		,UNITVALUE9 NUMBER(19,4)
		,UNITVALUE10 NUMBER(19,4)
		,UNITVALUE11 NUMBER(19,4)
		,UNITVALUE12 NUMBER(19,4)
		,PROUNITVALUE1 NUMBER(19,4)
		,PROUNITVALUE2 NUMBER(19,4)
		,PROUNITVALUE3 NUMBER(19,4)
		,PROUNITVALUE4 NUMBER(19,4)
		,PROUNITVALUE5 NUMBER(19,4)
		,PROUNITVALUE6 NUMBER(19,4)
		,PROUNITVALUE7 NUMBER(19,4)
		,PROUNITVALUE8 NUMBER(19,4)
		,PROUNITVALUE9 NUMBER(19,4)
		,PROUNITVALUE10 NUMBER(19,4)
		,PROUNITVALUE11 NUMBER(19,4)
		,PROUNITVALUE12 NUMBER(19,4)
		,TECHUNITVALUE1 NUMBER(19,4)
		,TECHUNITVALUE2 NUMBER(19,4)
		,TECHUNITVALUE3 NUMBER(19,4)
		,TECHUNITVALUE4 NUMBER(19,4)
		,TECHUNITVALUE5 NUMBER(19,4)
		,TECHUNITVALUE6 NUMBER(19,4)
		,TECHUNITVALUE7 NUMBER(19,4)
		,TECHUNITVALUE8 NUMBER(19,4)
		,TECHUNITVALUE9 NUMBER(19,4)
		,TECHUNITVALUE10 NUMBER(19,4)
		,TECHUNITVALUE11 NUMBER(19,4)
		,TECHUNITVALUE12 NUMBER(19,4)
		,SITECODE VARCHAR(3) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.JURISDICTION
		,T.EXTENSION
		,T.PROCEDURECODE
		,T.FSPROCDESCRIPTION
		,T.SV
		,T.STAR
		,T.PANEL
		,T.IP
		,T.MULT
		,T.ASSTSURGEON
		,T.SECTIONFLAG
		,T.FUP
		,T.BAV
		,T.PROCGROUP
		,T.VIEWTYPE
		,T.UNITVALUE1
		,T.UNITVALUE2
		,T.UNITVALUE3
		,T.UNITVALUE4
		,T.UNITVALUE5
		,T.UNITVALUE6
		,T.UNITVALUE7
		,T.UNITVALUE8
		,T.UNITVALUE9
		,T.UNITVALUE10
		,T.UNITVALUE11
		,T.UNITVALUE12
		,T.PROUNITVALUE1
		,T.PROUNITVALUE2
		,T.PROUNITVALUE3
		,T.PROUNITVALUE4
		,T.PROUNITVALUE5
		,T.PROUNITVALUE6
		,T.PROUNITVALUE7
		,T.PROUNITVALUE8
		,T.PROUNITVALUE9
		,T.PROUNITVALUE10
		,T.PROUNITVALUE11
		,T.PROUNITVALUE12
		,T.TECHUNITVALUE1
		,T.TECHUNITVALUE2
		,T.TECHUNITVALUE3
		,T.TECHUNITVALUE4
		,T.TECHUNITVALUE5
		,T.TECHUNITVALUE6
		,T.TECHUNITVALUE7
		,T.TECHUNITVALUE8
		,T.TECHUNITVALUE9
		,T.TECHUNITVALUE10
		,T.TECHUNITVALUE11
		,T.TECHUNITVALUE12
		,T.SITECODE
FROM src.FSProcedure T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		JURISDICTION,
		EXTENSION,
		PROCEDURECODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.FSProcedure
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		JURISDICTION,
		EXTENSION,
		PROCEDURECODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.JURISDICTION = S.JURISDICTION
	AND T.EXTENSION = S.EXTENSION
	AND T.PROCEDURECODE = S.PROCEDURECODE
WHERE T.DMLOPERATION <> 'D'

$$;


