CREATE OR REPLACE FUNCTION dbo.if_ProviderCluster(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,PROVIDERSUBSET VARCHAR(4)
		,PROVIDERSEQ NUMBER(19,0)
		,ORGODSCUSTOMERID NUMBER(10,0)
		,MITCHELLPROVIDERKEY VARCHAR(200)
		,PROVIDERCLUSTERKEY VARCHAR(200)
		,PROVIDERTYPE VARCHAR(30) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.PROVIDERSUBSET
		,T.PROVIDERSEQ
		,T.ORGODSCUSTOMERID
		,T.MITCHELLPROVIDERKEY
		,T.PROVIDERCLUSTERKEY
		,T.PROVIDERTYPE
FROM src.ProviderCluster T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		PROVIDERSUBSET,
		PROVIDERSEQ,
		ORGODSCUSTOMERID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ProviderCluster
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		PROVIDERSUBSET,
		PROVIDERSEQ,
		ORGODSCUSTOMERID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.PROVIDERSUBSET = S.PROVIDERSUBSET
	AND T.PROVIDERSEQ = S.PROVIDERSEQ
	AND T.ORGODSCUSTOMERID = S.ORGODSCUSTOMERID
WHERE T.DMLOPERATION <> 'D'

$$;


