CREATE OR REPLACE FUNCTION dbo.if_ProviderSys(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,PROVIDERSUBSET VARCHAR(4)
		,PROVIDERSUBSETDESC VARCHAR(30)
		,PROVIDERACCESS VARCHAR(1)
		,TAXADDRREQUIRED VARCHAR(1)
		,ALLOWDUMMYPROVIDERS VARCHAR(1)
		,CASCADEUPDATESONIMPORT VARCHAR(1)
		,ROOTEXTIDOVERRIDEDELIMITER VARCHAR(1) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.PROVIDERSUBSET
		,T.PROVIDERSUBSETDESC
		,T.PROVIDERACCESS
		,T.TAXADDRREQUIRED
		,T.ALLOWDUMMYPROVIDERS
		,T.CASCADEUPDATESONIMPORT
		,T.ROOTEXTIDOVERRIDEDELIMITER
FROM src.ProviderSys T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		PROVIDERSUBSET,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ProviderSys
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		PROVIDERSUBSET) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.PROVIDERSUBSET = S.PROVIDERSUBSET
WHERE T.DMLOPERATION <> 'D'

$$;


