CREATE OR REPLACE FUNCTION dbo.if_ODGData(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,ICDDIAGNOSISID NUMBER(10,0)
		,PROCEDURECODE VARCHAR(30)
		,ICDDESCRIPTION VARCHAR(300)
		,PROCEDUREDESCRIPTION VARCHAR(800)
		,INCIDENCERATE NUMBER(19,4)
		,PROCEDUREFREQUENCY NUMBER(19,4)
		,VISITS25PERC NUMBER(5,0)
		,VISITS50PERC NUMBER(5,0)
		,VISITS75PERC NUMBER(5,0)
		,VISITSMEAN NUMBER(19,4)
		,COSTSMEAN NUMBER(19,4)
		,AUTOAPPROVALCODE VARCHAR(5)
		,PAYMENTFLAG NUMBER(5,0)
		,COSTPERVISIT NUMBER(19,4) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.ICDDIAGNOSISID
		,T.PROCEDURECODE
		,T.ICDDESCRIPTION
		,T.PROCEDUREDESCRIPTION
		,T.INCIDENCERATE
		,T.PROCEDUREFREQUENCY
		,T.VISITS25PERC
		,T.VISITS50PERC
		,T.VISITS75PERC
		,T.VISITSMEAN
		,T.COSTSMEAN
		,T.AUTOAPPROVALCODE
		,T.PAYMENTFLAG
		,T.COSTPERVISIT
FROM src.ODGData T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		ICDDIAGNOSISID,
		PROCEDURECODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ODGData
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		ICDDIAGNOSISID,
		PROCEDURECODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.ICDDIAGNOSISID = S.ICDDIAGNOSISID
	AND T.PROCEDURECODE = S.PROCEDURECODE
WHERE T.DMLOPERATION <> 'D'

$$;


