CREATE OR REPLACE FUNCTION dbo.if_Policy(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,POLICYSEQ NUMBER(10,0)
		,NAME VARCHAR(60)
		,EXTERNALID VARCHAR(20)
		,POLICYID VARCHAR(30)
		,ADMINKEY VARCHAR(40)
		,LOCATIONCODE VARCHAR(10)
		,ADDRESS1 VARCHAR(30)
		,ADDRESS2 VARCHAR(30)
		,CITY VARCHAR(20)
		,STATE VARCHAR(2)
		,ZIP VARCHAR(9)
		,PHONENUM VARCHAR(20)
		,FAXNUM VARCHAR(20)
		,EFFECTIVEDATE DATETIME
		,TERMINATIONDATE DATETIME
		,TIN VARCHAR(9)
		,STATETAXID VARCHAR(30)
		,DEPTINDUSRELNUM VARCHAR(20)
		,EQOPPINDICATOR VARCHAR(1)
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MCOFLAG VARCHAR(1)
		,MCOSTARTDATE DATETIME
		,FEERATECTRLEX VARCHAR(4)
		,CREATEBY VARCHAR(2)
		,FEERATECTRLIN VARCHAR(4)
		,CREATEDATE DATETIME
		,SELFINSURED VARCHAR(1)
		,NAICSCODE VARCHAR(15)
		,MONTHLYPREMIUM NUMBER(19,4)
		,PPOPROFILESITECODE VARCHAR(3)
		,PPOPROFILEID NUMBER(10,0)
		,SALESTAXEXEMPT VARCHAR(1)
		,RECEIPTHANDLINGCODE VARCHAR(1)
		,TXNONSUBSCRIB VARCHAR(1)
		,SUBDIVISIONNAME VARCHAR(60)
		,POLICYCOPAYAMOUNT NUMBER(19,4)
		,POLICYCOPAYPCT NUMBER(5,0)
		,POLICYDEDUCTIBLE NUMBER(19,4)
		,POLICYLIMITAMOUNT NUMBER(19,4)
		,POLICYTIMELIMIT NUMBER(5,0)
		,POLICYLIMITWARNINGPCT NUMBER(5,0)
		,POLICYLIMITRESULT VARCHAR(1)
		,URPROFILEID VARCHAR(8) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.POLICYSEQ
		,T.NAME
		,T.EXTERNALID
		,T.POLICYID
		,T.ADMINKEY
		,T.LOCATIONCODE
		,T.ADDRESS1
		,T.ADDRESS2
		,T.CITY
		,T.STATE
		,T.ZIP
		,T.PHONENUM
		,T.FAXNUM
		,T.EFFECTIVEDATE
		,T.TERMINATIONDATE
		,T.TIN
		,T.STATETAXID
		,T.DEPTINDUSRELNUM
		,T.EQOPPINDICATOR
		,T.MODUSERID
		,T.MODDATE
		,T.MCOFLAG
		,T.MCOSTARTDATE
		,T.FEERATECTRLEX
		,T.CREATEBY
		,T.FEERATECTRLIN
		,T.CREATEDATE
		,T.SELFINSURED
		,T.NAICSCODE
		,T.MONTHLYPREMIUM
		,T.PPOPROFILESITECODE
		,T.PPOPROFILEID
		,T.SALESTAXEXEMPT
		,T.RECEIPTHANDLINGCODE
		,T.TXNONSUBSCRIB
		,T.SUBDIVISIONNAME
		,T.POLICYCOPAYAMOUNT
		,T.POLICYCOPAYPCT
		,T.POLICYDEDUCTIBLE
		,T.POLICYLIMITAMOUNT
		,T.POLICYTIMELIMIT
		,T.POLICYLIMITWARNINGPCT
		,T.POLICYLIMITRESULT
		,T.URPROFILEID
FROM src.Policy T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		POLICYSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Policy
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		POLICYSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.POLICYSEQ = S.POLICYSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


