CREATE OR REPLACE FUNCTION dbo.if_EDIXmitBill(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,EDIXMITBILLSEQ NUMBER(10,0)
		,EDIXMITSEQ NUMBER(10,0)
		,EDIHISTORYPROVIDERSEQ NUMBER(10,0)
		,EDIHISTORYCLAIMSEQ NUMBER(10,0)
		,EDIHISTORYINSURERSEQ NUMBER(10,0)
		,EDICONTROLSEQ NUMBER(10,0)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,JURISDICTION VARCHAR(2)
		,TOB VARCHAR(1)
		,UB92TOB VARCHAR(10)
		,BILLSEQORGREV NUMBER(10,0)
		,TOTALCHARGE NUMBER(19,4)
		,BILLABLELINES NUMBER(10,0)
		,PAIDDATE DATETIME
		,PAIDAMOUNT NUMBER(19,4)
		,DRG VARCHAR(3)
		,PATIENTSTATUS VARCHAR(2)
		,POSTDATE DATETIME
		,DOCCTRLID VARCHAR(50)
		,DOSFIRST DATETIME
		,DOSLAST DATETIME
		,PPONETWORKID VARCHAR(2)
		,PPOCONTRACTID VARCHAR(30)
		,ADJUSTER VARCHAR(25)
		,CARRIERSEQNEW VARCHAR(30)
		,PROVINVOICE VARCHAR(14)
		,PROVSPECIALTY1 VARCHAR(10)
		,CLIENTTOB VARCHAR(5)
		,SUBPRODUCTCODE VARCHAR(1)
		,DUPCLIENTCODE VARCHAR(4)
		,DUPBILLSEQ NUMBER(10,0)
		,CONSULTDATE DATETIME
		,ADMITDATE DATETIME
		,DISCHARGEDATE DATETIME
		,SUBMITDATE DATETIME
		,RCVDDATE DATETIME
		,RCVDBRDATE DATETIME
		,REVIEWDATE DATETIME
		,DUEDATE DATETIME
		,PMTAUTH VARCHAR(4)
		,FORCEPAY VARCHAR(1)
		,PROVLICENSENUM VARCHAR(30)
		,CREATEUSERID VARCHAR(2)
		,MODUSERID VARCHAR(2)
		,PATIENTACCOUNT VARCHAR(20)
		,REFPROVNAME VARCHAR(40)
		,PROVTYPE VARCHAR(3)
		,DOI DATETIME
		,GEOSTATE VARCHAR(2)
		,MANUALREDUCTIONMODE NUMBER(5,0)
		,PPONETWORKJURISDICTIONIND VARCHAR(1)
		,PPONETWORKJURISDICTIONINSURERSEQ NUMBER(10,0)
		,WFQUEUEPARAMETER1 VARCHAR(35)
		,CHECKNUM VARCHAR(30)
		,EXTERNALID VARCHAR(50)
		,EDITESTINDICATOR VARCHAR(1)
		,ICDVERSION NUMBER(5,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.EDIXMITBILLSEQ
		,T.EDIXMITSEQ
		,T.EDIHISTORYPROVIDERSEQ
		,T.EDIHISTORYCLAIMSEQ
		,T.EDIHISTORYINSURERSEQ
		,T.EDICONTROLSEQ
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.JURISDICTION
		,T.TOB
		,T.UB92TOB
		,T.BILLSEQORGREV
		,T.TOTALCHARGE
		,T.BILLABLELINES
		,T.PAIDDATE
		,T.PAIDAMOUNT
		,T.DRG
		,T.PATIENTSTATUS
		,T.POSTDATE
		,T.DOCCTRLID
		,T.DOSFIRST
		,T.DOSLAST
		,T.PPONETWORKID
		,T.PPOCONTRACTID
		,T.ADJUSTER
		,T.CARRIERSEQNEW
		,T.PROVINVOICE
		,T.PROVSPECIALTY1
		,T.CLIENTTOB
		,T.SUBPRODUCTCODE
		,T.DUPCLIENTCODE
		,T.DUPBILLSEQ
		,T.CONSULTDATE
		,T.ADMITDATE
		,T.DISCHARGEDATE
		,T.SUBMITDATE
		,T.RCVDDATE
		,T.RCVDBRDATE
		,T.REVIEWDATE
		,T.DUEDATE
		,T.PMTAUTH
		,T.FORCEPAY
		,T.PROVLICENSENUM
		,T.CREATEUSERID
		,T.MODUSERID
		,T.PATIENTACCOUNT
		,T.REFPROVNAME
		,T.PROVTYPE
		,T.DOI
		,T.GEOSTATE
		,T.MANUALREDUCTIONMODE
		,T.PPONETWORKJURISDICTIONIND
		,T.PPONETWORKJURISDICTIONINSURERSEQ
		,T.WFQUEUEPARAMETER1
		,T.CHECKNUM
		,T.EXTERNALID
		,T.EDITESTINDICATOR
		,T.ICDVERSION
FROM src.EDIXmitBill T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		EDIXMITBILLSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.EDIXmitBill
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		EDIXMITBILLSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.EDIXMITBILLSEQ = S.EDIXMITBILLSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


