CREATE OR REPLACE FUNCTION dbo.if_Attorney(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,ATTORNEYSEQ NUMBER(19,0)
		,TIN VARCHAR(9)
		,TINSUFFIX VARCHAR(6)
		,EXTERNALID VARCHAR(30)
		,NAME VARCHAR(50)
		,GROUPCODE VARCHAR(5)
		,LICENSENUM VARCHAR(30)
		,MEDICARENUM VARCHAR(20)
		,PRACTICEADDRESSSEQ NUMBER(10,0)
		,BILLINGADDRESSSEQ NUMBER(10,0)
		,ATTORNEYTYPE VARCHAR(3)
		,SPECIALTY1 VARCHAR(8)
		,SPECIALTY2 VARCHAR(8)
		,CREATEUSERID VARCHAR(2)
		,CREATEDATE DATETIME
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,STATUS VARCHAR(1)
		,EXTERNALSTATUS VARCHAR(1)
		,EXPORTDATE DATETIME
		,SSNTININDICATOR VARCHAR(1)
		,PMTDAYS NUMBER(5,0)
		,AUTHBEGINDATE DATETIME
		,AUTHENDDATE DATETIME
		,TAXADDRESSSEQ NUMBER(10,0)
		,CTRLNUM1099 VARCHAR(4)
		,SURCHARGECODE VARCHAR(1)
		,WORKCOMPNUM VARCHAR(18)
		,WORKCOMPSTATE VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.ATTORNEYSEQ
		,T.TIN
		,T.TINSUFFIX
		,T.EXTERNALID
		,T.NAME
		,T.GROUPCODE
		,T.LICENSENUM
		,T.MEDICARENUM
		,T.PRACTICEADDRESSSEQ
		,T.BILLINGADDRESSSEQ
		,T.ATTORNEYTYPE
		,T.SPECIALTY1
		,T.SPECIALTY2
		,T.CREATEUSERID
		,T.CREATEDATE
		,T.MODUSERID
		,T.MODDATE
		,T.STATUS
		,T.EXTERNALSTATUS
		,T.EXPORTDATE
		,T.SSNTININDICATOR
		,T.PMTDAYS
		,T.AUTHBEGINDATE
		,T.AUTHENDDATE
		,T.TAXADDRESSSEQ
		,T.CTRLNUM1099
		,T.SURCHARGECODE
		,T.WORKCOMPNUM
		,T.WORKCOMPSTATE
FROM src.Attorney T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		ATTORNEYSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Attorney
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		ATTORNEYSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.ATTORNEYSEQ = S.ATTORNEYSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


