CREATE OR REPLACE FUNCTION dbo.if_ProfileRegion(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,SITECODE VARCHAR(3)
		,PROFILEREGIONID NUMBER(10,0)
		,REGIONTYPECODE VARCHAR(2)
		,REGIONNAME VARCHAR(50) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.SITECODE
		,T.PROFILEREGIONID
		,T.REGIONTYPECODE
		,T.REGIONNAME
FROM src.ProfileRegion T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		SITECODE,
		PROFILEREGIONID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ProfileRegion
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		SITECODE,
		PROFILEREGIONID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.SITECODE = S.SITECODE
	AND T.PROFILEREGIONID = S.PROFILEREGIONID
WHERE T.DMLOPERATION <> 'D'

$$;


