CREATE OR REPLACE FUNCTION dbo.if_Adjuster(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,ADJUSTER VARCHAR(25)
		,FIRSTNAME VARCHAR(20)
		,LASTNAME VARCHAR(20)
		,MINITIAL VARCHAR(1)
		,TITLE VARCHAR(20)
		,ADDRESS1 VARCHAR(30)
		,ADDRESS2 VARCHAR(30)
		,CITY VARCHAR(20)
		,STATE VARCHAR(2)
		,ZIP VARCHAR(9)
		,PHONENUM VARCHAR(20)
		,PHONENUMEXT VARCHAR(10)
		,FAXNUM VARCHAR(20)
		,EMAIL VARCHAR(128)
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.ADJUSTER
		,T.FIRSTNAME
		,T.LASTNAME
		,T.MINITIAL
		,T.TITLE
		,T.ADDRESS1
		,T.ADDRESS2
		,T.CITY
		,T.STATE
		,T.ZIP
		,T.PHONENUM
		,T.PHONENUMEXT
		,T.FAXNUM
		,T.EMAIL
		,T.CREATEDATE
		,T.CREATEUSERID
		,T.MODDATE
		,T.MODUSERID
FROM src.Adjuster T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		ADJUSTER,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Adjuster
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		ADJUSTER) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.ADJUSTER = S.ADJUSTER
WHERE T.DMLOPERATION <> 'D'

$$;


