CREATE OR REPLACE FUNCTION dbo.if_ClientInsurer(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,INSURERTYPE VARCHAR(1)
		,EFFECTIVEDATE DATETIME
		,INSURERSEQ NUMBER(10,0)
		,TERMINATIONDATE DATETIME )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.INSURERTYPE
		,T.EFFECTIVEDATE
		,T.INSURERSEQ
		,T.TERMINATIONDATE
FROM src.ClientInsurer T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		INSURERTYPE,
		EFFECTIVEDATE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ClientInsurer
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		INSURERTYPE,
		EFFECTIVEDATE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.INSURERTYPE = S.INSURERTYPE
	AND T.EFFECTIVEDATE = S.EFFECTIVEDATE
WHERE T.DMLOPERATION <> 'D'

$$;


