CREATE OR REPLACE FUNCTION dbo.if_Branch(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,BRANCHSEQ NUMBER(10,0)
		,NAME VARCHAR(60)
		,EXTERNALID VARCHAR(20)
		,BRANCHID VARCHAR(20)
		,LOCATIONCODE VARCHAR(10)
		,ADMINKEY VARCHAR(40)
		,ADDRESS1 VARCHAR(30)
		,ADDRESS2 VARCHAR(30)
		,CITY VARCHAR(20)
		,STATE VARCHAR(2)
		,ZIP VARCHAR(9)
		,PHONENUM VARCHAR(20)
		,FAXNUM VARCHAR(20)
		,CONTACTNAME VARCHAR(30)
		,TIN VARCHAR(9)
		,STATETAXID VARCHAR(30)
		,DIRNUM VARCHAR(20)
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,RULEFIRE VARCHAR(4)
		,FEERATECNTRLEX VARCHAR(4)
		,FEERATECNTRLIN VARCHAR(4)
		,SALESTAXEXEMPT VARCHAR(1)
		,EFFECTIVEDATE DATETIME
		,TERMINATIONDATE DATETIME )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.BRANCHSEQ
		,T.NAME
		,T.EXTERNALID
		,T.BRANCHID
		,T.LOCATIONCODE
		,T.ADMINKEY
		,T.ADDRESS1
		,T.ADDRESS2
		,T.CITY
		,T.STATE
		,T.ZIP
		,T.PHONENUM
		,T.FAXNUM
		,T.CONTACTNAME
		,T.TIN
		,T.STATETAXID
		,T.DIRNUM
		,T.MODUSERID
		,T.MODDATE
		,T.RULEFIRE
		,T.FEERATECNTRLEX
		,T.FEERATECNTRLIN
		,T.SALESTAXEXEMPT
		,T.EFFECTIVEDATE
		,T.TERMINATIONDATE
FROM src.Branch T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		BRANCHSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Branch
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		BRANCHSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.BRANCHSEQ = S.BRANCHSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


