CREATE OR REPLACE FUNCTION dbo.if_PendComment(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,PENDSEQ NUMBER(5,0)
		,PENDCOMMENTSEQ NUMBER(5,0)
		,PENDCOMMENT VARCHAR(7500)
		,CREATEUSERID VARCHAR(2)
		,CREATEDATE DATETIME
		,CREATEDBYEXTERNALUSERNAME VARCHAR(128) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.PENDSEQ
		,T.PENDCOMMENTSEQ
		,T.PENDCOMMENT
		,T.CREATEUSERID
		,T.CREATEDATE
		,T.CREATEDBYEXTERNALUSERNAME
FROM src.PendComment T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		PENDSEQ,
		PENDCOMMENTSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.PendComment
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		PENDSEQ,
		PENDCOMMENTSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.PENDSEQ = S.PENDSEQ
	AND T.PENDCOMMENTSEQ = S.PENDCOMMENTSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


