CREATE OR REPLACE FUNCTION dbo.if_BillICDDiagnosis(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,BILLDIAGNOSISSEQ NUMBER(5,0)
		,ICDDIAGNOSISID NUMBER(10,0)
		,POA VARCHAR(1)
		,BILLEDICDDIAGNOSIS VARCHAR(8)
		,ICDBILLUSAGETYPEID NUMBER(5,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.BILLDIAGNOSISSEQ
		,T.ICDDIAGNOSISID
		,T.POA
		,T.BILLEDICDDIAGNOSIS
		,T.ICDBILLUSAGETYPEID
FROM src.BillICDDiagnosis T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		BILLDIAGNOSISSEQ,
		ICDBILLUSAGETYPEID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.BillICDDiagnosis
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		BILLDIAGNOSISSEQ,
		ICDBILLUSAGETYPEID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.BILLDIAGNOSISSEQ = S.BILLDIAGNOSISSEQ
	AND T.ICDBILLUSAGETYPEID = S.ICDBILLUSAGETYPEID
WHERE T.DMLOPERATION <> 'D'

$$;


