CREATE OR REPLACE FUNCTION dbo.if_Line(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,LINESEQ NUMBER(5,0)
		,DUPCLIENTCODE VARCHAR(4)
		,DUPBILLSEQ NUMBER(10,0)
		,DOS DATETIME
		,PROCTYPE VARCHAR(1)
		,PPOOVERRIDE NUMBER(19,4)
		,CLIENTLINETYPE VARCHAR(5)
		,PROVTYPE VARCHAR(3)
		,URQTYALLOW NUMBER(5,0)
		,URQTYSVD NUMBER(5,0)
		,DOSTO DATETIME
		,URALLOW NUMBER(19,4)
		,URCASESEQ NUMBER(10,0)
		,REVENUECODE VARCHAR(4)
		,PROCBILLED VARCHAR(30)
		,URREVIEWSEQ NUMBER(5,0)
		,URPRIORITY NUMBER(5,0)
		,PROCCODE VARCHAR(30)
		,UNITS NUMBER(11,3)
		,ALLOWUNITS NUMBER(11,3)
		,CHARGE NUMBER(19,4)
		,BRALLOW NUMBER(19,4)
		,PPOALLOW NUMBER(19,4)
		,PAYOVERRIDE NUMBER(19,4)
		,PROCNEW VARCHAR(30)
		,ADJALLOW NUMBER(19,4)
		,REEVALAMOUNT NUMBER(19,4)
		,POS VARCHAR(2)
		,DXREFLIST VARCHAR(30)
		,TOS VARCHAR(2)
		,REEVALTXTPTR NUMBER(5,0)
		,FSAMOUNT NUMBER(19,4)
		,UCAMOUNT NUMBER(19,4)
		,COPAY NUMBER(19,4)
		,DEDUCTIBLE NUMBER(19,4)
		,COSTTOCHARGERATIO FLOAT(53)
		,RXNUMBER VARCHAR(20)
		,DAYSSUPPLY NUMBER(5,0)
		,DXREF VARCHAR(4)
		,EXTERNALID VARCHAR(30)
		,ITEMCOSTINVOICED NUMBER(19,4)
		,ITEMCOSTADDITIONAL NUMBER(19,4)
		,REFILL VARCHAR(1)
		,PROVSECONDARYID VARCHAR(30)
		,CERTIFICATION VARCHAR(1)
		,REEVALTXTSRC VARCHAR(3)
		,BASISOFCOST VARCHAR(1)
		,DMEFREQUENCYCODE VARCHAR(1)
		,PROVRENDERINGNPI VARCHAR(10)
		,PROVSECONDARYIDQUALIFIER VARCHAR(2)
		,PAIDPROCCODE VARCHAR(30)
		,PAIDPROCTYPE VARCHAR(3)
		,URSTATUS VARCHAR(1)
		,URWORKFLOWSTATUS VARCHAR(1)
		,OVERRIDEALLOWUNITS NUMBER(11,3)
		,LINESEQORGREV NUMBER(5,0)
		,ODGFLAG NUMBER(5,0)
		,COMPOUNDDRUGINDICATOR VARCHAR(1)
		,PRIORAUTHNUM VARCHAR(50)
		,REEVALPARAGRAPHJURISDICTION VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.LINESEQ
		,T.DUPCLIENTCODE
		,T.DUPBILLSEQ
		,T.DOS
		,T.PROCTYPE
		,T.PPOOVERRIDE
		,T.CLIENTLINETYPE
		,T.PROVTYPE
		,T.URQTYALLOW
		,T.URQTYSVD
		,T.DOSTO
		,T.URALLOW
		,T.URCASESEQ
		,T.REVENUECODE
		,T.PROCBILLED
		,T.URREVIEWSEQ
		,T.URPRIORITY
		,T.PROCCODE
		,T.UNITS
		,T.ALLOWUNITS
		,T.CHARGE
		,T.BRALLOW
		,T.PPOALLOW
		,T.PAYOVERRIDE
		,T.PROCNEW
		,T.ADJALLOW
		,T.REEVALAMOUNT
		,T.POS
		,T.DXREFLIST
		,T.TOS
		,T.REEVALTXTPTR
		,T.FSAMOUNT
		,T.UCAMOUNT
		,T.COPAY
		,T.DEDUCTIBLE
		,T.COSTTOCHARGERATIO
		,T.RXNUMBER
		,T.DAYSSUPPLY
		,T.DXREF
		,T.EXTERNALID
		,T.ITEMCOSTINVOICED
		,T.ITEMCOSTADDITIONAL
		,T.REFILL
		,T.PROVSECONDARYID
		,T.CERTIFICATION
		,T.REEVALTXTSRC
		,T.BASISOFCOST
		,T.DMEFREQUENCYCODE
		,T.PROVRENDERINGNPI
		,T.PROVSECONDARYIDQUALIFIER
		,T.PAIDPROCCODE
		,T.PAIDPROCTYPE
		,T.URSTATUS
		,T.URWORKFLOWSTATUS
		,T.OVERRIDEALLOWUNITS
		,T.LINESEQORGREV
		,T.ODGFLAG
		,T.COMPOUNDDRUGINDICATOR
		,T.PRIORAUTHNUM
		,T.REEVALPARAGRAPHJURISDICTION
FROM src.Line T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		LINESEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Line
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		LINESEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.LINESEQ = S.LINESEQ
WHERE T.DMLOPERATION <> 'D'

$$;


