CREATE OR REPLACE FUNCTION dbo.if_PPORateType(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,RATETYPECODE VARCHAR(8)
		,PPONETWORKID VARCHAR(2)
		,CATEGORY VARCHAR(1)
		,PRIORITY VARCHAR(1)
		,VBCOLOR NUMBER(5,0)
		,RATETYPEDESCRIPTION VARCHAR(70)
		,EXPLANATION VARCHAR(6000) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.RATETYPECODE
		,T.PPONETWORKID
		,T.CATEGORY
		,T.PRIORITY
		,T.VBCOLOR
		,T.RATETYPEDESCRIPTION
		,T.EXPLANATION
FROM src.PPORateType T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		RATETYPECODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.PPORateType
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		RATETYPECODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.RATETYPECODE = S.RATETYPECODE
WHERE T.DMLOPERATION <> 'D'

$$;


