CREATE OR REPLACE FUNCTION dbo.if_ClaimSysData(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,TYPECODE VARCHAR(6)
		,SUBTYPE VARCHAR(12)
		,SUBSEQ NUMBER(5,0)
		,NUMDATA NUMBER(18,6)
		,TEXTDATA VARCHAR(6000) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.TYPECODE
		,T.SUBTYPE
		,T.SUBSEQ
		,T.NUMDATA
		,T.TEXTDATA
FROM src.ClaimSysData T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		TYPECODE,
		SUBTYPE,
		SUBSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ClaimSysData
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		TYPECODE,
		SUBTYPE,
		SUBSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.TYPECODE = S.TYPECODE
	AND T.SUBTYPE = S.SUBTYPE
	AND T.SUBSEQ = S.SUBSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


