CREATE OR REPLACE FUNCTION dbo.if_Claim(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,CLAIMSEQ NUMBER(10,0)
		,CLAIMID VARCHAR(35)
		,DOI DATETIME
		,PATIENTSSN VARCHAR(9)
		,PATIENTFIRSTNAME VARCHAR(10)
		,PATIENTLASTNAME VARCHAR(20)
		,PATIENTMINITIAL VARCHAR(1)
		,EXTERNALCLAIMID VARCHAR(35)
		,POLICYCOPAYAMOUNT NUMBER(19,4)
		,POLICYCOPAYPCT NUMBER(5,0)
		,POLICYDEDUCTIBLE NUMBER(19,4)
		,STATUS VARCHAR(1)
		,POLICYLIMIT NUMBER(19,4)
		,POLICYID VARCHAR(30)
		,POLICYTIMELIMIT NUMBER(5,0)
		,ADJUSTER VARCHAR(25)
		,POLICYLIMITWARNINGPCT NUMBER(5,0)
		,FIRSTDOS DATETIME
		,LASTDOS DATETIME
		,LOADDATE DATETIME
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2)
		,PATIENTSEX VARCHAR(1)
		,PATIENTCITY VARCHAR(20)
		,PATIENTDOB DATETIME
		,PATIENTSTREET2 VARCHAR(30)
		,PATIENTSTATE VARCHAR(2)
		,PATIENTZIP VARCHAR(9)
		,PATIENTSTREET1 VARCHAR(30)
		,MMIDATE DATETIME
		,BODYPART1 VARCHAR(3)
		,BODYPART2 VARCHAR(3)
		,BODYPART3 VARCHAR(3)
		,BODYPART4 VARCHAR(3)
		,BODYPART5 VARCHAR(3)
		,LOCATION VARCHAR(10)
		,NATUREINJ VARCHAR(3)
		,URFLAG VARCHAR(1)
		,CARKNOWDATE DATETIME
		,CLAIMTYPE VARCHAR(2)
		,CTRLDAY NUMBER(5,0)
		,MCOCHOICE VARCHAR(2)
		,CLIENTCODEDEFAULT VARCHAR(4)
		,CLOSEDATE DATETIME
		,REOPENDATE DATETIME
		,MEDCLOSEDATE DATETIME
		,MEDSTIPDATE DATETIME
		,LEGALSTATUS1 VARCHAR(2)
		,LEGALSTATUS2 VARCHAR(2)
		,LEGALSTATUS3 VARCHAR(2)
		,JURISDICTION VARCHAR(2)
		,PRODUCTCODE VARCHAR(1)
		,PLAINTIFFATTORNEYSEQ NUMBER(19,0)
		,DEFENDANTATTORNEYSEQ NUMBER(19,0)
		,BRANCHID VARCHAR(20)
		,OCCCODE VARCHAR(2)
		,CLAIMSEVERITY VARCHAR(2)
		,DATELOSTBEGAN DATETIME
		,ACCIDENTEMPLOYMENT VARCHAR(1)
		,RELATIONTOINSURED VARCHAR(1)
		,POLICY5DAYS VARCHAR(2)
		,POLICY90DAYS VARCHAR(2)
		,JOB5DAYS VARCHAR(2)
		,JOB90DAYS VARCHAR(2)
		,LOSTDAYS NUMBER(5,0)
		,ACTUALRTWDATE DATETIME
		,MCOTRANSIND VARCHAR(2)
		,QUALIFIEDINJWORKIND VARCHAR(2)
		,PERMSTATIONARYIND VARCHAR(2)
		,HOSPITALADMIT VARCHAR(2)
		,QUALIFIEDINJWORKDATE DATETIME
		,RETTOWORKDATE DATETIME
		,PERMSTATIONARYDATE DATETIME
		,MCOFEIN VARCHAR(9)
		,CREATEUSERID VARCHAR(2)
		,IDCODE VARCHAR(80)
		,IDTYPE VARCHAR(2)
		,MPNOPTOUTEFFECTIVEDATE DATETIME
		,MPNOPTOUTTERMINATIONDATE DATETIME
		,MPNOPTOUTPHYSICIANNAME VARCHAR(50)
		,MPNOPTOUTPHYSICIANTIN VARCHAR(9)
		,MPNCHOICE VARCHAR(2)
		,JURISDICTIONCLAIMID VARCHAR(35)
		,POLICYLIMITRESULT VARCHAR(1)
		,PATIENTPRIMARYPHONE VARCHAR(20)
		,PATIENTWORKPHONE VARCHAR(20)
		,PATIENTALTERNATEPHONE VARCHAR(20)
		,ICDVERSION NUMBER(5,0)
		,LASTDATEOFTRAUMA DATETIME
		,CLAIMADMINCLAIMNUM VARCHAR(35)
		,PATIENTCOUNTRYCODE VARCHAR(3) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.CLAIMSEQ
		,T.CLAIMID
		,T.DOI
		,T.PATIENTSSN
		,T.PATIENTFIRSTNAME
		,T.PATIENTLASTNAME
		,T.PATIENTMINITIAL
		,T.EXTERNALCLAIMID
		,T.POLICYCOPAYAMOUNT
		,T.POLICYCOPAYPCT
		,T.POLICYDEDUCTIBLE
		,T.STATUS
		,T.POLICYLIMIT
		,T.POLICYID
		,T.POLICYTIMELIMIT
		,T.ADJUSTER
		,T.POLICYLIMITWARNINGPCT
		,T.FIRSTDOS
		,T.LASTDOS
		,T.LOADDATE
		,T.MODDATE
		,T.MODUSERID
		,T.PATIENTSEX
		,T.PATIENTCITY
		,T.PATIENTDOB
		,T.PATIENTSTREET2
		,T.PATIENTSTATE
		,T.PATIENTZIP
		,T.PATIENTSTREET1
		,T.MMIDATE
		,T.BODYPART1
		,T.BODYPART2
		,T.BODYPART3
		,T.BODYPART4
		,T.BODYPART5
		,T.LOCATION
		,T.NATUREINJ
		,T.URFLAG
		,T.CARKNOWDATE
		,T.CLAIMTYPE
		,T.CTRLDAY
		,T.MCOCHOICE
		,T.CLIENTCODEDEFAULT
		,T.CLOSEDATE
		,T.REOPENDATE
		,T.MEDCLOSEDATE
		,T.MEDSTIPDATE
		,T.LEGALSTATUS1
		,T.LEGALSTATUS2
		,T.LEGALSTATUS3
		,T.JURISDICTION
		,T.PRODUCTCODE
		,T.PLAINTIFFATTORNEYSEQ
		,T.DEFENDANTATTORNEYSEQ
		,T.BRANCHID
		,T.OCCCODE
		,T.CLAIMSEVERITY
		,T.DATELOSTBEGAN
		,T.ACCIDENTEMPLOYMENT
		,T.RELATIONTOINSURED
		,T.POLICY5DAYS
		,T.POLICY90DAYS
		,T.JOB5DAYS
		,T.JOB90DAYS
		,T.LOSTDAYS
		,T.ACTUALRTWDATE
		,T.MCOTRANSIND
		,T.QUALIFIEDINJWORKIND
		,T.PERMSTATIONARYIND
		,T.HOSPITALADMIT
		,T.QUALIFIEDINJWORKDATE
		,T.RETTOWORKDATE
		,T.PERMSTATIONARYDATE
		,T.MCOFEIN
		,T.CREATEUSERID
		,T.IDCODE
		,T.IDTYPE
		,T.MPNOPTOUTEFFECTIVEDATE
		,T.MPNOPTOUTTERMINATIONDATE
		,T.MPNOPTOUTPHYSICIANNAME
		,T.MPNOPTOUTPHYSICIANTIN
		,T.MPNCHOICE
		,T.JURISDICTIONCLAIMID
		,T.POLICYLIMITRESULT
		,T.PATIENTPRIMARYPHONE
		,T.PATIENTWORKPHONE
		,T.PATIENTALTERNATEPHONE
		,T.ICDVERSION
		,T.LASTDATEOFTRAUMA
		,T.CLAIMADMINCLAIMNUM
		,T.PATIENTCOUNTRYCODE
FROM src.Claim T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		CLAIMSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Claim
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		CLAIMSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.CLAIMSEQ = S.CLAIMSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


