CREATE OR REPLACE FUNCTION dbo.if_Provider(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,PROVIDERSUBSET VARCHAR(4)
		,PROVIDERSEQ NUMBER(19,0)
		,TIN VARCHAR(9)
		,TINSUFFIX VARCHAR(6)
		,EXTERNALID VARCHAR(30)
		,NAME VARCHAR(50)
		,GROUPCODE VARCHAR(5)
		,LICENSENUM VARCHAR(30)
		,MEDICARENUM VARCHAR(20)
		,PRACTICEADDRESSSEQ NUMBER(10,0)
		,BILLINGADDRESSSEQ NUMBER(10,0)
		,HOSPITALSEQ NUMBER(10,0)
		,PROVTYPE VARCHAR(3)
		,SPECIALTY1 VARCHAR(8)
		,SPECIALTY2 VARCHAR(8)
		,CREATEUSERID VARCHAR(2)
		,CREATEDATE DATETIME
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,STATUS VARCHAR(1)
		,EXTERNALSTATUS VARCHAR(1)
		,EXPORTDATE DATETIME
		,SSNTININDICATOR VARCHAR(1)
		,PMTDAYS NUMBER(5,0)
		,AUTHBEGINDATE DATETIME
		,AUTHENDDATE DATETIME
		,TAXADDRESSSEQ NUMBER(10,0)
		,CTRLNUM1099 VARCHAR(4)
		,SURCHARGECODE VARCHAR(1)
		,WORKCOMPNUM VARCHAR(18)
		,WORKCOMPSTATE VARCHAR(2)
		,NCPDPID VARCHAR(10)
		,ENTITYTYPE VARCHAR(1)
		,LASTNAME VARCHAR(35)
		,FIRSTNAME VARCHAR(25)
		,MIDDLENAME VARCHAR(25)
		,SUFFIX VARCHAR(10)
		,NPI VARCHAR(10)
		,FACILITYNPI VARCHAR(10)
		,VERIFICATIONGROUPID VARCHAR(30) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.PROVIDERSUBSET
		,T.PROVIDERSEQ
		,T.TIN
		,T.TINSUFFIX
		,T.EXTERNALID
		,T.NAME
		,T.GROUPCODE
		,T.LICENSENUM
		,T.MEDICARENUM
		,T.PRACTICEADDRESSSEQ
		,T.BILLINGADDRESSSEQ
		,T.HOSPITALSEQ
		,T.PROVTYPE
		,T.SPECIALTY1
		,T.SPECIALTY2
		,T.CREATEUSERID
		,T.CREATEDATE
		,T.MODUSERID
		,T.MODDATE
		,T.STATUS
		,T.EXTERNALSTATUS
		,T.EXPORTDATE
		,T.SSNTININDICATOR
		,T.PMTDAYS
		,T.AUTHBEGINDATE
		,T.AUTHENDDATE
		,T.TAXADDRESSSEQ
		,T.CTRLNUM1099
		,T.SURCHARGECODE
		,T.WORKCOMPNUM
		,T.WORKCOMPSTATE
		,T.NCPDPID
		,T.ENTITYTYPE
		,T.LASTNAME
		,T.FIRSTNAME
		,T.MIDDLENAME
		,T.SUFFIX
		,T.NPI
		,T.FACILITYNPI
		,T.VERIFICATIONGROUPID
FROM src.Provider T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		PROVIDERSUBSET,
		PROVIDERSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Provider
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		PROVIDERSUBSET,
		PROVIDERSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.PROVIDERSUBSET = S.PROVIDERSUBSET
	AND T.PROVIDERSEQ = S.PROVIDERSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


