CREATE OR REPLACE FUNCTION dbo.if_Insurer(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,INSURERTYPE VARCHAR(1)
		,INSURERSEQ NUMBER(10,0)
		,JURISDICTION VARCHAR(2)
		,STATEID VARCHAR(30)
		,TIN VARCHAR(9)
		,ALTID VARCHAR(18)
		,NAME VARCHAR(30)
		,ADDRESS1 VARCHAR(30)
		,ADDRESS2 VARCHAR(30)
		,CITY VARCHAR(20)
		,STATE VARCHAR(2)
		,ZIP VARCHAR(9)
		,PHONENUM VARCHAR(20)
		,CREATEUSERID VARCHAR(2)
		,CREATEDATE DATETIME
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,FAXNUM VARCHAR(20)
		,NAICCOCODE VARCHAR(6)
		,NAICGPCODE VARCHAR(30)
		,NCCICARRIERCODE VARCHAR(5)
		,NCCIGROUPCODE VARCHAR(5) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.INSURERTYPE
		,T.INSURERSEQ
		,T.JURISDICTION
		,T.STATEID
		,T.TIN
		,T.ALTID
		,T.NAME
		,T.ADDRESS1
		,T.ADDRESS2
		,T.CITY
		,T.STATE
		,T.ZIP
		,T.PHONENUM
		,T.CREATEUSERID
		,T.CREATEDATE
		,T.MODUSERID
		,T.MODDATE
		,T.FAXNUM
		,T.NAICCOCODE
		,T.NAICGPCODE
		,T.NCCICARRIERCODE
		,T.NCCIGROUPCODE
FROM src.Insurer T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		INSURERTYPE,
		INSURERSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Insurer
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		INSURERTYPE,
		INSURERSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.INSURERTYPE = S.INSURERTYPE
	AND T.INSURERSEQ = S.INSURERSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


