CREATE OR REPLACE FUNCTION dbo.if_WFQueue(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,ENTITYTYPECODE VARCHAR(2)
		,ENTITYSUBSET VARCHAR(4)
		,ENTITYSEQ NUMBER(19,0)
		,WFTASKSEQ NUMBER(10,0)
		,PRIORWFTASKSEQ NUMBER(10,0)
		,STATUS VARCHAR(1)
		,PRIORITY VARCHAR(1)
		,CREATEUSERID VARCHAR(2)
		,CREATEDATE DATETIME
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,TASKMESSAGE VARCHAR(500)
		,PARAMETER1 VARCHAR(35)
		,CONTEXTID VARCHAR(256)
		,PRIORSTATUS VARCHAR(1) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.ENTITYTYPECODE
		,T.ENTITYSUBSET
		,T.ENTITYSEQ
		,T.WFTASKSEQ
		,T.PRIORWFTASKSEQ
		,T.STATUS
		,T.PRIORITY
		,T.CREATEUSERID
		,T.CREATEDATE
		,T.MODUSERID
		,T.MODDATE
		,T.TASKMESSAGE
		,T.PARAMETER1
		,T.CONTEXTID
		,T.PRIORSTATUS
FROM src.WFQueue T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		ENTITYTYPECODE,
		ENTITYSUBSET,
		ENTITYSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.WFQueue
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		ENTITYTYPECODE,
		ENTITYSUBSET,
		ENTITYSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.ENTITYTYPECODE = S.ENTITYTYPECODE
	AND T.ENTITYSUBSET = S.ENTITYSUBSET
	AND T.ENTITYSEQ = S.ENTITYSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


