CREATE OR REPLACE FUNCTION dbo.if_PolicyInsurer(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,POLICYSEQ NUMBER(10,0)
		,JURISDICTION VARCHAR(2)
		,INSURERTYPE VARCHAR(1)
		,EFFECTIVEDATE DATETIME
		,INSURERSEQ NUMBER(10,0)
		,TERMINATIONDATE DATETIME )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.POLICYSEQ
		,T.JURISDICTION
		,T.INSURERTYPE
		,T.EFFECTIVEDATE
		,T.INSURERSEQ
		,T.TERMINATIONDATE
FROM src.PolicyInsurer T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		POLICYSEQ,
		JURISDICTION,
		INSURERTYPE,
		EFFECTIVEDATE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.PolicyInsurer
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		POLICYSEQ,
		JURISDICTION,
		INSURERTYPE,
		EFFECTIVEDATE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.POLICYSEQ = S.POLICYSEQ
	AND T.JURISDICTION = S.JURISDICTION
	AND T.INSURERTYPE = S.INSURERTYPE
	AND T.EFFECTIVEDATE = S.EFFECTIVEDATE
WHERE T.DMLOPERATION <> 'D'

$$;


