CREATE OR REPLACE FUNCTION dbo.if_AdjusterPendGroup(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,ADJUSTER VARCHAR(25)
		,PENDGROUPCODE VARCHAR(12) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.ADJUSTER
		,T.PENDGROUPCODE
FROM src.AdjusterPendGroup T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		ADJUSTER,
		PENDGROUPCODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.AdjusterPendGroup
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		ADJUSTER,
		PENDGROUPCODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.ADJUSTER = S.ADJUSTER
	AND T.PENDGROUPCODE = S.PENDGROUPCODE
WHERE T.DMLOPERATION <> 'D'

$$;


