CREATE OR REPLACE FUNCTION dbo.if_BillFee(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,FEETYPE VARCHAR(1)
		,TRANSACTIONTYPE VARCHAR(6)
		,FEECTRLSOURCE VARCHAR(1)
		,FEECONTROLSEQ NUMBER(10,0)
		,FEEAMOUNT NUMBER(19,4)
		,INVOICESEQ NUMBER(19,0)
		,INVOICESUBSEQ NUMBER(5,0)
		,PPONETWORKID VARCHAR(2)
		,REDUCTIONCODE NUMBER(5,0)
		,FEEOVERRIDE VARCHAR(1)
		,OVERRIDEVERIFIED VARCHAR(1)
		,EXCLUSIVEFEE VARCHAR(1)
		,FEESOURCEID VARCHAR(20)
		,HANDLINGFEE VARCHAR(1) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.FEETYPE
		,T.TRANSACTIONTYPE
		,T.FEECTRLSOURCE
		,T.FEECONTROLSEQ
		,T.FEEAMOUNT
		,T.INVOICESEQ
		,T.INVOICESUBSEQ
		,T.PPONETWORKID
		,T.REDUCTIONCODE
		,T.FEEOVERRIDE
		,T.OVERRIDEVERIFIED
		,T.EXCLUSIVEFEE
		,T.FEESOURCEID
		,T.HANDLINGFEE
FROM src.BillFee T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		FEETYPE,
		TRANSACTIONTYPE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.BillFee
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		FEETYPE,
		TRANSACTIONTYPE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.FEETYPE = S.FEETYPE
	AND T.TRANSACTIONTYPE = S.TRANSACTIONTYPE
WHERE T.DMLOPERATION <> 'D'

$$;


