CREATE OR REPLACE FUNCTION dbo.if_EDIXmit(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,EDIXMITSEQ NUMBER(10,0)
		,FILESPEC VARCHAR(8000)
		,FILELOCATION VARCHAR(255)
		,RECOMMENDEDPAYMENT NUMBER(19,4)
		,USERID VARCHAR(2)
		,XMITDATE DATETIME
		,DATEFROM DATETIME
		,DATETO DATETIME
		,EDITYPE VARCHAR(1)
		,EDIPARTNERID VARCHAR(3)
		,DBVERSION VARCHAR(20)
		,EDIMAPTOOLSITECODE VARCHAR(3)
		,EDIPORTTYPE VARCHAR(1)
		,EDIMAPTOOLID NUMBER(10,0)
		,TRANSMISSIONSTATUS VARCHAR(1)
		,BATCHNUMBER NUMBER(10,0)
		,SENDERID VARCHAR(20)
		,RECEIVERID VARCHAR(20)
		,EXTERNALBATCHID VARCHAR(50)
		,SARELATEDBATCHID NUMBER(19,0)
		,ACKNOTECODE VARCHAR(3)
		,ACKNOTE VARCHAR(50)
		,EXTERNALBATCHDATE DATETIME
		,USERNOTES VARCHAR(1000)
		,RESUBMITDATE DATETIME
		,RESUBMITUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.EDIXMITSEQ
		,T.FILESPEC
		,T.FILELOCATION
		,T.RECOMMENDEDPAYMENT
		,T.USERID
		,T.XMITDATE
		,T.DATEFROM
		,T.DATETO
		,T.EDITYPE
		,T.EDIPARTNERID
		,T.DBVERSION
		,T.EDIMAPTOOLSITECODE
		,T.EDIPORTTYPE
		,T.EDIMAPTOOLID
		,T.TRANSMISSIONSTATUS
		,T.BATCHNUMBER
		,T.SENDERID
		,T.RECEIVERID
		,T.EXTERNALBATCHID
		,T.SARELATEDBATCHID
		,T.ACKNOTECODE
		,T.ACKNOTE
		,T.EXTERNALBATCHDATE
		,T.USERNOTES
		,T.RESUBMITDATE
		,T.RESUBMITUSERID
		,T.MODDATE
		,T.MODUSERID
FROM src.EDIXmit T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		EDIXMITSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.EDIXmit
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		EDIXMITSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.EDIXMITSEQ = S.EDIXMITSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


