CREATE OR REPLACE FUNCTION dbo.if_BillReevalReason(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,BILLREEVALREASONCODE VARCHAR(30)
		,SITECODE VARCHAR(3)
		,BILLREEVALREASONCATEGORYSEQ NUMBER(10,0)
		,SHORTDESCRIPTION VARCHAR(40)
		,LONGDESCRIPTION VARCHAR(255)
		,ACTIVE BOOLEAN
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.BILLREEVALREASONCODE
		,T.SITECODE
		,T.BILLREEVALREASONCATEGORYSEQ
		,T.SHORTDESCRIPTION
		,T.LONGDESCRIPTION
		,T.ACTIVE
		,T.CREATEDATE
		,T.CREATEUSERID
		,T.MODDATE
		,T.MODUSERID
FROM src.BillReevalReason T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		BILLREEVALREASONCODE,
		SITECODE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.BillReevalReason
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		BILLREEVALREASONCODE,
		SITECODE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.BILLREEVALREASONCODE = S.BILLREEVALREASONCODE
	AND T.SITECODE = S.SITECODE
WHERE T.DMLOPERATION <> 'D'

$$;


