CREATE OR REPLACE FUNCTION dbo.if_EntityType(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,ENTITYTYPEID NUMBER(10,0)
		,ENTITYTYPEKEY VARCHAR(250)
		,DESCRIPTION VARCHAR )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.ENTITYTYPEID
		,T.ENTITYTYPEKEY
		,T.DESCRIPTION
FROM src.EntityType T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		ENTITYTYPEID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.EntityType
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		ENTITYTYPEID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.ENTITYTYPEID = S.ENTITYTYPEID
WHERE T.DMLOPERATION <> 'D'

$$;


