CREATE OR REPLACE FUNCTION dbo.if_LineMod(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLIENTCODE VARCHAR(4)
		,BILLSEQ NUMBER(10,0)
		,LINESEQ NUMBER(5,0)
		,MODSEQ NUMBER(5,0)
		,USERENTERED VARCHAR(1)
		,MODSITECODE VARCHAR(3)
		,MODIFIER VARCHAR(6)
		,REDUCTIONCODE NUMBER(5,0)
		,MODSUBSET VARCHAR(2)
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,REASONCLIENTCODE VARCHAR(4)
		,REASONBILLSEQ NUMBER(10,0)
		,REASONLINESEQ NUMBER(5,0)
		,REASONTYPE VARCHAR(1)
		,REASONVALUE VARCHAR(30) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLIENTCODE
		,T.BILLSEQ
		,T.LINESEQ
		,T.MODSEQ
		,T.USERENTERED
		,T.MODSITECODE
		,T.MODIFIER
		,T.REDUCTIONCODE
		,T.MODSUBSET
		,T.MODUSERID
		,T.MODDATE
		,T.REASONCLIENTCODE
		,T.REASONBILLSEQ
		,T.REASONLINESEQ
		,T.REASONTYPE
		,T.REASONVALUE
FROM src.LineMod T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		LINESEQ,
		MODSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.LineMod
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLIENTCODE,
		BILLSEQ,
		LINESEQ,
		MODSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLIENTCODE = S.CLIENTCODE
	AND T.BILLSEQ = S.BILLSEQ
	AND T.LINESEQ = S.LINESEQ
	AND T.MODSEQ = S.MODSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


