CREATE OR REPLACE FUNCTION dbo.if_PPOProfileNetworks(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,PPOPROFILESITECODE VARCHAR(3)
		,PPOPROFILEID NUMBER(10,0)
		,PROFILEREGIONSITECODE VARCHAR(3)
		,PROFILEREGIONID NUMBER(10,0)
		,NETWORKORDER NUMBER(5,0)
		,PPONETWORKID VARCHAR(2)
		,SEARCHLOGIC VARCHAR(1)
		,VERIFICATION VARCHAR(1)
		,EFFECTIVEDATE DATETIME
		,TERMINATIONDATE DATETIME
		,JURISDICTIONIND VARCHAR(1)
		,JURISDICTIONINSURERSEQ NUMBER(10,0)
		,JURISDICTIONUSEONLY VARCHAR(1)
		,PPOSSTINREQ VARCHAR(1)
		,PPOSSLICREQ VARCHAR(1)
		,DEFAULTEXTENDEDSEARCHES NUMBER(5,0)
		,DEFAULTEXTENDEDFILTERS NUMBER(5,0)
		,SEVEREDTIES VARCHAR(1)
		,POS VARCHAR(500) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.PPOPROFILESITECODE
		,T.PPOPROFILEID
		,T.PROFILEREGIONSITECODE
		,T.PROFILEREGIONID
		,T.NETWORKORDER
		,T.PPONETWORKID
		,T.SEARCHLOGIC
		,T.VERIFICATION
		,T.EFFECTIVEDATE
		,T.TERMINATIONDATE
		,T.JURISDICTIONIND
		,T.JURISDICTIONINSURERSEQ
		,T.JURISDICTIONUSEONLY
		,T.PPOSSTINREQ
		,T.PPOSSLICREQ
		,T.DEFAULTEXTENDEDSEARCHES
		,T.DEFAULTEXTENDEDFILTERS
		,T.SEVEREDTIES
		,T.POS
FROM src.PPOProfileNetworks T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		PPOPROFILESITECODE,
		PPOPROFILEID,
		PROFILEREGIONSITECODE,
		PROFILEREGIONID,
		NETWORKORDER,
		EFFECTIVEDATE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.PPOProfileNetworks
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		PPOPROFILESITECODE,
		PPOPROFILEID,
		PROFILEREGIONSITECODE,
		PROFILEREGIONID,
		NETWORKORDER,
		EFFECTIVEDATE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.PPOPROFILESITECODE = S.PPOPROFILESITECODE
	AND T.PPOPROFILEID = S.PPOPROFILEID
	AND T.PROFILEREGIONSITECODE = S.PROFILEREGIONSITECODE
	AND T.PROFILEREGIONID = S.PROFILEREGIONID
	AND T.NETWORKORDER = S.NETWORKORDER
	AND T.EFFECTIVEDATE = S.EFFECTIVEDATE
WHERE T.DMLOPERATION <> 'D'

$$;


