CREATE OR REPLACE FUNCTION dbo.if_FSServiceCode(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,JURISDICTION VARCHAR(2)
		,SERVICECODE VARCHAR(30)
		,GEOAREACODE VARCHAR(12)
		,EFFECTIVEDATE DATETIME
		,DESCRIPTION VARCHAR(255)
		,TERMDATE DATETIME
		,CODESOURCE VARCHAR(6)
		,CODEGROUP VARCHAR(12) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.JURISDICTION
		,T.SERVICECODE
		,T.GEOAREACODE
		,T.EFFECTIVEDATE
		,T.DESCRIPTION
		,T.TERMDATE
		,T.CODESOURCE
		,T.CODEGROUP
FROM src.FSServiceCode T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		JURISDICTION,
		SERVICECODE,
		GEOAREACODE,
		EFFECTIVEDATE,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.FSServiceCode
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		JURISDICTION,
		SERVICECODE,
		GEOAREACODE,
		EFFECTIVEDATE) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.JURISDICTION = S.JURISDICTION
	AND T.SERVICECODE = S.SERVICECODE
	AND T.GEOAREACODE = S.GEOAREACODE
	AND T.EFFECTIVEDATE = S.EFFECTIVEDATE
WHERE T.DMLOPERATION <> 'D'

$$;


