CREATE OR REPLACE FUNCTION dbo.if_PPOProfile(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,SITECODE VARCHAR(3)
		,PPOPROFILEID NUMBER(10,0)
		,PROFILEDESC VARCHAR(50)
		,CREATEDATE DATETIME
		,CREATEUSERID VARCHAR(2)
		,MODDATE DATETIME
		,MODUSERID VARCHAR(2)
		,SMARTSEARCHPAGEMAX NUMBER(5,0)
		,JURISDICTIONSTACKEXCLUSIVE VARCHAR(1)
		,REEVALFULLSTACKWHENORIGALLOWNOHIT VARCHAR(1) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.SITECODE
		,T.PPOPROFILEID
		,T.PROFILEDESC
		,T.CREATEDATE
		,T.CREATEUSERID
		,T.MODDATE
		,T.MODUSERID
		,T.SMARTSEARCHPAGEMAX
		,T.JURISDICTIONSTACKEXCLUSIVE
		,T.REEVALFULLSTACKWHENORIGALLOWNOHIT
FROM src.PPOProfile T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		SITECODE,
		PPOPROFILEID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.PPOProfile
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		SITECODE,
		PPOPROFILEID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.SITECODE = S.SITECODE
	AND T.PPOPROFILEID = S.PPOPROFILEID
WHERE T.DMLOPERATION <> 'D'

$$;


