CREATE OR REPLACE FUNCTION dbo.if_WFlow(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,WFLOWSEQ NUMBER(10,0)
		,DESCRIPTION VARCHAR(50)
		,RECORDSTATUS VARCHAR(1)
		,ENTITYTYPECODE VARCHAR(2)
		,CREATEUSERID VARCHAR(2)
		,CREATEDATE DATETIME
		,MODUSERID VARCHAR(2)
		,MODDATE DATETIME
		,INITIALTASKSEQ NUMBER(10,0)
		,PAUSETASKSEQ NUMBER(10,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.WFLOWSEQ
		,T.DESCRIPTION
		,T.RECORDSTATUS
		,T.ENTITYTYPECODE
		,T.CREATEUSERID
		,T.CREATEDATE
		,T.MODUSERID
		,T.MODDATE
		,T.INITIALTASKSEQ
		,T.PAUSETASKSEQ
FROM src.WFlow T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		WFLOWSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.WFlow
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		WFLOWSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.WFLOWSEQ = S.WFLOWSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


