CREATE OR REPLACE FUNCTION dbo.if_Region(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,JURISDICTION VARCHAR(2)
		,EXTENSION VARCHAR(3)
		,ENDZIP VARCHAR(5)
		,BEG VARCHAR(5)
		,REGION NUMBER(5,0)
		,REGIONDESCRIPTION VARCHAR(4) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.JURISDICTION
		,T.EXTENSION
		,T.ENDZIP
		,T.BEG
		,T.REGION
		,T.REGIONDESCRIPTION
FROM src.Region T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		JURISDICTION,
		EXTENSION,
		ENDZIP,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Region
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		JURISDICTION,
		EXTENSION,
		ENDZIP) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.JURISDICTION = S.JURISDICTION
	AND T.EXTENSION = S.EXTENSION
	AND T.ENDZIP = S.ENDZIP
WHERE T.DMLOPERATION <> 'D'

$$;


