CREATE OR REPLACE FUNCTION dbo.if_CityStateZip(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,ZIPCODE VARCHAR(5)
		,CTYSTKEY VARCHAR(6)
		,CPYDTLCODE VARCHAR(1)
		,ZIPCLSCODE VARCHAR(1)
		,CTYSTNAME VARCHAR(28)
		,CTYSTNAMEABV VARCHAR(13)
		,CTYSTFACCODE VARCHAR(1)
		,CTYSTMAILIND VARCHAR(1)
		,PRELSTCTYKEY VARCHAR(6)
		,PRELSTCTYNME VARCHAR(28)
		,CTYDLVIND VARCHAR(1)
		,AUTZONEIND VARCHAR(1)
		,UNQZIPIND VARCHAR(1)
		,FINANCENUM VARCHAR(6)
		,STATEABBRV VARCHAR(2)
		,COUNTYNUM VARCHAR(3)
		,COUNTYNAME VARCHAR(25) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.ZIPCODE
		,T.CTYSTKEY
		,T.CPYDTLCODE
		,T.ZIPCLSCODE
		,T.CTYSTNAME
		,T.CTYSTNAMEABV
		,T.CTYSTFACCODE
		,T.CTYSTMAILIND
		,T.PRELSTCTYKEY
		,T.PRELSTCTYNME
		,T.CTYDLVIND
		,T.AUTZONEIND
		,T.UNQZIPIND
		,T.FINANCENUM
		,T.STATEABBRV
		,T.COUNTYNUM
		,T.COUNTYNAME
FROM src.CityStateZip T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		ZIPCODE,
		CTYSTKEY,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.CityStateZip
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		ZIPCODE,
		CTYSTKEY) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.ZIPCODE = S.ZIPCODE
	AND T.CTYSTKEY = S.CTYSTKEY
WHERE T.DMLOPERATION <> 'D'

$$;


