CREATE OR REPLACE FUNCTION dbo.if_Jurisdiction(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,JURISDICTIONID VARCHAR(2)
		,NAME VARCHAR(30)
		,POSTABLECODE VARCHAR(2)
		,TOSTABLECODE VARCHAR(2)
		,TOBTABLECODE VARCHAR(2)
		,PROVTYPETABLECODE VARCHAR(2)
		,HOSPITAL VARCHAR(1)
		,PROVSPCLTABLECODE VARCHAR(2)
		,DAYSTOPAY NUMBER(5,0)
		,DAYSTOPAYQUALIFY VARCHAR(2)
		,OUTPATIENTFS VARCHAR(1)
		,PROCFILEVER VARCHAR(1)
		,ANESTUNIT NUMBER(5,0)
		,ANESTRNDUP NUMBER(5,0)
		,ANESTFORMAT VARCHAR(1)
		,STATEMANDATESSN VARCHAR(1)
		,ICDEDITION NUMBER(5,0)
		,ICD10COMPLIANCEDATE DATETIME
		,EBILLSDAYSTOPAY NUMBER(5,0)
		,EBILLSDAYSTOPAYQUALIFY VARCHAR(2)
		,DISPUTEDAYSTOPAY NUMBER(5,0)
		,DISPUTEDAYSTOPAYQUALIFY VARCHAR(2) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.JURISDICTIONID
		,T.NAME
		,T.POSTABLECODE
		,T.TOSTABLECODE
		,T.TOBTABLECODE
		,T.PROVTYPETABLECODE
		,T.HOSPITAL
		,T.PROVSPCLTABLECODE
		,T.DAYSTOPAY
		,T.DAYSTOPAYQUALIFY
		,T.OUTPATIENTFS
		,T.PROCFILEVER
		,T.ANESTUNIT
		,T.ANESTRNDUP
		,T.ANESTFORMAT
		,T.STATEMANDATESSN
		,T.ICDEDITION
		,T.ICD10COMPLIANCEDATE
		,T.EBILLSDAYSTOPAY
		,T.EBILLSDAYSTOPAYQUALIFY
		,T.DISPUTEDAYSTOPAY
		,T.DISPUTEDAYSTOPAYQUALIFY
FROM src.Jurisdiction T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		JURISDICTIONID,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.Jurisdiction
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		JURISDICTIONID) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.JURISDICTIONID = S.JURISDICTIONID
WHERE T.DMLOPERATION <> 'D'

$$;


