CREATE OR REPLACE FUNCTION dbo.if_ClaimICDDiagnosis(
		IF_ODSPOSTINGGROUPAUDITID INT
)
RETURNS TABLE  (
		 ODSPOSTINGGROUPAUDITID NUMBER(10,0)
		,ODSCUSTOMERID NUMBER(10,0)
		,ODSCREATEDATE DATETIME
		,ODSSNAPSHOTDATE DATETIME
		,ODSROWISCURRENT INT
		,ODSHASHBYTESVALUE BINARY(8000)
		,DMLOPERATION VARCHAR(1)
		,CLAIMSYSSUBSET VARCHAR(4)
		,CLAIMSEQ NUMBER(10,0)
		,CLAIMDIAGNOSISSEQ NUMBER(5,0)
		,ICDDIAGNOSISID NUMBER(10,0) )
AS
$$
SELECT T.ODSPOSTINGGROUPAUDITID
		,T.ODSCUSTOMERID
		,T.ODSCREATEDATE
		,T.ODSSNAPSHOTDATE
		,T.ODSROWISCURRENT
		,T.ODSHASHBYTESVALUE
		,T.DMLOPERATION
		,T.CLAIMSYSSUBSET
		,T.CLAIMSEQ
		,T.CLAIMDIAGNOSISSEQ
		,T.ICDDIAGNOSISID
FROM src.ClaimICDDiagnosis T
INNER JOIN (
	SELECT 
		ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		CLAIMSEQ,
		CLAIMDIAGNOSISSEQ,
		MAX(ODSPOSTINGGROUPAUDITID) AS ODSPOSTINGGROUPAUDITID
	FROM src.ClaimICDDiagnosis
	WHERE ODSPOSTINGGROUPAUDITID <= IF_ODSPOSTINGGROUPAUDITID
	GROUP BY ODSCUSTOMERID,
		CLAIMSYSSUBSET,
		CLAIMSEQ,
		CLAIMDIAGNOSISSEQ) S
ON T.ODSPOSTINGGROUPAUDITID = S.ODSPOSTINGGROUPAUDITID
	AND T.ODSCUSTOMERID = S.ODSCUSTOMERID
	AND T.CLAIMSYSSUBSET = S.CLAIMSYSSUBSET
	AND T.CLAIMSEQ = S.CLAIMSEQ
	AND T.CLAIMDIAGNOSISSEQ = S.CLAIMDIAGNOSISSEQ
WHERE T.DMLOPERATION <> 'D'

$$;


