
CREATE SCHEMA IF NOT EXISTS dbo;
CREATE SCHEMA IF NOT EXISTS adm DATA_RETENTION_TIME_IN_DAYS=90;
CREATE SCHEMA IF NOT EXISTS src DATA_RETENTION_TIME_IN_DAYS=90;
CREATE SCHEMA IF NOT EXISTS stg;
CREATE SCHEMA IF NOT EXISTS rpt DATA_RETENTION_TIME_IN_DAYS=90;