call ADM.DROP_OBJECT('drop', 'constraint', 'PRIMARY KEY', 'ADM', '');
ALTER TABLE adm.App_Version ADD PRIMARY KEY (App_Version_Id);
ALTER TABLE ADM.POSTING_GROUP_INJEST_AUDIT ADD PRIMARY KEY(Posting_Group_Audit_Id);
ALTER TABLE ADM.PROCESS_FILE_AUDIT  ADD PRIMARY KEY(Process_File_Audit_Id);
ALTER TABLE ADM.PROCESS_INJEST_AUDIT ADD PRIMARY KEY(Process_Audit_Id);
