CREATE OR REPLACE VIEW dbo.Adjuster
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,ADJUSTER
		,FIRSTNAME
		,LASTNAME
		,MINITIAL
		,TITLE
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
		,PHONENUM
		,PHONENUMEXT
		,FAXNUM
		,EMAIL
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.Adjuster
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.AdjusterPendGroup
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,ADJUSTER
		,PENDGROUPCODE
FROM src.AdjusterPendGroup
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Attorney
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,ATTORNEYSEQ
		,TIN
		,TINSUFFIX
		,EXTERNALID
		,NAME
		,GROUPCODE
		,LICENSENUM
		,MEDICARENUM
		,PRACTICEADDRESSSEQ
		,BILLINGADDRESSSEQ
		,ATTORNEYTYPE
		,SPECIALTY1
		,SPECIALTY2
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,STATUS
		,EXTERNALSTATUS
		,EXPORTDATE
		,SSNTININDICATOR
		,PMTDAYS
		,AUTHBEGINDATE
		,AUTHENDDATE
		,TAXADDRESSSEQ
		,CTRLNUM1099
		,SURCHARGECODE
		,WORKCOMPNUM
		,WORKCOMPSTATE
FROM src.Attorney
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.AttorneyAddress
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,ATTORNEYADDRESSSEQ
		,RECTYPE
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
		,PHONENUM
		,FAXNUM
		,CONTACTFIRSTNAME
		,CONTACTLASTNAME
		,CONTACTMIDDLEINITIAL
		,URFIRSTNAME
		,URLASTNAME
		,URMIDDLEINITIAL
		,FACILITYNAME
		,COUNTRYCODE
		,MAILCODE
FROM src.AttorneyAddress
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Bill
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,CLAIMSEQ
		,CLAIMSYSSUBSET
		,PROVIDERSEQ
		,PROVIDERSUBSET
		,POSTDATE
		,DOSFIRST
		,INVOICED
		,INVOICEDPPO
		,CREATEUSERID
		,CARRIERSEQNEW
		,DOCCTRLTYPE
		,DOSLAST
		,PPONETWORKID
		,POS
		,PROVTYPE
		,PROVSPECIALTY1
		,PROVZIP
		,PROVSTATE
		,SUBMITDATE
		,PROVINVOICE
		,REGION
		,HOSPITALSEQ
		,MODUSERID
		,STATUS
		,STATUSPRIOR
		,BILLABLELINES
		,TOTALCHARGE
		,BRREDUCTION
		,BRFEE
		,TOTALALLOW
		,TOTALFEE
		,DUPCLIENTCODE
		,DUPBILLSEQ
		,FUPSTARTDATE
		,FUPENDDATE
		,SENDBACKMSG1SITECODE
		,SENDBACKMSG1
		,SENDBACKMSG2SITECODE
		,SENDBACKMSG2
		,PPOREDUCTION
		,PPOPRC
		,PPOCONTRACTID
		,PPOSTATUS
		,PPOFEE
		,NGDREDUCTION
		,NGDFEE
		,URFEE
		,OTHERDATA
		,EXTERNALSTATUS
		,URFLAG
		,VISITS
		,TOS
		,TOB
		,SUBPRODUCTCODE
		,FORCEPAY
		,PMTAUTH
		,FLOWSTATUS
		,CONSULTDATE
		,RCVDDATE
		,ADMISSIONTYPE
		,PAIDDATE
		,ADMITDATE
		,DISCHARGEDATE
		,TXBILLTYPE
		,RCVDBRDATE
		,DUEDATE
		,ADJUSTER
		,DOI
		,RETCTRLFLG
		,RETCTRLNUM
		,SITECODE
		,SOURCEID
		,CASETYPE
		,SUBPRODUCTID
		,SUBPRODUCTPRICE
		,URREDUCTION
		,PROVLICENSENUM
		,PROVMEDICARENUM
		,PROVSPECIALTY2
		,PMTEXPORTDATE
		,PMTACCEPTDATE
		,CLIENTTOB
		,BRFEENET
		,PPOFEENET
		,NGDFEENET
		,URFEENET
		,SUBPRODUCTPRICENET
		,BILLSEQNEWREV
		,BILLSEQORGREV
		,VOCPLANSEQ
		,REVIEWDATE
		,AUDITDATE
		,REEVALALLOW
		,CHECKNUM
		,NEGOTYPE
		,DISCHARGEHOUR
		,UB92TOB
		,MCO
		,DRG
		,PATIENTACCOUNT
		,EXAMINERREVFLAG
		,REFPROVNAME
		,PAIDAMOUNT
		,ADMISSIONSOURCE
		,ADMITHOUR
		,PATIENTSTATUS
		,DRGVALUE
		,COMPANYSEQ
		,TOTALCOPAY
		,UB92PROCMETHOD
		,TOTALDEDUCTIBLE
		,POLICYCOPAYAMOUNT
		,POLICYCOPAYPCT
		,DOCCTRLID
		,RESOURCEUTILGROUP
		,POLICYDEDUCTIBLE
		,POLICYLIMIT
		,POLICYTIMELIMIT
		,POLICYWARNINGPCT
		,APPBENEFITS
		,APPASSIGNEE
		,CREATEDATE
		,MODDATE
		,INCREMENTVALUE
		,ADJVERIFREQUESTDATE
		,ADJVERIFRCVDDATE
		,RENDERINGPROVLASTNAME
		,RENDERINGPROVFIRSTNAME
		,RENDERINGPROVMIDDLENAME
		,RENDERINGPROVSUFFIX
		,REREVIEWCOUNT
		,DRGBILLED
		,DRGCALCULATED
		,PROVRXLICENSENUM
		,PROVSIGONFILE
		,REFPROVFIRSTNAME
		,REFPROVMIDDLENAME
		,REFPROVSUFFIX
		,REFPROVDEANUM
		,SENDBACKMSG1SUBSET
		,SENDBACKMSG2SUBSET
		,PPONETWORKJURISDICTIONIND
		,MANUALREDUCTIONMODE
		,WHOLESALESALESTAXZIP
		,RETAILSALESTAXZIP
		,PPONETWORKJURISDICTIONINSURERSEQ
		,INVOICEDWHOLESALE
		,INVOICEDPPOWHOLESALE
		,ADMITTINGDXREF
		,ADMITTINGDXCODE
		,PROVFACILITYNPI
		,PROVBILLINGNPI
		,PROVRENDERINGNPI
		,PROVOPERATINGNPI
		,PROVREFERRINGNPI
		,PROVOTHER1NPI
		,PROVOTHER2NPI
		,PROVOPERATINGLICENSENUM
		,EHUBID
		,OTHERBILLINGPROVIDERSUBSET
		,OTHERBILLINGPROVIDERSEQ
		,RESUBMISSIONREASONCODE
		,CONTRACTTYPE
		,CONTRACTAMOUNT
		,PRIORAUTHREFERRALNUM1
		,PRIORAUTHREFERRALNUM2
		,DRGCOMPOSITEFACTOR
		,DRGDISCHARGEFRACTION
		,DRGINPATIENTMULTIPLIER
		,DRGWEIGHT
		,EFTPMTMETHODCODE
		,EFTPMTFORMATCODE
		,EFTSENDERDFIID
		,EFTSENDERACCTNUM
		,EFTORIGCOSUPPLCODE
		,EFTRECEIVERDFIID
		,EFTRECEIVERACCTQUAL
		,EFTRECEIVERACCTNUM
		,POLICYLIMITRESULT
		,HISTORYBATCHNUMBER
		,PROVBILLINGTAXONOMY
		,PROVFACILITYTAXONOMY
		,PROVRENDERINGTAXONOMY
		,PPOSTACKLIST
		,ICDVERSION
		,ODGFLAG
		,PROVBILLLICENSENUM
		,PROVFACILITYLICENSENUM
		,PROVVENDOREXTERNALID
		,BRACTUALCLIENTCODE
		,BROVERRIDECLIENTCODE
		,BILLREEVALREASONCODE
		,PAYMENTCLEAREDDATE
		,ESTIMATEDBRCLIENTCODE
		,ESTIMATEDBRJURIS
		,OVERRIDEFEECONTROLRETAIL
		,OVERRIDEFEECONTROLWHOLESALE
		,STATEMENTFROMDATE
		,STATEMENTTHROUGHDATE
FROM src.Bill
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillControl
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLCONTROLSEQ
		,MODDATE
		,CREATEDATE
		,CONTROL
		,EXTERNALID
		,BATCHNUMBER
		,MODUSERID
		,EXTERNALID2
		,MESSAGE
FROM src.BillControl
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillControlHistory
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLCONTROLHISTORYSEQ
		,CLIENTCODE
		,BILLSEQ
		,BILLCONTROLSEQ
		,CREATEDATE
		,CONTROL
		,EXTERNALID
		,EDIBATCHLOGSEQ
		,DELETED
		,MODUSERID
		,EXTERNALID2
		,MESSAGE
FROM src.BillControlHistory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillData
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,TYPECODE
		,SUBTYPE
		,SUBSEQ
		,NUMDATA
		,TEXTDATA
		,MODDATE
		,MODUSERID
		,CREATEDATE
		,CREATEUSERID
FROM src.BillData
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillFee
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,FEETYPE
		,TRANSACTIONTYPE
		,FEECTRLSOURCE
		,FEECONTROLSEQ
		,FEEAMOUNT
		,INVOICESEQ
		,INVOICESUBSEQ
		,PPONETWORKID
		,REDUCTIONCODE
		,FEEOVERRIDE
		,OVERRIDEVERIFIED
		,EXCLUSIVEFEE
		,FEESOURCEID
		,HANDLINGFEE
FROM src.BillFee
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillICD
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLICDSEQ
		,CODETYPE
		,ICDCODE
		,CODEDATE
		,POA
FROM src.BillICD
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillICDDiagnosis
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLDIAGNOSISSEQ
		,ICDDIAGNOSISID
		,POA
		,BILLEDICDDIAGNOSIS
		,ICDBILLUSAGETYPEID
FROM src.BillICDDiagnosis
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillICDProcedure
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLPROCEDURESEQ
		,ICDPROCEDUREID
		,CODEDATE
		,BILLEDICDPROCEDURE
		,ICDBILLUSAGETYPEID
FROM src.BillICDProcedure
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillPPORate
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINKNAME
		,RATETYPE
		,APPLIED
FROM src.BillPPORate
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillProvider
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLPROVIDERSEQ
		,QUALIFIER
		,LASTNAME
		,FIRSTNAME
		,MIDDLENAME
		,SUFFIX
		,NPI
		,LICENSENUM
		,DEANUM
FROM src.BillProvider
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillReevalReason
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLREEVALREASONCODE
		,SITECODE
		,BILLREEVALREASONCATEGORYSEQ
		,SHORTDESCRIPTION
		,LONGDESCRIPTION
		,ACTIVE
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.BillReevalReason
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BillRuleFire
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINESEQ
		,RULEID
		,RULETYPE
		,DATERULEFIRED
		,VALIDATED
		,VALIDATEDUSERID
		,DATEVALIDATED
		,PENDTOID
		,RULESEVERITY
		,WFTASKSEQ
		,CHILDTARGETSUBSET
		,CHILDTARGETSEQ
		,CAPSTONERULEID
FROM src.BillRuleFire
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Branch
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,BRANCHSEQ
		,NAME
		,EXTERNALID
		,BRANCHID
		,LOCATIONCODE
		,ADMINKEY
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
		,PHONENUM
		,FAXNUM
		,CONTACTNAME
		,TIN
		,STATETAXID
		,DIRNUM
		,MODUSERID
		,MODDATE
		,RULEFIRE
		,FEERATECNTRLEX
		,FEERATECNTRLIN
		,SALESTAXEXEMPT
		,EFFECTIVEDATE
		,TERMINATIONDATE
FROM src.Branch
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.BRERuleCategory
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BRERULECATEGORYID
		,CATEGORYDESCRIPTION
FROM src.BRERuleCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.CityStateZip
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ZIPCODE
		,CTYSTKEY
		,CPYDTLCODE
		,ZIPCLSCODE
		,CTYSTNAME
		,CTYSTNAMEABV
		,CTYSTFACCODE
		,CTYSTMAILIND
		,PRELSTCTYKEY
		,PRELSTCTYNME
		,CTYDLVIND
		,AUTZONEIND
		,UNQZIPIND
		,FINANCENUM
		,STATEABBRV
		,COUNTYNUM
		,COUNTYNAME
FROM src.CityStateZip
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Claim
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMSEQ
		,CLAIMID
		,DOI
		,PATIENTSSN
		,PATIENTFIRSTNAME
		,PATIENTLASTNAME
		,PATIENTMINITIAL
		,EXTERNALCLAIMID
		,POLICYCOPAYAMOUNT
		,POLICYCOPAYPCT
		,POLICYDEDUCTIBLE
		,STATUS
		,POLICYLIMIT
		,POLICYID
		,POLICYTIMELIMIT
		,ADJUSTER
		,POLICYLIMITWARNINGPCT
		,FIRSTDOS
		,LASTDOS
		,LOADDATE
		,MODDATE
		,MODUSERID
		,PATIENTSEX
		,PATIENTCITY
		,PATIENTDOB
		,PATIENTSTREET2
		,PATIENTSTATE
		,PATIENTZIP
		,PATIENTSTREET1
		,MMIDATE
		,BODYPART1
		,BODYPART2
		,BODYPART3
		,BODYPART4
		,BODYPART5
		,LOCATION
		,NATUREINJ
		,URFLAG
		,CARKNOWDATE
		,CLAIMTYPE
		,CTRLDAY
		,MCOCHOICE
		,CLIENTCODEDEFAULT
		,CLOSEDATE
		,REOPENDATE
		,MEDCLOSEDATE
		,MEDSTIPDATE
		,LEGALSTATUS1
		,LEGALSTATUS2
		,LEGALSTATUS3
		,JURISDICTION
		,PRODUCTCODE
		,PLAINTIFFATTORNEYSEQ
		,DEFENDANTATTORNEYSEQ
		,BRANCHID
		,OCCCODE
		,CLAIMSEVERITY
		,DATELOSTBEGAN
		,ACCIDENTEMPLOYMENT
		,RELATIONTOINSURED
		,POLICY5DAYS
		,POLICY90DAYS
		,JOB5DAYS
		,JOB90DAYS
		,LOSTDAYS
		,ACTUALRTWDATE
		,MCOTRANSIND
		,QUALIFIEDINJWORKIND
		,PERMSTATIONARYIND
		,HOSPITALADMIT
		,QUALIFIEDINJWORKDATE
		,RETTOWORKDATE
		,PERMSTATIONARYDATE
		,MCOFEIN
		,CREATEUSERID
		,IDCODE
		,IDTYPE
		,MPNOPTOUTEFFECTIVEDATE
		,MPNOPTOUTTERMINATIONDATE
		,MPNOPTOUTPHYSICIANNAME
		,MPNOPTOUTPHYSICIANTIN
		,MPNCHOICE
		,JURISDICTIONCLAIMID
		,POLICYLIMITRESULT
		,PATIENTPRIMARYPHONE
		,PATIENTWORKPHONE
		,PATIENTALTERNATEPHONE
		,ICDVERSION
		,LASTDATEOFTRAUMA
		,CLAIMADMINCLAIMNUM
		,PATIENTCOUNTRYCODE
FROM src.Claim
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ClaimData
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMSEQ
		,TYPECODE
		,SUBTYPE
		,SUBSEQ
		,NUMDATA
		,TEXTDATA
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.ClaimData
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ClaimDiag
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMSEQ
		,CLAIMDIAGSEQ
		,DIAGCODE
FROM src.ClaimDiag
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ClaimICDDiagnosis
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMSEQ
		,CLAIMDIAGNOSISSEQ
		,ICDDIAGNOSISID
FROM src.ClaimICDDiagnosis
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ClaimInsurer
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMSEQ
		,INSURERTYPE
		,EFFECTIVEDATE
		,INSURERSEQ
		,TERMINATIONDATE
		,EXTERNALPOLICYNUMBER
		,UNITSTATCLAIMID
		,UNITSTATPOLICYID
		,POLICYEFFECTIVEDATE
		,SELFINSURED
		,CLAIMADMINCLAIMNUM
FROM src.ClaimInsurer
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ClaimSys
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMIDMASK
		,CLAIMACCESS
		,CLAIMSYSDESC
		,POLICYHOLDERREQ
		,VALIDATEBRANCH
		,VALIDATEPOLICY
		,LGLCODE1TABLECODE
		,LGLCODE2TABLECODE
		,LGLCODE3TABLECODE
		,UROCCTABLECODE
		,POLICY5DAYSTABLECODE
		,POLICY90DAYSTABLECODE
		,JOB5DAYSTABLECODE
		,JOB90DAYSTABLECODE
		,HCOTRANSINDTABLECODE
		,QUALIFIEDINJWORKTABLECODE
		,PERMSTATIONARYTABLECODE
		,VALIDATEADJUSTER
		,MCOPROGRAM
		,ADJUSTERREQUIRED
		,HOSPITALADMITTABLECODE
		,ATTORNEYTAXADDRREQUIRED
		,BODYPARTTABLECODE
		,POLICYDEFAULTS
		,POLICYCOPAYAMOUNT
		,POLICYCOPAYPCT
		,POLICYDEDUCTIBLE
		,POLICYLIMIT
		,POLICYTIMELIMIT
		,POLICYLIMITWARNINGPCT
		,RESTRICTUSERACCESS
		,BEOVERRIDEPERMISSIONFLAG
		,ROOTCLAIMLENGTH
		,RELATECLAIMSTOTALPOLICYDETAIL
		,POLICYLIMITRESULT
		,ENABLECLAIMCLIENTCODEDEFAULT
		,REEVALCOPYDOCCTRLID
		,ENABLECEPHEADERFIELDEDITS
		,ENABLESMARTCLIENTSELECTION
		,SCSCLIENTSELECTIONCODE
		,SCSPROVIDERSUBSET
		,SCSCLIENTCODEMASK
		,SCSDEFAULTCLIENT
		,CLAIMEXTERNALIDASCARRIERCLAIMID
		,POLICYEXTERNALIDASCARRIERPOLICYID
		,URPROFILEID
		,BEUROVERRIDESREQUIREREVIEWREF
		,URENTRYVALIDATIONS
		,PENDPPOEDICONTROL
		,BEREEVALLINEADDDELETE
		,CPTGROUPTOINDIVIDUAL
		,CLAIMEXTERNALIDASCLAIMADMINCLAIMNUM
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,FINANCIALAGGREGATION
FROM src.ClaimSys
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ClaimSysData
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,TYPECODE
		,SUBTYPE
		,SUBSEQ
		,NUMDATA
		,TEXTDATA
FROM src.ClaimSysData
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Client
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,NAME
		,JURISDICTION
		,CONTROLNUM
		,POLICYTIMELIMIT
		,POLICYLIMITWARNINGPCT
		,POLICYLIMIT
		,POLICYDEDUCTIBLE
		,POLICYCOPAYPCT
		,POLICYCOPAYAMOUNT
		,BEDIAGNOSIS
		,INVOICEBRCYCLE
		,STATUS
		,INVOICEGROUPBY
		,BEDOI
		,DRUGMARKUPBRAND
		,SUPPLYLIMIT
		,INVOICEPPOCYCLE
		,INVOICEPPOTAX
		,DRUGMARKUPGEN
		,DRUGDISPGEN
		,DRUGDISPBRAND
		,BEADJUSTER
		,INVOICETAX
		,COMPANYSEQ
		,BEMEDALERT
		,UCRPERCENTILE
		,CLIENTCOMMENT
		,REMITATTENTION
		,REMITADDRESS1
		,REMITADDRESS2
		,REMITCITYSTATEZIP
		,REMITPHONE
		,EXTERNALID
		,BEOTHER
		,MEDALERTDAYS
		,MEDALERTVISITS
		,MEDALERTMAXCHARGE
		,MEDALERTWARNVISITS
		,PROVIDERSUBSET
		,ALLOWREREVIEW
		,ACCTREP
		,CLIENTTYPE
		,UCRMARKUP
		,INVOICECOMBINED
		,BESUBMITDT
		,BERCVDCARRIERDATE
		,BERCVDBILLREVIEWDATE
		,BEDUEDATE
		,PRODUCTCODE
		,BEPROVINVOICE
		,CLAIMSYSSUBSET
		,DEFAULTBRTOUCR
		,BASEPPOFEESOFFFS
		,BECLIENTTOBTABLECODE
		,BEFORCEPAY
		,BEPAYAUTHORIZATION
		,BECARRIERSEQFLAG
		,BEPROVTYPETABLECODE
		,BEPROVSPCL1TABLECODE
		,BEPROVLICENSE
		,BEPAYAUTHTABLECODE
		,PENDREASONTABLECODE
		,VOCREHAB
		,EDIACKREQUIRED
		,STATERPTIND
		,BEPATIENTACCTNUM
		,AUTODUP
		,USEALLOWONDUP
		,URIMPORTUSED
		,URPROGSTARTDATE
		,URIMPORTCTRLNUM
		,URIMPORTCTRLGROUP
		,UCRSOURCE
		,UCRMARKUP2
		,NGDTABLECODE
		,BESUBPRODUCTTABLECODE
		,COUNTRYTABLECODE
		,BEREFPHYS
		,BEPMTWARNDAYS
		,GEOSTATE
		,BEDISABLEDOICHECK
		,DELAYDAYS
		,BEVALIDATETOTAL
		,BEFASTMATCH
		,BEPRIORBILLDEFAULT
		,BECLIENTDUEDAYS
		,BEAUTOCALCDUEDATE
		,UCRSOURCE2
		,UCRPERCENTILE2
		,BEPROVSPCL2TABLECODE
		,FEERATECNTRLEX
		,FEERATECNTRLIN
		,BECOLLISIONPROVBILLS
		,BECOLLISIONBILLS
		,SUPPLYMARKUP
		,BECOLLISIONPROVIDERS
		,DEFAULTCOPAYDEDUCT
		,AUTOBUNDLING
		,BEVALIDATEBILLCLAIMICD9
		,ENABLEGENERICREPRICE
		,BESUBPRODFEEINFO
		,DENYNONINJDRUGS
		,BECOLLISIONDOSLINES
		,PPOPROFILESITECODE
		,PPOPROFILEID
		,BESHOWDEAWARNING
		,BEHIDEADJUSTERCOLUMN
		,BEHIDECOPAYCOLUMN
		,BEHIDEDEDUCTCOLUMN
		,BEPAIDDATE
		,BEPROCCROSSWALK
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,BECONSULTDATE
		,BESHOWPHARMACYCOLUMNS
		,BEADJVERIFDATES
		,FUTUREDOSMONTHLIMIT
		,BESTOPATLINEUNITS
		,BENYNF10FIELDS
		,ENABLEDRGGROUPER
		,APPLYCPTAMAUCRRULES
		,BEPROVSIGONFILE
		,BETIMEENTRY
		,SALESTAXEXEMPT
		,INVOICERETAILPROFILE
		,INVOICEWHOLESALEPROFILE
		,BEDEFAULTTAXZIP
		,RECEIPTHANDLINGCODE
		,PAYMENTHANDLINGCODE
		,DEFAULTRETAILSALESTAXZIP
		,DEFAULTWHOLESALESALESTAXZIP
		,TXNONSUBSCRIB
		,ROOTCLAIMLENGTH
		,BEDAWTABLECODE
		,EORPROFILESEQ
		,BEOTHERBILLINGPROVIDER
		,BEDOCCTRLID
		,REPORTINGETL
		,CLAIMVERIFICATION
		,PROVVERIFICATION
		,BEPERMITALLOWOVER
		,BESTOPATLINEDXREF
		,BEQUICKINFOCODE
		,EXCLUDEDSMARTCLIENTSELECT
		,COLLISIONSSEARCHBY
		,AUTODUPINCLUDEPROV
		,URPROFILEID
		,EXCLUDEURDM
		,BECOLLISIONURCASES
		,MUEEDITS
		,CPTRARITY
		,ICDRARITY
		,ICDTOCPTRARITY
		,BEDISABLEPPOSEARCH
		,BESHOWLINEEXTERNALIDCOLUMN
		,BESHOWLINEPRIORAUTHCOLUMN
		,SMARTGUIDELINESFLAG
		,BEPROVBILLINGLICENSE
		,BEPROVFACILITYLICENSE
		,VENDORPROVIDERSUBSET
		,DEFAULTJURISCLIENTCODE
		,CLIENTGROUPID
		,DRUGDISPFEEAPPLYTO
FROM src.Client
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ClientData
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,TYPECODE
		,SUBTYPE
		,SUBSEQ
		,NUMDATA
		,TEXTDATA
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.ClientData
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ClientInsurer
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,INSURERTYPE
		,EFFECTIVEDATE
		,INSURERSEQ
		,TERMINATIONDATE
FROM src.ClientInsurer
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Drugs
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,DRUGCODE
		,DRUGSDESCRIPTION
		,DISP
		,DRUGTYPE
		,CAT
		,UPDATEFLAG
		,UV
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.Drugs
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.EDIControl
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EDICONTROLSEQ
		,EDIMAPTOOLSITECODE
		,EDIPORTTYPE
		,EDIMAPTOOLID
		,NAME
		,LASTTAPEDATE
		,LASTSTARTDATE
		,LASTENDDATE
		,DAYCOUNTER
		,TOTALCOUNTER
		,VENDORNUM
		,VENDORCONTACT
		,VENDORPHONE
		,ACCOUNTNUM
		,OFFICENUM
		,EDISENDERQUALIFIER
		,EDISENDERIDENTIFIER
		,EDIRECEIVERQUALIFIER
		,EDIRECEIVERIDENTIFIER
		,EDIACKNOWLEDGEMENT
		,EDITESTINDICATOR
		,EXPORTCREDITS
		,EXPORTNEGATIVES
		,CREATEEORS
		,SPECIALPROCESSFLAG
		,ARCOMPANY
		,ARCONTACT
		,ARADDR1
		,ARADDR2
		,ARCITY
		,ARSTATE
		,ARZIP
		,ARPHONE
		,EDISENDERZIP
		,EDIRECEIVERZIP
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
		,PENDUSERGROUP
		,DAYBILLCOUNT
		,TOTALBILLCOUNT
		,EXPORTZEROALLOWBILLS
		,CREATENF10S
		,PRINTNF10IDENTIFIER
		,NF10FILEFORMAT
		,EORFILEFORMAT
		,PRINTEORIDENTIFIER
		,CREATEEORWITHNF10
		,EXCLUDEADJUSTER
		,EXCLUDEATTORNEY
		,EXCLUDEBRANCH
		,EXCLUDECLAIM
		,EXCLUDEINSURER
		,EXCLUDEPOLICY
		,DAYSPAST
		,EMAILNOTIFICATIONLIST
		,WFVALIDATIONFLAG
		,PRINTNF10PROVBILLINGADDR
		,BATCHACKSLA
		,DETAILACKSLA
		,EXPORTOTHERBILLINGPROVIDER
		,FORMATREVENUECODES
		,CREATEC8S
		,PRINTC8IDENTIFIER
		,CREATEEORWITHC8
		,NYPROVIDERC81
		,NYPROVIDERC84
		,NYPROVIDERC8IDENTIFIER
		,NYPROVIDERC8EOR
		,NYBOARDC81
		,NYBOARDC84
		,NYBOARDC8IDENTIFIER
		,NYBOARDC8EOR
		,NYCLAIMANTC81
		,NYCLAIMANTC8IDENTIFIER
		,NYCLAIMANTC8EOR
		,NYCLAIMANTC8EORCOVER
		,NYATTORNEYC81
		,NYATTORNEYC8IDENTIFIER
		,NYATTORNEYC8EOR
		,NYATTORNEYC8EORCOVER
		,NYPROVIDERFORMAT
		,NYBOARDFORMAT
		,NYCLAIMANTFORMAT
		,NYATTORNEYFORMAT
		,EXPORTPPOBILLCOMMENT
		,INCLUDENETWORK
		,INCLUDECLAIMUDF
		,INCLUDEPROVIDERUDF
		,INCLUDEBILLUDF
		,NETREEVALFEES
		,EXPORTCARCS
		,EXTENDEDHEADER
		,EXTENDEDTRAILER
		,SUBMISSIONREASONCODE
		,INCLUDEBILLATTACHMENT
		,USEEXTENDEDLAYOUT
		,EXCLUDEBILLATTACHMENT
		,EXPORTDIARYNOTES
		,UPDATEZABILLCONTROLTOACCEPTED
		,UPDATEZAPAIDDATETOPOSTDATE
		,SETZAPAIDDATETOPOSTDATEDAYS
		,INCLUDEADJUSTERUDF
		,INCLUDEPOLICYUDF
		,EXPORTZEROALLOWREEVALS
		,UPDATEREVALBILLCONTROLTOACCEPTED
		,UPDATEREVALPAIDDATETOPOSTDATE
		,SETREVALPAIDDATETOPOSTDATEDAYS
		,REDUCTIONSPEREORPROFILE
		,INCLUDEBILLIMAGE
		,NYCLAIMANTC84
		,NYATTORNEYC84
		,EDIJURISDICTION
FROM src.EDIControl
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.EDIMapTool
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SITECODE
		,EDIPORTTYPE
		,EDIMAPTOOLID
		,EDISOURCEID
		,EDIMAPTOOLNAME
		,EDIMAPTOOLTYPE
		,EDIMAPTOOLDESC
		,EDIOBJECTID
		,MENUTITLE
		,SECURITYLEVEL
		,EDIINPUTFILENAME
		,EDIOUTPUTFILENAME
		,EDIMULTIFILES
		,EDIREPORTTYPE
		,FORMPROPERTIES
		,JURISDICTION
		,EDITYPE
		,EDIPARTNERID
		,BILLCONTROLTABLECODE
		,EDICONTROLFLAG
		,BILLCONTROLSEQ
		,EDIOBJECTSITECODE
		,PERMITUNDEFINEDRECIDS
		,SELECTIONQUERY
		,REPORTSELECTIONQUERY
		,CLASS
		,LINESELECTIONQUERY
		,PORTPROPERTIES
		,EDIFILECONFIGSITECODE
		,EDIFILECONFIGSEQ
		,LZCONTROLTABLECODE
		,LZCONTROLSEQ
FROM src.EDIMapTool
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.EDIXmit
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EDIXMITSEQ
		,FILESPEC
		,FILELOCATION
		,RECOMMENDEDPAYMENT
		,USERID
		,XMITDATE
		,DATEFROM
		,DATETO
		,EDITYPE
		,EDIPARTNERID
		,DBVERSION
		,EDIMAPTOOLSITECODE
		,EDIPORTTYPE
		,EDIMAPTOOLID
		,TRANSMISSIONSTATUS
		,BATCHNUMBER
		,SENDERID
		,RECEIVERID
		,EXTERNALBATCHID
		,SARELATEDBATCHID
		,ACKNOTECODE
		,ACKNOTE
		,EXTERNALBATCHDATE
		,USERNOTES
		,RESUBMITDATE
		,RESUBMITUSERID
		,MODDATE
		,MODUSERID
FROM src.EDIXmit
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.EDIXmitBill
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EDIXMITBILLSEQ
		,EDIXMITSEQ
		,EDIHISTORYPROVIDERSEQ
		,EDIHISTORYCLAIMSEQ
		,EDIHISTORYINSURERSEQ
		,EDICONTROLSEQ
		,CLIENTCODE
		,BILLSEQ
		,JURISDICTION
		,TOB
		,UB92TOB
		,BILLSEQORGREV
		,TOTALCHARGE
		,BILLABLELINES
		,PAIDDATE
		,PAIDAMOUNT
		,DRG
		,PATIENTSTATUS
		,POSTDATE
		,DOCCTRLID
		,DOSFIRST
		,DOSLAST
		,PPONETWORKID
		,PPOCONTRACTID
		,ADJUSTER
		,CARRIERSEQNEW
		,PROVINVOICE
		,PROVSPECIALTY1
		,CLIENTTOB
		,SUBPRODUCTCODE
		,DUPCLIENTCODE
		,DUPBILLSEQ
		,CONSULTDATE
		,ADMITDATE
		,DISCHARGEDATE
		,SUBMITDATE
		,RCVDDATE
		,RCVDBRDATE
		,REVIEWDATE
		,DUEDATE
		,PMTAUTH
		,FORCEPAY
		,PROVLICENSENUM
		,CREATEUSERID
		,MODUSERID
		,PATIENTACCOUNT
		,REFPROVNAME
		,PROVTYPE
		,DOI
		,GEOSTATE
		,MANUALREDUCTIONMODE
		,PPONETWORKJURISDICTIONIND
		,PPONETWORKJURISDICTIONINSURERSEQ
		,WFQUEUEPARAMETER1
		,CHECKNUM
		,EXTERNALID
		,EDITESTINDICATOR
		,ICDVERSION
FROM src.EDIXmitBill
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.EntityType
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENTITYTYPEID
		,ENTITYTYPEKEY
		,DESCRIPTION
FROM src.EntityType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.FSProcedure
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTION
		,EXTENSION
		,PROCEDURECODE
		,FSPROCDESCRIPTION
		,SV
		,STAR
		,PANEL
		,IP
		,MULT
		,ASSTSURGEON
		,SECTIONFLAG
		,FUP
		,BAV
		,PROCGROUP
		,VIEWTYPE
		,UNITVALUE1
		,UNITVALUE2
		,UNITVALUE3
		,UNITVALUE4
		,UNITVALUE5
		,UNITVALUE6
		,UNITVALUE7
		,UNITVALUE8
		,UNITVALUE9
		,UNITVALUE10
		,UNITVALUE11
		,UNITVALUE12
		,PROUNITVALUE1
		,PROUNITVALUE2
		,PROUNITVALUE3
		,PROUNITVALUE4
		,PROUNITVALUE5
		,PROUNITVALUE6
		,PROUNITVALUE7
		,PROUNITVALUE8
		,PROUNITVALUE9
		,PROUNITVALUE10
		,PROUNITVALUE11
		,PROUNITVALUE12
		,TECHUNITVALUE1
		,TECHUNITVALUE2
		,TECHUNITVALUE3
		,TECHUNITVALUE4
		,TECHUNITVALUE5
		,TECHUNITVALUE6
		,TECHUNITVALUE7
		,TECHUNITVALUE8
		,TECHUNITVALUE9
		,TECHUNITVALUE10
		,TECHUNITVALUE11
		,TECHUNITVALUE12
		,SITECODE
FROM src.FSProcedure
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.FSProcedureMV
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTION
		,EXTENSION
		,PROCEDURECODE
		,EFFECTIVEDATE
		,TERMINATIONDATE
		,FSPROCDESCRIPTION
		,SV
		,STAR
		,PANEL
		,IP
		,MULT
		,ASSTSURGEON
		,SECTIONFLAG
		,FUP
		,BAV
		,PROCGROUP
		,VIEWTYPE
		,UNITVALUE
		,PROUNITVALUE
		,TECHUNITVALUE
		,SITECODE
FROM src.FSProcedureMV
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.FSServiceCode
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTION
		,SERVICECODE
		,GEOAREACODE
		,EFFECTIVEDATE
		,DESCRIPTION
		,TERMDATE
		,CODESOURCE
		,CODEGROUP
FROM src.FSServiceCode
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ICD_Diagnosis
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ICDDIAGNOSISID
		,CODE
		,SHORTDESC
		,DESCRIPTION
		,DETAILED
FROM src.ICD_Diagnosis
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Insurer
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,INSURERTYPE
		,INSURERSEQ
		,JURISDICTION
		,STATEID
		,TIN
		,ALTID
		,NAME
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
		,PHONENUM
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,FAXNUM
		,NAICCOCODE
		,NAICGPCODE
		,NCCICARRIERCODE
		,NCCIGROUPCODE
FROM src.Insurer
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Jurisdiction
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTIONID
		,NAME
		,POSTABLECODE
		,TOSTABLECODE
		,TOBTABLECODE
		,PROVTYPETABLECODE
		,HOSPITAL
		,PROVSPCLTABLECODE
		,DAYSTOPAY
		,DAYSTOPAYQUALIFY
		,OUTPATIENTFS
		,PROCFILEVER
		,ANESTUNIT
		,ANESTRNDUP
		,ANESTFORMAT
		,STATEMANDATESSN
		,ICDEDITION
		,ICD10COMPLIANCEDATE
		,EBILLSDAYSTOPAY
		,EBILLSDAYSTOPAYQUALIFY
		,DISPUTEDAYSTOPAY
		,DISPUTEDAYSTOPAYQUALIFY
FROM src.Jurisdiction
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Line
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINESEQ
		,DUPCLIENTCODE
		,DUPBILLSEQ
		,DOS
		,PROCTYPE
		,PPOOVERRIDE
		,CLIENTLINETYPE
		,PROVTYPE
		,URQTYALLOW
		,URQTYSVD
		,DOSTO
		,URALLOW
		,URCASESEQ
		,REVENUECODE
		,PROCBILLED
		,URREVIEWSEQ
		,URPRIORITY
		,PROCCODE
		,UNITS
		,ALLOWUNITS
		,CHARGE
		,BRALLOW
		,PPOALLOW
		,PAYOVERRIDE
		,PROCNEW
		,ADJALLOW
		,REEVALAMOUNT
		,POS
		,DXREFLIST
		,TOS
		,REEVALTXTPTR
		,FSAMOUNT
		,UCAMOUNT
		,COPAY
		,DEDUCTIBLE
		,COSTTOCHARGERATIO
		,RXNUMBER
		,DAYSSUPPLY
		,DXREF
		,EXTERNALID
		,ITEMCOSTINVOICED
		,ITEMCOSTADDITIONAL
		,REFILL
		,PROVSECONDARYID
		,CERTIFICATION
		,REEVALTXTSRC
		,BASISOFCOST
		,DMEFREQUENCYCODE
		,PROVRENDERINGNPI
		,PROVSECONDARYIDQUALIFIER
		,PAIDPROCCODE
		,PAIDPROCTYPE
		,URSTATUS
		,URWORKFLOWSTATUS
		,OVERRIDEALLOWUNITS
		,LINESEQORGREV
		,ODGFLAG
		,COMPOUNDDRUGINDICATOR
		,PRIORAUTHNUM
		,REEVALPARAGRAPHJURISDICTION
FROM src.Line
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.LineMod
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINESEQ
		,MODSEQ
		,USERENTERED
		,MODSITECODE
		,MODIFIER
		,REDUCTIONCODE
		,MODSUBSET
		,MODUSERID
		,MODDATE
		,REASONCLIENTCODE
		,REASONBILLSEQ
		,REASONLINESEQ
		,REASONTYPE
		,REASONVALUE
FROM src.LineMod
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.LineReduction
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINESEQ
		,REDUCTIONCODE
		,REDUCTIONAMOUNT
		,OVERRIDEAMOUNT
		,MODUSERID
FROM src.LineReduction
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.MedicareICQM
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTION
		,MDICQMSEQ
		,PROVIDERNUM
		,PROVSUFFIX
		,SERVICECODE
		,HCPCS
		,REVENUE
		,MEDICAREICQMDESCRIPTION
		,IP1995
		,OP1995
		,IP1996
		,OP1996
		,IP1997
		,OP1997
		,IP1998
		,OP1998
		,NPI
FROM src.MedicareICQM
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE  VIEW dbo.Medispan
AS

SELECT 
	 OdsPostingGroupAuditId
	,OdsCustomerId
	,OdsCreateDate
	,OdsSnapshotDate
	,OdsRowIsCurrent
	,OdsHashbytesValue
	,DmlOperation
	,NDC
	,DEA
	,Name1
	,Name2
	,Name3
	,Strength
	,Unit
	,Pkg
	,Factor
	,GenericDrug
	,Desicode
	,Rxotc
	,GPI
	,Awp1
	,Awp0
	,Awp2
	,EffectiveDt2
	,EffectiveDt1
	,EffectiveDt0
	,FDAEquivalence
	,NDCFormat
	,RestrictDrugs
	,GPPC
	,Status
	,UpdateDate
	,AAWP
	,GAWP
	,RepackagedCode
FROM src.Medispan
WHERE   OdsRowIsCurrent = 1
	AND DmlOperation <> 'D';



CREATE OR REPLACE VIEW dbo.Modifier
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTION
		,CODE
		,SITECODE
		,FUNC
		,VAL
		,MODTYPE
		,GROUPCODE
		,MODDESCRIPTION
		,MODCOMMENT1
		,MODCOMMENT2
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
		,STATUTE
		,REMARK1
		,REMARKQUALIFIER1
		,REMARK2
		,REMARKQUALIFIER2
		,REMARK3
		,REMARKQUALIFIER3
		,REMARK4
		,REMARKQUALIFIER4
		,CBREREASONID
FROM src.Modifier
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ODGData
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ICDDIAGNOSISID
		,PROCEDURECODE
		,ICDDESCRIPTION
		,PROCEDUREDESCRIPTION
		,INCIDENCERATE
		,PROCEDUREFREQUENCY
		,VISITS25PERC
		,VISITS50PERC
		,VISITS75PERC
		,VISITSMEAN
		,COSTSMEAN
		,AUTOAPPROVALCODE
		,PAYMENTFLAG
		,COSTPERVISIT
FROM src.ODGData
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Pend
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,PENDSEQ
		,PENDDATE
		,RELEASEFLAG
		,PENDTOID
		,PRIORITY
		,RELEASEDATE
		,REASONCODE
		,PENDBYUSERID
		,RELEASEBYUSERID
		,AUTOPENDFLAG
		,RULEID
		,WFTASKSEQ
		,RELEASEDBYEXTERNALUSERNAME
FROM src.Pend
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PendComment
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,PENDSEQ
		,PENDCOMMENTSEQ
		,PENDCOMMENT
		,CREATEUSERID
		,CREATEDATE
		,CREATEDBYEXTERNALUSERNAME
FROM src.PendComment
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Policy
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,POLICYSEQ
		,NAME
		,EXTERNALID
		,POLICYID
		,ADMINKEY
		,LOCATIONCODE
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
		,PHONENUM
		,FAXNUM
		,EFFECTIVEDATE
		,TERMINATIONDATE
		,TIN
		,STATETAXID
		,DEPTINDUSRELNUM
		,EQOPPINDICATOR
		,MODUSERID
		,MODDATE
		,MCOFLAG
		,MCOSTARTDATE
		,FEERATECTRLEX
		,CREATEBY
		,FEERATECTRLIN
		,CREATEDATE
		,SELFINSURED
		,NAICSCODE
		,MONTHLYPREMIUM
		,PPOPROFILESITECODE
		,PPOPROFILEID
		,SALESTAXEXEMPT
		,RECEIPTHANDLINGCODE
		,TXNONSUBSCRIB
		,SUBDIVISIONNAME
		,POLICYCOPAYAMOUNT
		,POLICYCOPAYPCT
		,POLICYDEDUCTIBLE
		,POLICYLIMITAMOUNT
		,POLICYTIMELIMIT
		,POLICYLIMITWARNINGPCT
		,POLICYLIMITRESULT
		,URPROFILEID
FROM src.Policy
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PolicyInsurer
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,POLICYSEQ
		,JURISDICTION
		,INSURERTYPE
		,EFFECTIVEDATE
		,INSURERSEQ
		,TERMINATIONDATE
FROM src.PolicyInsurer
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PPOContract
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPONETWORKID
		,PPOCONTRACTID
		,SITECODE
		,TIN
		,ALTERNATETIN
		,STARTDATE
		,ENDDATE
		,OPLINEITEMDEFAULTDISCOUNT
		,COMPANYNAME
		,FIRST
		,GROUPCODE
		,GROUPNAME
		,OPDISCOUNTBASEVALUE
		,OPOFFFS
		,OPOFFUCR
		,OPOFFCHARGE
		,OPEFFECTIVEDATE
		,OPADDITIONALDISCOUNTOFFLINK
		,OPTERMINATIONDATE
		,OPUCRPERCENTILE
		,OPCONDITION
		,IPDISCOUNTBASEVALUE
		,IPOFFFS
		,IPOFFUCR
		,IPOFFCHARGE
		,IPEFFECTIVEDATE
		,IPTERMINATIONDATE
		,IPCONDITION
		,IPSTOPCAPAMOUNT
		,IPSTOPCAPRATE
		,MINDISC
		,MAXDISC
		,MEDICALPERDIEM
		,SURGICALPERDIEM
		,ICUPERDIEM
		,PSYCHIATRICPERDIEM
		,MISCPARM
		,SPCCODE
		,PPOTYPE
		,BILLINGADDRESS1
		,BILLINGADDRESS2
		,BILLINGCITY
		,BILLINGSTATE
		,BILLINGZIP
		,PRACTICEADDRESS1
		,PRACTICEADDRESS2
		,PRACTICECITY
		,PRACTICESTATE
		,PRACTICEZIP
		,PHONENUM
		,OUTFILE
		,INPATFILE
		,URCOORDINATORFLAG
		,EXCLUSIVEPPOORGFLAG
		,STOPLOSSTYPECODE
		,BR_RNEDISCOUNT
		,MODDATE
		,EXPORTFLAG
		,OPMANUALINDICATOR
		,OPSTOPCAPAMOUNT
		,OPSTOPCAPRATE
		,SPECIALTY1
		,SPECIALTY2
		,LESSOROFTHRESHOLD
		,BILATERALDISCOUNT
		,SURGERYDISCOUNT2
		,SURGERYDISCOUNT3
		,SURGERYDISCOUNT4
		,SURGERYDISCOUNT5
		,MATRIX
		,PROVTYPE
		,ALLINCLUSIVE
		,REGION
		,PAYMENTADDRESSFLAG
		,MEDICALGROUP
		,MEDICALGROUPCODE
		,RATEMODE
		,PRACTICECOUNTY
		,FIPSCOUNTYCODE
		,PRIMARYCAREFLAG
		,PPOCONTRACTIDOLD
		,MULTISURG
		,BILEVEL
		,DRGRATE
		,DRGGREATERTHANBC
		,DRGMINPERCENTBC
		,CARVEOUT
		,PPOTOFSSEQ
		,LICENSENUM
		,MEDICARENUM
		,NPI
FROM src.PPOContract
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PPONetwork
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPONETWORKID
		,NAME
		,TIN
		,ZIP
		,STATE
		,CITY
		,STREET
		,PHONENUM
		,PPONETWORKCOMMENT
		,ALLOWMAINT
		,REQEXTPPO
		,DEMORATES
		,PRINTASPROVIDER
		,PPOTYPE
		,PPOVERSION
		,PPOBRIDGEEXISTS
		,USESDRG
		,PPOTOOTHER
		,SUBNETWORKINDICATOR
		,EMAILADDRESS
		,WEBSITE
		,BILLCONTROLSEQ
FROM src.PPONetwork
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PPOProfile
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SITECODE
		,PPOPROFILEID
		,PROFILEDESC
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
		,SMARTSEARCHPAGEMAX
		,JURISDICTIONSTACKEXCLUSIVE
		,REEVALFULLSTACKWHENORIGALLOWNOHIT
FROM src.PPOProfile
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PPOProfileHistory
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPOPROFILEHISTORYSEQ
		,RECORDDELETED
		,LOGDATETIME
		,LOGINAME
		,SITECODE
		,PPOPROFILEID
		,PROFILEDESC
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
		,SMARTSEARCHPAGEMAX
		,JURISDICTIONSTACKEXCLUSIVE
		,REEVALFULLSTACKWHENORIGALLOWNOHIT
FROM src.PPOProfileHistory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PPOProfileNetworks
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPOPROFILESITECODE
		,PPOPROFILEID
		,PROFILEREGIONSITECODE
		,PROFILEREGIONID
		,NETWORKORDER
		,PPONETWORKID
		,SEARCHLOGIC
		,VERIFICATION
		,EFFECTIVEDATE
		,TERMINATIONDATE
		,JURISDICTIONIND
		,JURISDICTIONINSURERSEQ
		,JURISDICTIONUSEONLY
		,PPOSSTINREQ
		,PPOSSLICREQ
		,DEFAULTEXTENDEDSEARCHES
		,DEFAULTEXTENDEDFILTERS
		,SEVEREDTIES
		,POS
FROM src.PPOProfileNetworks
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PPOProfileNetworksHistory
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPOPROFILENETWORKSHISTORYSEQ
		,RECORDDELETED
		,LOGDATETIME
		,LOGINAME
		,PPOPROFILESITECODE
		,PPOPROFILEID
		,PROFILEREGIONSITECODE
		,PROFILEREGIONID
		,NETWORKORDER
		,PPONETWORKID
		,SEARCHLOGIC
		,VERIFICATION
		,EFFECTIVEDATE
		,TERMINATIONDATE
		,JURISDICTIONIND
		,JURISDICTIONINSURERSEQ
		,JURISDICTIONUSEONLY
		,PPOSSTINREQ
		,PPOSSLICREQ
		,DEFAULTEXTENDEDSEARCHES
		,DEFAULTEXTENDEDFILTERS
		,SEVEREDTIES
		,POS
FROM src.PPOProfileNetworksHistory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PPORateType
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,RATETYPECODE
		,PPONETWORKID
		,CATEGORY
		,PRIORITY
		,VBCOLOR
		,RATETYPEDESCRIPTION
		,EXPLANATION
FROM src.PPORateType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.PPOSubNetwork
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPONETWORKID
		,GROUPCODE
		,GROUPNAME
		,EXTERNALID
		,SITECODE
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
		,STREET1
		,STREET2
		,CITY
		,STATE
		,ZIP
		,PHONENUM
		,EMAILADDRESS
		,WEBSITE
		,TIN
		,COMMENT
FROM src.PPOSubNetwork
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProfileRegion
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SITECODE
		,PROFILEREGIONID
		,REGIONTYPECODE
		,REGIONNAME
FROM src.ProfileRegion
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProfileRegionDetail
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROFILEREGIONSITECODE
		,PROFILEREGIONID
		,ZIPCODEFROM
		,ZIPCODETO
FROM src.ProfileRegionDetail
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Provider
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERSUBSET
		,PROVIDERSEQ
		,TIN
		,TINSUFFIX
		,EXTERNALID
		,NAME
		,GROUPCODE
		,LICENSENUM
		,MEDICARENUM
		,PRACTICEADDRESSSEQ
		,BILLINGADDRESSSEQ
		,HOSPITALSEQ
		,PROVTYPE
		,SPECIALTY1
		,SPECIALTY2
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,STATUS
		,EXTERNALSTATUS
		,EXPORTDATE
		,SSNTININDICATOR
		,PMTDAYS
		,AUTHBEGINDATE
		,AUTHENDDATE
		,TAXADDRESSSEQ
		,CTRLNUM1099
		,SURCHARGECODE
		,WORKCOMPNUM
		,WORKCOMPSTATE
		,NCPDPID
		,ENTITYTYPE
		,LASTNAME
		,FIRSTNAME
		,MIDDLENAME
		,SUFFIX
		,NPI
		,FACILITYNPI
		,VERIFICATIONGROUPID
FROM src.Provider
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderAddress
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERSUBSET
		,PROVIDERADDRESSSEQ
		,RECTYPE
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
		,PHONENUM
		,FAXNUM
		,CONTACTFIRSTNAME
		,CONTACTLASTNAME
		,CONTACTMIDDLEINITIAL
		,URFIRSTNAME
		,URLASTNAME
		,URMIDDLEINITIAL
		,FACILITYNAME
		,COUNTRYCODE
		,MAILCODE
FROM src.ProviderAddress
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderCluster
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERSUBSET
		,PROVIDERSEQ
		,ORGODSCUSTOMERID
		,MITCHELLPROVIDERKEY
		,PROVIDERCLUSTERKEY
		,PROVIDERTYPE
FROM src.ProviderCluster
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderSpecialty
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ID
		,DESCRIPTION
		,IMPLEMENTATIONDATE
		,DEACTIVATIONDATE
		,DATASOURCE
		,CREATOR
		,CREATEDATE
		,LASTUPDATER
		,LASTUPDATEDATE
		,CBRCODE
FROM src.ProviderSpecialty
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ProviderSys
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERSUBSET
		,PROVIDERSUBSETDESC
		,PROVIDERACCESS
		,TAXADDRREQUIRED
		,ALLOWDUMMYPROVIDERS
		,CASCADEUPDATESONIMPORT
		,ROOTEXTIDOVERRIDEDELIMITER
FROM src.ProviderSys
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ReductionType
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REDUCTIONCODE
		,REDUCTIONDESCRIPTION
		,BEOVERRIDE
		,BEMSG
		,ABBREVIATION
		,DEFAULTMESSAGECODE
		,DEFAULTDENIALMESSAGECODE
FROM src.ReductionType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.Region
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTION
		,EXTENSION
		,ENDZIP
		,BEG
		,REGION
		,REGIONDESCRIPTION
FROM src.Region
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.ServiceCodeGroup
AS

SELECT 
	 OdsPostingGroupAuditId
	,OdsCustomerId
	,OdsCreateDate
	,OdsSnapshotDate
	,OdsRowIsCurrent
	,OdsHashbytesValue
	,DmlOperation
	,SiteCode
	,GroupType
	,Family
	,Revision
	,GroupCode
	,CodeOrder
	,ServiceCode
	,ServiceCodeType
	,LinkGroupType
	,LinkGroupFamily
	,CodeLevel
	,GlobalPriority
	,Active
	,Comment
	,CustomParameters
	,CreateDate
	,CreateUserID
	,ModDate
	,ModUserID
FROM src.ServiceCodeGroup
WHERE   OdsRowIsCurrent = 1
	AND DmlOperation <> 'D';


CREATE OR REPLACE VIEW dbo.TableLookUp
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,TABLECODE
		,TYPECODE
		,CODE
		,SITECODE
		,OLDCODE
		,SHORTDESC
		,SOURCE
		,PRIORITY
		,LONGDESC
		,OWNERAPP
		,RECORDSTATUS
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.TableLookUp
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.UserInfo
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,USERID
		,USERPASSWORD
		,NAME
		,SECURITYLEVEL
		,ENABLEADJUSTERMENU
		,ENABLEPROVADDS
		,ALLOWPOSTING
		,ENABLECLAIMADDS
		,ENABLEPOLICYADDS
		,ENABLEINVOICECREDITVOID
		,ENABLEREEVALUATIONS
		,ENABLEPPOACCESS
		,ENABLEURCOMMENTVIEW
		,ENABLEPENDRELEASE
		,ENABLEXTABLEUPDATE
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,ENABLEPPOFASTMATCHADDS
		,EXTERNALID
		,EMAILADDRESS
		,EMAILNOTIFY
		,ACTIVESTATUS
		,COMPANYSEQ
		,NETWORKLOGIN
		,AUTOMATICNETWORKLOGIN
		,LASTLOGGEDINDATE
		,PROMPTTOCREATEMCC
		,ACCESSALLWORKQUEUES
		,LANDINGZONEACCESS
		,REVIEWLEVEL
		,ENABLEUSERMAINTENANCE
		,ENABLEHISTORYMAINTENANCE
		,ENABLECLIENTMAINTENANCE
		,FEEACCESS
		,ENABLESALESTAXMAINTENANCE
		,BESALESTAXZIPCODEACCESS
		,INVOICEGENACCESS
		,BEPERMITALLOWOVER
		,PERMITREREVIEWS
		,EDITBILLCONTROL
		,RESTRICTEORNOTES
		,UWQAUTONEXTBILL
		,UWQDISABLEOPTIONS
		,UWQDISABLERULES
		,PERMITCHECKREISSUE
		,ENABLEEDIAUTOMATIONMAINTENANCE
		,RESTRICTDIARYNOTES
		,RESTRICTEXTERNALDIARYNOTES
		,BEDEFERMANUALMODEMSG
		,USERROLEID
		,ERASEBILLTEMPHISTORY
		,EDITPPOPROFILE
		,ENABLEURACCESS
		,CAPSTONECONFIGURATIONACCESS
		,PERMITUDFDEFINITION
		,ENABLEPPOPROFILEEDIT
		,ENABLESUPERVISORROLE
FROM src.UserInfo
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.WFlow
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,WFLOWSEQ
		,DESCRIPTION
		,RECORDSTATUS
		,ENTITYTYPECODE
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,INITIALTASKSEQ
		,PAUSETASKSEQ
FROM src.WFlow
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.WFQueue
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENTITYTYPECODE
		,ENTITYSUBSET
		,ENTITYSEQ
		,WFTASKSEQ
		,PRIORWFTASKSEQ
		,STATUS
		,PRIORITY
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,TASKMESSAGE
		,PARAMETER1
		,CONTEXTID
		,PRIORSTATUS
FROM src.WFQueue
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.WFTask
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,WFTASKSEQ
		,WFLOWSEQ
		,WFTASKREGISTRYSEQ
		,NAME
		,PARAMETER1
		,RECORDSTATUS
		,NODELEFT
		,NODETOP
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,NOPRIOR
		,NORESTART
		,PARAMETERX
		,DEFAULTPENDGROUP
		,CONFIGURATION
FROM src.WFTask
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.WFTaskLink
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,FROMTASKSEQ
		,LINKWHEN
		,TOTASKSEQ
FROM src.WFTaskLink
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


CREATE OR REPLACE VIEW dbo.WFTaskRegistry
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,WFTASKREGISTRYSEQ
		,ENTITYTYPECODE
		,DESCRIPTION
		,ACTION
		,SMALLIMAGERESID
		,LARGEIMAGERESID
		,PERSISTBEFORE
		,NACTION
FROM src.WFTaskRegistry
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


