CREATE OR REPLACE TASK ADM.TASK_ETL_LOG_ERRORS
  WAREHOUSE = &DWSIZE
  SCHEDULE = 'USING CRON 10,20,30,40,50 18-22 * * * America/Los_Angeles'
AS
CALL ADM.ETL_LOG_ERRORS ('ETL_Snowflake_Ods_Load','ADM','TASK_ETL_LOG_ERRORS','ADM','false');
