 CREATE OR REPLACE FILE FORMAT ADM.FORMAT_FILE_DEL_TAB
 COMPRESSION = 'GZIP' 
 FIELD_DELIMITER = '\t' 
 RECORD_DELIMITER = '\n' 
 SKIP_HEADER = 0 
 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' 
 TRIM_SPACE = FALSE 
 ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
 ESCAPE = 'NONE' 
 ESCAPE_UNENCLOSED_FIELD = '\134' 
 DATE_FORMAT = 'AUTO' 
 TIMESTAMP_FORMAT = 'AUTO' 
 NULL_IF = ('', 'NULL', '\\N', '\x00');
 
 