CREATE OR REPLACE VIEW dbo.BillControl
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLCONTROLSEQ
		,MODDATE
		,CREATEDATE
		,CONTROL
		,EXTERNALID
		,BATCHNUMBER
		,MODUSERID
		,EXTERNALID2
		,MESSAGE
FROM src.BillControl
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


