CREATE OR REPLACE VIEW dbo.Provider
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERSUBSET
		,PROVIDERSEQ
		,TIN
		,TINSUFFIX
		,EXTERNALID
		,NAME
		,GROUPCODE
		,LICENSENUM
		,MEDICARENUM
		,PRACTICEADDRESSSEQ
		,BILLINGADDRESSSEQ
		,HOSPITALSEQ
		,PROVTYPE
		,SPECIALTY1
		,SPECIALTY2
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,STATUS
		,EXTERNALSTATUS
		,EXPORTDATE
		,SSNTININDICATOR
		,PMTDAYS
		,AUTHBEGINDATE
		,AUTHENDDATE
		,TAXADDRESSSEQ
		,CTRLNUM1099
		,SURCHARGECODE
		,WORKCOMPNUM
		,WORKCOMPSTATE
		,NCPDPID
		,ENTITYTYPE
		,LASTNAME
		,FIRSTNAME
		,MIDDLENAME
		,SUFFIX
		,NPI
		,FACILITYNPI
		,VERIFICATIONGROUPID
FROM src.Provider
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


