CREATE OR REPLACE VIEW dbo.Line
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINESEQ
		,DUPCLIENTCODE
		,DUPBILLSEQ
		,DOS
		,PROCTYPE
		,PPOOVERRIDE
		,CLIENTLINETYPE
		,PROVTYPE
		,URQTYALLOW
		,URQTYSVD
		,DOSTO
		,URALLOW
		,URCASESEQ
		,REVENUECODE
		,PROCBILLED
		,URREVIEWSEQ
		,URPRIORITY
		,PROCCODE
		,UNITS
		,ALLOWUNITS
		,CHARGE
		,BRALLOW
		,PPOALLOW
		,PAYOVERRIDE
		,PROCNEW
		,ADJALLOW
		,REEVALAMOUNT
		,POS
		,DXREFLIST
		,TOS
		,REEVALTXTPTR
		,FSAMOUNT
		,UCAMOUNT
		,COPAY
		,DEDUCTIBLE
		,COSTTOCHARGERATIO
		,RXNUMBER
		,DAYSSUPPLY
		,DXREF
		,EXTERNALID
		,ITEMCOSTINVOICED
		,ITEMCOSTADDITIONAL
		,REFILL
		,PROVSECONDARYID
		,CERTIFICATION
		,REEVALTXTSRC
		,BASISOFCOST
		,DMEFREQUENCYCODE
		,PROVRENDERINGNPI
		,PROVSECONDARYIDQUALIFIER
		,PAIDPROCCODE
		,PAIDPROCTYPE
		,URSTATUS
		,URWORKFLOWSTATUS
		,OVERRIDEALLOWUNITS
		,LINESEQORGREV
		,ODGFLAG
		,COMPOUNDDRUGINDICATOR
		,PRIORAUTHNUM
		,REEVALPARAGRAPHJURISDICTION
FROM src.Line
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


