CREATE OR REPLACE VIEW dbo.Policy
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,POLICYSEQ
		,NAME
		,EXTERNALID
		,POLICYID
		,ADMINKEY
		,LOCATIONCODE
		,ADDRESS1
		,ADDRESS2
		,CITY
		,STATE
		,ZIP
		,PHONENUM
		,FAXNUM
		,EFFECTIVEDATE
		,TERMINATIONDATE
		,TIN
		,STATETAXID
		,DEPTINDUSRELNUM
		,EQOPPINDICATOR
		,MODUSERID
		,MODDATE
		,MCOFLAG
		,MCOSTARTDATE
		,FEERATECTRLEX
		,CREATEBY
		,FEERATECTRLIN
		,CREATEDATE
		,SELFINSURED
		,NAICSCODE
		,MONTHLYPREMIUM
		,PPOPROFILESITECODE
		,PPOPROFILEID
		,SALESTAXEXEMPT
		,RECEIPTHANDLINGCODE
		,TXNONSUBSCRIB
		,SUBDIVISIONNAME
		,POLICYCOPAYAMOUNT
		,POLICYCOPAYPCT
		,POLICYDEDUCTIBLE
		,POLICYLIMITAMOUNT
		,POLICYTIMELIMIT
		,POLICYLIMITWARNINGPCT
		,POLICYLIMITRESULT
		,URPROFILEID
FROM src.Policy
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


