CREATE OR REPLACE VIEW dbo.AdjusterPendGroup
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,ADJUSTER
		,PENDGROUPCODE
FROM src.AdjusterPendGroup
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


