CREATE OR REPLACE VIEW dbo.PolicyInsurer
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,POLICYSEQ
		,JURISDICTION
		,INSURERTYPE
		,EFFECTIVEDATE
		,INSURERSEQ
		,TERMINATIONDATE
FROM src.PolicyInsurer
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


