CREATE OR REPLACE VIEW dbo.FSProcedure
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTION
		,EXTENSION
		,PROCEDURECODE
		,FSPROCDESCRIPTION
		,SV
		,STAR
		,PANEL
		,IP
		,MULT
		,ASSTSURGEON
		,SECTIONFLAG
		,FUP
		,BAV
		,PROCGROUP
		,VIEWTYPE
		,UNITVALUE1
		,UNITVALUE2
		,UNITVALUE3
		,UNITVALUE4
		,UNITVALUE5
		,UNITVALUE6
		,UNITVALUE7
		,UNITVALUE8
		,UNITVALUE9
		,UNITVALUE10
		,UNITVALUE11
		,UNITVALUE12
		,PROUNITVALUE1
		,PROUNITVALUE2
		,PROUNITVALUE3
		,PROUNITVALUE4
		,PROUNITVALUE5
		,PROUNITVALUE6
		,PROUNITVALUE7
		,PROUNITVALUE8
		,PROUNITVALUE9
		,PROUNITVALUE10
		,PROUNITVALUE11
		,PROUNITVALUE12
		,TECHUNITVALUE1
		,TECHUNITVALUE2
		,TECHUNITVALUE3
		,TECHUNITVALUE4
		,TECHUNITVALUE5
		,TECHUNITVALUE6
		,TECHUNITVALUE7
		,TECHUNITVALUE8
		,TECHUNITVALUE9
		,TECHUNITVALUE10
		,TECHUNITVALUE11
		,TECHUNITVALUE12
		,SITECODE
FROM src.FSProcedure
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


