CREATE OR REPLACE VIEW dbo.ICD_Diagnosis
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ICDDIAGNOSISID
		,CODE
		,SHORTDESC
		,DESCRIPTION
		,DETAILED
FROM src.ICD_Diagnosis
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


