CREATE OR REPLACE VIEW dbo.ProviderCluster
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERSUBSET
		,PROVIDERSEQ
		,ORGODSCUSTOMERID
		,MITCHELLPROVIDERKEY
		,PROVIDERCLUSTERKEY
		,PROVIDERTYPE
FROM src.ProviderCluster
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


