CREATE OR REPLACE VIEW dbo.BillICDProcedure
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLPROCEDURESEQ
		,ICDPROCEDUREID
		,CODEDATE
		,BILLEDICDPROCEDURE
		,ICDBILLUSAGETYPEID
FROM src.BillICDProcedure
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


