CREATE OR REPLACE VIEW dbo.WFTaskLink
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,FROMTASKSEQ
		,LINKWHEN
		,TOTASKSEQ
FROM src.WFTaskLink
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


