CREATE OR REPLACE VIEW dbo.Jurisdiction
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,JURISDICTIONID
		,NAME
		,POSTABLECODE
		,TOSTABLECODE
		,TOBTABLECODE
		,PROVTYPETABLECODE
		,HOSPITAL
		,PROVSPCLTABLECODE
		,DAYSTOPAY
		,DAYSTOPAYQUALIFY
		,OUTPATIENTFS
		,PROCFILEVER
		,ANESTUNIT
		,ANESTRNDUP
		,ANESTFORMAT
		,STATEMANDATESSN
		,ICDEDITION
		,ICD10COMPLIANCEDATE
		,EBILLSDAYSTOPAY
		,EBILLSDAYSTOPAYQUALIFY
		,DISPUTEDAYSTOPAY
		,DISPUTEDAYSTOPAYQUALIFY
FROM src.Jurisdiction
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


