CREATE OR REPLACE VIEW dbo.WFQueue
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENTITYTYPECODE
		,ENTITYSUBSET
		,ENTITYSEQ
		,WFTASKSEQ
		,PRIORWFTASKSEQ
		,STATUS
		,PRIORITY
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,TASKMESSAGE
		,PARAMETER1
		,CONTEXTID
		,PRIORSTATUS
FROM src.WFQueue
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


