CREATE OR REPLACE VIEW dbo.LineMod
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINESEQ
		,MODSEQ
		,USERENTERED
		,MODSITECODE
		,MODIFIER
		,REDUCTIONCODE
		,MODSUBSET
		,MODUSERID
		,MODDATE
		,REASONCLIENTCODE
		,REASONBILLSEQ
		,REASONLINESEQ
		,REASONTYPE
		,REASONVALUE
FROM src.LineMod
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


