CREATE OR REPLACE VIEW dbo.BRERuleCategory
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BRERULECATEGORYID
		,CATEGORYDESCRIPTION
FROM src.BRERuleCategory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


