CREATE OR REPLACE VIEW dbo.BillFee
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,FEETYPE
		,TRANSACTIONTYPE
		,FEECTRLSOURCE
		,FEECONTROLSEQ
		,FEEAMOUNT
		,INVOICESEQ
		,INVOICESUBSEQ
		,PPONETWORKID
		,REDUCTIONCODE
		,FEEOVERRIDE
		,OVERRIDEVERIFIED
		,EXCLUSIVEFEE
		,FEESOURCEID
		,HANDLINGFEE
FROM src.BillFee
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


