CREATE OR REPLACE VIEW dbo.ClientInsurer
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,INSURERTYPE
		,EFFECTIVEDATE
		,INSURERSEQ
		,TERMINATIONDATE
FROM src.ClientInsurer
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


