CREATE OR REPLACE VIEW dbo.PPOProfile
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SITECODE
		,PPOPROFILEID
		,PROFILEDESC
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
		,SMARTSEARCHPAGEMAX
		,JURISDICTIONSTACKEXCLUSIVE
		,REEVALFULLSTACKWHENORIGALLOWNOHIT
FROM src.PPOProfile
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


