CREATE OR REPLACE VIEW dbo.PPONetwork
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPONETWORKID
		,NAME
		,TIN
		,ZIP
		,STATE
		,CITY
		,STREET
		,PHONENUM
		,PPONETWORKCOMMENT
		,ALLOWMAINT
		,REQEXTPPO
		,DEMORATES
		,PRINTASPROVIDER
		,PPOTYPE
		,PPOVERSION
		,PPOBRIDGEEXISTS
		,USESDRG
		,PPOTOOTHER
		,SUBNETWORKINDICATOR
		,EMAILADDRESS
		,WEBSITE
		,BILLCONTROLSEQ
FROM src.PPONetwork
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


