CREATE OR REPLACE VIEW dbo.BillPPORate
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINKNAME
		,RATETYPE
		,APPLIED
FROM src.BillPPORate
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


