CREATE OR REPLACE VIEW dbo.UserInfo
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,USERID
		,USERPASSWORD
		,NAME
		,SECURITYLEVEL
		,ENABLEADJUSTERMENU
		,ENABLEPROVADDS
		,ALLOWPOSTING
		,ENABLECLAIMADDS
		,ENABLEPOLICYADDS
		,ENABLEINVOICECREDITVOID
		,ENABLEREEVALUATIONS
		,ENABLEPPOACCESS
		,ENABLEURCOMMENTVIEW
		,ENABLEPENDRELEASE
		,ENABLEXTABLEUPDATE
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,ENABLEPPOFASTMATCHADDS
		,EXTERNALID
		,EMAILADDRESS
		,EMAILNOTIFY
		,ACTIVESTATUS
		,COMPANYSEQ
		,NETWORKLOGIN
		,AUTOMATICNETWORKLOGIN
		,LASTLOGGEDINDATE
		,PROMPTTOCREATEMCC
		,ACCESSALLWORKQUEUES
		,LANDINGZONEACCESS
		,REVIEWLEVEL
		,ENABLEUSERMAINTENANCE
		,ENABLEHISTORYMAINTENANCE
		,ENABLECLIENTMAINTENANCE
		,FEEACCESS
		,ENABLESALESTAXMAINTENANCE
		,BESALESTAXZIPCODEACCESS
		,INVOICEGENACCESS
		,BEPERMITALLOWOVER
		,PERMITREREVIEWS
		,EDITBILLCONTROL
		,RESTRICTEORNOTES
		,UWQAUTONEXTBILL
		,UWQDISABLEOPTIONS
		,UWQDISABLERULES
		,PERMITCHECKREISSUE
		,ENABLEEDIAUTOMATIONMAINTENANCE
		,RESTRICTDIARYNOTES
		,RESTRICTEXTERNALDIARYNOTES
		,BEDEFERMANUALMODEMSG
		,USERROLEID
		,ERASEBILLTEMPHISTORY
		,EDITPPOPROFILE
		,ENABLEURACCESS
		,CAPSTONECONFIGURATIONACCESS
		,PERMITUDFDEFINITION
		,ENABLEPPOPROFILEEDIT
		,ENABLESUPERVISORROLE
FROM src.UserInfo
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


