CREATE OR REPLACE VIEW dbo.ProfileRegion
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,SITECODE
		,PROFILEREGIONID
		,REGIONTYPECODE
		,REGIONNAME
FROM src.ProfileRegion
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


