CREATE OR REPLACE VIEW dbo.WFTask
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,WFTASKSEQ
		,WFLOWSEQ
		,WFTASKREGISTRYSEQ
		,NAME
		,PARAMETER1
		,RECORDSTATUS
		,NODELEFT
		,NODETOP
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,NOPRIOR
		,NORESTART
		,PARAMETERX
		,DEFAULTPENDGROUP
		,CONFIGURATION
FROM src.WFTask
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


