CREATE OR REPLACE VIEW dbo.BillReevalReason
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLREEVALREASONCODE
		,SITECODE
		,BILLREEVALREASONCATEGORYSEQ
		,SHORTDESCRIPTION
		,LONGDESCRIPTION
		,ACTIVE
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.BillReevalReason
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


