CREATE OR REPLACE VIEW dbo.EDIXmitBill
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EDIXMITBILLSEQ
		,EDIXMITSEQ
		,EDIHISTORYPROVIDERSEQ
		,EDIHISTORYCLAIMSEQ
		,EDIHISTORYINSURERSEQ
		,EDICONTROLSEQ
		,CLIENTCODE
		,BILLSEQ
		,JURISDICTION
		,TOB
		,UB92TOB
		,BILLSEQORGREV
		,TOTALCHARGE
		,BILLABLELINES
		,PAIDDATE
		,PAIDAMOUNT
		,DRG
		,PATIENTSTATUS
		,POSTDATE
		,DOCCTRLID
		,DOSFIRST
		,DOSLAST
		,PPONETWORKID
		,PPOCONTRACTID
		,ADJUSTER
		,CARRIERSEQNEW
		,PROVINVOICE
		,PROVSPECIALTY1
		,CLIENTTOB
		,SUBPRODUCTCODE
		,DUPCLIENTCODE
		,DUPBILLSEQ
		,CONSULTDATE
		,ADMITDATE
		,DISCHARGEDATE
		,SUBMITDATE
		,RCVDDATE
		,RCVDBRDATE
		,REVIEWDATE
		,DUEDATE
		,PMTAUTH
		,FORCEPAY
		,PROVLICENSENUM
		,CREATEUSERID
		,MODUSERID
		,PATIENTACCOUNT
		,REFPROVNAME
		,PROVTYPE
		,DOI
		,GEOSTATE
		,MANUALREDUCTIONMODE
		,PPONETWORKJURISDICTIONIND
		,PPONETWORKJURISDICTIONINSURERSEQ
		,WFQUEUEPARAMETER1
		,CHECKNUM
		,EXTERNALID
		,EDITESTINDICATOR
		,ICDVERSION
FROM src.EDIXmitBill
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


