CREATE OR REPLACE VIEW dbo.LineReduction
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINESEQ
		,REDUCTIONCODE
		,REDUCTIONAMOUNT
		,OVERRIDEAMOUNT
		,MODUSERID
FROM src.LineReduction
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


