CREATE OR REPLACE VIEW dbo.BillRuleFire
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,LINESEQ
		,RULEID
		,RULETYPE
		,DATERULEFIRED
		,VALIDATED
		,VALIDATEDUSERID
		,DATEVALIDATED
		,PENDTOID
		,RULESEVERITY
		,WFTASKSEQ
		,CHILDTARGETSUBSET
		,CHILDTARGETSEQ
		,CAPSTONERULEID
FROM src.BillRuleFire
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


