CREATE OR REPLACE VIEW dbo.EntityType
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ENTITYTYPEID
		,ENTITYTYPEKEY
		,DESCRIPTION
FROM src.EntityType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


