CREATE OR REPLACE VIEW dbo.ReductionType
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,REDUCTIONCODE
		,REDUCTIONDESCRIPTION
		,BEOVERRIDE
		,BEMSG
		,ABBREVIATION
		,DEFAULTMESSAGECODE
		,DEFAULTDENIALMESSAGECODE
FROM src.ReductionType
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


