CREATE OR REPLACE VIEW dbo.ProviderSys
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PROVIDERSUBSET
		,PROVIDERSUBSETDESC
		,PROVIDERACCESS
		,TAXADDRREQUIRED
		,ALLOWDUMMYPROVIDERS
		,CASCADEUPDATESONIMPORT
		,ROOTEXTIDOVERRIDEDELIMITER
FROM src.ProviderSys
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


