CREATE OR REPLACE VIEW dbo.BillICDDiagnosis
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLDIAGNOSISSEQ
		,ICDDIAGNOSISID
		,POA
		,BILLEDICDDIAGNOSIS
		,ICDBILLUSAGETYPEID
FROM src.BillICDDiagnosis
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


