CREATE OR REPLACE VIEW dbo.PPOProfileNetworks
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPOPROFILESITECODE
		,PPOPROFILEID
		,PROFILEREGIONSITECODE
		,PROFILEREGIONID
		,NETWORKORDER
		,PPONETWORKID
		,SEARCHLOGIC
		,VERIFICATION
		,EFFECTIVEDATE
		,TERMINATIONDATE
		,JURISDICTIONIND
		,JURISDICTIONINSURERSEQ
		,JURISDICTIONUSEONLY
		,PPOSSTINREQ
		,PPOSSLICREQ
		,DEFAULTEXTENDEDSEARCHES
		,DEFAULTEXTENDEDFILTERS
		,SEVEREDTIES
		,POS
FROM src.PPOProfileNetworks
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


