CREATE OR REPLACE VIEW dbo.ClaimDiag
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMSEQ
		,CLAIMDIAGSEQ
		,DIAGCODE
FROM src.ClaimDiag
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


