CREATE OR REPLACE VIEW dbo.PendComment
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,PENDSEQ
		,PENDCOMMENTSEQ
		,PENDCOMMENT
		,CREATEUSERID
		,CREATEDATE
		,CREATEDBYEXTERNALUSERNAME
FROM src.PendComment
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


