CREATE OR REPLACE VIEW dbo.ClientData
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,TYPECODE
		,SUBTYPE
		,SUBSEQ
		,NUMDATA
		,TEXTDATA
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.ClientData
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


