CREATE OR REPLACE VIEW dbo.PPOProfileNetworksHistory
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,PPOPROFILENETWORKSHISTORYSEQ
		,RECORDDELETED
		,LOGDATETIME
		,LOGINAME
		,PPOPROFILESITECODE
		,PPOPROFILEID
		,PROFILEREGIONSITECODE
		,PROFILEREGIONID
		,NETWORKORDER
		,PPONETWORKID
		,SEARCHLOGIC
		,VERIFICATION
		,EFFECTIVEDATE
		,TERMINATIONDATE
		,JURISDICTIONIND
		,JURISDICTIONINSURERSEQ
		,JURISDICTIONUSEONLY
		,PPOSSTINREQ
		,PPOSSLICREQ
		,DEFAULTEXTENDEDSEARCHES
		,DEFAULTEXTENDEDFILTERS
		,SEVEREDTIES
		,POS
FROM src.PPOProfileNetworksHistory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


