CREATE OR REPLACE VIEW dbo.ClaimData
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMSEQ
		,TYPECODE
		,SUBTYPE
		,SUBSEQ
		,NUMDATA
		,TEXTDATA
		,CREATEDATE
		,CREATEUSERID
		,MODDATE
		,MODUSERID
FROM src.ClaimData
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


