CREATE OR REPLACE VIEW dbo.WFlow
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,WFLOWSEQ
		,DESCRIPTION
		,RECORDSTATUS
		,ENTITYTYPECODE
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,INITIALTASKSEQ
		,PAUSETASKSEQ
FROM src.WFlow
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


