CREATE OR REPLACE VIEW dbo.ODGData
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,ICDDIAGNOSISID
		,PROCEDURECODE
		,ICDDESCRIPTION
		,PROCEDUREDESCRIPTION
		,INCIDENCERATE
		,PROCEDUREFREQUENCY
		,VISITS25PERC
		,VISITS50PERC
		,VISITS75PERC
		,VISITSMEAN
		,COSTSMEAN
		,AUTOAPPROVALCODE
		,PAYMENTFLAG
		,COSTPERVISIT
FROM src.ODGData
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


