CREATE OR REPLACE VIEW dbo.ClaimInsurer
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,CLAIMSEQ
		,INSURERTYPE
		,EFFECTIVEDATE
		,INSURERSEQ
		,TERMINATIONDATE
		,EXTERNALPOLICYNUMBER
		,UNITSTATCLAIMID
		,UNITSTATPOLICYID
		,POLICYEFFECTIVEDATE
		,SELFINSURED
		,CLAIMADMINCLAIMNUM
FROM src.ClaimInsurer
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


