CREATE OR REPLACE VIEW dbo.BillControlHistory
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,BILLCONTROLHISTORYSEQ
		,CLIENTCODE
		,BILLSEQ
		,BILLCONTROLSEQ
		,CREATEDATE
		,CONTROL
		,EXTERNALID
		,EDIBATCHLOGSEQ
		,DELETED
		,MODUSERID
		,EXTERNALID2
		,MESSAGE
FROM src.BillControlHistory
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


