CREATE OR REPLACE VIEW dbo.Attorney
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLAIMSYSSUBSET
		,ATTORNEYSEQ
		,TIN
		,TINSUFFIX
		,EXTERNALID
		,NAME
		,GROUPCODE
		,LICENSENUM
		,MEDICARENUM
		,PRACTICEADDRESSSEQ
		,BILLINGADDRESSSEQ
		,ATTORNEYTYPE
		,SPECIALTY1
		,SPECIALTY2
		,CREATEUSERID
		,CREATEDATE
		,MODUSERID
		,MODDATE
		,STATUS
		,EXTERNALSTATUS
		,EXPORTDATE
		,SSNTININDICATOR
		,PMTDAYS
		,AUTHBEGINDATE
		,AUTHENDDATE
		,TAXADDRESSSEQ
		,CTRLNUM1099
		,SURCHARGECODE
		,WORKCOMPNUM
		,WORKCOMPSTATE
FROM src.Attorney
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


