CREATE OR REPLACE VIEW dbo.EDIXmit
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,EDIXMITSEQ
		,FILESPEC
		,FILELOCATION
		,RECOMMENDEDPAYMENT
		,USERID
		,XMITDATE
		,DATEFROM
		,DATETO
		,EDITYPE
		,EDIPARTNERID
		,DBVERSION
		,EDIMAPTOOLSITECODE
		,EDIPORTTYPE
		,EDIMAPTOOLID
		,TRANSMISSIONSTATUS
		,BATCHNUMBER
		,SENDERID
		,RECEIVERID
		,EXTERNALBATCHID
		,SARELATEDBATCHID
		,ACKNOTECODE
		,ACKNOTE
		,EXTERNALBATCHDATE
		,USERNOTES
		,RESUBMITDATE
		,RESUBMITUSERID
		,MODDATE
		,MODUSERID
FROM src.EDIXmit
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


