CREATE OR REPLACE VIEW dbo.BillProvider
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,BILLPROVIDERSEQ
		,QUALIFIER
		,LASTNAME
		,FIRSTNAME
		,MIDDLENAME
		,SUFFIX
		,NPI
		,LICENSENUM
		,DEANUM
FROM src.BillProvider
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


