CREATE OR REPLACE VIEW dbo.Pend
AS

SELECT 
		ODSPOSTINGGROUPAUDITID
		,ODSCUSTOMERID
		,ODSCREATEDATE
		,ODSSNAPSHOTDATE
		,ODSROWISCURRENT
		,ODSHASHBYTESVALUE
		,DMLOPERATION
		,CLIENTCODE
		,BILLSEQ
		,PENDSEQ
		,PENDDATE
		,RELEASEFLAG
		,PENDTOID
		,PRIORITY
		,RELEASEDATE
		,REASONCODE
		,PENDBYUSERID
		,RELEASEBYUSERID
		,AUTOPENDFLAG
		,RULEID
		,WFTASKSEQ
		,RELEASEDBYEXTERNALUSERNAME
FROM src.Pend
WHERE   ODSROWISCURRENT = 1
	AND DMLOPERATION <> 'D';


