CALL ADM.DROP_OBJECT('DROP', 'VIEW', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME'); -- Remove old view, if it's sitting around

CREATE TABLE IF NOT EXISTS DBO.CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME
(
    ODS_CUSTOMER_ID INT NULL,
    CUSTOMER_NAME VARCHAR(100) NULL,
    COMPANY VARCHAR(100) NULL,
    OFFICE VARCHAR(100) NULL,
    SOJ VARCHAR(2) NULL,
    CLAIM_COVERAGE_TYPE VARCHAR(5) NULL,
    BILL_COVERAGE_TYPE VARCHAR(5) NULL,
    FORM_TYPE VARCHAR(12) NULL,
    CLAIM_NO VARCHAR(255) NULL,
    CLAIMANT_ID INT NULL,
    PROVIDER_TIN VARCHAR(15) NULL,
    BILL_ID INT NULL,
    BILL_CREATE_DATE DATETIME NULL,
    BILL_COMMIT_DATE DATETIME NULL,
    MITCHELL_COMPLETE_DATE DATETIME NULL,
    CLAIM_CREATE_DATE DATETIME NULL,
    CLAIM_DATE_OF_LOSS DATETIME NULL,
    EXPECTED_RECOVERY_DATE DATETIME NULL,
    BILL_LINE INT NULL,
	LINE_TYPE INT NULL,
	NDC VARCHAR(20) NULL,
    PROCEDURE_CODE VARCHAR(15) NULL,
    PROCEDURE_CODE_DESCRIPTION VARCHAR NULL,
    PROCEDURE_CODE_MAJOR_GROUP VARCHAR(100) NULL,
	REDUCTION_TYPE VARCHAR(100) NULL,
    ADJ_SUB_CAT_NAME VARCHAR(50) NULL,
    ADJUSTMENT DECIMAL(19, 9) NULL,
    DUPLICATE_BILL_FLAG SMALLINT NULL,
    DUPLICATE_LINE_FLAG SMALLINT NULL,
	COMPANY_ID INT NULL,
    OFFICE_ID INT NULL,
	BILL_CREATE_DATE_YEAR INT NULL,
    BILL_CREATE_DATE_QUARTER INT NULL,
    BILL_CREATE_DATE_MONTH INT NULL,
    BILL_CREATE_DATE_WEEK INT NULL,
    BILL_CREATE_DATE_DAY INT NULL,
    BILL_COMMIT_DATE_YEAR INT NULL,
    BILL_COMMIT_DATE_QUARTER INT NULL,
    BILL_COMMIT_DATE_MONTH INT NULL,
    BILL_COMMIT_DATE_WEEK INT NULL,
    BILL_COMMIT_DATE_DAY INT NULL,
	NETWORK_NAME VARCHAR(50) NULL,
	CMT_ZIP VARCHAR(12) NULL,
	LINE_START_DATE_OF_SERVICE DATETIME NULL,
	LINE_END_DATE_OF_SERVICE DATETIME NULL,
	PVD_LAST_NAME VARCHAR(60) NULL,
	PVD_FIRST_NAME VARCHAR(35) NULL,
	PVD_GROUP VARCHAR(60) NULL,
	PVD_ZOS VARCHAR(12) NULL,
	PVD_STATE VARCHAR(2) NULL,
	PVD_SPC_LIST VARCHAR(8000) NULL,
	CMT_DOB DATETIME NULL,
	DX VARCHAR(8) NULL,
	ICD_DIAGNOSIS_CODE_DICTIONARY_DESCRIPTION VARCHAR(8000) NULL,
	ICD_VERSION INT NULL,
	DX_MAJOR_GROUP VARCHAR(8000) NULL,
	MODIFIER VARCHAR(14) NULL,
	MODIFIER_DICTIONARY_DESCRIPTION VARCHAR(8000) NULL,
	TYPE_OF_BILL VARCHAR(4) NULL,
	UB_BILL_TYPE_DESCRIPTION VARCHAR(8000) NULL,
	REV_CODE VARCHAR(4) NULL,
	POS_CODE VARCHAR(4) NULL,
	ADJUSTOR_ID INT NULL,
	USER_ID INT NULL,
	PPO_RECEIVED_DATE DATETIME NULL,
	PPO_RETURNED_DATE DATETIME NULL,
	CARRIER_RECEIVED_DATE DATETIME NULL,
	MITCHELL_RECEIVED_DATE DATETIME NULL,
	OVERRIDE_DATE_TIME DATETIME NULL,
	FIRST_NURSE_COMPLETE_DATE DATETIME NULL,
	SECOND_NURSE_COMPLETE_DATE DATETIME NULL,
	THIRD_NURSE_COMPLETE_DATE DATETIME NULL,
	EBILL_FLAG BOOLEAN NULL,
	ADJUSTOR_LAST_NAME VARCHAR(30) NULL,
	ADJUSTOR_FIRST_NAME VARCHAR(30) NULL,
    CONSTRAINT PK_CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME PRIMARY KEY (ODS_CUSTOMER_ID, BILL_ID, BILL_LINE, ADJ_SUB_CAT_NAME)
);

--RENAME
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ODSCUSTOMERID', 'ODS_CUSTOMER_ID');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CUSTOMERNAME', 'CUSTOMER_NAME');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'COMPANY', 'COMPANY');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'OFFICE', 'OFFICE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'SOJ', 'SOJ');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CLAIMCOVERAGETYPE', 'CLAIM_COVERAGE_TYPE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCOVERAGETYPE', 'BILL_COVERAGE_TYPE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'FORMTYPE', 'FORM_TYPE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CLAIMID', 'CLAIM_NO');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CLAIM_ID', 'CLAIM_NO');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CLAIMANTID', 'CLAIMANT_ID');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PROVIDERTIN', 'PROVIDER_TIN');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLID', 'BILL_ID');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCREATEDATE', 'BILL_CREATE_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCOMMITDATE', 'BILL_COMMIT_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'MITCHELLCOMPLETEDATE', 'MITCHELL_COMPLETE_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CLAIMCREATEDATE', 'CLAIM_CREATE_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CLAIMDATEOFLOSS', 'CLAIM_DATE_OF_LOSS');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'EXPECTEDRECOVERYDATE', 'EXPECTED_RECOVERY_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLLINE', 'BILL_LINE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PROCEDURECODE', 'PROCEDURE_CODE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PROCEDURECODEDESCRIPTION', 'PROCEDURE_CODE_DESCRIPTION');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PROCEDURECODEMAJORGROUP', 'PROCEDURE_CODE_MAJOR_GROUP');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'REDUCTIONTYPE', 'REDUCTION_TYPE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ADJSUBCATNAME', 'ADJ_SUB_CAT_NAME');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'DUPLICATEBILLFLAG', 'DUPLICATE_BILL_FLAG');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'DUPLICATELINEFLAG', 'DUPLICATE_LINE_FLAG');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ADJUSTMENT', 'ADJUSTMENT');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PROVIDERCHARGES', 'PROVIDER_CHARGES');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'TOTALALLOWED', 'TOTAL_ALLOWED');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'TOTALUNITS', 'TOTAL_UNITS');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'EXPECTEDRECOVERYDURATION', 'EXPECTED_RECOVERY_DURATION');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'COMPANYID', 'COMPANY_ID');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'OFFICEID', 'OFFICE_ID');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'NETWORKNAME', 'NETWORK_NAME');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CMTZIP', 'CMT_ZIP');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'LINESTARTDATEOFSERVICE', 'LINE_START_DATE_OF_SERVICE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'LINEENDDATEOFSERVICE', 'LINE_END_DATE_OF_SERVICE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVDLASTNAME', 'PVD_LAST_NAME');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVDFIRSTNAME', 'PVD_FIRST_NAME');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVDGROUP', 'PVD_GROUP');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVDZOS', 'PVD_ZOS');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVDSTATE', 'PVD_STATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVDSPC_LIST', 'PVD_SPC_LIST');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CMTDOB', 'CMT_DOB');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PRC_DESC', 'PRC_DESC');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'DX', 'DX');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'DXCODEDESCRIPTION', 'ICD_DIAGNOSIS_CODE_DICTIONARY_DESCRIPTION');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ICDVERSION', 'ICD_VERSION');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'DXMAJORGROUP', 'DX_MAJOR_GROUP');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'MODIFIER', 'MODIFIER');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'MODIFIERDESCRIPTION', 'MODIFIER_DICTIONARY_DESCRIPTION');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'MODIFIER_DESCRIPTION', 'MODIFIER_DICTIONARY_DESCRIPTION');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'TYPEOFBILL', 'TYPE_OF_BILL');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'DESCRIPTION', 'UB_BILL_TYPE_DESCRIPTION');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'REVCODE', 'REV_CODE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'POSCODE', 'POS_CODE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCREATEDATE_YEAR', 'BILL_CREATE_DATE_YEAR');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCREATEDATE_QUARTER', 'BILL_CREATE_DATE_QUARTER');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCREATEDATE_MONTH', 'BILL_CREATE_DATE_MONTH');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCREATEDATE_WEEK', 'BILL_CREATE_DATE_WEEK');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCREATEDATE_DAY', 'BILL_CREATE_DATE_DAY');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCOMMITDATE_YEAR', 'BILL_COMMIT_DATE_YEAR');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCOMMITDATE_QUARTER', 'BILL_COMMIT_DATE_QUARTER');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCOMMITDATE_MONTH', 'BILL_COMMIT_DATE_MONTH');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCOMMITDATE_WEEK', 'BILL_COMMIT_DATE_WEEK');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'BILLCOMMITDATE_DAY', 'BILL_COMMIT_DATE_DAY');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'LINETYPE', 'LINE_TYPE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ADJUSTERID', 'ADJUSTOR_ID');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ADJUSTER_ID', 'ADJUSTOR_ID');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'USERID', 'USER_ID');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PPORECEIVEDDATE', 'PPO_RECEIVED_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PPORETURNEDDATE', 'PPO_RETURNED_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CARRIERRECEIVEDDATE', 'CARRIER_RECEIVED_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'MITCHELLRECEIVEDDATE', 'MITCHELL_RECEIVED_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'OVERRIDEDATETIME', 'OVERRIDE_DATE_TIME');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'OVERRIDE_DATETIME', 'OVERRIDE_DATE_TIME');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'FIRSTNURSECOMPLETEDATE', 'FIRST_NURSE_COMPLETE_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'SECONDNURSECOMPLETEDATE', 'SECOND_NURSE_COMPLETE_DATE');
CALL ADM.ALTER_COLUMN('RENAME', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'THIRDNURSECOMPLETEDATE', 'THIRD_NURSE_COMPLETE_DATE');

--Add new columns
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'NDC', 'VARCHAR(20)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'NETWORK_NAME', 'VARCHAR(50)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CMT_ZIP', 'VARCHAR(12)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'LINE_START_DATE_OF_SERVICE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'LINE_END_DATE_OF_SERVICE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVD_LAST_NAME', 'VARCHAR(60)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVD_FIRST_NAME', 'VARCHAR(35)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVD_GROUP', 'VARCHAR(60)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVD_ZOS', 'VARCHAR(12)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVD_STATE', 'VARCHAR(2)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PVD_SPC_LIST', 'VARCHAR(8000)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CMT_DOB', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'DX', 'VARCHAR(8)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ICD_DIAGNOSIS_CODE_DICTIONARY_DESCRIPTION', 'VARCHAR(8000)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ICD_VERSION', 'INT', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'DX_MAJOR_GROUP', 'VARCHAR(8000)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'MODIFIER', 'VARCHAR(14)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'MODIFIER_DICTIONARY_DESCRIPTION', 'VARCHAR(8000)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'TYPE_OF_BILL', 'VARCHAR(4)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'UB_BILL_TYPE_DESCRIPTION', 'VARCHAR(8000)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'REV_CODE', 'VARCHAR(4)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'POS_CODE', 'VARCHAR(4)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ADJUSTOR_ID', 'INT', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'USER_ID', 'INT', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PPO_RECEIVED_DATE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'PPO_RETURNED_DATE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'CARRIER_RECEIVED_DATE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'MITCHELL_RECEIVED_DATE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'OVERRIDE_DATE_TIME', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'FIRST_NURSE_COMPLETE_DATE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'SECOND_NURSE_COMPLETE_DATE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'THIRD_NURSE_COMPLETE_DATE', 'DATETIME', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'EBILL_FLAG', 'BOOLEAN', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ADJUSTOR_LAST_NAME', 'VARCHAR(30)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'ADJUSTOR_FIRST_NAME', 'VARCHAR(30)', 'NULL', '');
CALL ADM.ALTER_COLUMN('ADD', 'DBO', 'CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME', 'LINE_TYPE', 'INT', 'NULL', '');

