CREATE OR REPLACE TASK ADM.ETL_Snowflake_Ods_Load
  WAREHOUSE = &DWSIZE
  SCHEDULE = 'USING CRON 0 18 * * * America/Los_Angeles'
AS
CALL ADM.ETL_MASTER_SNOWFLAKE_ODS_LOAD_multithread (20,'&DWSIZE',120,60,'@WCSODS.STG.s3_etl_PROD/WCS','WCSODS.STG.FORMAT_FILE_DEL_COMMA',FALSE);
