
DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_ADJSUBCATNAME;
DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_CLAIMCOVERAGETYPE;

DROP TABLE IF EXISTS CNFG.REPORT_COLUMN;
DROP TABLE IF EXISTS CNFG.REPORT_HIERARCHY_COLUMN;
DROP TABLE IF EXISTS CNFG.REPORT_COLUMN_TYPE;
DROP FUNCTION IF EXISTS CNFG.FN_GET_KPIS();
DROP FUNCTION IF EXISTS CNFG.FN_GET_KPIS_BY_REPORT_SUBJECT_AREA(INTEGER);
DROP FUNCTION IF EXISTS CNFG.FN_GET_KPIS_BY_REPORT_SUBJECT_AREA_SB();
DROP FUNCTION IF EXISTS CNFG.FN_GET_FILTERS();
DROP FUNCTION IF EXISTS CNFG.FN_GET_FILTERS_BY_REPORT_SUBJECT_AREA(INTEGER);
DROP FUNCTION IF EXISTS CNFG."FN_GET_GLOBAL_FILTERS_BY_REPORT_SUBJECT_AREA"(NUMBER);
DROP FUNCTION IF EXISTS CNFG.FN_GET_HIERARCHIES();
DROP FUNCTION IF EXISTS CNFG.FN_GET_HIERARCHIES_BY_REPORT_SUBJECT_AREA(INTEGER);

DROP FILE FORMAT IF EXISTS DBO.MYTABFORMAT;
DROP FILE FORMAT IF EXISTS DBO.MYZIPPEDPIPEFORMAT;

DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_ADJSUBCATNAME_ODSCUSTOMERID_CUSTOMERNAME;
DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_CLAIMCOVERAGETYPE_ODSCUSTOMERID_CUSTOMERNAME;
DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_SOJ_COMPANY_OFFICE_ODSCUSTOMERID_CUSTOMERNAME;

DROP TABLE IF EXISTS CNFG.LAYOUT_DETAIL;
DROP TABLE IF EXISTS CNFG.LAYOUT_REPORT_AREA;

DROP TABLE IF EXISTS CNFG.REPORT_HIERARCHY_REPORT_SUBJECT_AREA;
DROP TABLE IF EXISTS CNFG.REPORT_FILTER_REPORT_SUBJECT_AREA;

DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_BILLCOMMITDATE_CUSTOMERNAME;
DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_BILLCREATEDATE_CUSTOMERNAME;

DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_ADJSUBCATNAME_CUSTOMERNAME;
DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_CLAIMCOVERAGETYPE_CUSTOMERNAME;
DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_SOJ_COMPANY_OFFICE_CUSTOMERNAME;

DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_BILLLINE_ADJSUBCATNAME_CUSTOMERNAME;
DROP MATERIALIZED VIEW IF EXISTS DBO.DIM_CLAIM_DETAIL_BILLLINE_CLAIMCOVERAGETYPE_CUSTOMERNAME;
DROP MATERIALIZED VIEW IF EXISTS DBO.CLAIM_DETAIL_BILLLINE_SOJ_COMPANY_OFFICE_CUSTOMERNAME;

-- There are a bunch of old procedures hanging around (remember, different signatures are new procs).  Let's remove them here.
DROP PROCEDURE IF EXISTS CNFG.PROC_EXECUTE_SQL_SB(VARCHAR);
DROP PROCEDURE IF EXISTS CNFG.PROC_GENERATE_REPORT(VARCHAR, VARCHAR, VARCHAR, FLOAT);
DROP PROCEDURE IF EXISTS CNFG.PROC_GENERATE_SQL(VARCHAR, VARCHAR, VARCHAR, FLOAT);
DROP PROCEDURE IF EXISTS CNFG.PROC_GENERATE_SQL_SB(VARCHAR, VARCHAR, VARCHAR, FLOAT);
DROP PROCEDURE IF EXISTS CNFG.PROC_GET_HIERARCHY_PARTICIPANTS(FLOAT, FLOAT, VARCHAR, FLOAT);
DROP FUNCTION IF EXISTS CNFG.FN_GET_HIERARCHY_PARTICIPANTS(NUMBER, NUMBER, NUMBER);

DROP PROCEDURE IF EXISTS ADM.DROP_TABLE_WHEN_VIEW_MAY_EXIST(STRING, STRING);

DROP TABLE IF EXISTS DBO.CLAIM_DETAIL;